#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch G - 비뇨기/신장 (20개)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("nhiem-trung-duong-tiet-nieu","요로감염","nhiễm trùng đường tiết niệu",
      "세균이 요도, 방광, 신장 등 비뇨기계를 감염시켜 배뇨통, 빈뇨, 발열이 발생합니다. 통역 시 여성에게 흔하며, 충분한 수분 섭취와 완전 항생제 복용의 중요성을 강조합니다.",
      "Tình trạng vi khuẩn nhiễm vào hệ tiết niệu (niệu đạo, bàng quang, thận) gây đau khi tiểu, tiểu nhiều lần và sốt",
      "비뇨의학과",
      "여성 근로자들에게 흔한 질환입니다. 화장실 참지 않기, 앞에서 뒤로 닦기 등 예방법을 교육합니다.",
      [{"mistake":"증상 호전 시 항생제 중단 가능하다고 설명","correction":"처방 기간 반드시 완료해야 내성 예방","explanation":"불완전 치료는 재발과 내성을 유발합니다"},
       {"mistake":"방광염과 신우신염 구분 안 함","correction":"발열 있으면 신장 감염 의심","explanation":"치료 강도가 다릅니다"},
       {"mistake":"물만 많이 마시면 된다고 설명","correction":"항생제 치료가 필수","explanation":"자연 치유를 기대하면 안 됩니다"}],
      [{"ko":"요로감염으로 항생제를 7일간 드셔야 합니다.","vi":"Nhiễm trùng đường tiểu cần uống kháng sinh 7 ngày.","situation":"formal"},
       {"ko":"소변을 참지 마시고 물을 많이 드세요.","vi":"Đừng nhịn tiểu và uống nhiều nước.","situation":"onsite"},
       {"ko":"방광염이라 소변볼 때 따가워요.","vi":"Viêm bàng quang nên tiểu bị rát.","situation":"informal"}],
      ["항생제","소변검사","신우신염"]),

    t("soi-than","신장결석","sỏi thận",
      "신장에 돌이 생겨 옆구리 통증과 혈뇨를 유발합니다. 통역 시 심한 통증(산통)의 특성과 충분한 수분 섭취의 중요성을 설명합니다.",
      "Tình trạng hình thành sỏi trong thận gây đau hông sườn và tiểu ra máu",
      "비뇨의학과",
      "더운 환경에서 일하며 수분 섭취가 부족한 베트남 근로자들에게 흔합니다. 하루 2리터 이상 수분 섭취를 강조합니다.",
      [{"mistake":"작은 돌은 괜찮다고 안심시킴","correction":"크기에 따라 자연 배출 또는 시술 필요","explanation":"추적 관찰이 필요합니다"},
       {"mistake":"통증 조절만 하면 된다고 설명","correction":"결석 제거 또는 배출 필요","explanation":"방치 시 신장 손상 가능"},
       {"mistake":"한 번 생기면 계속 생긴다고 낙담시킴","correction":"예방으로 재발 줄일 수 있음","explanation":"생활습관 교정이 중요합니다"}],
      [{"ko":"신장결석 확인을 위해 CT 검사가 필요합니다.","vi":"Cần chụp CT để xác nhận sỏi thận.","situation":"formal"},
       {"ko":"하루에 물을 2리터 이상 드세요.","vi":"Uống hơn 2 lít nước mỗi ngày.","situation":"onsite"},
       {"ko":"신장결석이라 옆구리가 엄청 아팠어요.","vi":"Sỏi thận nên đau hông dữ dội.","situation":"informal"}],
      ["체외충격파쇄석술","요관경","수분섭취"]),

    t("suy-than-cap","급성신부전","suy thận cấp",
      "신장 기능이 갑자기 저하되어 노폐물 배설이 안 되는 응급 상황입니다. 통역 시 소변량 감소, 부종, 호흡곤란 등 증상을 설명하고 조기 치료의 중요성을 강조합니다.",
      "Tình trạng cấp cứu khi chức năng thận giảm đột ngột, không thể bài tiết chất thải",
      "신장내과",
      "탈수, 약물, 감염 등이 원인이 될 수 있습니다. 특히 진통제 남용을 경계하도록 교육합니다.",
      [{"mistake":"투석이 영구적이라고 겁줌","correction":"급성 신부전은 회복 가능한 경우 많음","explanation":"임시 투석 후 회복 가능"},
       {"mistake":"원인 확인 없이 치료","correction":"원인 제거가 핵심","explanation":"탈수, 약물, 폐쇄 등 확인"},
       {"mistake":"소변량만 보고 판단","correction":"혈액검사로 신기능 확인 필수","explanation":"크레아티닌 수치가 중요합니다"}],
      [{"ko":"급성신부전으로 일시적 투석이 필요할 수 있습니다.","vi":"Suy thận cấp có thể cần lọc máu tạm thời.","situation":"formal"},
       {"ko":"소변량이 갑자기 줄면 바로 오세요.","vi":"Nếu lượng nước tiểu giảm đột ngột hãy đến ngay.","situation":"onsite"},
       {"ko":"신장이 갑자기 안 좋아져서 투석했어요.","vi":"Thận đột ngột xấu đi nên phải lọc máu.","situation":"informal"}],
      ["투석","크레아티닌","수액치료"]),

    t("suy-than-man","만성신부전","suy thận mạn",
      "신장 기능이 점진적으로 저하되는 비가역적 상태입니다. 통역 시 5단계 분류와 투석/이식 시점에 대해 설명하고, 혈압과 혈당 관리의 중요성을 강조합니다.",
      "Tình trạng chức năng thận giảm dần không hồi phục",
      "신장내과",
      "당뇨와 고혈압이 주요 원인입니다. 기저질환 관리의 중요성을 강조합니다.",
      [{"mistake":"곧 투석해야 한다고만 설명","correction":"단계에 따라 관리 방법이 다름","explanation":"조기 발견 시 진행 억제 가능"},
       {"mistake":"식이 제한을 너무 엄격하게 강조","correction":"단계에 맞는 적절한 제한","explanation":"영양 결핍도 문제가 됩니다"},
       {"mistake":"투석하면 끝이라고 설명","correction":"이식으로 정상 생활 가능","explanation":"희망을 줍니다"}],
      [{"ko":"만성신부전 4단계로 투석 준비가 필요합니다.","vi":"Suy thận mạn giai đoạn 4, cần chuẩn bị lọc máu.","situation":"formal"},
       {"ko":"단백질과 염분 섭취를 조절하세요.","vi":"Hãy điều chỉnh lượng đạm và muối.","situation":"onsite"},
       {"ko":"신장이 안 좋아서 투석 받고 있어요.","vi":"Thận không tốt nên đang lọc máu.","situation":"informal"}],
      ["GFR","투석","신장이식"]),

    t("loc-mau","혈액투석","lọc máu",
      "신장 기능을 대신하여 기계로 혈액의 노폐물을 걸러내는 치료입니다. 통역 시 주 3회, 4시간씩 치료가 필요하며 생활 패턴 변화가 있음을 설명합니다.",
      "Phương pháp điều trị dùng máy lọc chất thải trong máu thay cho chức năng thận",
      "신장내과",
      "투석 환자의 직장 생활, 식이 제한, 수분 제한에 대해 구체적으로 안내합니다.",
      [{"mistake":"투석은 고통스럽다고만 강조","correction":"잘 적응하면 일상 생활 가능","explanation":"적응 기간이 필요합니다"},
       {"mistake":"수분 무제한이라고 설명","correction":"투석 환자는 수분 제한 필수","explanation":"체중 증가는 심장에 부담"},
       {"mistake":"투석하면 일 못 한다고 설명","correction":"야간 투석 등 옵션 있음","explanation":"생활 패턴에 맞출 수 있습니다"}],
      [{"ko":"혈액투석을 주 3회 받으셔야 합니다.","vi":"Cần lọc máu 3 lần mỗi tuần.","situation":"formal"},
       {"ko":"투석 사이에 체중이 많이 늘지 않도록 수분을 조절하세요.","vi":"Điều chỉnh nước uống để cân không tăng nhiều giữa các lần lọc.","situation":"onsite"},
       {"ko":"일주일에 세 번 투석받아요.","vi":"Mỗi tuần lọc máu 3 lần.","situation":"informal"}],
      ["동정맥루","투석기","건체중"]),

    t("ghep-than","신장이식","ghép thận",
      "말기신부전 환자에게 건강한 신장을 이식하는 수술입니다. 통역 시 생체 이식과 뇌사자 이식의 차이, 면역억제제 평생 복용을 설명합니다.",
      "Phẫu thuật cấy ghép thận khỏe mạnh cho bệnh nhân suy thận giai đoạn cuối",
      "이식외과",
      "한국의 장기이식 시스템과 대기 과정을 설명합니다. 가족 기증자가 있는지 확인합니다.",
      [{"mistake":"이식하면 완치라고 설명","correction":"면역억제제 평생 복용 필요","explanation":"거부반응 예방이 필수"},
       {"mistake":"수술만 강조","correction":"수술 후 관리가 더 중요","explanation":"감염 예방, 약물 복용이 핵심"},
       {"mistake":"누구나 받을 수 있다고 설명","correction":"건강 상태에 따라 적합성 평가","explanation":"사전 검사가 필요합니다"}],
      [{"ko":"신장이식 후 면역억제제를 평생 드셔야 합니다.","vi":"Sau ghép thận phải uống thuốc ức chế miễn dịch suốt đời.","situation":"formal"},
       {"ko":"가족 중 신장 기증 가능한 분이 있나요?","vi":"Trong gia đình có ai có thể hiến thận không?","situation":"onsite"},
       {"ko":"신장 이식받고 건강해졌어요.","vi":"Ghép thận xong khỏe lên.","situation":"informal"}],
      ["면역억제제","거부반응","HLA적합성"]),

    t("viem-than-be-than","사구체신염","viêm cầu thận",
      "신장의 사구체에 염증이 생겨 혈뇨, 단백뇨, 부종이 발생합니다. 통역 시 자가면역이나 감염 후 발생할 수 있으며, 만성화 가능성을 설명합니다.",
      "Tình trạng viêm cầu thận gây tiểu ra máu, đạm niệu và phù",
      "신장내과",
      "감기나 편도염 후에 발생할 수 있습니다. 소변색 변화(콜라색)에 주의하도록 교육합니다.",
      [{"mistake":"단순 감기로 치부","correction":"상기도 감염 후 사구체신염 가능","explanation":"소변 변화 관찰이 중요"},
       {"mistake":"항생제로 치료된다고 설명","correction":"면역억제제가 필요할 수 있음","explanation":"원인에 따라 치료가 다릅니다"},
       {"mistake":"완치 가능하다고만 설명","correction":"만성화되어 신부전으로 진행 가능","explanation":"정기 추적이 필요합니다"}],
      [{"ko":"사구체신염 확인을 위해 신장 조직검사가 필요할 수 있습니다.","vi":"Có thể cần sinh thiết thận để xác nhận viêm cầu thận.","situation":"formal"},
       {"ko":"소변이 콜라색처럼 보이면 바로 오세요.","vi":"Nếu nước tiểu đỏ như coca cola hãy đến ngay.","situation":"onsite"},
       {"ko":"사구체신염이라 부종이 있어요.","vi":"Viêm cầu thận nên bị phù.","situation":"informal"}],
      ["단백뇨","신장조직검사","면역억제제"]),

    t("than-da-nang","다낭신","thận đa nang",
      "신장에 여러 개의 낭종이 생겨 점점 커지면서 신장 기능이 저하되는 유전 질환입니다. 통역 시 가족력의 중요성과 정기 검진을 강조합니다.",
      "Bệnh di truyền với nhiều nang trong thận ngày càng lớn làm giảm chức năng thận",
      "신장내과",
      "상염색체 우성 유전으로 자녀에게 50% 확률로 유전됩니다. 가족 상담을 권합니다.",
      [{"mistake":"낭종이 곧 암이라고 겁줌","correction":"양성 낭종이지만 신장 손상 유발","explanation":"정기 관찰이 필요합니다"},
       {"mistake":"치료법이 없다고만 설명","correction":"진행 억제 약물, 혈압 조절 가능","explanation":"관리가 가능합니다"},
       {"mistake":"유전 상담 안 함","correction":"가족 검사와 유전 상담 필요","explanation":"조기 발견이 중요합니다"}],
      [{"ko":"다낭신은 유전 질환으로 가족 검사가 필요합니다.","vi":"Thận đa nang là bệnh di truyền, gia đình cần xét nghiệm.","situation":"formal"},
       {"ko":"혈압을 잘 조절하면 진행을 늦출 수 있어요.","vi":"Kiểm soát huyết áp tốt có thể làm chậm tiến triển.","situation":"onsite"},
       {"ko":"아버지도 다낭신이셨어요.","vi":"Bố cũng bị thận đa nang.","situation":"informal"}],
      ["초음파","혈압조절","유전상담"]),

    t("phi-dai-tuyen-tien-liet","전립선비대증","phì đại tuyến tiền liệt",
      "전립선이 커져서 소변 배출이 어려워지는 중년 이후 남성의 흔한 질환입니다. 통역 시 배뇨 증상(빈뇨, 야간뇨, 약한 소변줄기)을 구체적으로 확인합니다.",
      "Tình trạng tuyến tiền liệt to lên gây khó tiểu, phổ biến ở nam giới trung niên",
      "비뇨의학과",
      "중년 이상 남성 환자의 배뇨 문제를 물어볼 때 프라이버시를 배려합니다.",
      [{"mistake":"전립선암과 혼동","correction":"비대증은 양성, 별개 질환","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"약물로 조절 가능한 경우 많음","explanation":"단계적 치료가 필요합니다"},
       {"mistake":"증상을 참으라고 조언","correction":"요폐, 신장 손상 가능","explanation":"적극적 치료가 필요합니다"}],
      [{"ko":"전립선비대증으로 약물 치료를 시작하겠습니다.","vi":"Phì đại tuyến tiền liệt, sẽ bắt đầu điều trị thuốc.","situation":"formal"},
       {"ko":"밤에 몇 번이나 화장실에 가세요?","vi":"Đêm đi vệ sinh mấy lần?","situation":"onsite"},
       {"ko":"전립선 커져서 소변이 잘 안 나와요.","vi":"Tuyến tiền liệt to nên tiểu khó.","situation":"informal"}],
      ["알파차단제","PSA","경요도전립선절제술"]),

    t("ung-thu-tuyen-tien-liet","전립선암","ung thư tuyến tiền liệt",
      "전립선에 발생하는 악성 종양으로, 조기에는 증상이 없어 PSA 검사로 발견됩니다. 통역 시 느리게 진행하는 암이 많아 적극적 감시도 옵션임을 설명합니다.",
      "Khối u ác tính phát sinh ở tuyến tiền liệt, giai đoạn sớm không có triệu chứng, phát hiện qua xét nghiệm PSA",
      "비뇨의학과/종양내과",
      "전립선암은 진행이 느린 경우가 많아 과잉치료 우려도 있습니다. 개인화된 접근을 설명합니다.",
      [{"mistake":"암이면 곧 사망이라고 설명","correction":"전립선암은 예후가 좋은 편","explanation":"희망을 줍니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"적극적 감시, 방사선 등 옵션","explanation":"개인 상황에 맞는 선택"},
       {"mistake":"PSA 높으면 다 암이라고 설명","correction":"양성비대증도 PSA 상승 가능","explanation":"조직검사로 확진합니다"}],
      [{"ko":"전립선암 확인을 위해 조직검사가 필요합니다.","vi":"Cần sinh thiết để xác nhận ung thư tuyến tiền liệt.","situation":"formal"},
       {"ko":"PSA 수치가 높아서 추가 검사가 필요해요.","vi":"PSA cao nên cần xét nghiệm thêm.","situation":"onsite"},
       {"ko":"전립선암 초기라 지켜보고 있어요.","vi":"Ung thư tiền liệt giai đoạn đầu nên đang theo dõi.","situation":"informal"}],
      ["PSA","전립선조직검사","근치적전립선절제술"]),

    t("viem-tuyen-tien-liet","전립선염","viêm tuyến tiền liệt",
      "전립선에 염증이 생겨 회음부 통증, 배뇨통, 성기능 장애가 발생합니다. 통역 시 급성과 만성의 차이, 장기 치료가 필요할 수 있음을 설명합니다.",
      "Tình trạng viêm tuyến tiền liệt gây đau vùng đáy chậu, đau khi tiểu và rối loạn chức năng tình dục",
      "비뇨의학과",
      "만성 전립선염은 치료가 어려울 수 있습니다. 인내심을 갖고 치료에 임하도록 격려합니다.",
      [{"mistake":"항생제만 처방","correction":"비세균성 전립선염은 다른 치료 필요","explanation":"원인에 따라 접근이 다릅니다"},
       {"mistake":"금방 낫는다고 설명","correction":"만성화될 수 있음","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"성병으로 오해","correction":"성병과 다른 질환","explanation":"낙인을 피합니다"}],
      [{"ko":"전립선염으로 항생제와 소염제를 드셔야 합니다.","vi":"Viêm tiền liệt cần uống kháng sinh và thuốc chống viêm.","situation":"formal"},
       {"ko":"오래 앉아있는 것을 피하세요.","vi":"Tránh ngồi lâu.","situation":"onsite"},
       {"ko":"전립선염이라 아랫배가 불편해요.","vi":"Viêm tiền liệt nên khó chịu bụng dưới.","situation":"informal"}],
      ["전립선마사지","알파차단제","좌욕"]),

    t("ung-thu-bang-quang","방광암","ung thư bàng quang",
      "방광에 발생하는 악성 종양으로, 혈뇨가 주요 증상입니다. 통역 시 흡연이 주요 위험인자이며, 재발이 잦아 정기 추적이 필요함을 설명합니다.",
      "Khối u ác tính phát sinh ở bàng quang, triệu chứng chính là tiểu ra máu",
      "비뇨의학과/종양내과",
      "흡연과 직업적 노출(염료, 화학물질)이 위험인자입니다. 금연을 강조합니다.",
      [{"mistake":"혈뇨를 가볍게 여김","correction":"무통성 혈뇨는 방광암 의심","explanation":"조기 검사가 중요합니다"},
       {"mistake":"한 번 치료하면 끝이라고 설명","correction":"재발률이 높아 정기 추적 필수","explanation":"방광내시경 추적 필요"},
       {"mistake":"방광 전체 제거가 필수라고 설명","correction":"표재성은 방광 보존 가능","explanation":"병기에 따라 치료가 다릅니다"}],
      [{"ko":"방광암 확인을 위해 방광내시경이 필요합니다.","vi":"Cần nội soi bàng quang để xác nhận ung thư bàng quang.","situation":"formal"},
       {"ko":"피가 섞인 소변이 보이면 바로 오세요.","vi":"Nếu thấy nước tiểu lẫn máu hãy đến ngay.","situation":"onsite"},
       {"ko":"방광암이라 방광내시경 정기적으로 받아요.","vi":"Ung thư bàng quang nên nội soi bàng quang định kỳ.","situation":"informal"}],
      ["방광내시경","경요도방광종양절제술","BCG방광내주입"]),

    t("ung-thu-than","신장암","ung thư thận",
      "신장에 발생하는 악성 종양으로, 초기에는 증상이 없어 건강검진에서 우연히 발견되는 경우가 많습니다. 통역 시 조기 발견 시 수술로 완치 가능함을 설명합니다.",
      "Khối u ác tính phát sinh ở thận, giai đoạn sớm không có triệu chứng, thường phát hiện tình cờ khi khám sức khỏe",
      "비뇨의학과/종양내과",
      "흡연과 비만이 위험인자입니다. 정기 건강검진의 중요성을 강조합니다.",
      [{"mistake":"신장암은 치료 불가라고 설명","correction":"조기 발견 시 완치율 높음","explanation":"희망을 줍니다"},
       {"mistake":"신장 전체 제거가 필수라고 설명","correction":"부분 절제도 가능","explanation":"신기능 보존이 중요합니다"},
       {"mistake":"항암제가 효과 없다고 설명","correction":"표적치료, 면역치료 옵션 있음","explanation":"최신 치료법이 있습니다"}],
      [{"ko":"신장암 수술로 종양만 제거하고 신장을 보존할 수 있습니다.","vi":"Phẫu thuật ung thư thận có thể chỉ cắt u và bảo tồn thận.","situation":"formal"},
       {"ko":"정기 검진에서 우연히 발견된 건 다행이에요.","vi":"May mắn là phát hiện tình cờ khi khám sức khỏe.","situation":"onsite"},
       {"ko":"신장암이라 부분 절제 수술했어요.","vi":"Ung thư thận nên mổ cắt một phần.","situation":"informal"}],
      ["부분신장절제술","근치적신장절제술","표적치료"]),

    t("tieu-khong-tu-chu","요실금","tiểu không tự chủ",
      "자신의 의지와 상관없이 소변이 새는 상태입니다. 통역 시 유형(복압성, 절박성, 혼합성)에 따라 치료가 다르며, 부끄러워하지 말고 치료받도록 격려합니다.",
      "Tình trạng không kiểm soát được việc tiểu tiện",
      "비뇨의학과",
      "요실금은 부끄러워서 숨기는 경우가 많습니다. 흔한 질환이며 치료 가능함을 알려 치료를 독려합니다.",
      [{"mistake":"나이 들면 당연하다고 설명","correction":"치료 가능한 질환","explanation":"삶의 질 개선이 가능합니다"},
       {"mistake":"수술만 있다고 설명","correction":"골반저근운동, 약물도 효과적","explanation":"비수술적 치료 먼저"},
       {"mistake":"물을 적게 마시라고 조언","correction":"적절한 수분 섭취는 필요","explanation":"탈수는 다른 문제 유발"}],
      [{"ko":"요실금 유형을 확인하기 위해 요역동학검사가 필요합니다.","vi":"Cần xét nghiệm niệu động học để xác định loại tiểu không tự chủ.","situation":"formal"},
       {"ko":"케겔운동을 꾸준히 하면 좋아질 수 있어요.","vi":"Tập Kegel đều đặn có thể cải thiện.","situation":"onsite"},
       {"ko":"기침할 때 소변이 새요.","vi":"Khi ho thì bị rỉ nước tiểu.","situation":"informal"}],
      ["케겔운동","방광훈련","중부요도슬링수술"]),

    t("bang-quang-tang-hoat","과민성방광","bàng quang tăng hoạt",
      "방광이 과도하게 수축하여 갑작스러운 요의와 빈뇨가 발생합니다. 통역 시 긴급하게 화장실을 찾게 되어 일상에 불편을 주는 질환임을 설명합니다.",
      "Tình trạng bàng quang co bóp quá mức gây buồn tiểu đột ngột và tiểu nhiều lần",
      "비뇨의학과",
      "과민성방광은 삶의 질을 크게 저하시킵니다. 적절한 치료로 개선 가능함을 알립니다.",
      [{"mistake":"요로감염과 혼동","correction":"감염 없이도 발생하는 기능성 질환","explanation":"원인이 다릅니다"},
       {"mistake":"약 먹으면 바로 낫는다고 설명","correction":"생활습관 교정과 방광훈련 병행","explanation":"복합 치료가 효과적"},
       {"mistake":"참으라고 조언","correction":"적절한 배뇨 훈련이 필요","explanation":"참는 것도 기술입니다"}],
      [{"ko":"과민성방광으로 방광 이완 약물을 처방합니다.","vi":"Bàng quang tăng hoạt, sẽ kê thuốc giãn bàng quang.","situation":"formal"},
       {"ko":"커피와 술을 줄이면 증상이 좋아질 수 있어요.","vi":"Giảm cà phê và rượu có thể cải thiện triệu chứng.","situation":"onsite"},
       {"ko":"갑자기 급하게 화장실 가고 싶어져요.","vi":"Đột nhiên muốn đi vệ sinh gấp.","situation":"informal"}],
      ["항콜린제","방광훈련","보톡스방광주입"]),

    t("hep-nieu-dao","요도협착","hẹp niệu đạo",
      "요도가 좁아져 소변 배출이 어려워지는 상태입니다. 통역 시 원인(감염, 외상, 의료 시술)을 확인하고 치료 옵션을 설명합니다.",
      "Tình trạng niệu đạo bị hẹp gây khó tiểu",
      "비뇨의학과",
      "도뇨관 삽입이나 요도 손상 후에 발생할 수 있습니다. 과거 의료 병력을 확인합니다.",
      [{"mistake":"한 번 확장하면 끝이라고 설명","correction":"재협착이 흔함","explanation":"정기 추적 필요"},
       {"mistake":"수술만 있다고 설명","correction":"확장술, 내시경 시술도 있음","explanation":"단계적 접근이 필요"},
       {"mistake":"원인 확인 안 함","correction":"원인에 따라 재발 예방","explanation":"근본 치료가 중요"}],
      [{"ko":"요도협착 확인을 위해 요도조영술이 필요합니다.","vi":"Cần chụp niệu đạo để xác nhận hẹp niệu đạo.","situation":"formal"},
       {"ko":"소변줄기가 가늘어지면 검사를 받으세요.","vi":"Nếu tia tiểu yếu đi hãy đi khám.","situation":"onsite"},
       {"ko":"요도가 좁아져서 소변이 잘 안 나와요.","vi":"Niệu đạo bị hẹp nên tiểu khó.","situation":"informal"}],
      ["요도확장술","내요도절개술","요도성형술"]),

    t("tinh-hoan-an","잠복고환","tinh hoàn ẩn",
      "고환이 음낭으로 내려오지 않고 복강이나 서혜부에 위치한 상태입니다. 통역 시 조기 수술의 중요성(불임, 암 위험)을 설명합니다.",
      "Tình trạng tinh hoàn không xuống bìu mà nằm trong ổ bụng hoặc bẹn",
      "소아비뇨의학과",
      "소아 환자의 경우 보호자에게 설명합니다. 1세 이전 수술이 권장됩니다.",
      [{"mistake":"저절로 내려온다고 기다림","correction":"6개월 후에도 안 내려오면 수술 고려","explanation":"조기 치료가 중요합니다"},
       {"mistake":"미용적 문제로만 설명","correction":"불임, 고환암 위험 증가","explanation":"기능적 문제가 있습니다"},
       {"mistake":"성인에서 발견되면 괜찮다고 설명","correction":"암 위험으로 정기 검진 필요","explanation":"추적 관찰이 필수입니다"}],
      [{"ko":"잠복고환 수술은 1세 이전에 하는 것이 좋습니다.","vi":"Phẫu thuật tinh hoàn ẩn nên làm trước 1 tuổi.","situation":"formal"},
       {"ko":"고환이 음낭에 없으면 검사가 필요해요.","vi":"Nếu tinh hoàn không ở trong bìu cần xét nghiệm.","situation":"onsite"},
       {"ko":"어릴 때 잠복고환 수술했어요.","vi":"Hồi nhỏ đã mổ tinh hoàn ẩn.","situation":"informal"}],
      ["고환고정술","초음파","불임"]),

    t("xoan-tinh-hoan","고환염전","xoắn tinh hoàn",
      "고환으로 가는 혈관이 꼬여 혈류가 차단되는 응급 상황입니다. 통역 시 6시간 이내 수술해야 고환을 살릴 수 있음을 강조합니다.",
      "Tình trạng cấp cứu khi mạch máu đến tinh hoàn bị xoắn, tắc nghẽn lưu thông máu",
      "비뇨의학과/응급",
      "10대 청소년에게 흔합니다. 갑작스러운 고환 통증은 응급 상황임을 교육합니다.",
      [{"mistake":"타박상으로 오해","correction":"외상 없이도 발생 가능","explanation":"자발적 염전이 흔합니다"},
       {"mistake":"진통제로 지켜보자고 조언","correction":"6시간 내 수술 필요","explanation":"지연 시 고환 손실"},
       {"mistake":"한쪽만 문제라고 설명","correction":"반대쪽도 예방 고정 필요","explanation":"재발 방지가 중요합니다"}],
      [{"ko":"고환염전 응급 수술이 필요합니다.","vi":"Xoắn tinh hoàn cần phẫu thuật cấp cứu.","situation":"formal"},
       {"ko":"고환이 갑자기 아프면 바로 응급실로 오세요.","vi":"Tinh hoàn đau đột ngột hãy đến cấp cứu ngay.","situation":"onsite"},
       {"ko":"고환 꼬여서 응급 수술했어요.","vi":"Tinh hoàn bị xoắn nên mổ cấp cứu.","situation":"informal"}],
      ["도플러초음파","고환고정술","고환절제술"]),

    t("viem-mao-tinh-hoan","부고환염","viêm mào tinh hoàn",
      "부고환에 염증이 생겨 고환 통증과 부종이 발생합니다. 통역 시 성매개감염 가능성을 고려하여 파트너 검사도 안내합니다.",
      "Tình trạng viêm mào tinh hoàn gây đau và sưng tinh hoàn",
      "비뇨의학과",
      "젊은 남성에서는 성매개감염이 원인인 경우가 많습니다. 프라이버시를 배려하며 파트너 검사를 권합니다.",
      [{"mistake":"고환염전과 구분 안 함","correction":"초음파로 혈류 확인 필요","explanation":"응급 상황 배제가 우선"},
       {"mistake":"성병 관련 언급 안 함","correction":"젊은 성인은 STI 검사 필요","explanation":"원인 치료가 중요합니다"},
       {"mistake":"항생제만 처방","correction":"파트너 동시 치료 필요","explanation":"재감염 방지가 중요합니다"}],
      [{"ko":"부고환염으로 항생제 치료가 필요합니다.","vi":"Viêm mào tinh hoàn cần điều trị kháng sinh.","situation":"formal"},
       {"ko":"파트너도 함께 검사받는 게 좋아요.","vi":"Bạn tình cũng nên xét nghiệm cùng.","situation":"onsite"},
       {"ko":"부고환염이라 고환이 부었어요.","vi":"Viêm mào tinh hoàn nên tinh hoàn bị sưng.","situation":"informal"}],
      ["소변검사","초음파","STI검사"]),

    t("trang-duong-nuoc","음낭수종","tràng dương nước",
      "고환 주위에 액체가 고여 음낭이 부어오르는 상태입니다. 통역 시 대부분 양성이지만 원인 확인이 필요함을 설명합니다.",
      "Tình trạng dịch tích tụ quanh tinh hoàn khiến bìu sưng lên",
      "비뇨의학과",
      "성인에서 갑자기 생기면 원인 질환(감염, 외상, 종양)을 배제해야 합니다.",
      [{"mistake":"모두 수술 필요하다고 설명","correction":"작고 증상 없으면 관찰 가능","explanation":"불필요한 수술을 피합니다"},
       {"mistake":"원인 확인 없이 처치","correction":"종양 등 이차 원인 배제 필요","explanation":"초음파 검사가 중요합니다"},
       {"mistake":"음낭암이라고 겁줌","correction":"대부분 양성 수종","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"음낭수종 확인을 위해 초음파 검사가 필요합니다.","vi":"Cần siêu âm để xác nhận tràng dương nước.","situation":"formal"},
       {"ko":"크기가 작으면 지켜볼 수 있어요.","vi":"Nếu nhỏ có thể theo dõi.","situation":"onsite"},
       {"ko":"음낭에 물이 차서 부었어요.","vi":"Bìu chứa nước nên sưng lên.","situation":"informal"}],
      ["초음파","수종절제술","경화요법"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
