#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 추가 의료 용어들 - 소아과, 산부인과, 감염병 등
new = [
t("benh-kawasaki","가와사키병","bệnh Kawasaki","5세 이하 소아에서 발생하는 혈관 염증 질환입니다. 고열, 발진, 림프절 비대가 특징입니다. 관상동맥 합병증 예방이 중요합니다. 통역 시 응급성, 면역글로불린 치료, 추적 검사를 설명해야 합니다.",
"Bệnh viêm mạch máu ở trẻ dưới 5 tuổi gây sốt cao, phát ban","소아과","한국에서 가와사키병은 아시아 소아에게 많습니다. 조기 치료로 심장 합병증을 예방합니다.",
[{"mistake":"단순 감기나 발진으로 오해","correction":"5일 이상 고열 시 가와사키병 의심","explanation":"조기 진단이 중요합니다"},
{"mistake":"면역글로불린 치료 거부감","correction":"심장 합병증 예방에 필수적인 치료","explanation":"치료 협조를 얻습니다"},
{"mistake":"치료 후 추적 미안내","correction":"관상동맥 확인 위해 심장초음파 추적 필요","explanation":"장기 합병증을 예방합니다"}],
[{"ko":"가와사키병 의심으로 입원 치료가 필요합니다.","vi":"Nghi bệnh Kawasaki cần nhập viện điều trị.","situation":"formal"},
{"ko":"면역글로불린 주사를 맞으면 빨리 좋아집니다.","vi":"Tiêm immunoglobulin sẽ khỏi nhanh.","situation":"formal"},
{"ko":"열이 5일 넘으면 바로 데려오세요.","vi":"Sốt hơn 5 ngày thì đưa đến ngay.","situation":"informal"}],
["면역글로불린","관상동맥","소아"]),

t("suy-dinh-duong","영양실조","suy dinh dưỡng","영양 섭취가 불충분하여 발생하는 상태입니다. 체중 감소, 성장 부진, 면역 저하가 나타납니다. 원인 파악과 영양 공급이 필요합니다. 통역 시 원인, 영양 보충, 추적 관찰을 설명해야 합니다.",
"Tình trạng thiếu dinh dưỡng gây giảm cân, chậm tăng trưởng","소아과, 내과","한국에서 영양실조는 드물지만 노인, 만성질환자에서 볼 수 있습니다.",
[{"mistake":"영양실조를 단순 식욕 부진으로 봄","correction":"기저 질환 확인 필요, 암 등 가능성","explanation":"원인 파악이 중요합니다"},
{"mistake":"영양제만 권유","correction":"균형 잡힌 식사가 우선, 필요시 영양 보충","explanation":"종합적 접근을 권합니다"},
{"mistake":"소아 성장 부진 미고려","correction":"성장곡선 확인, 발달 평가 필요","explanation":"소아의 특수성을 고려합니다"}],
[{"ko":"영양 상태 개선이 필요합니다.","vi":"Cần cải thiện tình trạng dinh dưỡng.","situation":"formal"},
{"ko":"고단백 식사를 드세요.","vi":"Ăn nhiều đạm.","situation":"formal"},
{"ko":"제대로 못 드셔서 살이 빠진 거예요.","vi":"Không ăn uống đúng nên sụt cân.","situation":"informal"}],
["영양보충","성장부진","단백질"]),

t("viem-tieu-phe-quan","세기관지염","viêm tiểu phế quản","영아에서 흔한 하기도 감염입니다. RSV 바이러스가 주요 원인입니다. 쌕쌕거림, 호흡곤란이 나타납니다. 통역 시 보존적 치료, 입원 기준, 예방을 설명해야 합니다.",
"Nhiễm trùng đường hô hấp dưới phổ biến ở trẻ nhỏ do RSV","소아과","한국에서 세기관지염은 겨울철 영아 입원의 흔한 원인입니다.",
[{"mistake":"항생제 필요하다고 설명","correction":"바이러스성이므로 항생제 효과 없음","explanation":"불필요한 항생제 사용을 줄입니다"},
{"mistake":"가습기 효과 과장","correction":"적절한 습도 유지가 도움되나 치료는 아님","explanation":"올바른 가정 관리를 안내합니다"},
{"mistake":"입원 기준 미설명","correction":"수유 곤란, 산소 저하 시 입원 필요","explanation":"위험 신호를 알립니다"}],
[{"ko":"세기관지염으로 입원 관찰이 필요합니다.","vi":"Viêm tiểu phế quản cần nhập viện theo dõi.","situation":"formal"},
{"ko":"항생제는 효과 없고 시간이 지나면 좋아져요.","vi":"Kháng sinh không hiệu quả, qua thời gian sẽ khỏi.","situation":"formal"},
{"ko":"숨 쉬기 힘들어하면 바로 오세요.","vi":"Nếu bé khó thở thì đến ngay.","situation":"informal"}],
["RSV","영아","산소치료"]),

t("benh-tay-chan-mieng","수족구병","bệnh tay chân miệng","손, 발, 입에 물집이 생기는 바이러스 감염입니다. 영유아에게 흔합니다. 대부분 자연 회복되나 합병증에 주의해야 합니다. 통역 시 전염 예방, 합병증 신호, 수분 섭취를 설명해야 합니다.",
"Bệnh virus gây phát ban ở tay, chân, miệng, phổ biến ở trẻ nhỏ","소아과, 감염내과","한국에서 수족구병은 어린이집에서 유행합니다. 대부분 경증이지만 드물게 중증 합병증이 있습니다.",
[{"mistake":"모든 수족구가 경증이라고 설명","correction":"고열, 구토, 경련 시 중증 가능성 안내","explanation":"위험 신호를 알립니다"},
{"mistake":"항생제 처방","correction":"바이러스성이므로 대증치료","explanation":"불필요한 치료를 피합니다"},
{"mistake":"등원 제한 미안내","correction":"물집이 마를 때까지 어린이집 제한 권고","explanation":"전파를 예방합니다"}],
[{"ko":"수족구병으로 보입니다.","vi":"Đây có vẻ là bệnh tay chân miệng.","situation":"formal"},
{"ko":"물 많이 먹이시고 며칠 쉬면 나아요.","vi":"Cho bé uống nhiều nước và nghỉ vài ngày sẽ khỏi.","situation":"formal"},
{"ko":"고열 나거나 토하면 바로 오세요.","vi":"Nếu sốt cao hoặc nôn thì đến ngay.","situation":"informal"}],
["전염병","영유아","격리"]),

t("benh-soi","홍역","bệnh sởi","홍역 바이러스에 의한 급성 발진 질환입니다. 고열, 기침, 특징적 발진이 나타납니다. 예방접종으로 예방 가능합니다. 통역 시 전염성, 합병증, 백신을 설명해야 합니다.",
"Bệnh phát ban cấp tính do virus sởi, có thể phòng ngừa bằng vaccine","감염내과, 소아과","한국에서 홍역은 MMR 백신으로 대부분 예방되지만 해외 유입 사례가 있습니다.",
[{"mistake":"단순 발진으로 가볍게 봄","correction":"폐렴, 뇌염 등 심각한 합병증 가능","explanation":"질환의 심각성을 알립니다"},
{"mistake":"예방접종 상태 미확인","correction":"2회 접종 여부 확인, 미접종 시 추가 접종","explanation":"예방의 중요성을 강조합니다"},
{"mistake":"격리 기간 미안내","correction":"발진 후 5일간 격리 필요","explanation":"전파를 예방합니다"}],
[{"ko":"홍역으로 격리 치료가 필요합니다.","vi":"Bệnh sởi cần cách ly điều trị.","situation":"formal"},
{"ko":"예방접종 하셨나요?","vi":"Đã tiêm vaccine chưa?","situation":"formal"},
{"ko":"홍역은 예방주사 맞으면 안 걸려요.","vi":"Tiêm vaccine thì không bị sởi.","situation":"informal"}],
["MMR","발진","격리"]),

t("benh-quai-bi","볼거리","bệnh quai bị","볼거리 바이러스에 의한 이하선 부종 질환입니다. 귀 아래 부종, 발열이 특징입니다. MMR 백신으로 예방합니다. 통역 시 합병증(고환염, 뇌수막염), 격리를 설명해야 합니다.",
"Bệnh do virus quai bị gây sưng tuyến nước bọt","감염내과, 소아과","한국에서 볼거리는 MMR 백신 도입 후 크게 줄었습니다.",
[{"mistake":"단순 부종으로 가볍게 봄","correction":"고환염, 불임 가능성 등 합병증 주의","explanation":"특히 남성에게 중요합니다"},
{"mistake":"항생제 처방","correction":"바이러스성이므로 대증치료","explanation":"불필요한 치료를 피합니다"},
{"mistake":"격리 기간 미안내","correction":"부종 후 5일간 격리 권고","explanation":"전파를 예방합니다"}],
[{"ko":"볼거리로 안정이 필요합니다.","vi":"Bệnh quai bị cần nghỉ ngơi.","situation":"formal"},
{"ko":"남자아이는 고환염 합병증 조심해야 해요.","vi":"Bé trai phải cẩn thận biến chứng viêm tinh hoàn.","situation":"formal"},
{"ko":"부기 빠질 때까지 집에서 쉬세요.","vi":"Nghỉ ở nhà cho đến khi hết sưng.","situation":"informal"}],
["MMR","이하선","고환염"]),

t("benh-rubella","풍진","bệnh rubella","풍진 바이러스에 의한 발진 질환입니다. 대부분 경증이지만 임신 초기 감염 시 태아 기형을 유발합니다. 통역 시 임신 중 감염 위험, 백신을 강조해야 합니다.",
"Bệnh do virus rubella, nguy hiểm nếu nhiễm khi mang thai sớm","감염내과, 산부인과","한국에서 풍진은 임신 전 항체 검사와 백신이 권장됩니다.",
[{"mistake":"경증이라 무시","correction":"임신부 감염 시 태아 기형 위험 강조","explanation":"임신 계획 시 중요합니다"},
{"mistake":"임신 중 백신 가능하다고 설명","correction":"생백신이므로 임신 중 금기, 임신 전 접종","explanation":"백신 안전성을 알립니다"},
{"mistake":"항체 검사 미권유","correction":"가임기 여성은 항체 확인 권고","explanation":"예방을 강조합니다"}],
[{"ko":"풍진은 임신 중 위험하므로 미리 예방하세요.","vi":"Rubella nguy hiểm khi mang thai nên phòng ngừa trước.","situation":"formal"},
{"ko":"임신 계획 전에 항체 검사하세요.","vi":"Trước khi kế hoạch mang thai nên xét nghiệm kháng thể.","situation":"formal"},
{"ko":"아기 가지기 전에 주사 맞으세요.","vi":"Tiêm vaccine trước khi có con.","situation":"informal"}],
["MMR","선천성풍진증후군","가임기"]),

t("benh-thuy-dau","수두","bệnh thủy đậu","수두-대상포진 바이러스에 의한 발진 질환입니다. 전신 물집 발진이 특징입니다. 매우 전염성이 높습니다. 통역 시 격리, 가려움 관리, 합병증을 설명해야 합니다.",
"Bệnh do virus thủy đậu gây phát ban bóng nước toàn thân","감염내과, 소아과","한국에서 수두 예방접종은 국가예방접종에 포함됩니다.",
[{"mistake":"긁어도 된다고 안내","correction":"긁으면 2차 감염, 흉터 위험","explanation":"적절한 관리를 교육합니다"},
{"mistake":"아스피린 사용 가능하다고 안내","correction":"소아에서 라이증후군 위험, 아세트아미노펜 사용","explanation":"안전한 해열제를 안내합니다"},
{"mistake":"성인 수두 경시","correction":"성인은 더 심하고 폐렴 합병증 위험","explanation":"연령에 따른 차이를 설명합니다"}],
[{"ko":"수두로 격리가 필요합니다.","vi":"Bệnh thủy đậu cần cách ly.","situation":"formal"},
{"ko":"긁지 않게 손톱 짧게 깎아주세요.","vi":"Cắt móng tay ngắn để bé không gãi.","situation":"formal"},
{"ko":"딱지 앉을 때까지 집에 있으세요.","vi":"Ở nhà cho đến khi vảy khô.","situation":"informal"}],
["백신","격리","대상포진"]),

t("benh-bach-hau","백일해","bệnh bạch hầu","백일해균에 의한 호흡기 감염입니다. 심한 기침 발작이 100일간 지속됩니다. 영아에게 위험합니다. 통역 시 백신, 영아 접촉 주의, 항생제를 설명해야 합니다.",
"Nhiễm trùng hô hấp do vi khuẩn gây ho dữ dội kéo dài","감염내과, 소아과","한국에서 백일해는 DTaP 백신으로 예방하지만 청소년, 성인에서 재발할 수 있습니다.",
[{"mistake":"기침약으로 조절 가능하다고 설명","correction":"기침약 효과 없음, 항생제로 전파 예방","explanation":"적절한 치료를 안내합니다"},
{"mistake":"영아 위험성 미강조","correction":"3개월 미만 영아에게 치명적 가능성","explanation":"영아 보호를 강조합니다"},
{"mistake":"임산부 예방접종 미안내","correction":"임신 중 Tdap 접종으로 신생아 보호 가능","explanation":"예방을 강조합니다"}],
[{"ko":"백일해로 항생제 치료가 필요합니다.","vi":"Bệnh bạch hầu cần điều trị kháng sinh.","situation":"formal"},
{"ko":"어린 아기 접촉을 피하세요.","vi":"Tránh tiếp xúc với trẻ sơ sinh.","situation":"formal"},
{"ko":"기침이 몇 주 갈 수 있어요.","vi":"Ho có thể kéo dài vài tuần.","situation":"informal"}],
["DTaP","영아","항생제"]),

t("benh-lao","결핵","bệnh lao","결핵균에 의한 감염병입니다. 폐결핵이 가장 흔합니다. 기침, 가래, 체중 감소가 특징입니다. 6개월 이상 약물 치료가 필요합니다. 통역 시 약물 복용 기간, 격리, 접촉자 검사를 설명해야 합니다.",
"Bệnh nhiễm trùng do vi khuẩn lao, phổ biến nhất là lao phổi","감염내과, 호흡기내과","한국에서 결핵 발생률은 OECD 국가 중 높은 편입니다. 베트남도 결핵 고부담 국가입니다.",
[{"mistake":"치료 기간 짧게 설명","correction":"최소 6개월, 내성균은 더 오래 치료","explanation":"치료 완료의 중요성을 강조합니다"},
{"mistake":"약물 부작용으로 중단 허용","correction":"의사 상담 없이 중단 시 내성균 위험","explanation":"내성 예방을 강조합니다"},
{"mistake":"가족 검사 미안내","correction":"밀접접촉자 검사 필수","explanation":"전파를 예방합니다"}],
[{"ko":"폐결핵으로 6개월간 약을 드셔야 합니다.","vi":"Lao phổi cần uống thuốc 6 tháng.","situation":"formal"},
{"ko":"가족분들도 검사받으셔야 합니다.","vi":"Người nhà cũng cần xét nghiệm.","situation":"formal"},
{"ko":"약 중간에 끊으면 안 돼요, 내성 생겨요.","vi":"Không được ngưng thuốc giữa chừng, sẽ kháng thuốc.","situation":"informal"}],
["항결핵제","흉부X선","BCG"]),

t("nhiem-hiv","HIV감염","nhiễm HIV","HIV 바이러스에 감염된 상태입니다. 치료 없이 진행하면 AIDS로 발전합니다. 항레트로바이러스 치료로 정상 수명이 가능합니다. 통역 시 비밀유지, 치료 효과, 편견 해소를 강조해야 합니다.",
"Nhiễm virus HIV, điều trị bằng thuốc kháng retrovirus có thể sống bình thường","감염내과","한국에서 HIV 치료는 큰 발전을 이루어 만성질환으로 관리됩니다. 편견 해소가 중요합니다.",
[{"mistake":"AIDS와 동일시","correction":"HIV 감염과 AIDS는 다른 단계, 치료로 AIDS 예방 가능","explanation":"정확한 이해를 돕습니다"},
{"mistake":"비밀유지 미강조","correction":"환자 동의 없이 정보 공개 불가","explanation":"환자 권리를 보호합니다"},
{"mistake":"치료 효과 과소평가","correction":"약물 복용으로 정상 수명, 전파 위험 최소화 가능","explanation":"치료 동기를 부여합니다"}],
[{"ko":"HIV 양성이지만 치료하면 정상 생활이 가능합니다.","vi":"HIV dương tính nhưng điều trị thì sống bình thường được.","situation":"formal"},
{"ko":"약을 꾸준히 드시면 바이러스가 검출 안 될 정도로 줄어요.","vi":"Uống thuốc đều đặn thì virus giảm đến mức không phát hiện được.","situation":"formal"},
{"ko":"요즘은 HIV도 당뇨처럼 관리하는 병이에요.","vi":"Bây giờ HIV cũng quản lý như tiểu đường.","situation":"informal"}],
["항레트로바이러스","AIDS","예방"]),

t("benh-giang-mai","매독","bệnh giang mai","성매개감염병으로, 트레포네마균에 의해 발생합니다. 단계적으로 진행하며 적절한 치료 없이 심각한 합병증을 유발합니다. 통역 시 파트너 검사, 치료, 산전 검사를 설명해야 합니다.",
"Bệnh lây truyền qua đường tình dục do vi khuẩn treponema","감염내과, 비뇨기과","한국에서 매독은 증가 추세입니다. 조기 발견과 치료가 중요합니다.",
[{"mistake":"완치 불가능하다고 설명","correction":"조기 매독은 페니실린으로 완치 가능","explanation":"치료를 독려합니다"},
{"mistake":"파트너 검사 미권유","correction":"성 파트너 동시 검사, 치료 필요","explanation":"재감염을 예방합니다"},
{"mistake":"임신부 검사 중요성 미강조","correction":"선천성 매독 예방 위해 산전 검사 필수","explanation":"태아 보호를 강조합니다"}],
[{"ko":"매독으로 페니실린 치료가 필요합니다.","vi":"Giang mai cần điều trị bằng penicillin.","situation":"formal"},
{"ko":"파트너분도 검사받으셔야 합니다.","vi":"Đối tác cũng cần xét nghiệm.","situation":"formal"},
{"ko":"일찍 치료하면 완전히 나아요.","vi":"Điều trị sớm thì khỏi hoàn toàn.","situation":"informal"}],
["페니실린","성매개감염","선천성매독"]),

t("viem-gan-a","A형간염","viêm gan A","A형간염 바이러스에 의한 급성 간염입니다. 오염된 음식, 물로 전파됩니다. 대부분 자연 회복되며 백신으로 예방 가능합니다. 통역 시 위생, 백신, 격리를 설명해야 합니다.",
"Viêm gan cấp do virus viêm gan A, lây qua thực phẩm và nước bị ô nhiễm","감염내과, 소화기내과","한국에서 A형간염은 30-40대에 많이 발생합니다. 백신 접종이 권장됩니다.",
[{"mistake":"만성화된다고 설명","correction":"A형간염은 만성화 안 됨, B/C와 다름","explanation":"정확한 정보를 제공합니다"},
{"mistake":"위생 교육 부족","correction":"손 씻기, 익혀 먹기로 예방 가능","explanation":"예방을 강조합니다"},
{"mistake":"백신 미권유","correction":"항체 없으면 백신 접종 권고","explanation":"예방의 중요성을 알립니다"}],
[{"ko":"A형간염으로 안정이 필요합니다.","vi":"Viêm gan A cần nghỉ ngơi.","situation":"formal"},
{"ko":"손 자주 씻고 음식 익혀 드세요.","vi":"Rửa tay thường xuyên và ăn chín.","situation":"formal"},
{"ko":"A형간염은 백신 맞으면 안 걸려요.","vi":"Tiêm vaccine thì không bị viêm gan A.","situation":"informal"}],
["백신","급성간염","위생"]),

t("viem-mang-bung","복막염","viêm phúc mạc","복강 내 복막에 염증이 생기는 응급 질환입니다. 심한 복통, 복부 강직이 특징입니다. 천공, 감염이 원인입니다. 통역 시 응급성, 수술 필요성을 설명해야 합니다.",
"Viêm màng bụng, bệnh cấp cứu gây đau bụng dữ dội","외과, 응급의학","한국에서 복막염은 충수염 천공, 소화성궤양 천공 등으로 발생합니다.",
[{"mistake":"진통제로 관찰해도 된다고 설명","correction":"응급 수술이 필요한 경우가 많음","explanation":"응급성을 강조합니다"},
{"mistake":"원인 규명 미강조","correction":"천공 부위 확인, 원인 치료 필요","explanation":"근본 치료를 설명합니다"},
{"mistake":"패혈증 위험 미설명","correction":"지연 시 패혈증으로 생명 위협","explanation":"신속한 치료를 독려합니다"}],
[{"ko":"복막염으로 응급 수술이 필요합니다.","vi":"Viêm phúc mạc cần mổ cấp cứu.","situation":"formal"},
{"ko":"배가 많이 아프고 딱딱해지면 바로 오세요.","vi":"Nếu bụng đau nhiều và cứng thì đến ngay.","situation":"formal"},
{"ko":"빨리 수술 안 하면 위험해요.","vi":"Không mổ nhanh thì nguy hiểm.","situation":"informal"}],
["천공","응급수술","패혈증"]),

t("nhiem-trung-huyet","패혈증","nhiễm trùng huyết","감염에 대한 전신 염증 반응으로 장기 부전이 발생하는 응급 상태입니다. 발열/저체온, 빈맥, 저혈압이 특징입니다. 즉각적인 항생제와 수액이 필요합니다. 통역 시 응급성, 중환자 치료를 설명해야 합니다.",
"Phản ứng viêm toàn thân do nhiễm trùng gây suy đa tạng","응급의학, 감염내과","한국에서 패혈증은 병원 내 주요 사망원인입니다. 조기 인지와 치료가 생존율을 결정합니다.",
[{"mistake":"일반 감염과 동일시","correction":"패혈증은 생명을 위협하는 응급상황","explanation":"심각성을 인지시킵니다"},
{"mistake":"1시간 법칙 미설명","correction":"진단 1시간 내 항생제 투여가 생존율에 중요","explanation":"신속한 치료를 강조합니다"},
{"mistake":"중환자실 입원 필요성 미설명","correction":"장기 부전 시 집중 모니터링 필요","explanation":"치료 계획을 설명합니다"}],
[{"ko":"패혈증으로 중환자실 치료가 필요합니다.","vi":"Nhiễm trùng huyết cần điều trị tại ICU.","situation":"formal"},
{"ko":"항생제를 빨리 시작해야 합니다.","vi":"Phải bắt đầu kháng sinh nhanh.","situation":"formal"},
{"ko":"감염이 온몸으로 퍼진 거예요, 심각해요.","vi":"Nhiễm trùng lan khắp cơ thể, nghiêm trọng.","situation":"informal"}],
["항생제","중환자실","장기부전"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"C배치 추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
