#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical 651-700번 용어 추가 (소화기내과, 내분비내과, 신장내과, 혈액종양내과)"""

import json

def t(s,k,v,hj,hjr,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":hj,"hanjaReading":hjr,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    # 소화기내과 (651-665)
    t("viem-da-day",
      "위염",
      "viêm dạ dày",
      "胃炎",
      "위(위 위) + 염(불꽃 염)",
      "위 점막에 염증이 생긴 상태로, 속쓰림, 소화불량, 오심 등이 나타납니다. 헬리코박터균 감염, 진통제, 음주, 스트레스 등이 원인입니다. 통역 시 위염과 위궤양의 차이를 설명하고, 헬리코박터 검사와 제균 치료의 중요성을 안내해야 합니다. 한국 음식의 자극성도 악화 요인이 될 수 있습니다.",
      "Tình trạng viêm niêm mạc dạ dày, gây ợ nóng, khó tiêu và buồn nôn.",
      "소화기내과, 가정의학과",
      "베트남에서는 위 불편함을 자가 치료하는 경향이 있지만, 한국에서는 위내시경 검사로 정확한 진단이 가능합니다. 또한 한국 음식의 매운맛과 발효음식이 위염을 악화시킬 수 있어 식습관 조절이 필요합니다.",
      [{"mistake":"위염과 위궤양을 동일시","correction":"위염(viêm)은 염증, 위궤양(loét)은 점막 손상으로 구분","explanation":"치료 기간과 강도가 다릅니다"},
       {"mistake":"헬리코박터 설명 누락","correction":"헬리코박터균(H. pylori) 감염 여부 확인 필요함을 설명","explanation":"균 제거로 재발을 줄일 수 있습니다"},
       {"mistake":"약물 복용 주의 설명 누락","correction":"진통제(NSAIDs)가 위염을 악화시킬 수 있음을 설명","explanation":"약 처방 시 위장 보호가 필요할 수 있습니다"}],
      [{"ko":"위염입니다. 위 내시경 결과 위 점막에 염증이 있습니다. 약물 치료와 식이 조절이 필요합니다.","vi":"Đây là viêm dạ dày. Nội soi cho thấy niêm mạc dạ dày bị viêm. Cần điều trị thuốc và điều chỉnh chế độ ăn.","situation":"formal"},
       {"ko":"위염이에요. 매운 거, 술 피하세요. 약 드시면 나아요.","vi":"Bị viêm dạ dày. Tránh đồ cay và rượu. Uống thuốc sẽ đỡ.","situation":"onsite"},
       {"ko":"위에 염증 생긴 거예요. 자극적인 음식 조심하세요.","vi":"Dạ dày bị viêm. Cẩn thận đồ ăn kích thích.","situation":"informal"}],
      ["속쓰림", "헬리코박터", "위내시경", "제산제"]),

    t("loet-da-day",
      "위궤양",
      "loét dạ dày",
      "胃潰瘍",
      "위(위 위) + 궤(헐 궤) + 양(종기 양)",
      "위 점막이 손상되어 깊은 상처(궤양)가 생긴 상태입니다. 식후 통증, 오심, 체중 감소가 나타나며, 출혈이나 천공 같은 합병증이 발생할 수 있습니다. 통역 시 헬리코박터 제균 치료와 위산 억제제 복용의 중요성을 강조하고, 흡연과 진통제가 악화 요인임을 설명해야 합니다.",
      "Tình trạng niêm mạc dạ dày bị tổn thương tạo thành vết loét sâu.",
      "소화기내과, 외과(합병증 시)",
      "베트남 근로자들이 위 통증을 참고 일하다가 천공이나 출혈로 응급실에 오는 경우가 있습니다. 검은 대변이나 피를 토하면 즉시 병원에 가야 함을 강조해야 합니다.",
      [{"mistake":"위궤양을 위암으로 오해하게 설명","correction":"대부분의 위궤양은 양성이며 치료로 완치됨을 설명","explanation":"불필요한 공포를 줄여야 합니다"},
       {"mistake":"합병증 징후 설명 누락","correction":"검은 변, 토혈은 응급 상황임을 설명","explanation":"출혈성 궤양은 생명을 위협합니다"},
       {"mistake":"재발 방지 설명 누락","correction":"헬리코박터 제균, 금연, 진통제 주의가 재발 방지에 중요함을 설명","explanation":"재발률이 높은 질환입니다"}],
      [{"ko":"위궤양입니다. 위에 깊은 상처가 있습니다. 헬리코박터 제균 치료를 시작합니다.","vi":"Đây là loét dạ dày. Có vết loét sâu ở dạ dày. Sẽ bắt đầu điều trị diệt H. pylori.","situation":"formal"},
       {"ko":"위궤양이에요. 위에 상처 났어요. 약 잘 드시고 담배 끊으세요.","vi":"Bị loét dạ dày. Dạ dày bị thương. Uống thuốc đều và bỏ thuốc lá.","situation":"onsite"},
       {"ko":"위에 구멍 비슷하게 났어요. 심하면 피 나요.","vi":"Dạ dày bị loét như thủng. Nặng thì chảy máu.","situation":"informal"}],
      ["복통", "헬리코박터", "위내시경", "토혈"]),

    t("trao-nguoc-da-day-thuc-quan",
      "역류성식도염",
      "trào ngược dạ dày thực quản",
      "逆流性食道炎",
      "역(거스를 역) + 류(흐를 류) + 성(성품 성) + 식(밥 식) + 도(길 도) + 염(불꽃 염)",
      "위산이 식도로 역류하여 식도 점막에 염증이 생기는 질환입니다. 가슴쓰림, 신물 올라옴, 만성 기침이 특징입니다. 비만, 야식, 눕는 자세 등이 악화 요인입니다. 통역 시 생활습관 개선이 약물 치료만큼 중요함을 강조하고, 식후 바로 눕지 않도록 안내해야 합니다.",
      "Bệnh lý khi axit dạ dày trào ngược lên thực quản gây viêm niêm mạc thực quản.",
      "소화기내과",
      "베트남 근로자들이 야식 습관이나 식후 바로 눕는 습관이 있으면 역류성 식도염이 악화될 수 있습니다. 한국에서는 PPI(양성자펌프억제제)가 효과적이지만 장기 복용 시 부작용도 있음을 설명해야 합니다.",
      [{"mistake":"역류성 식도염을 심장 문제로 오해하게 설명","correction":"가슴 통증이 식도 문제임을 명확히","explanation":"심장 문제와 감별이 필요합니다"},
       {"mistake":"생활습관 개선 설명 누락","correction":"체중 관리, 야식 금지, 식후 3시간 후 눕기 등 안내","explanation":"약물만으로는 완전히 조절되지 않습니다"},
       {"mistake":"장기 약물 복용 부작용 설명 누락","correction":"PPI 장기 복용 시 골다공증, 감염 위험 증가 가능성 설명","explanation":"필요시만 복용해야 합니다"}],
      [{"ko":"역류성 식도염입니다. 위산이 식도로 올라와 염증이 생겼습니다.","vi":"Đây là trào ngược dạ dày thực quản. Axit dạ dày trào lên thực quản gây viêm.","situation":"formal"},
       {"ko":"역류성 식도염이에요. 신물 올라오죠? 야식 끊고 식후에 바로 눕지 마세요.","vi":"Bị trào ngược. Hay bị ợ chua phải không? Bỏ ăn đêm và không nằm ngay sau ăn.","situation":"onsite"},
       {"ko":"위산이 올라와서 그래요. 밤에 늦게 먹지 마세요.","vi":"Do axit dạ dày trào lên. Đừng ăn khuya.","situation":"informal"}],
      ["가슴쓰림", "위산", "PPI", "생활습관"]),

    t("viem-gan",
      "간염",
      "viêm gan",
      "肝炎",
      "간(간 간) + 염(불꽃 염)",
      "간에 염증이 생긴 상태로, 바이러스(A, B, C형 등), 알코올, 약물, 자가면역 등이 원인입니다. 피로, 황달, 소화불량이 나타나며, 만성화 시 간경변이나 간암으로 진행할 수 있습니다. 통역 시 간염의 유형과 전파 경로를 정확히 설명하고, B형간염 보균자의 정기 검진 중요성을 강조해야 합니다.",
      "Tình trạng viêm gan, có thể do virus (A, B, C), rượu, thuốc hoặc tự miễn.",
      "소화기내과, 감염내과",
      "베트남은 B형간염 유병률이 높은 국가입니다. 한국에 입국한 베트남 근로자들 중 B형간염 보균자가 많을 수 있어, 정기적인 간 기능 검사와 간암 검진의 중요성을 안내해야 합니다.",
      [{"mistake":"간염 유형을 구분하지 않음","correction":"A형(급성), B/C형(만성화 가능) 등 구분 필요","explanation":"치료와 예후가 다릅니다"},
       {"mistake":"B형간염 전파 경로 오해","correction":"혈액, 성관계로 전파되며 일상 접촉으로는 전파 안 됨을 설명","explanation":"사회적 차별을 줄여야 합니다"},
       {"mistake":"보균자 관리 설명 누락","correction":"B형간염 보균자는 6개월마다 검진 필요함을 강조","explanation":"간암 조기 발견이 중요합니다"}],
      [{"ko":"B형 간염 보균자입니다. 현재 활동성은 아니지만 정기 검진이 필요합니다.","vi":"Là người mang vi rút viêm gan B. Hiện không hoạt động nhưng cần khám định kỳ.","situation":"formal"},
       {"ko":"B형 간염 있어요. 6개월마다 검사 받으세요. 간암 예방 차원에서요.","vi":"Có viêm gan B. Cứ 6 tháng khám một lần. Để phòng ngừa ung thư gan.","situation":"onsite"},
       {"ko":"간염 보균자예요. 정기 검사 꼭 받아야 해요.","vi":"Là người mang viêm gan. Phải khám định kỳ.","situation":"informal"}],
      ["황달", "피로", "간기능검사", "간암"]),

    t("xo-gan",
      "간경변",
      "xơ gan",
      "肝硬變",
      "간(간 간) + 경(굳을 경) + 변(변할 변)",
      "간이 지속적인 손상으로 딱딱해지고 기능이 저하되는 말기 간질환입니다. 복수, 황달, 의식 변화, 출혈 경향이 나타납니다. 알코올, B/C형 간염, 지방간이 주요 원인입니다. 통역 시 간경변이 비가역적임을 설명하면서도 합병증 관리로 생존 기간을 늘릴 수 있음을 안내해야 합니다.",
      "Bệnh gan giai đoạn cuối với gan bị cứng và suy giảm chức năng do tổn thương liên tục.",
      "소화기내과, 간이식외과",
      "베트남 근로자들 중 음주 습관이 있거나 B형간염 보균자인 경우 간경변 위험이 있습니다. 한국에서는 간경변 합병증 관리와 필요시 간이식이 가능함을 설명할 수 있습니다.",
      [{"mistake":"간경변을 완치 가능하다고 설명","correction":"비가역적이지만 진행을 늦추고 합병증을 관리할 수 있음을 설명","explanation":"현실적인 치료 목표를 제시해야 합니다"},
       {"mistake":"합병증 설명 누락","correction":"복수, 식도정맥류 출혈, 간성 뇌증 등 주요 합병증 안내","explanation":"합병증 관리가 핵심입니다"},
       {"mistake":"금주의 중요성 과소평가","correction":"원인에 관계없이 절대 금주가 필수임을 강조","explanation":"음주는 간 손상을 가속화합니다"}],
      [{"ko":"간경변 진단입니다. 간이 딱딱해져서 기능이 떨어졌습니다. 절대 금주하셔야 합니다.","vi":"Chẩn đoán xơ gan. Gan bị cứng và suy giảm chức năng. Phải kiêng rượu hoàn toàn.","situation":"formal"},
       {"ko":"간경변이에요. 간이 굳어버렸어요. 술 절대 안 돼요.","vi":"Bị xơ gan. Gan đã cứng. Tuyệt đối không được uống rượu.","situation":"onsite"},
       {"ko":"간이 망가진 거예요. 술 마시면 더 나빠져요.","vi":"Gan đã hỏng. Uống rượu sẽ tệ hơn.","situation":"informal"}],
      ["복수", "황달", "간이식", "금주"]),

    t("ung-thu-gan",
      "간암",
      "ung thư gan",
      "肝癌",
      "간(간 간) + 암(바위 암)",
      "간에서 발생하는 악성 종양으로, B/C형 간염, 간경변, 알코올이 주요 위험요인입니다. 초기에는 증상이 없다가 복통, 체중 감소, 황달이 나타납니다. 통역 시 고위험군(간염 보균자, 간경변 환자)의 정기 검진으로 조기 발견이 가능함을 강조하고, 다양한 치료 옵션을 안내해야 합니다.",
      "Khối u ác tính phát sinh ở gan, các yếu tố nguy cơ chính là viêm gan B/C, xơ gan và rượu.",
      "소화기내과, 종양내과, 간이식외과",
      "베트남은 B형간염으로 인한 간암 발생률이 높습니다. 한국에서는 6개월마다 간초음파와 AFP 검사로 간암 선별 검사가 가능하며, 조기 발견 시 완치율이 높음을 설명해야 합니다.",
      [{"mistake":"간암을 불치병으로만 설명","correction":"조기 발견 시 수술, 고주파 치료 등으로 완치 가능함을 설명","explanation":"검진의 중요성을 강조합니다"},
       {"mistake":"선별 검사 안내 누락","correction":"고위험군은 6개월마다 초음파와 AFP 검사 필요함을 안내","explanation":"조기 발견이 생존율을 높입니다"},
       {"mistake":"간이식 옵션 설명 누락","correction":"진행된 경우에도 간이식으로 완치 가능함을 설명","explanation":"희망을 유지하게 합니다"}],
      [{"ko":"간암이 발견되었습니다. 크기가 작아 수술로 완치가 가능합니다.","vi":"Đã phát hiện ung thư gan. Kích thước nhỏ nên có thể chữa khỏi bằng phẫu thuật.","situation":"formal"},
       {"ko":"간에 암이 있어요. 빨리 발견해서 다행이에요. 치료하면 나을 수 있어요.","vi":"Có ung thư ở gan. May mà phát hiện sớm. Điều trị thì có thể khỏi.","situation":"onsite"},
       {"ko":"간암이에요. 일찍 찾아서 치료 가능해요.","vi":"Bị ung thư gan. Phát hiện sớm nên điều trị được.","situation":"informal"}],
      ["간염", "간경변", "간초음파", "AFP"]),

    t("viem-tuy-cap",
      "급성췌장염",
      "viêm tụy cấp",
      "急性膵臟炎",
      "급(급할 급) + 성(성품 성) + 췌(이자 췌) + 장(오장 장) + 염(불꽃 염)",
      "췌장에 급성 염증이 발생하여 심한 복통, 구역, 구토가 나타나는 응급 상황입니다. 담석과 음주가 가장 흔한 원인이며, 중증 시 장기 부전으로 사망할 수 있습니다. 통역 시 금식과 수액 치료의 중요성을 설명하고, 재발 방지를 위해 원인 제거(담석 제거, 금주)가 필수임을 강조해야 합니다.",
      "Tình huống cấp cứu với viêm tụy cấp tính gây đau bụng dữ dội, buồn nôn và nôn.",
      "소화기내과, 응급의학과, 중환자의학과",
      "베트남 근로자들의 음주 문화로 인해 알코올성 췌장염이 발생할 수 있습니다. 한 번 췌장염을 앓으면 재발 위험이 높으므로, 절대 금주의 중요성을 강조해야 합니다.",
      [{"mistake":"췌장염 위치 설명 오류","correction":"췌장(tụy)은 위 뒤쪽에 있어 등으로 뻗치는 통증이 특징임을 설명","explanation":"통증 양상이 진단에 중요합니다"},
       {"mistake":"금식의 중요성 설명 누락","correction":"췌장을 쉬게 하기 위해 금식이 필수임을 설명","explanation":"음식 섭취가 췌장을 자극합니다"},
       {"mistake":"재발 방지 설명 누락","correction":"담석 제거, 금주 등 원인 제거가 필수임을 강조","explanation":"재발 시 만성 췌장염으로 진행할 수 있습니다"}],
      [{"ko":"급성 췌장염입니다. 췌장에 심한 염증이 있습니다. 금식하고 입원 치료가 필요합니다.","vi":"Đây là viêm tụy cấp. Tụy bị viêm nặng. Cần nhịn ăn và nhập viện điều trị.","situation":"formal"},
       {"ko":"췌장염이에요. 배가 많이 아프죠? 아무것도 드시면 안 돼요.","vi":"Bị viêm tụy. Đau bụng nhiều phải không? Không được ăn gì.","situation":"onsite"},
       {"ko":"췌장 염증이에요. 술 때문이에요. 술 끊어야 해요.","vi":"Viêm tụy. Do rượu. Phải bỏ rượu.","situation":"informal"}],
      ["복통", "담석", "금주", "금식"]),

    t("viem-ruot",
      "장염",
      "viêm ruột",
      "腸炎",
      "장(창자 장) + 염(불꽃 염)",
      "장(소장 또는 대장)에 염증이 생긴 상태로, 복통, 설사, 구역, 발열이 나타납니다. 바이러스, 세균, 기생충 감염이 주요 원인입니다. 통역 시 급성 장염은 대부분 자연 회복되지만, 탈수 예방이 중요함을 설명하고, 피가 섞인 설사나 고열은 병원 방문이 필요함을 안내해야 합니다.",
      "Tình trạng viêm ruột (ruột non hoặc ruột già), gây đau bụng, tiêu chảy, buồn nôn và sốt.",
      "소화기내과, 감염내과, 응급의학과",
      "베트남 근로자들이 한국 음식에 적응하는 과정에서 장염이 발생할 수 있습니다. 또한 생굴 등 익히지 않은 해산물 섭취 후 노로바이러스 감염이 흔하므로 주의가 필요합니다.",
      [{"mistake":"장염에 무조건 항생제 필요하다고 설명","correction":"대부분 바이러스성으로 항생제 불필요, 수분 보충이 핵심","explanation":"불필요한 항생제는 장내 세균총을 해칩니다"},
       {"mistake":"탈수 위험성 설명 누락","correction":"설사로 인한 탈수가 위험할 수 있어 수분/전해질 보충 중요","explanation":"특히 노인, 어린이는 탈수 위험이 큽니다"},
       {"mistake":"위험 징후 설명 누락","correction":"피가 섞인 설사, 고열, 탈수 증상 시 병원 방문 필요함을 안내","explanation":"세균성 장염이나 합병증일 수 있습니다"}],
      [{"ko":"급성 장염입니다. 바이러스 감염으로 보입니다. 수분 섭취가 중요합니다.","vi":"Đây là viêm ruột cấp. Có vẻ do nhiễm virus. Bổ sung nước rất quan trọng.","situation":"formal"},
       {"ko":"장염이에요. 물 많이 마시고 죽 같은 부드러운 거 드세요.","vi":"Bị viêm ruột. Uống nhiều nước và ăn cháo mềm.","situation":"onsite"},
       {"ko":"배탈 난 거예요. 물 마시고 쉬면 나아요.","vi":"Bị đau bụng tiêu chảy. Uống nước và nghỉ ngơi sẽ đỡ.","situation":"informal"}],
      ["설사", "복통", "탈수", "수분보충"]),

    t("hoi-chung-ruot-kich-thich",
      "과민성장증후군",
      "hội chứng ruột kích thích",
      "過敏性腸症候群",
      "과(지나칠 과) + 민(민감할 민) + 성(성품 성) + 장(창자 장) + 증(증상 증) + 후(뒤 후) + 군(무리 군)",
      "기질적 이상 없이 복통, 복부 팽만감, 배변 습관 변화(설사/변비)가 반복되는 기능성 장질환입니다. 스트레스가 주요 악화 요인입니다. 통역 시 검사에서 이상이 없어도 증상은 실재함을 인정하고, 식이조절과 스트레스 관리의 중요성을 설명해야 합니다.",
      "Bệnh chức năng với đau bụng, đầy hơi và thay đổi thói quen đi tiêu tái phát mà không có bất thường thực thể.",
      "소화기내과, 정신건강의학과",
      "베트남 근로자들이 한국에서의 스트레스(언어 장벽, 향수병 등)로 과민성장증후군이 악화될 수 있습니다. 심리적 지지와 함께 FODMAP 식이 등 관리 방법을 안내해야 합니다.",
      [{"mistake":"과민성장증후군을 꾀병으로 취급","correction":"기능성 질환이지만 증상과 고통은 실재함을 인정","explanation":"환자의 신뢰를 얻어야 치료에 협조합니다"},
       {"mistake":"스트레스 관리 설명 누락","correction":"스트레스가 증상을 악화시키므로 관리가 중요함을 설명","explanation":"약물만으로는 완전히 조절되지 않습니다"},
       {"mistake":"식이 조절 안내 누락","correction":"가스 유발 음식(FODMAP) 제한이 도움될 수 있음을 안내","explanation":"개인별로 악화 요인이 다릅니다"}],
      [{"ko":"과민성장증후군입니다. 검사상 이상은 없지만 장이 예민한 상태입니다.","vi":"Đây là hội chứng ruột kích thích. Xét nghiệm bình thường nhưng ruột đang nhạy cảm.","situation":"formal"},
       {"ko":"과민성 장증후군이에요. 스트레스받으면 배 아프죠? 장이 예민한 거예요.","vi":"Bị hội chứng ruột kích thích. Stress thì đau bụng phải không? Ruột đang nhạy cảm.","situation":"onsite"},
       {"ko":"장이 예민해서 그래요. 긴장하면 더 아파요.","vi":"Ruột nhạy cảm nên thế. Căng thẳng thì đau thêm.","situation":"informal"}],
      ["복통", "설사", "변비", "스트레스"]),

    t("viem-ruot-man",
      "염증성장질환",
      "viêm ruột mạn",
      "炎症性腸疾患",
      "염(불꽃 염) + 증(증상 증) + 성(성품 성) + 장(창자 장) + 질(병 질) + 환(걱정 환)",
      "크론병과 궤양성 대장염을 포함하는 만성 염증성 장질환입니다. 만성 설사, 복통, 혈변, 체중 감소가 특징이며, 평생 관리가 필요합니다. 통역 시 자가면역 질환임을 설명하고, 약물 치료의 중요성과 장기 합병증(대장암 등) 감시의 필요성을 안내해야 합니다.",
      "Bệnh viêm ruột mạn tính bao gồm bệnh Crohn và viêm loét đại tràng.",
      "소화기내과",
      "베트남에서는 염증성 장질환의 인식이 낮습니다. 한국에서는 생물학적 제제 등 최신 치료가 가능하며, 질병을 잘 조절하면 정상적인 생활이 가능함을 설명해야 합니다.",
      [{"mistake":"감염성 장염과 혼동","correction":"염증성 장질환은 자가면역 질환으로 평생 관리 필요함을 설명","explanation":"치료 접근이 완전히 다릅니다"},
       {"mistake":"크론병과 궤양성 대장염 구분 안 함","correction":"크론병(Crohn)은 전 소화관, 궤양성 대장염은 대장에 국한됨을 설명","explanation":"치료 전략이 다릅니다"},
       {"mistake":"생물학적 제제 설명 누락","correction":"기존 약에 반응 없으면 생물학적 제제로 좋은 효과를 볼 수 있음을 안내","explanation":"최신 치료 옵션입니다"}],
      [{"ko":"궤양성 대장염입니다. 대장에 만성 염증이 있습니다. 평생 관리가 필요합니다.","vi":"Đây là viêm loét đại tràng. Đại tràng bị viêm mạn tính. Cần theo dõi suốt đời.","situation":"formal"},
       {"ko":"염증성 장질환이에요. 약 꾸준히 드셔야 해요. 안 먹으면 재발해요.","vi":"Bị bệnh viêm ruột. Phải uống thuốc đều. Không uống sẽ tái phát.","situation":"onsite"},
       {"ko":"장에 만성 염증이에요. 자가면역 문제예요. 평생 관리해요.","vi":"Ruột bị viêm mạn. Là vấn đề tự miễn. Phải theo dõi suốt đời.","situation":"informal"}],
      ["혈변", "설사", "크론병", "생물학적제제"]),

    # 내분비내과 (666-675)
    t("tieu-duong-type-1",
      "제1형 당뇨병",
      "tiểu đường type 1",
      "第一型糖尿病",
      "제(차례 제) + 일(한 일) + 형(모양 형) + 당(엿 당) + 뇨(오줌 뇨) + 병(병 병)",
      "췌장의 인슐린 분비 세포가 파괴되어 인슐린이 절대적으로 부족한 당뇨병입니다. 주로 소아청소년에서 발병하며, 평생 인슐린 주사가 필요합니다. 통역 시 제2형과 달리 생활습관과 무관하게 발생함을 설명하고, 인슐린은 생명 유지에 필수적임을 강조해야 합니다.",
      "Đái tháo đường do tế bào sản xuất insulin của tụy bị phá hủy, thiếu insulin tuyệt đối.",
      "내분비내과, 소아청소년과",
      "베트남에서는 당뇨병을 노인병으로 인식하는 경향이 있어, 젊은 환자나 소아에서의 제1형 당뇨병에 대한 인식이 낮습니다. 한국에서는 인슐린 펌프, 연속혈당측정기 등 첨단 기기를 사용할 수 있음을 안내할 수 있습니다.",
      [{"mistake":"제1형과 제2형 당뇨병 구분 안 함","correction":"제1형은 인슐린 절대 부족, 제2형은 인슐린 저항성이 주원인","explanation":"치료 전략이 완전히 다릅니다"},
       {"mistake":"인슐린 거부감 해소 실패","correction":"제1형에서 인슐린은 선택이 아닌 생존 필수임을 강조","explanation":"인슐린 없이는 생명이 위험합니다"},
       {"mistake":"저혈당 대처법 설명 누락","correction":"저혈당 증상과 응급 대처법(당분 섭취) 교육 필요","explanation":"저혈당은 생명을 위협할 수 있습니다"}],
      [{"ko":"제1형 당뇨병입니다. 인슐린이 거의 분비되지 않아 평생 인슐린 주사가 필요합니다.","vi":"Đây là tiểu đường type 1. Insulin hầu như không tiết ra nên cần tiêm insulin suốt đời.","situation":"formal"},
       {"ko":"1형 당뇨예요. 인슐린 주사 꼭 맞아야 해요. 안 맞으면 위험해요.","vi":"Tiểu đường type 1. Phải tiêm insulin. Không tiêm thì nguy hiểm.","situation":"onsite"},
       {"ko":"췌장에서 인슐린이 안 나와서 주사 맞아야 해요.","vi":"Tụy không tiết insulin nên phải tiêm.","situation":"informal"}],
      ["인슐린", "혈당", "저혈당", "췌장"]),

    t("tieu-duong-type-2",
      "제2형 당뇨병",
      "tiểu đường type 2",
      "第二型糖尿病",
      "제(차례 제) + 이(두 이) + 형(모양 형) + 당(엿 당) + 뇨(오줌 뇨) + 병(병 병)",
      "인슐린 저항성과 상대적 인슐린 부족으로 혈당이 높아지는 가장 흔한 당뇨병입니다. 비만, 운동 부족, 유전이 주요 원인입니다. 통역 시 생활습관 개선이 치료의 기본임을 강조하고, 합병증(신경병증, 신장병, 망막병증 등) 예방을 위한 혈당 조절의 중요성을 설명해야 합니다.",
      "Đái tháo đường phổ biến nhất do kháng insulin và thiếu insulin tương đối.",
      "내분비내과, 가정의학과",
      "베트남 근로자들이 한국에서 탄수화물 위주의 식사와 운동 부족으로 당뇨병이 악화될 수 있습니다. 한국의 당뇨 관리 시스템(정기 검진, 자가혈당측정)을 활용하도록 안내해야 합니다.",
      [{"mistake":"당뇨병을 단순 혈당 문제로 설명","correction":"전신 혈관 합병증을 유발하는 심각한 질환임을 설명","explanation":"합병증 예방의 동기를 부여합니다"},
       {"mistake":"약만 먹으면 된다고 설명","correction":"식이조절, 운동이 약물만큼 중요함을 강조","explanation":"생활습관 개선 없이는 조절이 어렵습니다"},
       {"mistake":"합병증 검진 안내 누락","correction":"눈, 신장, 발 정기 검진 필요성을 안내","explanation":"조기 발견으로 합병증을 예방합니다"}],
      [{"ko":"제2형 당뇨병입니다. 혈당 조절을 위해 식이요법, 운동, 약물 치료가 필요합니다.","vi":"Đây là tiểu đường type 2. Cần chế độ ăn, tập thể dục và thuốc để kiểm soát đường huyết.","situation":"formal"},
       {"ko":"당뇨병이에요. 밥 적게, 운동 많이, 약 잘 드세요.","vi":"Bị tiểu đường. Ăn ít cơm, tập thể dục nhiều, uống thuốc đều.","situation":"onsite"},
       {"ko":"혈당 높은 거예요. 단 거, 밥 많이 먹으면 안 돼요.","vi":"Đường huyết cao. Không được ăn đồ ngọt và cơm nhiều.","situation":"informal"}],
      ["혈당", "인슐린저항성", "합병증", "생활습관"]),

    t("cuong-giap",
      "갑상선기능항진증",
      "cường giáp",
      "甲狀腺機能亢進症",
      "갑(갑옷 갑) + 상(모양 상) + 선(샘 선) + 기(틀 기) + 능(능할 능) + 항(높을 항) + 진(나아갈 진) + 증(증상 증)",
      "갑상선 호르몬이 과다 분비되어 대사가 항진되는 질환입니다. 체중 감소, 빈맥, 손 떨림, 더위 못 참음, 눈 돌출이 특징입니다. 그레이브스병이 가장 흔한 원인입니다. 통역 시 치료하지 않으면 심장에 무리가 가고, 갑상선 위기로 사망할 수 있음을 설명해야 합니다.",
      "Bệnh lý khi hormone tuyến giáp tiết ra quá nhiều làm tăng chuyển hóa.",
      "내분비내과",
      "베트남 근로자들이 체중 감소를 좋게 여기거나, 두근거림을 스트레스로 생각하여 치료가 늦어질 수 있습니다. 치료하지 않으면 심방세동, 골다공증 등 합병증이 발생함을 설명해야 합니다.",
      [{"mistake":"갑상선 항진을 좋은 것으로 오해하게 설명","correction":"대사 항진이 심장과 뼈에 부담을 준다는 것을 설명","explanation":"치료 필요성의 동기를 부여합니다"},
       {"mistake":"눈 증상 설명 누락","correction":"그레이브스병에서 눈 돌출, 시력 문제가 발생할 수 있음을 안내","explanation":"안과 검진이 필요할 수 있습니다"},
       {"mistake":"치료 옵션 설명 불충분","correction":"약물, 방사성 요오드, 수술 등 다양한 치료 옵션 안내","explanation":"환자 상황에 맞는 치료를 선택합니다"}],
      [{"ko":"갑상선기능항진증입니다. 갑상선 호르몬이 과다 분비되고 있습니다. 약물 치료를 시작합니다.","vi":"Đây là cường giáp. Hormone tuyến giáp đang tiết quá nhiều. Sẽ bắt đầu điều trị thuốc.","situation":"formal"},
       {"ko":"갑상선 항진증이에요. 두근거리고 살 빠지죠? 약 드시면 나아요.","vi":"Bị cường giáp. Tim đập nhanh và sụt cân phải không? Uống thuốc sẽ đỡ.","situation":"onsite"},
       {"ko":"갑상선이 너무 많이 일해서 그래요. 약으로 조절해요.","vi":"Tuyến giáp hoạt động quá nhiều. Kiểm soát bằng thuốc.","situation":"informal"}],
      ["빈맥", "체중감소", "그레이브스병", "항갑상선제"]),

    t("suy-giap",
      "갑상선기능저하증",
      "suy giáp",
      "甲狀腺機能低下症",
      "갑(갑옷 갑) + 상(모양 상) + 선(샘 선) + 기(틀 기) + 능(능할 능) + 저(낮을 저) + 하(아래 하) + 증(증상 증)",
      "갑상선 호르몬이 부족하여 대사가 저하되는 질환입니다. 피로, 체중 증가, 추위 못 참음, 변비, 우울감이 특징입니다. 하시모토 갑상선염이 가장 흔한 원인입니다. 통역 시 증상이 서서히 나타나 노화로 오인하기 쉬움을 설명하고, 갑상선 호르몬제 복용으로 정상 생활이 가능함을 안내해야 합니다.",
      "Bệnh lý khi hormone tuyến giáp thiếu hụt làm giảm chuyển hóa.",
      "내분비내과",
      "베트남 근로자들이 피로와 체중 증가를 단순 과로나 식습관 탓으로 여겨 검사를 미루는 경우가 있습니다. 간단한 혈액검사로 진단이 가능하고, 약물로 쉽게 치료됨을 설명해야 합니다.",
      [{"mistake":"갑상선 저하를 영양 문제로 오해하게 설명","correction":"호르몬 부족으로 인한 전신 대사 저하임을 설명","explanation":"식이 조절만으로는 해결되지 않습니다"},
       {"mistake":"평생 약 복용에 대한 거부감 해소 실패","correction":"갑상선 호르몬제는 부작용이 거의 없고 정상 호르몬 보충일 뿐임을 설명","explanation":"복용 순응도가 중요합니다"},
       {"mistake":"임신 중 중요성 설명 누락","correction":"임신 중 갑상선 저하는 태아 발달에 영향을 미치므로 관리가 중요함을 설명","explanation":"가임기 여성에게 특히 중요합니다"}],
      [{"ko":"갑상선기능저하증입니다. 갑상선 호르몬이 부족합니다. 호르몬제를 복용하시면 정상화됩니다.","vi":"Đây là suy giáp. Thiếu hormone tuyến giáp. Uống thuốc hormone sẽ bình thường.","situation":"formal"},
       {"ko":"갑상선 저하증이에요. 피곤하고 살찌죠? 약 먹으면 좋아져요.","vi":"Bị suy giáp. Mệt và tăng cân phải không? Uống thuốc sẽ đỡ.","situation":"onsite"},
       {"ko":"갑상선이 약해서 그래요. 약으로 호르몬 보충하면 돼요.","vi":"Tuyến giáp yếu nên thế. Bổ sung hormone bằng thuốc là được.","situation":"informal"}],
      ["피로", "체중증가", "갑상선호르몬", "하시모토"]),

    t("loang-xuong",
      "골다공증",
      "loãng xương",
      "骨多孔症",
      "골(뼈 골) + 다(많을 다) + 공(빌 공) + 증(증상 증)",
      "뼈의 밀도가 감소하고 구조가 약해져서 골절 위험이 높아지는 질환입니다. 폐경 후 여성, 고령자에서 흔하며, 증상 없이 진행되다가 골절로 발견됩니다. 통역 시 예방(칼슘, 비타민D, 운동)과 조기 검진(골밀도 검사)의 중요성을 강조하고, 약물로 골절 위험을 줄일 수 있음을 설명해야 합니다.",
      "Bệnh lý với mật độ xương giảm và cấu trúc xương yếu đi, tăng nguy cơ gãy xương.",
      "내분비내과, 류마티스내과, 정형외과",
      "베트남 여성 근로자들 중 폐경기 이후 골다공증 위험이 있습니다. 한국에서는 골밀도 검사가 건강검진에 포함되어 있으며, 조기 발견과 치료로 골절을 예방할 수 있음을 안내해야 합니다.",
      [{"mistake":"골다공증을 노화로만 설명","correction":"치료와 예방이 가능한 질환임을 강조","explanation":"적극적 관리로 골절을 예방합니다"},
       {"mistake":"증상 없으면 괜찮다고 설명","correction":"증상 없이 진행되다 골절로 발견되므로 검진이 중요함을 설명","explanation":"침묵의 질환입니다"},
       {"mistake":"칼슘만 강조하고 다른 요소 누락","correction":"비타민D, 체중 부하 운동, 약물 치료도 중요함을 설명","explanation":"종합적 접근이 필요합니다"}],
      [{"ko":"골다공증입니다. 뼈 밀도가 낮아 골절 위험이 높습니다. 약물 치료와 생활습관 개선이 필요합니다.","vi":"Đây là loãng xương. Mật độ xương thấp nên nguy cơ gãy xương cao. Cần điều trị thuốc và thay đổi lối sống.","situation":"formal"},
       {"ko":"뼈가 약해졌어요. 넘어지면 쉽게 부러져요. 약 드시고 운동하세요.","vi":"Xương yếu đi. Ngã thì dễ gãy. Uống thuốc và tập thể dục.","situation":"onsite"},
       {"ko":"골다공증이에요. 칼슘이랑 비타민D 드세요.","vi":"Bị loãng xương. Uống canxi và vitamin D.","situation":"informal"}],
      ["골밀도", "골절", "칼슘", "비타민D"]),

    t("suy-tuyen-thuong-than",
      "부신기능저하증",
      "suy tuyến thượng thận",
      "副腎機能低下症",
      "부(도울 부) + 신(콩팥 신) + 기(틀 기) + 능(능할 능) + 저(낮을 저) + 하(아래 하) + 증(증상 증)",
      "부신에서 코르티솔 등 호르몬 분비가 부족한 상태입니다. 피로, 체중 감소, 저혈압, 피부 색소 침착이 특징입니다. 스트레스 상황에서 부신 위기로 사망할 수 있어 위험합니다. 통역 시 스테로이드 복용 중단의 위험성과 응급 시 주사 필요성을 강조해야 합니다.",
      "Tình trạng tuyến thượng thận tiết không đủ hormone như cortisol.",
      "내분비내과, 응급의학과",
      "베트남 근로자들이 피로를 과로로 여기거나, 스테로이드 약물을 임의로 중단하는 경우가 있습니다. 부신기능저하 환자는 스트레스 시 호르몬 용량 조절이 필요함을 반드시 교육해야 합니다.",
      [{"mistake":"부신 위기의 위험성 설명 누락","correction":"스트레스(감염, 수술 등) 시 호르몬 부족으로 쇼크 가능함을 설명","explanation":"응급 상황 대비가 필수입니다"},
       {"mistake":"스테로이드 임의 중단 경고 누락","correction":"갑자기 약을 끊으면 생명이 위험함을 강조","explanation":"용량 조절은 반드시 의사와 상의해야 합니다"},
       {"mistake":"응급 대처 교육 누락","correction":"응급 시 히드로코르티손 주사와 의료진에게 알릴 사항 교육","explanation":"환자 스스로 대처할 수 있어야 합니다"}],
      [{"ko":"부신기능저하증입니다. 스테로이드 호르몬 보충이 필요하며, 절대 임의로 중단하면 안 됩니다.","vi":"Đây là suy tuyến thượng thận. Cần bổ sung hormone steroid và tuyệt đối không được tự ý ngừng thuốc.","situation":"formal"},
       {"ko":"부신 기능이 약해요. 약 꼭 드세요. 안 먹으면 위험해요.","vi":"Tuyến thượng thận yếu. Phải uống thuốc. Không uống thì nguy hiểm.","situation":"onsite"},
       {"ko":"호르몬이 부족해서 약 먹어야 해요. 끊으면 큰일 나요.","vi":"Thiếu hormone nên phải uống thuốc. Ngừng thì nguy.","situation":"informal"}],
      ["피로", "저혈압", "스테로이드", "부신위기"]),

    # 신장내과 (676-685)
    t("suy-than-cap",
      "급성신부전",
      "suy thận cấp",
      "急性腎不全",
      "급(급할 급) + 성(성품 성) + 신(콩팥 신) + 부(아닐 부) + 전(온전할 전)",
      "신장 기능이 갑자기 저하되어 노폐물과 수분을 제대로 배출하지 못하는 응급 상황입니다. 소변량 감소, 부종, 전해질 이상이 나타납니다. 탈수, 약물, 감염, 요로 폐쇄 등이 원인입니다. 통역 시 원인을 제거하면 회복 가능한 경우가 많음을 설명하고, 투석이 일시적으로 필요할 수 있음을 안내해야 합니다.",
      "Tình huống cấp cứu khi chức năng thận giảm đột ngột, không thải được chất thải và nước.",
      "신장내과, 응급의학과, 중환자의학과",
      "베트남 근로자들이 탈수나 진통제 과용으로 급성 신부전이 발생할 수 있습니다. 여름철 야외 작업 시 충분한 수분 섭취와 진통제 남용 주의를 당부해야 합니다.",
      [{"mistake":"급성과 만성 신부전 구분 안 함","correction":"급성(cấp)은 회복 가능, 만성(mạn)은 비가역적임을 구분","explanation":"예후와 치료 전략이 다릅니다"},
       {"mistake":"투석을 영구적인 것으로 오해하게 설명","correction":"급성 신부전의 투석은 일시적이며 회복 후 중단 가능함을 설명","explanation":"환자의 불안을 줄여줍니다"},
       {"mistake":"원인 제거의 중요성 누락","correction":"탈수 교정, 원인 약물 중단 등으로 회복 가능함을 설명","explanation":"적극적 원인 치료가 핵심입니다"}],
      [{"ko":"급성 신부전입니다. 신장 기능이 갑자기 떨어졌습니다. 원인 치료와 일시적 투석이 필요할 수 있습니다.","vi":"Đây là suy thận cấp. Chức năng thận giảm đột ngột. Có thể cần điều trị nguyên nhân và lọc máu tạm thời.","situation":"formal"},
       {"ko":"급성으로 신장이 안 좋아졌어요. 원인 찾아서 치료하면 회복돼요.","vi":"Thận yếu đi đột ngột. Tìm nguyên nhân và điều trị thì sẽ hồi phục.","situation":"onsite"},
       {"ko":"신장이 갑자기 안 돌아가요. 치료하면 나아질 수 있어요.","vi":"Thận đột ngột không hoạt động. Điều trị có thể đỡ.","situation":"informal"}],
      ["소변량감소", "부종", "투석", "크레아티닌"]),

    t("suy-than-man",
      "만성신부전",
      "suy thận mạn",
      "慢性腎不全",
      "만(오랠 만) + 성(성품 성) + 신(콩팥 신) + 부(아닐 부) + 전(온전할 전)",
      "신장 기능이 점진적으로 저하되어 노폐물 배출과 체액 조절이 어려워지는 비가역적 상태입니다. 당뇨, 고혈압이 주요 원인입니다. 말기에는 투석이나 신장이식이 필요합니다. 통역 시 진행을 늦추기 위한 혈압, 혈당 조절의 중요성과 신장 보호 약물에 대해 설명해야 합니다.",
      "Tình trạng chức năng thận giảm dần không hồi phục, khó thải chất thải và điều hòa dịch.",
      "신장내과",
      "베트남 근로자들 중 당뇨, 고혈압 관리가 잘 되지 않아 만성신부전으로 진행하는 경우가 있습니다. 한국에서는 투석과 이식 시스템이 잘 갖춰져 있으나, 예방이 최선임을 강조해야 합니다.",
      [{"mistake":"만성신부전을 즉시 투석이 필요한 것으로 설명","correction":"단계에 따라 관리하며, 말기에만 투석이 필요함을 설명","explanation":"불필요한 공포를 줄여야 합니다"},
       {"mistake":"혈압/혈당 조절의 중요성 누락","correction":"원인 질환 관리가 진행을 늦추는 핵심임을 강조","explanation":"적극적 관리로 투석을 늦출 수 있습니다"},
       {"mistake":"식이 제한 설명 누락","correction":"단백질, 염분, 칼륨 제한이 필요할 수 있음을 안내","explanation":"신장 부담을 줄이는 데 중요합니다"}],
      [{"ko":"만성 신부전 3기입니다. 신장 기능이 절반 정도 남았습니다. 혈압과 혈당 관리가 중요합니다.","vi":"Đây là suy thận mạn giai đoạn 3. Chức năng thận còn khoảng một nửa. Kiểm soát huyết áp và đường huyết rất quan trọng.","situation":"formal"},
       {"ko":"만성 신장병이에요. 더 나빠지지 않게 관리해야 해요.","vi":"Bị bệnh thận mạn. Phải quản lý để không xấu thêm.","situation":"onsite"},
       {"ko":"신장이 서서히 약해지고 있어요. 혈압, 당뇨 잘 관리하세요.","vi":"Thận đang yếu dần. Kiểm soát tốt huyết áp và tiểu đường.","situation":"informal"}],
      ["투석", "이식", "크레아티닌", "사구체여과율"]),

    t("soi-than",
      "신장결석",
      "sỏi thận",
      "腎臟結石",
      "신(콩팥 신) + 장(오장 장) + 결(맺을 결) + 석(돌 석)",
      "신장에 칼슘, 요산 등이 뭉쳐서 돌처럼 굳어진 상태입니다. 옆구리 통증(산통), 혈뇨가 특징이며, 결석이 요관으로 내려오면 극심한 통증을 유발합니다. 통역 시 수분 섭취의 중요성과 결석 크기에 따른 치료 방법(자연 배출, 체외충격파, 내시경)을 설명해야 합니다.",
      "Tình trạng canxi, axit uric kết tụ thành sỏi trong thận.",
      "비뇨의학과, 신장내과, 응급의학과",
      "베트남 근로자들이 더운 환경에서 일하면서 수분 섭취가 부족하면 결석 위험이 높아집니다. 하루 2리터 이상의 물을 마시도록 권장해야 합니다.",
      [{"mistake":"결석 통증을 다른 복통과 혼동","correction":"옆구리에서 사타구니로 뻗치는 특징적 통증 양상 설명","explanation":"진단에 중요한 단서입니다"},
       {"mistake":"크기별 치료 설명 누락","correction":"작은 결석(5mm 미만)은 자연 배출 가능, 큰 결석은 시술 필요","explanation":"치료 방법 선택에 중요합니다"},
       {"mistake":"재발 예방 설명 누락","correction":"수분 섭취 증가, 식이 조절로 재발을 줄일 수 있음을 안내","explanation":"재발률이 높은 질환입니다"}],
      [{"ko":"신장 결석입니다. 5mm 크기로 자연 배출 가능성이 있습니다. 물을 많이 드세요.","vi":"Đây là sỏi thận. Kích thước 5mm có thể tự đào thải. Uống nhiều nước.","situation":"formal"},
       {"ko":"신장에 돌 있어요. 물 많이 마시면 빠질 수도 있어요.","vi":"Có sỏi trong thận. Uống nhiều nước có thể tự ra.","situation":"onsite"},
       {"ko":"콩팥에 돌 생긴 거예요. 물 많이 마셔요.","vi":"Có sỏi trong thận. Uống nhiều nước nhé.","situation":"informal"}],
      ["옆구리통증", "혈뇨", "체외충격파", "수분섭취"]),

    t("viem-cau-than",
      "사구체신염",
      "viêm cầu thận",
      "絲球體腎炎",
      "사(실 사) + 구(공 구) + 체(몸 체) + 신(콩팥 신) + 염(불꽃 염)",
      "신장의 여과 장치인 사구체에 염증이 생긴 상태입니다. 혈뇨, 단백뇨, 부종, 고혈압이 나타납니다. 감염 후, 자가면역 질환 등이 원인입니다. 통역 시 사구체신염이 만성 신부전으로 진행할 수 있어 조기 치료가 중요함을 설명하고, 정기적인 소변 검사의 필요성을 강조해야 합니다.",
      "Tình trạng viêm cầu thận - bộ phận lọc của thận.",
      "신장내과",
      "베트남에서 상기도 감염 후 발생하는 급성 사구체신염이 흔합니다. 한국에서는 신장 조직검사로 정확한 진단과 치료가 가능함을 설명할 수 있습니다.",
      [{"mistake":"사구체신염을 단순 요로감염으로 오해하게 설명","correction":"신장 자체의 면역 반응으로 인한 염증임을 설명","explanation":"치료 접근이 다릅니다"},
       {"mistake":"단백뇨의 중요성 설명 누락","correction":"단백뇨가 지속되면 신장 손상이 진행됨을 설명","explanation":"적극적 치료의 동기를 부여합니다"},
       {"mistake":"조직검사 필요성 설명 누락","correction":"정확한 진단과 치료를 위해 신장 조직검사가 필요할 수 있음을 안내","explanation":"원인에 따라 치료가 다릅니다"}],
      [{"ko":"사구체신염입니다. 신장의 여과 장치에 염증이 있습니다. 면역억제제 치료가 필요할 수 있습니다.","vi":"Đây là viêm cầu thận. Bộ phận lọc của thận bị viêm. Có thể cần điều trị thuốc ức chế miễn dịch.","situation":"formal"},
       {"ko":"사구체신염이에요. 소변에 피랑 단백질이 나와요. 신장 검사해야 해요.","vi":"Bị viêm cầu thận. Có máu và protein trong nước tiểu. Cần xét nghiệm thận.","situation":"onsite"},
       {"ko":"신장 여과기에 염증 생긴 거예요. 치료 안 하면 신장 나빠져요.","vi":"Bộ lọc thận bị viêm. Không điều trị thì thận sẽ yếu.","situation":"informal"}],
      ["혈뇨", "단백뇨", "부종", "면역억제제"]),

    t("hoi-chung-than-hu",
      "신증후군",
      "hội chứng thận hư",
      "腎症候群",
      "신(콩팥 신) + 증(증상 증) + 후(뒤 후) + 군(무리 군)",
      "사구체 손상으로 대량의 단백질이 소변으로 빠져나가 저단백혈증, 부종, 고지혈증이 나타나는 증후군입니다. 눈 주위 부종으로 시작하여 전신 부종으로 진행합니다. 통역 시 부종이 신장 문제 때문임을 설명하고, 스테로이드 등 면역억제 치료가 필요함을 안내해야 합니다.",
      "Hội chứng với đạm niệu ồ ạt do tổn thương cầu thận, gây giảm protein máu, phù và tăng lipid máu.",
      "신장내과, 소아청소년과",
      "베트남에서는 부종을 신장 문제로 연결 짓지 못하는 경우가 있습니다. 소아에서 발생하는 경우가 많으며, 스테로이드 치료에 잘 반응함을 설명해야 합니다.",
      [{"mistake":"부종을 단순 알레르기로 오해하게 설명","correction":"신장에서 단백질이 새어 나가 생기는 부종임을 설명","explanation":"원인 치료가 필요합니다"},
       {"mistake":"스테로이드 치료 거부감 해소 실패","correction":"소아 신증후군은 스테로이드에 잘 반응하며 완해가 가능함을 설명","explanation":"치료 순응도가 중요합니다"},
       {"mistake":"식이 조절 설명 누락","correction":"부종 시 염분 제한이 필요함을 안내","explanation":"증상 조절에 도움됩니다"}],
      [{"ko":"신증후군입니다. 신장에서 단백질이 빠져나가 부종이 생겼습니다. 스테로이드 치료를 시작합니다.","vi":"Đây là hội chứng thận hư. Protein thoát ra từ thận gây phù. Sẽ bắt đầu điều trị steroid.","situation":"formal"},
       {"ko":"신증후군이에요. 단백질이 소변으로 나가서 붓는 거예요.","vi":"Bị hội chứng thận hư. Protein ra theo nước tiểu nên bị phù.","situation":"onsite"},
       {"ko":"신장에서 단백질이 새서 붓는 거예요. 약 먹으면 좋아져요.","vi":"Protein rò từ thận nên phù. Uống thuốc sẽ đỡ.","situation":"informal"}],
      ["부종", "단백뇨", "저단백혈증", "스테로이드"]),

    # 혈액종양내과 (686-700)
    t("thieu-mau",
      "빈혈",
      "thiếu máu",
      "貧血",
      "빈(가난할 빈) + 혈(피 혈)",
      "혈액 내 적혈구나 헤모글로빈이 감소한 상태입니다. 피로, 창백함, 어지러움, 호흡곤란이 나타납니다. 철 결핍, 출혈, 만성 질환, 골수 문제 등 다양한 원인이 있습니다. 통역 시 빈혈의 원인을 찾는 것이 중요함을 설명하고, 철분제 복용법과 부작용을 안내해야 합니다.",
      "Tình trạng giảm hồng cầu hoặc hemoglobin trong máu.",
      "혈액내과, 내과",
      "베트남 여성 근로자들 중 월경과다나 불균형한 식사로 철결핍성 빈혈이 흔합니다. 철분이 풍부한 음식과 철분제 복용에 대해 안내해야 합니다.",
      [{"mistake":"빈혈을 단순 철분 부족으로만 설명","correction":"다양한 원인(출혈, 만성질환, 골수 문제)이 있음을 설명","explanation":"원인에 따라 치료가 다릅니다"},
       {"mistake":"철분제 복용법 설명 누락","correction":"빈속에 복용, 비타민C와 함께 복용 시 흡수 증가함을 안내","explanation":"효과적인 복용을 위해 중요합니다"},
       {"mistake":"원인 질환 검사의 필요성 누락","correction":"빈혈 원인을 찾기 위한 추가 검사(대장내시경 등)가 필요할 수 있음을 설명","explanation":"숨은 출혈이나 암을 발견할 수 있습니다"}],
      [{"ko":"철결핍성 빈혈입니다. 헤모글로빈 수치가 낮습니다. 철분제를 복용하시고, 원인 검사가 필요합니다.","vi":"Đây là thiếu máu thiếu sắt. Hemoglobin thấp. Cần uống thuốc sắt và xét nghiệm tìm nguyên nhân.","situation":"formal"},
       {"ko":"빈혈이에요. 피가 부족해요. 철분제 드시고 고기 많이 드세요.","vi":"Bị thiếu máu. Thiếu máu. Uống thuốc sắt và ăn nhiều thịt.","situation":"onsite"},
       {"ko":"피가 부족해서 어지러운 거예요. 철분 먹어요.","vi":"Chóng mặt do thiếu máu. Uống sắt nhé.","situation":"informal"}],
      ["피로", "어지러움", "철분", "헤모글로빈"]),

    t("bach-cau-cap",
      "급성백혈병",
      "bạch cầu cấp",
      "急性白血病",
      "급(급할 급) + 성(성품 성) + 백(흰 백) + 혈(피 혈) + 병(병 병)",
      "골수에서 비정상적인 백혈구가 급격히 증식하는 혈액암입니다. 피로, 발열, 출혈, 감염이 빠르게 진행됩니다. 급성 골수성(AML)과 급성 림프구성(ALL)으로 나뉩니다. 통역 시 응급 치료가 필요함을 설명하고, 항암치료와 조혈모세포이식의 가능성을 안내해야 합니다.",
      "Ung thư máu với tế bào bạch cầu bất thường tăng sinh nhanh trong tủy xương.",
      "혈액종양내과",
      "백혈병 진단은 환자와 가족에게 큰 충격입니다. 한국의 혈액암 치료 수준이 높고, 조혈모세포 이식 성공률이 좋음을 설명하여 희망을 유지하게 해야 합니다.",
      [{"mistake":"백혈병을 불치병으로만 설명","correction":"항암치료와 이식으로 완치 가능함을 설명","explanation":"희망을 유지하게 합니다"},
       {"mistake":"급성과 만성 구분 안 함","correction":"급성(cấp)은 빠르게 진행, 만성(mạn)은 천천히 진행","explanation":"치료 긴급성이 다릅니다"},
       {"mistake":"감염 예방의 중요성 누락","correction":"면역력 저하로 감염에 취약함을 설명","explanation":"치료 중 생명을 위협하는 합병증입니다"}],
      [{"ko":"급성 백혈병 진단입니다. 즉시 항암 치료를 시작해야 합니다. 완치를 목표로 치료합니다.","vi":"Chẩn đoán bạch cầu cấp. Cần bắt đầu hóa trị ngay. Điều trị nhằm mục tiêu chữa khỏi.","situation":"formal"},
       {"ko":"급성 백혈병이에요. 빨리 치료해야 해요. 치료하면 나을 수 있어요.","vi":"Bị bạch cầu cấp. Phải điều trị nhanh. Điều trị có thể khỏi.","situation":"onsite"},
       {"ko":"혈액암이에요. 응급이에요. 항암 치료 시작해야 해요.","vi":"Bị ung thư máu. Cấp cứu. Phải bắt đầu hóa trị.","situation":"informal"}],
      ["항암치료", "조혈모세포이식", "골수", "수혈"]),

    t("u-lympho",
      "림프종",
      "u lympho",
      None,
      None,
      "림프계에서 발생하는 악성 종양으로, 호지킨 림프종과 비호지킨 림프종으로 나뉩니다. 림프절 종대, 발열, 야간 발한, 체중 감소가 특징입니다. 통역 시 림프종이 고형암과 달리 전신에 퍼져 있어도 치료 가능한 경우가 많음을 설명하고, 항암치료 반응이 좋은 경우가 많음을 안내해야 합니다.",
      "Khối u ác tính phát sinh từ hệ bạch huyết, chia thành Hodgkin và non-Hodgkin.",
      "혈액종양내과, 방사선종양학과",
      "베트남에서는 림프절이 부으면 결핵을 먼저 의심하는 경향이 있습니다. 한국에서는 조직검사로 정확한 진단이 가능하며, 림프종 치료 성적이 좋음을 설명할 수 있습니다.",
      [{"mistake":"림프종을 말기암으로만 설명","correction":"진행된 병기에서도 완치 가능한 경우가 많음을 설명","explanation":"림프종은 치료 반응이 좋습니다"},
       {"mistake":"호지킨과 비호지킨 구분 안 함","correction":"유형에 따라 치료와 예후가 다름을 설명","explanation":"정확한 진단이 중요합니다"},
       {"mistake":"B 증상 설명 누락","correction":"발열, 야간 발한, 체중 감소가 예후와 관련됨을 설명","explanation":"병기 결정에 중요합니다"}],
      [{"ko":"비호지킨 림프종 진단입니다. 항암 치료로 좋은 결과를 기대할 수 있습니다.","vi":"Chẩn đoán u lympho non-Hodgkin. Có thể kỳ vọng kết quả tốt với hóa trị.","situation":"formal"},
       {"ko":"림프종이에요. 림프절 암이에요. 항암 치료 잘 듣는 편이에요.","vi":"Bị u lympho. Ung thư hạch bạch huyết. Hóa trị thường hiệu quả.","situation":"onsite"},
       {"ko":"림프절 암이에요. 치료하면 좋아질 수 있어요.","vi":"Ung thư hạch. Điều trị có thể khỏi.","situation":"informal"}],
      ["림프절", "항암치료", "PET-CT", "조직검사"]),

    t("da-u-tuy",
      "다발골수종",
      "đa u tủy",
      "多發骨髓腫",
      "다(많을 다) + 발(필 발) + 골(뼈 골) + 수(골 수) + 종(종기 종)",
      "골수의 형질세포가 악성화되어 비정상 항체를 만들고 뼈를 파괴하는 혈액암입니다. 뼈 통증, 골절, 빈혈, 신장 손상이 나타납니다. 주로 고령에서 발생합니다. 통역 시 새로운 치료제로 생존 기간이 크게 늘어났음을 설명하고, 뼈 합병증 예방의 중요성을 안내해야 합니다.",
      "Ung thư máu khi tương bào trong tủy xương ác tính hóa, tạo kháng thể bất thường và phá hủy xương.",
      "혈액종양내과",
      "다발골수종은 복잡한 질환이어서 베트남어로 설명하기 어려울 수 있습니다. 골수에서 비정상 세포가 증식하여 뼈를 약하게 하고 신장을 손상시킨다는 핵심을 간결하게 전달해야 합니다.",
      [{"mistake":"다발골수종을 골암으로 오해하게 설명","correction":"골수(tủy xương)의 혈액암이며 뼈 자체의 암이 아님을 설명","explanation":"치료 접근이 다릅니다"},
       {"mistake":"예후만 비관적으로 설명","correction":"새로운 치료제로 장기 생존이 가능해졌음을 설명","explanation":"희망을 유지하게 합니다"},
       {"mistake":"뼈 합병증 예방 설명 누락","correction":"골절 예방을 위한 비스포스포네이트, 낙상 주의 안내","explanation":"삶의 질 유지에 중요합니다"}],
      [{"ko":"다발골수종입니다. 골수의 형질세포에서 발생한 혈액암입니다. 최신 치료로 좋은 결과를 기대합니다.","vi":"Đây là đa u tủy. Ung thư máu từ tương bào trong tủy xương. Kỳ vọng kết quả tốt với điều trị mới.","situation":"formal"},
       {"ko":"다발골수종이에요. 뼈가 약해지는 혈액암이에요. 치료 잘 되는 편이에요.","vi":"Bị đa u tủy. Ung thư máu làm yếu xương. Điều trị thường hiệu quả.","situation":"onsite"},
       {"ko":"골수 암이에요. 뼈가 아프죠? 치료하면 좋아져요.","vi":"Ung thư tủy xương. Đau xương phải không? Điều trị sẽ đỡ.","situation":"informal"}],
      ["뼈통증", "빈혈", "신부전", "항암치료"]),

    t("giam-tieu-cau",
      "혈소판감소증",
      "giảm tiểu cầu",
      "血小板減少症",
      "혈(피 혈) + 소(작을 소) + 판(판 판) + 감(덜 감) + 소(작을 소) + 증(증상 증)",
      "혈액 응고에 필요한 혈소판 수치가 감소한 상태입니다. 멍, 잇몸 출혈, 점상 출혈이 나타납니다. 면역 이상, 감염, 약물, 골수 문제 등이 원인입니다. 통역 시 경미한 외상에도 출혈 위험이 있음을 설명하고, 원인에 따라 치료가 달라짐을 안내해야 합니다.",
      "Tình trạng giảm số lượng tiểu cầu cần thiết cho đông máu.",
      "혈액내과",
      "베트남 근로자들이 멍이 잘 드는 것을 대수롭지 않게 여길 수 있습니다. 원인 불명의 멍이나 출혈이 반복되면 검사가 필요함을 안내해야 합니다.",
      [{"mistake":"혈소판 감소를 단순 빈혈로 오해하게 설명","correction":"빈혈(thiếu máu)은 적혈구, 혈소판감소(giảm tiểu cầu)는 혈소판 문제","explanation":"치료 접근이 다릅니다"},
       {"mistake":"출혈 위험 경고 누락","correction":"외상, 수술 시 출혈 위험 증가함을 경고","explanation":"안전 주의가 필요합니다"},
       {"mistake":"원인 검사의 중요성 누락","correction":"면역성, 약물성, 골수 문제 등 원인 감별이 필요함을 설명","explanation":"치료가 원인에 따라 다릅니다"}],
      [{"ko":"면역성 혈소판감소증입니다. 혈소판 수치가 낮아 출혈 위험이 있습니다.","vi":"Đây là giảm tiểu cầu miễn dịch. Tiểu cầu thấp nên có nguy cơ chảy máu.","situation":"formal"},
       {"ko":"혈소판이 적어요. 멍 잘 들고 피 잘 나요. 조심하세요.","vi":"Tiểu cầu ít. Hay bầm tím và chảy máu. Cẩn thận nhé.","situation":"onsite"},
       {"ko":"피 응고 세포가 부족해요. 다치면 피 잘 안 멈춰요.","vi":"Thiếu tế bào đông máu. Bị thương thì máu khó cầm.","situation":"informal"}],
      ["출혈", "멍", "혈소판", "면역억제제"]),

    t("huyet-khoi-tinh-mach-sau",
      "심부정맥혈전증",
      "huyết khối tĩnh mạch sâu",
      "深部靜脈血栓症",
      "심(깊을 심) + 부(마을 부) + 정(고요할 정) + 맥(맥 맥) + 혈(피 혈) + 전(구를 전) + 증(증상 증)",
      "주로 다리의 깊은 정맥에 혈전이 생기는 질환입니다. 다리 부종, 통증, 발적이 특징입니다. 장시간 부동, 수술 후, 암 환자에서 위험이 높습니다. 혈전이 폐로 이동하면 폐색전증으로 사망할 수 있습니다. 통역 시 항응고제 치료의 중요성과 장기간 복용 필요성을 설명해야 합니다.",
      "Bệnh lý với huyết khối hình thành trong tĩnh mạch sâu, thường ở chân.",
      "혈관외과, 혈액내과, 호흡기내과",
      "베트남 근로자들이 장시간 비행이나 작업 후 다리가 붓고 아프면 심부정맥혈전증을 의심해야 합니다. 폐색전증 예방을 위해 빠른 진단과 치료가 중요함을 강조해야 합니다.",
      [{"mistake":"다리 부종을 단순 피로로 설명","correction":"한쪽 다리만 붓고 아프면 혈전을 의심해야 함을 설명","explanation":"폐색전증으로 진행할 수 있습니다"},
       {"mistake":"폐색전증 위험 설명 누락","correction":"혈전이 폐로 이동하면 생명이 위험함을 경고","explanation":"치료의 긴급성을 이해시킵니다"},
       {"mistake":"항응고제 복용 기간 설명 누락","correction":"최소 3-6개월, 경우에 따라 더 오래 복용 필요함을 설명","explanation":"재발 방지를 위해 중요합니다"}],
      [{"ko":"심부정맥혈전증입니다. 다리 정맥에 혈전이 있습니다. 항응고제 치료를 시작합니다.","vi":"Đây là huyết khối tĩnh mạch sâu. Có cục máu đông trong tĩnh mạch chân. Bắt đầu điều trị chống đông.","situation":"formal"},
       {"ko":"다리에 피떡이 생겼어요. 폐로 가면 위험해요. 피 묽게 하는 약 드세요.","vi":"Có cục máu đông ở chân. Nếu đi lên phổi thì nguy hiểm. Uống thuốc làm loãng máu.","situation":"onsite"},
       {"ko":"다리 혈관에 피 뭉친 거예요. 약 먹어야 해요.","vi":"Máu vón cục trong mạch chân. Phải uống thuốc.","situation":"informal"}],
      ["다리부종", "폐색전증", "항응고제", "압박스타킹"]),

    t("tang-bach-cau-eosin",
      "호산구증가증",
      "tăng bạch cầu eosin",
      "好酸球增加症",
      "호(좋을 호) + 산(산 산) + 구(공 구) + 증(더할 증) + 가(더할 가) + 증(증상 증)",
      "혈액 내 호산구(백혈구의 일종)가 비정상적으로 증가한 상태입니다. 알레르기, 기생충 감염, 약물, 자가면역 질환, 악성 종양 등이 원인입니다. 통역 시 호산구 증가의 원인을 찾는 것이 중요함을 설명하고, 베트남에서 기생충 감염 가능성을 고려해야 함을 안내해야 합니다.",
      "Tình trạng tăng bất thường bạch cầu eosin (một loại bạch cầu) trong máu.",
      "혈액내과, 알레르기내과, 감염내과",
      "베트남 근로자들 중 기생충 감염(간흡충 등)으로 인한 호산구 증가가 발견될 수 있습니다. 기생충 검사와 치료가 필요할 수 있음을 설명해야 합니다.",
      [{"mistake":"호산구 증가를 단순 알레르기로만 설명","correction":"기생충, 약물, 악성종양 등 다양한 원인 가능성을 설명","explanation":"원인 감별이 중요합니다"},
       {"mistake":"기생충 검사 필요성 누락","correction":"베트남 출신 환자에서 기생충 감염 가능성을 고려해야 함을 설명","explanation":"치료 가능한 원인입니다"},
       {"mistake":"장기 손상 위험 설명 누락","correction":"심한 호산구 증가는 심장, 폐 등 장기 손상을 유발할 수 있음을 설명","explanation":"적극적 치료의 필요성을 이해시킵니다"}],
      [{"ko":"호산구증가증입니다. 알레르기 외에 기생충 감염 가능성도 검사해야 합니다.","vi":"Đây là tăng bạch cầu eosin. Ngoài dị ứng cần xét nghiệm khả năng nhiễm ký sinh trùng.","situation":"formal"},
       {"ko":"호산구가 높아요. 알레르기일 수도, 기생충일 수도 있어요. 검사해 봐요.","vi":"Bạch cầu eosin cao. Có thể dị ứng hoặc ký sinh trùng. Cần xét nghiệm.","situation":"onsite"},
       {"ko":"피검사에서 호산구가 많이 나왔어요. 원인 찾아야 해요.","vi":"Xét nghiệm máu cho thấy eosin cao. Cần tìm nguyên nhân.","situation":"informal"}],
      ["알레르기", "기생충", "호산구", "약물반응"]),

    t("roi-loan-dong-mau",
      "응고장애",
      "rối loạn đông máu",
      "凝固障碍",
      "응(엉길 응) + 고(굳을 고) + 장(막을 장) + 애(막힐 애)",
      "혈액 응고 과정에 이상이 있어 출혈이 멈추지 않거나, 반대로 혈전이 잘 생기는 상태입니다. 선천성(혈우병 등)과 후천성(간질환, 약물 등)으로 나뉩니다. 통역 시 응고장애의 종류에 따라 출혈 경향 또는 혈전 경향이 있음을 설명하고, 수술이나 치과 치료 전 반드시 의료진에게 알려야 함을 강조해야 합니다.",
      "Tình trạng bất thường trong quá trình đông máu, gây chảy máu không cầm hoặc ngược lại dễ hình thành huyết khối.",
      "혈액내과",
      "베트남 근로자들이 응고장애가 있는지 모르고 수술이나 외상을 당하면 위험할 수 있습니다. 과거 출혈 병력이나 가족력을 확인하는 것이 중요합니다.",
      [{"mistake":"응고장애를 출혈만의 문제로 설명","correction":"출혈 경향 또는 혈전 경향 모두 있을 수 있음을 설명","explanation":"유형에 따라 관리가 다릅니다"},
       {"mistake":"선천성 응고장애 설명 누락","correction":"혈우병 등 유전성 응고장애도 있음을 설명","explanation":"가족력 확인이 중요합니다"},
       {"mistake":"의료 시술 전 주의 설명 누락","correction":"수술, 치과 치료 전 응고장애를 의료진에게 알려야 함을 강조","explanation":"출혈 합병증을 예방합니다"}],
      [{"ko":"응고장애가 있습니다. 출혈이 잘 멈추지 않을 수 있어 주의가 필요합니다.","vi":"Có rối loạn đông máu. Có thể khó cầm máu nên cần cẩn thận.","situation":"formal"},
       {"ko":"피가 잘 안 멈추는 체질이에요. 수술할 때 꼭 말해야 해요.","vi":"Thể chất máu khó đông. Khi mổ phải nói với bác sĩ.","situation":"onsite"},
       {"ko":"피 응고에 문제 있어요. 다치면 조심해야 해요.","vi":"Có vấn đề đông máu. Cẩn thận khi bị thương.","situation":"informal"}],
      ["출혈", "혈전", "혈우병", "응고인자"]),

    t("benh-bach-huyet",
      "만성백혈병",
      "bệnh bạch huyết mạn",
      "慢性白血病",
      "만(오랠 만) + 성(성품 성) + 백(흰 백) + 혈(피 혈) + 병(병 병)",
      "골수에서 비정상적인 백혈구가 서서히 증식하는 혈액암입니다. 만성 골수성(CML)과 만성 림프구성(CLL)으로 나뉩니다. 초기에는 증상이 없어 건강검진에서 발견되는 경우가 많습니다. 통역 시 만성 백혈병은 표적치료제로 장기 조절이 가능함을 설명하고, 정기 추적의 중요성을 안내해야 합니다.",
      "Ung thư máu với tế bào bạch cầu bất thường tăng sinh chậm trong tủy xương.",
      "혈액종양내과",
      "만성 골수성 백혈병(CML)은 표적치료제(이마티닙 등)로 정상 수명을 기대할 수 있게 되었습니다. 이 혁신적인 치료에 대해 설명하여 환자에게 희망을 줄 수 있습니다.",
      [{"mistake":"만성과 급성 백혈병 구분 안 함","correction":"만성(mạn)은 천천히 진행하여 장기 관리 가능함을 설명","explanation":"예후와 치료 접근이 다릅니다"},
       {"mistake":"표적치료제 효과 설명 누락","correction":"CML은 표적치료제로 거의 정상 생활이 가능함을 설명","explanation":"치료의 혁신을 알려줍니다"},
       {"mistake":"복용 순응도의 중요성 누락","correction":"약을 꾸준히 복용해야 효과가 유지됨을 강조","explanation":"중단 시 질병이 진행합니다"}],
      [{"ko":"만성 골수성 백혈병입니다. 표적치료제로 장기간 조절이 가능합니다. 약을 꾸준히 드셔야 합니다.","vi":"Đây là bạch cầu mạn dòng tủy. Có thể kiểm soát lâu dài bằng thuốc nhắm trúng đích. Phải uống thuốc đều.","situation":"formal"},
       {"ko":"만성 백혈병이에요. 급한 건 아니에요. 약 잘 드시면 오래 사세요.","vi":"Bị bạch cầu mạn. Không cấp. Uống thuốc đều thì sống lâu.","situation":"onsite"},
       {"ko":"백혈병인데 천천히 가는 종류예요. 약으로 조절돼요.","vi":"Là loại bạch cầu tiến triển chậm. Kiểm soát được bằng thuốc.","situation":"informal"}],
      ["표적치료제", "골수", "백혈구", "정기검사"]),

    t("hoi-chung-mds",
      "골수이형성증후군",
      "hội chứng MDS",
      "骨髓異形成症候群",
      "골(뼈 골) + 수(골 수) + 이(다를 이) + 형(모양 형) + 성(이룰 성) + 증(증상 증) + 후(뒤 후) + 군(무리 군)",
      "골수에서 혈액 세포가 비정상적으로 만들어지는 질환군입니다. 빈혈, 감염, 출혈이 나타나며, 일부는 급성 백혈병으로 진행합니다. 주로 고령에서 발생합니다. 통역 시 MDS가 전백혈병 상태일 수 있음을 설명하고, 수혈, 약물, 이식 등 치료 옵션을 안내해야 합니다.",
      "Nhóm bệnh với tế bào máu được sản xuất bất thường trong tủy xương.",
      "혈액종양내과",
      "MDS는 복잡한 질환이어서 설명이 어려울 수 있습니다. 골수에서 피가 제대로 만들어지지 않아 수혈이 필요할 수 있고, 백혈병으로 진행 가능성이 있다는 핵심을 전달해야 합니다.",
      [{"mistake":"MDS를 빈혈로만 설명","correction":"골수의 문제로 모든 혈액 세포 생산에 이상이 있음을 설명","explanation":"빈혈, 감염, 출혈 모두 발생합니다"},
       {"mistake":"백혈병 진행 가능성 설명 누락","correction":"일부 환자에서 급성 백혈병으로 진행할 수 있음을 안내","explanation":"정기 추적의 필요성을 이해시킵니다"},
       {"mistake":"치료 옵션 설명 불충분","correction":"수혈, 저메틸화제, 이식 등 다양한 치료 옵션 안내","explanation":"환자 상태에 맞는 치료를 선택합니다"}],
      [{"ko":"골수이형성증후군입니다. 골수에서 혈액 세포가 제대로 만들어지지 않습니다. 정기 추적이 필요합니다.","vi":"Đây là hội chứng MDS. Tủy xương không sản xuất tế bào máu bình thường. Cần theo dõi định kỳ.","situation":"formal"},
       {"ko":"MDS예요. 골수에서 피가 제대로 안 만들어져요. 수혈이 필요할 수 있어요.","vi":"Bị MDS. Tủy xương không tạo máu đúng cách. Có thể cần truyền máu.","situation":"onsite"},
       {"ko":"골수 문제로 피가 부족해요. 백혈병 될 수도 있어서 검사 자주 받아야 해요.","vi":"Thiếu máu do tủy xương có vấn đề. Có thể thành bạch cầu nên phải xét nghiệm thường xuyên.","situation":"informal"}],
      ["빈혈", "수혈", "백혈병", "골수이식"]),
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms (651-700). Total: {len(data)}")
