#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 추가 의료 용어 - 진료과별 전문 용어, 검사, 시술
new = [
t("viem-phu-khoa","부인과염증","viêm phụ khoa","여성 생식기에 발생하는 염증입니다. 질염, 자궁경부염, 골반염 등이 있습니다. 항생제, 항진균제로 치료합니다. 통역 시 증상, 원인, 예방법을 민감하게 설명해야 합니다.",
"Viêm nhiễm ở cơ quan sinh sản nữ như viêm âm đạo, viêm cổ tử cung",
"산부인과","한국에서 부인과 질환은 민감한 주제입니다. 베트남 환자에게 프라이버시를 보장하고 편안한 분위기에서 설명합니다.",
[{"mistake":"민감한 부위 직접적 표현","correction":"'여성 질환', '아래쪽 염증' 등 완곡하게 표현","explanation":"환자의 편안함을 고려합니다"},
{"mistake":"성병과 모든 염증 동일시","correction":"성병 외 위생, 면역 문제도 원인임을 설명","explanation":"불필요한 오해를 줄입니다"},
{"mistake":"파트너 치료 필요성 미안내","correction":"일부 감염은 파트너 동시 치료 필요","explanation":"재감염을 예방합니다"}],
[{"ko":"부인과 검진이 필요합니다.","vi":"Cần khám phụ khoa.","situation":"formal"},
{"ko":"질 분비물 검사를 하겠습니다.","vi":"Sẽ xét nghiệm dịch tiết âm đạo.","situation":"formal"},
{"ko":"약 넣으시면 금방 나아요.","vi":"Đặt thuốc thì sẽ khỏi nhanh.","situation":"informal"}],
["질염","항진균제","산부인과"]),

t("co-tu-cung","자궁근종","u xơ tử cung","자궁에 생기는 양성 종양입니다. 폐경 전 여성에게 흔합니다. 무증상일 수 있고 월경 과다, 압박 증상이 나타납니다. 통역 시 양성 종양임을 강조하고 치료 옵션을 설명해야 합니다.",
"U lành tính ở tử cung, phổ biến ở phụ nữ trước mãn kinh",
"산부인과","한국에서 자궁근종은 가임기 여성의 30%가 가지고 있습니다. 암이 아님을 확실히 설명합니다.",
[{"mistake":"근종을 암으로 오해하게 설명","correction":"양성 종양으로 암이 아님을 명확히","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"모든 근종이 수술 필요하다고 설명","correction":"증상 없으면 경과 관찰 가능","explanation":"불필요한 수술을 피합니다"},
{"mistake":"임신에 미치는 영향 미설명","correction":"위치에 따라 임신에 영향, 상담 필요","explanation":"가임기 여성에게 중요한 정보입니다"}],
[{"ko":"자궁근종이 있으나 양성이니 걱정 마세요.","vi":"Có u xơ tử cung nhưng lành tính, đừng lo.","situation":"formal"},
{"ko":"지금은 경과 관찰하겠습니다.","vi":"Hiện tại sẽ theo dõi.","situation":"formal"},
{"ko":"근종 있어도 임신 잘 되는 경우 많아요.","vi":"Có u xơ vẫn có thể mang thai bình thường.","situation":"informal"}],
["양성종양","자궁적출술","월경과다"]),

t("kham-thai","산전검사","khám thai","임신 중 태아와 산모의 건강을 확인하는 검사입니다. 초음파, 혈액검사, 기형아검사 등이 포함됩니다. 정기적으로 시행합니다. 통역 시 검사 일정, 각 검사의 목적을 설명해야 합니다.",
"Các xét nghiệm kiểm tra sức khỏe thai nhi và mẹ trong thai kỳ",
"산부인과","한국에서 산전검사는 건강보험이 적용됩니다. 정기적인 산전 관리가 안전한 출산에 중요합니다.",
[{"mistake":"검사 시기 미안내","correction":"임신 주수별 필요한 검사 시기 안내","explanation":"적절한 시기에 검사받도록 합니다"},
{"mistake":"기형아검사 결과 해석 부족","correction":"선별검사와 확진검사 차이 설명","explanation":"불필요한 불안을 줄입니다"},
{"mistake":"초음파 검사 횟수 미안내","correction":"정상 임신 시 최소 3회 초음파 권장","explanation":"검사 계획을 세웁니다"}],
[{"ko":"오늘 정기 산전검사를 하겠습니다.","vi":"Hôm nay sẽ khám thai định kỳ.","situation":"formal"},
{"ko":"기형아검사는 12주쯤 하시면 됩니다.","vi":"Xét nghiệm dị tật thai nhi làm khoảng tuần 12.","situation":"formal"},
{"ko":"아기 잘 자라고 있어요.","vi":"Em bé đang phát triển tốt.","situation":"informal"}],
["초음파","기형아검사","임신"]),

t("cat-amidan","편도절제술","cắt amidan","비대해지거나 반복 감염되는 편도를 제거하는 수술입니다. 소아에게 많이 시행됩니다. 전신마취 하에 시행합니다. 통역 시 수술 이유, 회복 과정, 식이 제한을 설명해야 합니다.",
"Phẫu thuật cắt bỏ amidan bị phì đại hoặc nhiễm trùng tái phát",
"이비인후과","한국에서 편도절제술은 소아에게 흔한 수술입니다. 수술 후 통증 관리와 식이가 중요합니다.",
[{"mistake":"수술 후 통증 없다고 설명","correction":"1-2주간 목 통증 있음, 진통제 처방","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"식이 제한 미안내","correction":"차갑고 부드러운 음식만, 뜨겁고 딱딱한 거 금지","explanation":"출혈을 예방합니다"},
{"mistake":"출혈 위험성 미설명","correction":"수술 후 1-2주 출혈 가능성, 이상 시 내원","explanation":"응급 상황에 대비합니다"}],
[{"ko":"반복되는 편도염으로 수술을 권합니다.","vi":"Vì viêm amidan tái phát nên khuyên mổ.","situation":"formal"},
{"ko":"수술 후 2주간 차가운 음식만 드세요.","vi":"Sau mổ 2 tuần chỉ ăn đồ lạnh và mềm.","situation":"formal"},
{"ko":"아이스크림 많이 먹어도 돼요.","vi":"Được ăn nhiều kem.","situation":"informal"}],
["편도염","전신마취","소아외과"]),

t("phau-thuat-mui","코수술","phẫu thuật mũi","비중격만곡, 비염, 축농증 등을 치료하는 수술입니다. 기능적 수술과 미용 수술이 있습니다. 내시경으로 시행합니다. 통역 시 수술 목적, 회복 기간, 주의사항을 설명해야 합니다.",
"Phẫu thuật điều trị lệch vách ngăn mũi, viêm mũi, viêm xoang",
"이비인후과","한국에서 코 기능 수술은 건강보험이 적용됩니다. 미용 목적은 비급여입니다.",
[{"mistake":"기능적 수술과 미용 수술 혼동","correction":"기능 개선은 보험, 미용은 비급여 구분","explanation":"비용 예측에 중요합니다"},
{"mistake":"수술 후 코막힘 설명 부족","correction":"부종으로 2-4주간 코막힘 있음, 점차 호전","explanation":"환자를 안심시킵니다"},
{"mistake":"패킹 제거 설명 없음","correction":"코에 솜 넣어두고 1-2일 후 제거","explanation":"회복 과정을 이해시킵니다"}],
[{"ko":"비중격만곡증으로 수술이 필요합니다.","vi":"Cần phẫu thuật vì lệch vách ngăn mũi.","situation":"formal"},
{"ko":"수술 후 2주 정도 코가 막힐 수 있어요.","vi":"Sau mổ có thể nghẹt mũi khoảng 2 tuần.","situation":"formal"},
{"ko":"코 푸는 건 한 달 후에 하세요.","vi":"Một tháng sau mới được xì mũi.","situation":"informal"}],
["비중격만곡증","축농증","내시경"]),

t("dieu-tri-rang","치과치료","điều trị răng","치아와 잇몸의 질환을 치료하는 것입니다. 충치치료, 신경치료, 발치, 보철 등이 있습니다. 통역 시 치료 과정, 마취, 비용을 설명해야 합니다.",
"Điều trị các bệnh về răng và nướu",
"치과","한국에서 치과 치료는 일부만 건강보험이 적용됩니다. 비급여 항목이 많아 비용 설명이 중요합니다.",
[{"mistake":"모든 치과 치료가 보험이라고 설명","correction":"보철, 임플란트 등 비급여 항목 많음 안내","explanation":"비용 예측에 중요합니다"},
{"mistake":"마취 종류 미설명","correction":"국소마취가 기본, 무통마취 옵션 안내","explanation":"환자 선택을 돕습니다"},
{"mistake":"치료 후 주의사항 미안내","correction":"마취 풀릴 때까지 식사 제한 등 안내","explanation":"안전을 보장합니다"}],
[{"ko":"충치가 있어서 치료가 필요합니다.","vi":"Có sâu răng cần điều trị.","situation":"formal"},
{"ko":"마취 주사를 맞으실 거예요.","vi":"Sẽ tiêm thuốc tê.","situation":"formal"},
{"ko":"마취 풀릴 때까지 밥 먹지 마세요.","vi":"Đừng ăn cho đến khi hết tê.","situation":"informal"}],
["충치","신경치료","임플란트"]),

t("cay-ghep-rang","임플란트","cấy ghép răng","빠진 치아 자리에 인공 치아를 심는 시술입니다. 뼈에 고정하는 금속 나사와 치아 모양의 크라운으로 구성됩니다. 치료 기간이 수개월 걸립니다. 통역 시 치료 단계, 기간, 비용을 설명해야 합니다.",
"Cấy ghép răng nhân tạo vào vị trí răng đã mất",
"치과","한국에서 임플란트는 비급여로 비용이 높습니다. 65세 이상은 일부 보험 적용됩니다.",
[{"mistake":"임플란트를 간단한 시술로 설명","correction":"3-6개월 치료 기간, 여러 번 방문 필요","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"영구적이라고만 설명","correction":"관리 잘하면 오래 가지만 영구적은 아님","explanation":"관리의 중요성을 강조합니다"},
{"mistake":"비용 설명 부족","correction":"1개당 100-200만원 정도, 부위/재료에 따라 다름","explanation":"재정 계획을 돕습니다"}],
[{"ko":"빠진 치아에 임플란트를 권합니다.","vi":"Khuyên cấy ghép răng ở vị trí răng mất.","situation":"formal"},
{"ko":"뼈가 붙을 때까지 3개월 정도 걸립니다.","vi":"Mất khoảng 3 tháng để xương lành.","situation":"formal"},
{"ko":"임플란트 하면 자기 이처럼 편해요.","vi":"Làm implant thì thoải mái như răng thật.","situation":"informal"}],
["발치","크라운","골이식"]),

t("dinh-chinh-rang","치아교정","chỉnh nha","교정장치로 치아 배열을 바로잡는 치료입니다. 2-3년 정도 걸립니다. 금속, 투명, 설측 교정 등이 있습니다. 통역 시 치료 기간, 관리, 비용을 설명해야 합니다.",
"Điều trị sắp xếp lại hàm răng bằng mắc cài hoặc khay trong suốt",
"치과교정과","한국에서 치아교정은 비급여입니다. 청소년기에 많이 하지만 성인도 가능합니다.",
[{"mistake":"치료 기간 짧게 설명","correction":"보통 2-3년, 개인차 있음 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"교정 중 관리 미설명","correction":"양치질 중요, 딱딱한 음식 제한 안내","explanation":"치료 효과를 보장합니다"},
{"mistake":"유지장치 착용 미안내","correction":"교정 후에도 유지장치 필요, 착용 안 하면 원래대로","explanation":"결과 유지에 중요합니다"}],
[{"ko":"치아교정을 권합니다.","vi":"Khuyên niềng răng.","situation":"formal"},
{"ko":"2년 정도 걸릴 거예요.","vi":"Sẽ mất khoảng 2 năm.","situation":"formal"},
{"ko":"교정하면 양치 더 열심히 해야 해요.","vi":"Niềng răng thì phải đánh răng kỹ hơn.","situation":"informal"}],
["교정장치","투명교정","유지장치"]),

t("kham-mat","안과검진","khám mắt","눈의 건강 상태를 확인하는 검사입니다. 시력, 안압, 망막 검사 등이 포함됩니다. 정기 검진으로 눈 질환을 조기 발견합니다. 통역 시 검사 항목, 산동제 사용, 주의사항을 설명해야 합니다.",
"Kiểm tra sức khỏe mắt bao gồm thị lực, nhãn áp, võng mạc",
"안과","한국에서 40세 이상은 녹내장 등 눈 질환 선별을 위해 정기 검진이 권장됩니다.",
[{"mistake":"산동검사 주의사항 미설명","correction":"산동제 후 4-6시간 눈부심, 운전 피하기","explanation":"안전을 보장합니다"},
{"mistake":"시력과 안압만 검사한다고 설명","correction":"망막, 시신경, 각막 등 종합 검사 안내","explanation":"눈 건강 전체를 확인합니다"},
{"mistake":"고위험군 미안내","correction":"당뇨, 고혈압 환자는 정기 검진 중요","explanation":"합병증을 조기 발견합니다"}],
[{"ko":"눈 정기검진을 받으시겠습니다.","vi":"Bạn sẽ khám mắt định kỳ.","situation":"formal"},
{"ko":"동공을 키우는 약을 넣어서 검사합니다.","vi":"Sẽ nhỏ thuốc giãn đồng tử để kiểm tra.","situation":"formal"},
{"ko":"검사 후 운전하지 마세요.","vi":"Sau kiểm tra không được lái xe.","situation":"informal"}],
["시력검사","안압검사","망막검사"]),

t("kham-da","피부과검진","khám da","피부 상태를 확인하고 질환을 진단하는 검사입니다. 점 검사, 피부암 선별, 알레르기 검사 등이 있습니다. 통역 시 검사 목적, 조직검사 필요성, 치료 옵션을 설명해야 합니다.",
"Kiểm tra tình trạng da và chẩn đoán bệnh da liễu",
"피부과","한국에서 피부암 발생이 증가하고 있어 점 검사가 중요합니다.",
[{"mistake":"모든 점이 암이라고 설명","correction":"대부분 양성, 변화가 있으면 검사 권장","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"피부 조직검사 설명 부족","correction":"펀치 생검으로 간단히 시행, 흉터 작음","explanation":"검사를 두려워하지 않게 합니다"},
{"mistake":"자외선 차단 교육 부족","correction":"피부암 예방을 위한 자외선 차단 중요","explanation":"예방 교육을 합니다"}],
[{"ko":"점이 변했다면 검사가 필요합니다.","vi":"Nếu nốt ruồi thay đổi thì cần kiểm tra.","situation":"formal"},
{"ko":"조직검사로 확인하겠습니다.","vi":"Sẽ lấy mẫu mô để xác nhận.","situation":"formal"},
{"ko":"이 점은 그냥 놔둬도 돼요.","vi":"Nốt ruồi này để yên cũng được.","situation":"informal"}],
["피부암","점검사","조직검사"]),

t("viem-da-tiep-xuc","접촉성피부염","viêm da tiếp xúc","알레르겐이나 자극물질에 접촉하여 발생하는 피부 염증입니다. 발진, 가려움, 물집이 나타납니다. 원인 물질 회피와 스테로이드로 치료합니다. 통역 시 원인 물질 규명, 회피 방법, 약물 사용을 설명해야 합니다.",
"Viêm da do tiếp xúc với chất gây dị ứng hoặc kích ứng",
"피부과, 알레르기내과","한국에서 접촉성피부염은 화장품, 금속, 세제 등이 흔한 원인입니다.",
[{"mistake":"원인 물질 규명 미강조","correction":"패치테스트로 원인 물질 찾기 권장","explanation":"재발 방지에 중요합니다"},
{"mistake":"스테로이드 사용 기간 미안내","correction":"짧은 기간 사용, 장기 사용 부작용 설명","explanation":"안전한 사용을 보장합니다"},
{"mistake":"직업성 피부염 가능성 미고려","correction":"작업 환경 확인, 산재 가능성 안내","explanation":"베트남 근로자에게 중요합니다"}],
[{"ko":"접촉성피부염으로 보입니다.","vi":"Có vẻ là viêm da tiếp xúc.","situation":"formal"},
{"ko":"어떤 물질에 닿았는지 생각해 보세요.","vi":"Thử nghĩ xem đã tiếp xúc với chất gì.","situation":"formal"},
{"ko":"이 물질 안 만지면 안 생겨요.","vi":"Không chạm vào chất này thì không bị.","situation":"informal"}],
["패치테스트","알레르기","스테로이드연고"]),

t("zona","대상포진","zona","수두 바이러스가 재활성화되어 발생하는 질환입니다. 띠 모양의 발진과 심한 통증이 특징입니다. 항바이러스제로 치료합니다. 통역 시 조기 치료의 중요성, 합병증(신경통), 예방접종을 설명해야 합니다.",
"Bệnh do virus thủy đậu tái hoạt, gây phát ban dạng dải và đau dữ dội",
"피부과, 감염내과","한국에서 50세 이상은 대상포진 백신이 권장됩니다. 조기 치료가 신경통 예방에 중요합니다.",
[{"mistake":"단순 피부 발진으로 설명","correction":"신경 침범으로 심한 통증 동반됨을 설명","explanation":"통증 관리의 중요성을 이해시킵니다"},
{"mistake":"조기 치료 시기 미안내","correction":"발진 72시간 내 항바이러스제 시작 중요","explanation":"합병증을 예방합니다"},
{"mistake":"대상포진 후 신경통 미설명","correction":"치료 늦으면 수개월 통증 지속 가능","explanation":"조기 치료를 독려합니다"}],
[{"ko":"대상포진으로 항바이러스제가 필요합니다.","vi":"Zona cần thuốc kháng virus.","situation":"formal"},
{"ko":"빨리 치료해야 신경통이 안 남아요.","vi":"Điều trị sớm thì không bị đau thần kinh sau này.","situation":"formal"},
{"ko":"50세 넘으면 예방주사 맞으세요.","vi":"Trên 50 tuổi nên tiêm vaccine.","situation":"informal"}],
["항바이러스제","신경통","예방접종"]),

t("benh-vay-nen","건선","bệnh vảy nến","피부 세포가 과증식하여 두꺼운 은백색 비늘이 생기는 만성 피부 질환입니다. 자가면역 관련 질환입니다. 완치보다 관리가 목표입니다. 통역 시 만성 질환임을 설명하고 치료 옵션, 심리적 지지를 제공해야 합니다.",
"Bệnh da mãn tính làm tế bào da tăng sinh quá mức tạo vảy trắng bạc",
"피부과","한국에서 건선은 삶의 질에 큰 영향을 미칩니다. 전염성이 없음을 주변에 알리는 것도 중요합니다.",
[{"mistake":"건선을 전염병으로 오해","correction":"전염되지 않는 자가면역 질환임을 명확히","explanation":"사회적 오해를 줄입니다"},
{"mistake":"완치 가능하다고 설명","correction":"관리로 호전 가능하나 완치는 어려움","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"심리적 어려움 무시","correction":"외모 변화로 인한 스트레스 인정, 지지 제공","explanation":"전인적 돌봄을 제공합니다"}],
[{"ko":"건선으로 꾸준한 관리가 필요합니다.","vi":"Bệnh vảy nến cần quản lý lâu dài.","situation":"formal"},
{"ko":"전염되지 않으니 걱정 마세요.","vi":"Không lây nhiễm nên đừng lo.","situation":"formal"},
{"ko":"스트레스 받으면 더 심해지니 마음 편히 가지세요.","vi":"Stress làm nặng thêm nên hãy thoải mái.","situation":"informal"}],
["자가면역질환","광선치료","생물학적제제"]),

t("dau-khop-co-chan","족저근막염","viêm cân gan bàn chân","발바닥의 근막에 염증이 생겨 통증이 발생하는 질환입니다. 아침에 첫 발을 딛을 때 통증이 특징입니다. 스트레칭, 깔창, 약물로 치료합니다. 통역 시 원인, 자가관리, 치료 기간을 설명해야 합니다.",
"Viêm cân gan bàn chân gây đau khi bước chân đầu tiên vào buổi sáng",
"정형외과, 재활의학과","한국에서 족저근막염은 장시간 서있는 직업에 많습니다. 베트남 근로자에게 흔할 수 있습니다.",
[{"mistake":"수술이 필요하다고 설명","correction":"대부분 비수술적 치료로 호전됨 안내","explanation":"불필요한 수술 공포를 줄입니다"},
{"mistake":"스트레칭 방법 미교육","correction":"종아리, 발바닥 스트레칭 구체적으로 교육","explanation":"자가관리가 효과적입니다"},
{"mistake":"치료 기간 짧게 설명","correction":"호전에 수개월 걸릴 수 있음 안내","explanation":"꾸준한 치료를 독려합니다"}],
[{"ko":"족저근막염으로 발뒤꿈치가 아프십니다.","vi":"Viêm cân gan bàn chân làm đau gót.","situation":"formal"},
{"ko":"스트레칭을 매일 하셔야 해요.","vi":"Phải tập giãn cơ mỗi ngày.","situation":"formal"},
{"ko":"깔창 깔면 많이 편해져요.","vi":"Lót đế thì đỡ nhiều.","situation":"informal"}],
["발뒤꿈치통증","스트레칭","깔창"]),

t("hoi-chung-ong-co-tay","손목터널증후군","hội chứng ống cổ tay","손목의 신경이 눌려 손 저림과 통증이 발생하는 질환입니다. 반복적인 손목 사용이 원인입니다. 부목, 주사, 수술로 치료합니다. 통역 시 원인, 예방, 치료 옵션을 설명해야 합니다.",
"Hội chứng đường hầm cổ tay gây tê và đau tay do thần kinh bị chèn ép",
"신경외과, 정형외과","한국에서 손목터널증후군은 사무직, 공장 근로자에게 많습니다. 산재 인정이 가능합니다.",
[{"mistake":"수술만이 치료라고 설명","correction":"초기에는 부목, 스테로이드 주사로 호전 가능","explanation":"보존적 치료를 먼저 시도합니다"},
{"mistake":"직업 관련성 미설명","correction":"반복 작업이 원인, 작업 환경 개선 권고","explanation":"재발 방지에 중요합니다"},
{"mistake":"산재 가능성 미안내","correction":"직업병으로 산재 인정 가능함을 안내","explanation":"베트남 근로자에게 중요한 정보입니다"}],
[{"ko":"손목터널증후군으로 손이 저리십니다.","vi":"Hội chứng ống cổ tay làm tê tay.","situation":"formal"},
{"ko":"밤에 부목을 차고 주무세요.","vi":"Ban đêm đeo nẹp khi ngủ.","situation":"formal"},
{"ko":"컴퓨터 많이 하면 더 심해져요.","vi":"Dùng máy tính nhiều thì nặng thêm.","situation":"informal"}],
["근전도검사","부목","스테로이드주사"]),

t("viem-gay-xuong","골절","gãy xương","뼈가 부러지거나 금이 간 상태입니다. 외상이 주요 원인입니다. 석고붕대, 수술로 치료합니다. 통역 시 골절 유형, 치료 방법, 회복 기간을 설명해야 합니다.",
"Xương bị gãy hoặc nứt do chấn thương",
"정형외과, 응급의학","한국에서 골절은 산업재해의 흔한 원인입니다. 치료 후 재활이 중요합니다.",
[{"mistake":"모든 골절이 수술 필요하다고 설명","correction":"단순 골절은 석고붕대로 치료 가능","explanation":"치료 옵션을 정확히 안내합니다"},
{"mistake":"회복 기간 짧게 설명","correction":"부위에 따라 6-12주 소요, 재활 포함 더 김","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"산재 가능성 미안내","correction":"작업 중 발생 시 산재 처리 가능","explanation":"근로자 권리를 알립니다"}],
[{"ko":"팔뼈가 골절되어 석고붕대가 필요합니다.","vi":"Xương cánh tay bị gãy cần bó bột.","situation":"formal"},
{"ko":"6주 정도 고정해야 합니다.","vi":"Cần cố định khoảng 6 tuần.","situation":"formal"},
{"ko":"무리하면 안 붙어요.","vi":"Nếu gắng sức thì không lành.","situation":"informal"}],
["석고붕대","수술","재활"]),

t("bong","화상","bỏng","열, 화학물질, 전기 등에 의해 피부가 손상된 상태입니다. 1-3도로 분류됩니다. 초기 처치가 중요합니다. 통역 시 응급처치, 치료, 흉터 관리를 설명해야 합니다.",
"Tổn thương da do nhiệt, hóa chất hoặc điện",
"응급의학, 성형외과","한국에서 화상은 가정내 사고가 많습니다. 초기 냉각이 중요합니다.",
[{"mistake":"버터나 된장을 바르라고 안내","correction":"흐르는 찬물로 20분 냉각이 올바른 응급처치","explanation":"잘못된 민간요법을 바로잡습니다"},
{"mistake":"화상 정도 미설명","correction":"1도(빨갛), 2도(물집), 3도(검음)로 설명","explanation":"치료 방향을 이해시킵니다"},
{"mistake":"감염 예방 미안내","correction":"화상 부위 청결 유지, 물집 터뜨리지 않기","explanation":"합병증을 예방합니다"}],
[{"ko":"2도 화상으로 치료가 필요합니다.","vi":"Bỏng độ 2 cần điều trị.","situation":"formal"},
{"ko":"찬물로 20분 식히셨어야 했어요.","vi":"Phải làm mát bằng nước lạnh 20 phút.","situation":"formal"},
{"ko":"물집 터뜨리면 안 돼요.","vi":"Không được chọc bóng nước.","situation":"informal"}],
["응급처치","드레싱","흉터"]),

t("cat-thuong","열상","vết cắt","피부가 날카로운 것에 베인 상처입니다. 출혈, 감염 위험이 있습니다. 봉합이 필요할 수 있습니다. 통역 시 상처 관리, 봉합 필요성, 파상풍 예방을 설명해야 합니다.",
"Vết thương do bị cắt bởi vật sắc nhọn",
"응급의학, 외과","한국에서 열상은 작업장, 주방 사고에서 흔합니다. 깊은 상처는 봉합이 필요합니다.",
[{"mistake":"모든 상처가 봉합 필요하다고 설명","correction":"얕은 상처는 테이프나 접착제로 가능","explanation":"적절한 치료를 안내합니다"},
{"mistake":"파상풍 접종 확인 안 함","correction":"마지막 접종 10년 이상이면 추가 접종 권고","explanation":"파상풍을 예방합니다"},
{"mistake":"상처 관리 미교육","correction":"청결 유지, 실밥 제거 시기 안내","explanation":"감염을 예방합니다"}],
[{"ko":"상처가 깊어서 봉합이 필요합니다.","vi":"Vết thương sâu cần khâu.","situation":"formal"},
{"ko":"파상풍 주사는 언제 맞으셨어요?","vi":"Tiêm uốn ván lần cuối khi nào?","situation":"formal"},
{"ko":"실밥은 일주일 후에 뽑아요.","vi":"Một tuần sau cắt chỉ.","situation":"informal"}],
["봉합","파상풍","상처관리"]),

t("ngo-doc-thuc-pham","식중독","ngộ độc thực phẩm","오염된 음식 섭취로 발생하는 질환입니다. 구토, 설사, 복통이 주 증상입니다. 수분 보충이 중요합니다. 통역 시 탈수 방지, 식이, 의료 기관 방문 시기를 설명해야 합니다.",
"Bệnh do ăn thực phẩm bị ô nhiễm gây nôn, tiêu chảy, đau bụng",
"감염내과, 응급의학","한국에서 식중독은 여름철에 많습니다. 탈수가 위험할 수 있어 수분 보충이 중요합니다.",
[{"mistake":"무조건 항생제 필요하다고 설명","correction":"대부분 자연 회복, 세균성일 때만 항생제","explanation":"불필요한 항생제 사용을 줄입니다"},
{"mistake":"탈수 증상 미설명","correction":"소변 감소, 어지러움 시 병원 방문 안내","explanation":"탈수를 조기 인지합니다"},
{"mistake":"식이 지도 부족","correction":"물, 이온음료 섭취, 기름진 음식 피하기","explanation":"회복을 돕습니다"}],
[{"ko":"식중독으로 보입니다.","vi":"Có vẻ là ngộ độc thực phẩm.","situation":"formal"},
{"ko":"물을 자주 드세요.","vi":"Uống nước thường xuyên.","situation":"formal"},
{"ko":"설사 심하면 다시 오세요.","vi":"Nếu tiêu chảy nặng thì đến lại.","situation":"informal"}],
["탈수","설사","이온음료"]),

t("say-ruou","음주폐해","say rượu","과음으로 인한 건강 문제입니다. 급성 알코올 중독, 간질환, 의존증이 있습니다. 통역 시 절주의 중요성, 알코올 의존 선별, 치료 연계를 설명해야 합니다.",
"Tác hại sức khỏe do uống rượu quá nhiều",
"내과, 정신건강의학과","한국에서 음주 문화가 있어 알코올 관련 질환이 많습니다. 베트남 근로자도 음주 문제가 있을 수 있습니다.",
[{"mistake":"음주를 개인 선택으로만 봄","correction":"알코올 의존은 질병, 치료 필요함을 설명","explanation":"편견을 줄입니다"},
{"mistake":"간검사만 권유","correction":"알코올 의존 선별 질문, 정신과 연계 고려","explanation":"근본 문제를 다룹니다"},
{"mistake":"문화적 맥락 무시","correction":"음주 압박 상황에서 거절 방법도 논의","explanation":"실질적 도움을 줍니다"}],
[{"ko":"간 수치가 높은 건 음주 때문입니다.","vi":"Chỉ số gan cao là do uống rượu.","situation":"formal"},
{"ko":"술을 줄이시거나 끊으셔야 합니다.","vi":"Cần giảm hoặc bỏ rượu.","situation":"formal"},
{"ko":"술 많이 드시면 간 망가져요.","vi":"Uống nhiều rượu thì gan hỏng.","situation":"informal"}],
["간질환","알코올의존","절주"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
