#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 의료장비/기구 + 추가 시술 + 간호/환자관리 용어
new = [
t("may-tho","인공호흡기","máy thở","호흡이 어려운 환자에게 산소를 공급하고 호흡을 보조하는 기계입니다. 중환자실에서 사용됩니다. 기관삽관 후 연결합니다. 통역 시 기계의 역할, 환자 상태, 가족에게 상황 설명이 필요합니다.",
"Máy hỗ trợ thở cho bệnh nhân không thể tự thở",
"중환자의학, 응급의학","한국 중환자실에서 인공호흡기는 생명 유지에 필수적입니다. 가족에게 환자 상태와 예후를 민감하게 설명합니다.",
[{"mistake":"인공호흡기를 영구적 치료로 설명","correction":"상태 호전 시 이탈(weaning) 가능","explanation":"희망을 유지하면서 현실적으로 설명합니다"},
{"mistake":"기계에만 의존한다고 설명","correction":"환자의 회복 노력과 치료 병행 설명","explanation":"치료 과정 전체를 이해시킵니다"},
{"mistake":"가족 면회 시 주의사항 미안내","correction":"면회 시간, 감염 예방 수칙 안내","explanation":"가족 참여를 돕습니다"}],
[{"ko":"호흡 보조를 위해 인공호흡기를 연결했습니다.","vi":"Đã nối máy thở để hỗ trợ hô hấp.","situation":"formal"},
{"ko":"상태가 좋아지면 기계를 뗄 수 있습니다.","vi":"Nếu tình trạng tốt hơn có thể rút máy thở.","situation":"formal"},
{"ko":"지금은 기계가 숨 쉬는 걸 도와주고 있어요.","vi":"Bây giờ máy đang giúp thở.","situation":"informal"}],
["기관삽관","중환자실","산소"]),

t("may-loc-mau","투석기","máy lọc máu","혈액에서 노폐물을 걸러내는 의료 기계입니다. 신부전 환자에게 사용됩니다. 동정맥루를 통해 혈액을 순환시킵니다. 통역 시 투석 과정, 시간, 주의사항을 설명해야 합니다.",
"Máy lọc chất thải từ máu cho bệnh nhân suy thận",
"신장내과","한국에서 투석 환자는 주 3회 4시간씩 투석을 받습니다. 생활 적응을 위한 교육이 중요합니다.",
[{"mistake":"투석기 사용을 일시적으로 설명","correction":"이식 전까지 평생 필요할 수 있음 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"투석 중 활동 제한 미설명","correction":"팔을 고정하고 4시간 대기 필요","explanation":"환자 준비를 돕습니다"},
{"mistake":"집에서 복막투석 옵션 미안내","correction":"복막투석으로 집에서 할 수도 있음 설명","explanation":"치료 선택지를 제공합니다"}],
[{"ko":"투석기로 혈액을 걸러냅니다.","vi":"Máy lọc máu sẽ lọc máu.","situation":"formal"},
{"ko":"4시간 동안 팔을 움직이면 안 됩니다.","vi":"Trong 4 tiếng không được cử động tay.","situation":"formal"},
{"ko":"투석하면서도 일상생활 할 수 있어요.","vi":"Vẫn có thể sống bình thường khi lọc máu.","situation":"informal"}],
["혈액투석","동정맥루","신부전"]),

t("may-kich-tim","제세동기","máy kích tim","심정지 시 전기 충격으로 심장 리듬을 회복시키는 기계입니다. 응급실, 공공장소에 비치됩니다. AED(자동제세동기)는 일반인도 사용 가능합니다. 통역 시 사용 시기, 방법을 설명해야 합니다.",
"Máy dùng điện kích để phục hồi nhịp tim khi ngừng tim",
"응급의학, 심장내과","한국 공공장소에 AED가 설치되어 있습니다. 심정지 시 즉각적인 사용이 생존율을 높입니다.",
[{"mistake":"전문가만 사용 가능하다고 설명","correction":"AED는 음성 안내에 따라 일반인도 사용 가능","explanation":"응급 상황에서 사용을 독려합니다"},
{"mistake":"사용 시 환자에게 해가 된다고 설명","correction":"심정지 환자에게는 필수, 더 악화될 수 없음","explanation":"사용 주저를 줄입니다"},
{"mistake":"심폐소생술과 병행 설명 부족","correction":"AED와 심폐소생술을 함께 시행 안내","explanation":"효과적인 응급 처치를 교육합니다"}],
[{"ko":"심정지로 제세동기를 사용했습니다.","vi":"Đã dùng máy kích tim vì ngừng tim.","situation":"formal"},
{"ko":"AED는 기계 음성을 따라하면 됩니다.","vi":"AED chỉ cần làm theo hướng dẫn bằng giọng nói.","situation":"formal"},
{"ko":"사람이 쓰러지면 AED 찾아서 쓰세요.","vi":"Nếu ai ngã thì tìm AED và dùng.","situation":"informal"}],
["심정지","AED","심폐소생술"]),

t("monitor","환자감시장치","monitor","환자의 활력징후를 실시간으로 모니터링하는 기계입니다. 심전도, 혈압, 산소포화도, 호흡을 측정합니다. 중환자실, 수술실에서 필수입니다. 통역 시 화면의 수치 의미를 설명해야 합니다.",
"Máy theo dõi sinh hiệu bệnh nhân theo thời gian thực",
"중환자의학, 마취통증의학과","한국 병원에서 모니터는 환자 상태 파악의 기본입니다. 알람이 울려도 즉각적인 위험이 아닐 수 있음을 가족에게 설명합니다.",
[{"mistake":"알람을 모두 위험 신호로 설명","correction":"일부 알람은 센서 문제, 간호사가 확인 중","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"수치의 의미 미설명","correction":"산소포화도, 혈압 정상 범위 간략히 안내","explanation":"가족이 상태를 이해합니다"},
{"mistake":"환자 움직임 제한 미안내","correction":"센서가 떨어지면 알람이 울림, 조심히 움직이기","explanation":"원활한 모니터링을 돕습니다"}],
[{"ko":"모니터로 환자 상태를 계속 확인합니다.","vi":"Monitor theo dõi tình trạng bệnh nhân liên tục.","situation":"formal"},
{"ko":"알람이 울려도 간호사가 바로 확인합니다.","vi":"Nếu chuông kêu điều dưỡng sẽ kiểm tra ngay.","situation":"formal"},
{"ko":"이 숫자들은 심장, 혈압, 산소예요.","vi":"Các số này là tim, huyết áp, oxy.","situation":"informal"}],
["활력징후","중환자실","산소포화도"]),

t("bom-truyen-dich","수액펌프","bơm truyền dịch","수액이나 약물을 정확한 속도로 투여하는 기계입니다. 정맥주사 라인에 연결됩니다. 용량 조절이 가능합니다. 통역 시 기계의 역할, 알람 발생 시 대처를 설명해야 합니다.",
"Máy truyền dịch hoặc thuốc với tốc độ chính xác",
"간호","한국 병원에서 수액펌프는 정확한 약물 투여에 사용됩니다. 환자가 움직여도 일정한 속도로 투여됩니다.",
[{"mistake":"기계가 복잡하다고 환자 불안 유발","correction":"정확한 양을 주기 위한 것, 안전함을 설명","explanation":"환자를 안심시킵니다"},
{"mistake":"알람 시 환자가 직접 조작하도록 안내","correction":"알람이 울리면 간호사 호출하도록 안내","explanation":"안전한 사용을 보장합니다"},
{"mistake":"라인 꼬임 주의사항 미설명","correction":"수액줄이 꼬이면 알람, 조심히 움직이기","explanation":"원활한 투여를 돕습니다"}],
[{"ko":"수액펌프로 약이 일정하게 들어갑니다.","vi":"Bơm truyền dịch đưa thuốc vào đều đều.","situation":"formal"},
{"ko":"기계가 삐 소리 나면 간호사 불러주세요.","vi":"Nếu máy kêu bíp thì gọi điều dưỡng.","situation":"formal"},
{"ko":"이 기계가 약 양을 정확히 맞춰줘요.","vi":"Máy này điều chỉnh lượng thuốc chính xác.","situation":"informal"}],
["수액","정맥주사","투약"]),

t("ong-thong-tieu","도뇨관","ống thông tiểu","방광에 삽입하여 소변을 배출하는 관입니다. 수술 후, 배뇨 곤란 시 사용합니다. 감염 예방이 중요합니다. 통역 시 삽입 이유, 관리 방법, 불편감을 설명해야 합니다.",
"Ống đặt vào bàng quang để dẫn nước tiểu ra ngoài",
"비뇨기과, 간호","한국 병원에서 도뇨관은 수술 환자에게 흔히 사용됩니다. 조기 제거를 위해 보행을 권합니다.",
[{"mistake":"도뇨관이 영구적이라고 설명","correction":"대부분 일시적, 회복되면 제거","explanation":"환자를 안심시킵니다"},
{"mistake":"불편감 미설명","correction":"이물감이 있을 수 있으나 참을 만함","explanation":"환자 준비를 돕습니다"},
{"mistake":"감염 예방 미안내","correction":"청결 유지, 소변주머니 바닥보다 낮게","explanation":"요로감염을 예방합니다"}],
[{"ko":"수술 후 도뇨관을 삽입합니다.","vi":"Sau mổ sẽ đặt ống thông tiểu.","situation":"formal"},
{"ko":"걸으실 수 있으면 빨리 뺄 수 있어요.","vi":"Nếu đi được thì có thể rút sớm.","situation":"formal"},
{"ko":"좀 불편해도 곧 익숙해져요.","vi":"Hơi khó chịu nhưng sẽ quen.","situation":"informal"}],
["방광","요로감염","수술후관리"]),

t("ong-thong-mui-da-day","비위관","ống thông mũi dạ dày","코를 통해 위까지 삽입하는 관입니다. 영양 공급, 위 내용물 배출에 사용됩니다. 삼킴 장애 환자에게 필요합니다. 통역 시 삽입 이유, 관리, 불편감을 설명해야 합니다.",
"Ống đưa qua mũi xuống dạ dày để cung cấp dinh dưỡng hoặc hút dịch",
"소화기내과, 신경과","한국에서 비위관은 뇌졸중, 수술 후 환자에게 흔히 사용됩니다. 구강 섭취가 가능해지면 제거합니다.",
[{"mistake":"비위관이 영구적이라고 설명","correction":"삼킴 기능 회복 시 제거 가능","explanation":"재활 동기를 유지합니다"},
{"mistake":"삽입 시 불편감 미설명","correction":"코와 목에 불편감 있으나 적응됨","explanation":"환자 준비를 돕습니다"},
{"mistake":"구강 위생 미안내","correction":"입으로 못 먹어도 구강 청결 유지 필요","explanation":"폐렴 예방에 중요합니다"}],
[{"ko":"삼키기 어려워 비위관으로 영양을 공급합니다.","vi":"Khó nuốt nên cung cấp dinh dưỡng qua ống thông mũi.","situation":"formal"},
{"ko":"삼킴 기능이 돌아오면 뺄 수 있어요.","vi":"Nếu nuốt được thì có thể rút.","situation":"formal"},
{"ko":"코에 불편해도 영양은 잘 들어가요.","vi":"Dù khó chịu ở mũi nhưng dinh dưỡng vào tốt.","situation":"informal"}],
["경관영양","삼킴장애","재활"]),

t("dau-trung-binh","알약","viên thuốc","경구 복용하는 고형 약물입니다. 정제, 캡슐 등의 형태가 있습니다. 물과 함께 복용합니다. 통역 시 복용 시간, 방법, 보관법을 설명해야 합니다.",
"Thuốc dạng viên uống bằng đường miệng",
"약학","한국에서 알약은 가장 흔한 약물 형태입니다. 베트남 환자에게 복용법과 부작용을 교육합니다.",
[{"mistake":"씹어 먹어도 된다고 설명","correction":"서방형 제제는 씹으면 안 됨, 통째로 삼키기","explanation":"약효에 영향을 미칩니다"},
{"mistake":"복용 시간 미안내","correction":"식전/식후/취침전 등 정확한 시간 안내","explanation":"흡수와 효과에 영향을 미칩니다"},
{"mistake":"보관법 미설명","correction":"습기 피하고, 어린이 손 닿지 않는 곳 보관","explanation":"약물 안전을 보장합니다"}],
[{"ko":"이 알약을 하루 세 번 식후에 드세요.","vi":"Uống viên thuốc này 3 lần mỗi ngày sau bữa ăn.","situation":"formal"},
{"ko":"물과 함께 통째로 삼키세요.","vi":"Nuốt cả viên với nước.","situation":"formal"},
{"ko":"이 약은 씹으면 안 돼요.","vi":"Thuốc này không được nhai.","situation":"informal"}],
["복용","처방전","부작용"]),

t("thuoc-nuoc","물약","thuốc nước","액체 형태의 경구 약물입니다. 계량컵이나 스포이드로 정확히 측정합니다. 어린이, 삼키기 어려운 환자에게 적합합니다. 통역 시 용량 측정, 복용 방법, 보관법을 설명해야 합니다.",
"Thuốc dạng lỏng uống bằng đường miệng",
"약학, 소아과","한국에서 물약은 어린이 약에 많이 사용됩니다. 정확한 용량 측정이 중요합니다.",
[{"mistake":"대충 눈대중으로 측정하도록 안내","correction":"반드시 동봉된 계량컵/스포이드 사용","explanation":"정확한 용량이 중요합니다"},
{"mistake":"냉장 보관 여부 미확인","correction":"개봉 후 냉장 보관 필요한 약 있음 안내","explanation":"약효 유지에 중요합니다"},
{"mistake":"유효기간 미안내","correction":"개봉 후 사용 기간 확인 안내","explanation":"변질된 약 사용을 방지합니다"}],
[{"ko":"이 물약을 5ml씩 하루 두 번 드세요.","vi":"Uống thuốc nước này 5ml, 2 lần mỗi ngày.","situation":"formal"},
{"ko":"계량컵으로 정확히 재서 드세요.","vi":"Đo chính xác bằng cốc đo rồi uống.","situation":"formal"},
{"ko":"냉장고에 보관하세요.","vi":"Bảo quản trong tủ lạnh.","situation":"informal"}],
["소아과","복용","계량컵"]),

t("thuoc-dat","좌약","thuốc đặt","항문이나 질에 삽입하는 약물입니다. 해열, 변비, 국소 치료에 사용됩니다. 냉장 보관이 필요합니다. 통역 시 삽입 방법, 시간, 보관법을 설명해야 합니다.",
"Thuốc đặt vào hậu môn hoặc âm đạo",
"소아과, 산부인과","한국에서 좌약은 어린이 해열, 변비 치료에 흔히 사용됩니다. 베트남 환자에게 사용법을 구체적으로 설명합니다.",
[{"mistake":"구강 복용하도록 설명","correction":"항문 삽입용임을 명확히 안내","explanation":"올바른 사용이 중요합니다"},
{"mistake":"삽입 후 바로 나올 수 있음 미설명","correction":"삽입 후 5-10분 눕거나 움직이지 않기","explanation":"약효를 보장합니다"},
{"mistake":"냉장 보관 미안내","correction":"녹을 수 있으니 냉장 보관 필수","explanation":"약물 형태를 유지합니다"}],
[{"ko":"열이 나면 이 좌약을 항문에 넣으세요.","vi":"Nếu sốt thì đặt thuốc này vào hậu môn.","situation":"formal"},
{"ko":"넣은 후 10분 정도 눕혀두세요.","vi":"Sau khi đặt cho bé nằm khoảng 10 phút.","situation":"formal"},
{"ko":"먹는 약 아니고 넣는 약이에요.","vi":"Không phải thuốc uống mà là thuốc đặt.","situation":"informal"}],
["해열","변비","소아과"]),

t("ong-hit","흡입기","ống hít","약물을 기도로 직접 흡입하는 장치입니다. 천식, COPD 치료에 필수입니다. 정확한 사용법이 효과를 좌우합니다. 통역 시 흡입 기술, 세척, 약물 종류를 교육해야 합니다.",
"Dụng cụ hít thuốc trực tiếp vào đường hô hấp",
"호흡기내과","한국에서 흡입기는 천식 환자의 필수품입니다. 올바른 사용법 교육이 치료 효과를 결정합니다.",
[{"mistake":"흡입기 종류 구분 미설명","correction":"조절제(매일)와 완화제(응급) 구분 교육","explanation":"올바른 사용이 중요합니다"},
{"mistake":"흡입 기술 미교육","correction":"숨 내쉬고-흡입-숨 참기 순서 시연","explanation":"폐까지 약이 도달해야 합니다"},
{"mistake":"스테로이드 흡입 후 구강 세척 미안내","correction":"구강 칸디다 예방 위해 입 헹구기","explanation":"부작용을 예방합니다"}],
[{"ko":"천식 조절을 위해 매일 흡입기를 사용하세요.","vi":"Để kiểm soát hen, dùng ống hít mỗi ngày.","situation":"formal"},
{"ko":"흡입 후에 물로 입을 헹구세요.","vi":"Sau khi hít, súc miệng bằng nước.","situation":"formal"},
{"ko":"흡입기 쓰는 법 제가 보여드릴게요.","vi":"Tôi sẽ hướng dẫn cách dùng ống hít.","situation":"informal"}],
["천식","COPD","스테로이드"]),

t("kim-tiem","주사기","kim tiêm","약물을 주사로 투여하는 의료기구입니다. 피하, 근육, 정맥 주사에 사용됩니다. 일회용 사용이 원칙입니다. 통역 시 주사 부위, 자가주사 방법을 설명해야 합니다.",
"Dụng cụ y tế để tiêm thuốc",
"간호, 약학","한국에서 주사기는 일회용입니다. 인슐린 등 자가주사가 필요한 환자에게 사용법을 교육합니다.",
[{"mistake":"주사기 재사용 가능하다고 설명","correction":"감염 예방 위해 일회용, 재사용 금지","explanation":"안전을 보장합니다"},
{"mistake":"자가주사 환자 교육 부족","correction":"주사 부위, 각도, 바늘 폐기법 교육","explanation":"안전한 자가주사를 돕습니다"},
{"mistake":"바늘 폐기법 미안내","correction":"전용 용기에 버리고 일반 쓰레기 금지","explanation":"찔림 사고를 예방합니다"}],
[{"ko":"인슐린 주사 놓는 법을 알려드릴게요.","vi":"Tôi sẽ hướng dẫn cách tiêm insulin.","situation":"formal"},
{"ko":"주사기는 한 번 쓰고 버리세요.","vi":"Kim tiêm dùng một lần rồi bỏ.","situation":"formal"},
{"ko":"바늘은 이 통에 넣어서 버려요.","vi":"Bỏ kim vào hộp này.","situation":"informal"}],
["인슐린","자가주사","감염예방"]),

t("sinh-hieu","활력징후","sinh hiệu","생명 유지 상태를 나타내는 기본 지표입니다. 혈압, 맥박, 체온, 호흡수를 포함합니다. 간호의 기본입니다. 통역 시 각 지표의 정상 범위와 의미를 설명해야 합니다.",
"Các chỉ số cơ bản thể hiện tình trạng sống: huyết áp, mạch, nhiệt độ, nhịp thở",
"간호","한국 병원에서 활력징후는 정기적으로 측정됩니다. 환자에게 정상 범위를 알려주면 안심할 수 있습니다.",
[{"mistake":"수치만 전달하고 의미 설명 안 함","correction":"정상 범위와 비교하여 설명","explanation":"환자가 자신의 상태를 이해합니다"},
{"mistake":"측정 시 자세 미안내","correction":"혈압은 편안히 앉아서, 체온은 5분 정도 안정 후","explanation":"정확한 측정을 돕습니다"},
{"mistake":"이상 시 대처 미설명","correction":"고열, 저혈압 등 이상 시 알리도록 안내","explanation":"조기 대처가 가능합니다"}],
[{"ko":"지금 활력징후를 측정하겠습니다.","vi":"Bây giờ tôi sẽ đo sinh hiệu.","situation":"formal"},
{"ko":"혈압이 정상 범위입니다.","vi":"Huyết áp trong phạm vi bình thường.","situation":"formal"},
{"ko":"열이 조금 있으시네요.","vi":"Bạn hơi sốt một chút.","situation":"informal"}],
["혈압","체온","맥박"]),

t("thay-bang","드레싱","thay băng","상처 부위를 소독하고 새 붕대로 교체하는 것입니다. 감염 예방과 치유 촉진을 위해 시행합니다. 상처 상태에 따라 주기가 다릅니다. 통역 시 드레싱 목적, 통증 관리, 자가 관리법을 설명해야 합니다.",
"Thay băng vết thương: sát trùng và băng mới",
"간호, 외과","한국 병원에서 드레싱은 간호사가 시행합니다. 퇴원 후 자가 관리가 필요하면 방법을 교육합니다.",
[{"mistake":"드레싱 시 통증 미설명","correction":"소독 시 따가울 수 있다고 미리 안내","explanation":"환자 준비를 돕습니다"},
{"mistake":"드레싱 주기 미안내","correction":"매일/격일/일주일 등 주기 설명","explanation":"관리 계획을 알려줍니다"},
{"mistake":"자가 드레싱 교육 부족","correction":"퇴원 후 관리법 구체적으로 교육","explanation":"감염을 예방합니다"}],
[{"ko":"상처 드레싱을 하겠습니다.","vi":"Tôi sẽ thay băng vết thương.","situation":"formal"},
{"ko":"소독할 때 좀 따가울 수 있어요.","vi":"Lúc sát trùng có thể hơi xót.","situation":"formal"},
{"ko":"이렇게 집에서도 하시면 돼요.","vi":"Ở nhà cũng làm như thế này.","situation":"informal"}],
["상처","소독","봉합"]),

t("hoi-chan","회진","hồi chẩn","담당 의사가 입원 환자를 정기적으로 방문하여 상태를 확인하는 것입니다. 보통 오전에 시행됩니다. 환자와 가족이 질문할 수 있는 기회입니다. 통역 시 회진 시간, 질문 준비를 안내해야 합니다.",
"Bác sĩ phụ trách đến thăm khám bệnh nhân nội trú định kỳ",
"의료행정, 간호","한국 병원에서 회진은 오전 8-10시에 주로 이루어집니다. 환자와 가족이 질문을 미리 준비하도록 권합니다.",
[{"mistake":"회진 시간 미안내","correction":"보통 오전 일찍, 정확한 시간은 병동마다 다름","explanation":"환자가 준비할 수 있습니다"},
{"mistake":"질문 준비 권유 없음","correction":"궁금한 점 미리 메모하도록 권유","explanation":"효과적인 의사소통을 돕습니다"},
{"mistake":"가족 면회 시간과 혼동","correction":"회진은 의사 방문, 면회는 가족 방문","explanation":"용어를 정확히 이해시킵니다"}],
[{"ko":"오전 9시에 담당 선생님 회진이 있습니다.","vi":"Lúc 9 giờ sáng bác sĩ sẽ đi thăm khám.","situation":"formal"},
{"ko":"궁금한 거 있으면 회진 때 물어보세요.","vi":"Nếu có thắc mắc thì hỏi lúc bác sĩ đến.","situation":"formal"},
{"ko":"아침에 선생님 오시니까 기다려주세요.","vi":"Sáng bác sĩ sẽ đến nên xin đợi.","situation":"informal"}],
["입원","담당의","질문"]),

t("xuat-vien","퇴원","xuất viện","치료가 완료되어 병원을 떠나는 것입니다. 퇴원 처방, 교육, 예약이 포함됩니다. 통역 시 퇴원약, 주의사항, 외래 예약을 안내해야 합니다.",
"Ra viện sau khi điều trị xong",
"의료행정","한국에서 퇴원은 담당의 허가 후 오전에 주로 이루어집니다. 퇴원 교육을 통해 가정에서의 관리를 안내합니다.",
[{"mistake":"퇴원 후 주의사항 미설명","correction":"식이, 활동 제한, 약 복용 등 구체적 안내","explanation":"합병증을 예방합니다"},
{"mistake":"외래 예약 미안내","correction":"퇴원 후 외래 방문 일정 확인","explanation":"추적 관찰이 필요합니다"},
{"mistake":"응급 상황 대처 미설명","correction":"이상 증상 발생 시 응급실 방문 안내","explanation":"안전을 보장합니다"}],
[{"ko":"오늘 퇴원하셔도 됩니다.","vi":"Hôm nay có thể xuất viện.","situation":"formal"},
{"ko":"퇴원약은 약국에서 받으세요.","vi":"Thuốc xuất viện lấy ở nhà thuốc.","situation":"formal"},
{"ko":"2주 후에 외래로 오세요.","vi":"2 tuần sau đến khám ngoại trú.","situation":"informal"}],
["퇴원약","외래예약","주의사항"]),

t("chuyen-vien","전원","chuyển viện","다른 병원으로 환자를 옮기는 것입니다. 전문 치료, 병상 부족, 환자 요청 등의 이유로 시행됩니다. 통역 시 전원 이유, 이송 방법, 준비물을 설명해야 합니다.",
"Chuyển bệnh nhân sang bệnh viện khác",
"의료행정, 응급의학","한국에서 전원은 상급병원 치료가 필요하거나 환자 요청 시 이루어집니다. 진료기록 지참이 중요합니다.",
[{"mistake":"전원을 포기로 오해","correction":"더 전문적인 치료를 위한 것임을 설명","explanation":"환자와 가족을 안심시킵니다"},
{"mistake":"이송 방법 미안내","correction":"구급차, 자가용 등 이송 방법 결정","explanation":"안전한 이송을 준비합니다"},
{"mistake":"진료기록 지참 미안내","correction":"기존 검사 결과, 진료기록 가져가기","explanation":"중복 검사를 줄입니다"}],
[{"ko":"전문 치료를 위해 대학병원으로 전원합니다.","vi":"Chuyển đến bệnh viện đại học để điều trị chuyên sâu.","situation":"formal"},
{"ko":"구급차로 모시고 갑니다.","vi":"Sẽ chuyển bằng xe cấp cứu.","situation":"formal"},
{"ko":"검사 결과 다 가져가세요.","vi":"Mang theo tất cả kết quả xét nghiệm.","situation":"informal"}],
["진료의뢰서","구급차","상급병원"]),

t("dieu-tri-ngoai-tru","외래진료","điều trị ngoại trú","입원하지 않고 병원을 방문하여 진료받는 것입니다. 예약제로 운영됩니다. 진료 후 귀가합니다. 통역 시 예약 방법, 대기 시간, 수납 절차를 안내해야 합니다.",
"Khám chữa bệnh tại bệnh viện mà không nhập viện",
"의료행정","한국에서 외래진료는 예약제가 기본입니다. 대기 시간이 길 수 있어 인내심을 요청합니다.",
[{"mistake":"예약 없이 방문해도 된다고 안내","correction":"예약 필수, 응급 아니면 예약 후 방문","explanation":"대기 시간을 줄입니다"},
{"mistake":"진료 순서 설명 부족","correction":"접수-대기-진료-수납-약국 순서 안내","explanation":"절차를 이해시킵니다"},
{"mistake":"필요 서류 미안내","correction":"건강보험증, 진료의뢰서 등 지참","explanation":"원활한 진료를 돕습니다"}],
[{"ko":"2주 후 외래로 오세요.","vi":"2 tuần sau đến khám ngoại trú.","situation":"formal"},
{"ko":"예약 시간 10분 전에 접수하세요.","vi":"Đăng ký 10 phút trước giờ hẹn.","situation":"formal"},
{"ko":"외래는 예약해야 빨라요.","vi":"Khám ngoại trú có hẹn thì nhanh hơn.","situation":"informal"}],
["예약","접수","수납"]),

t("cap-cuu-2","응급실","cấp cứu","긴급한 의료 상황에 대응하는 병원 부서입니다. 24시간 운영됩니다. 중증도에 따라 진료 순서가 결정됩니다. 통역 시 응급실 이용 기준, 중증도 분류, 대기 시간을 설명해야 합니다.",
"Khoa cấp cứu của bệnh viện, hoạt động 24 giờ",
"응급의학","한국 응급실은 중증 환자 우선입니다. 경증 환자는 대기 시간이 길 수 있음을 설명합니다.",
[{"mistake":"먼저 온 순서대로 진료한다고 설명","correction":"중증도에 따라 순서 결정됨을 안내","explanation":"응급 환자 우선 원칙을 이해시킵니다"},
{"mistake":"응급실 비용 미안내","correction":"응급 가산금이 붙어 비용이 높음 설명","explanation":"비용 예측을 돕습니다"},
{"mistake":"경증 환자 대안 미안내","correction":"경증은 주간 외래 방문 권유","explanation":"적절한 의료 이용을 돕습니다"}],
[{"ko":"응급실은 중한 환자부터 봅니다.","vi":"Phòng cấp cứu khám bệnh nhân nặng trước.","situation":"formal"},
{"ko":"대기 시간이 길 수 있습니다.","vi":"Thời gian chờ có thể lâu.","situation":"formal"},
{"ko":"급하지 않으면 내일 외래로 오세요.","vi":"Nếu không gấp thì mai đến khám ngoại trú.","situation":"informal"}],
["중증도분류","24시간","응급비용"]),

t("cham-soc-cuoi-doi","임종돌봄","chăm sóc cuối đời","환자의 마지막 시간을 존엄하게 보내도록 돕는 돌봄입니다. 통증 관리, 정서적 지지, 가족 지원을 포함합니다. 통역 시 민감하게 설명하고 가족의 준비를 돕습니다.",
"Chăm sóc giúp bệnh nhân trải qua thời gian cuối đời một cách tôn nghiêm",
"호스피스, 완화의학","한국에서 임종돌봄은 환자와 가족 모두를 위한 것입니다. 문화적으로 민감한 주제이므로 가족의 상태를 살피며 설명합니다.",
[{"mistake":"직접적으로 '죽음'이라고만 표현","correction":"'편안하게 보내드리다' 등 완곡한 표현 사용","explanation":"문화적 민감성을 존중합니다"},
{"mistake":"가족 지지 필요성 미안내","correction":"가족도 돌봄 대상, 심리 지원 가능 안내","explanation":"가족의 어려움을 인정합니다"},
{"mistake":"임종 과정 설명 부족","correction":"신체 변화, 예상 기간 등 솔직하게 설명","explanation":"준비할 수 있게 합니다"}],
[{"ko":"편안하게 마지막을 보내실 수 있도록 돕겠습니다.","vi":"Chúng tôi sẽ giúp bệnh nhân trải qua thời gian cuối một cách thoải mái.","situation":"formal"},
{"ko":"가족분들도 많이 힘드시면 상담받을 수 있어요.","vi":"Gia đình nếu quá khó khăn có thể được tư vấn.","situation":"formal"},
{"ko":"곁에 계시는 게 가장 중요해요.","vi":"Ở bên cạnh là quan trọng nhất.","situation":"informal"}],
["호스피스","완화의료","가족지지"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
