#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 약품/약물 용어 + 의료행정 + 환자관리
new = [
t("thuoc-giam-dau-opioid","마약성진통제","thuốc giảm đau opioid",
"강력한 통증 조절에 사용되는 약물로, 모르핀, 펜타닐 등이 있습니다. 암성 통증, 수술 후 통증에 처방됩니다. 중독성이 있어 의사 처방대로 복용해야 합니다. 통역 시 복용 방법, 부작용(변비, 졸음), 남용 위험을 설명해야 합니다.",
"Thuốc giảm đau mạnh có nguồn gốc từ morphine, dùng cho đau nặng",
"마취통증의학과, 종양내과","한국에서 마약성진통제는 엄격히 관리됩니다. 암 환자의 통증 조절에 중요하며, 적절히 사용하면 중독 위험이 낮음을 설명합니다.",
[{"mistake":"마약이라는 표현에 거부감 유발","correction":"의료용 강력 진통제로 설명, 중독과 구분","explanation":"환자가 필요한 통증 조절을 거부하지 않도록 합니다"},
{"mistake":"변비 부작용 미설명","correction":"대부분 변비가 생기므로 완하제 함께 처방","explanation":"흔한 부작용에 대비합니다"},
{"mistake":"복용 시간/용량 미강조","correction":"처방대로만 복용, 임의 증량 금지 안내","explanation":"안전한 사용이 중요합니다"}],
[{"ko":"통증 조절을 위해 마약성진통제를 처방합니다.","vi":"Kê thuốc giảm đau opioid để kiểm soát đau.","situation":"formal"},
{"ko":"변비약도 함께 드세요.","vi":"Uống thuốc nhuận tràng cùng.","situation":"formal"},
{"ko":"아플 때만 드시고 많이 드시면 안 돼요.","vi":"Chỉ uống khi đau và không được uống nhiều.","situation":"informal"}],
["통증","모르핀","펜타닐"]),

t("khang-sinh-tiem","주사용항생제","kháng sinh tiêm",
"정맥주사로 투여하는 항생제입니다. 경구 항생제보다 효과가 빠르고 강력합니다. 중증 감염, 패혈증에 사용됩니다. 통역 시 투여 시간, 알레르기 반응 관찰, 치료 기간을 설명해야 합니다.",
"Thuốc kháng sinh tiêm tĩnh mạch, hiệu quả nhanh và mạnh hơn thuốc uống",
"감염내과","한국에서 주사용항생제는 입원 환자에게 주로 사용됩니다. 치료 기간을 채우는 것이 내성 예방에 중요합니다.",
[{"mistake":"경구로 바꿀 수 있는 시점 미설명","correction":"호전되면 경구 항생제로 전환 가능함을 안내","explanation":"퇴원 계획에 영향을 미칩니다"},
{"mistake":"알레르기 반응 관찰 미강조","correction":"첫 투여 시 발진, 호흡곤란 등 관찰 필요","explanation":"아나필락시스 대비가 필요합니다"},
{"mistake":"치료 기간 설명 부족","correction":"증상 호전 후에도 일정 기간 투여 필요함을 안내","explanation":"조기 중단은 내성을 유발합니다"}],
[{"ko":"중증 폐렴으로 주사용항생제가 필요합니다.","vi":"Viêm phổi nặng cần kháng sinh tiêm.","situation":"formal"},
{"ko":"주사 맞을 때 가려우면 바로 말씀하세요.","vi":"Nếu ngứa khi tiêm thì báo ngay.","situation":"formal"},
{"ko":"좋아지면 약으로 바꿔서 집에서 드실 수 있어요.","vi":"Khi đỡ có thể đổi sang thuốc uống ở nhà.","situation":"informal"}],
["항생제","패혈증","내성균"]),

t("insulin","인슐린","insulin",
"혈당을 낮추는 호르몬으로, 당뇨병 치료에 주사로 투여합니다. 제1형 당뇨 필수, 제2형 당뇨에서도 필요시 사용합니다. 통역 시 주사 방법, 보관법(냉장), 저혈당 대처를 교육해야 합니다.",
"Hormone hạ đường huyết, tiêm để điều trị tiểu đường",
"내분비내과","한국에서 인슐린 주사는 당뇨 환자의 혈당 조절에 중요합니다. 베트남 환자에게 인슐린 주사가 질병 악화를 의미하지 않음을 설명합니다.",
[{"mistake":"인슐린을 마지막 수단으로 설명","correction":"필요시 조기 사용이 합병증 예방에 도움","explanation":"인슐린에 대한 편견을 줄입니다"},
{"mistake":"주사 부위 회전 미설명","correction":"같은 부위 반복 주사 피하도록 안내","explanation":"지방위축/비대를 예방합니다"},
{"mistake":"저혈당 대처법 미교육","correction":"사탕, 주스 상비, 증상 시 즉시 섭취 안내","explanation":"저혈당은 응급상황입니다"}],
[{"ko":"인슐린 주사를 시작하셔야 합니다.","vi":"Cần bắt đầu tiêm insulin.","situation":"formal"},
{"ko":"인슐린은 냉장 보관하세요.","vi":"Bảo quản insulin trong tủ lạnh.","situation":"formal"},
{"ko":"인슐린 맞는다고 병이 심해진 거 아니에요.","vi":"Tiêm insulin không có nghĩa là bệnh nặng hơn.","situation":"informal"}],
["당뇨병","혈당","저혈당"]),

t("thuoc-chong-dong","항응고제","thuốc chống đông",
"혈액 응고를 억제하여 혈전을 예방하는 약물입니다. 심방세동, 인공판막, 심부정맥혈전증에 처방됩니다. 출혈 위험이 있어 정기 검사가 필요합니다. 통역 시 복용 시간, 출혈 주의사항, 식이 상호작용을 설명해야 합니다.",
"Thuốc ức chế đông máu để ngăn ngừa huyết khối",
"심장내과, 혈액내과","한국에서 항응고제는 뇌졸중 예방에 중요합니다. 와파린은 비타민K 섭취에 주의해야 하고, 새로운 약물(NOAC)은 식이 제한이 덜합니다.",
[{"mistake":"와파린과 NOAC 구분 안 함","correction":"와파린은 정기 혈액검사, NOAC은 검사 덜 필요","explanation":"약물에 따라 관리가 다릅니다"},
{"mistake":"출혈 증상 미설명","correction":"코피, 잇몸출혈, 혈뇨, 검은변 시 내원 안내","explanation":"심각한 출혈을 조기 발견합니다"},
{"mistake":"시술/수술 전 약물 중단 미안내","correction":"치과, 내시경 등 전 의사 상담 필요","explanation":"출혈 위험 관리가 필요합니다"}],
[{"ko":"심방세동으로 항응고제를 드셔야 합니다.","vi":"Rung nhĩ cần uống thuốc chống đông.","situation":"formal"},
{"ko":"치과 가기 전에 꼭 말씀하세요.","vi":"Trước khi đi nha khoa phải báo bác sĩ.","situation":"formal"},
{"ko":"이 약 드시면서 멍이 잘 들 수 있어요.","vi":"Uống thuốc này dễ bị bầm.","situation":"informal"}],
["와파린","심방세동","혈전"]),

t("thuoc-ha-huyet-ap","혈압약","thuốc hạ huyết áp",
"혈압을 낮추는 약물로, 다양한 종류가 있습니다. ACE억제제, ARB, 칼슘채널차단제, 이뇨제 등이 있습니다. 대부분 평생 복용이 필요합니다. 통역 시 꾸준한 복용의 중요성, 부작용, 임의 중단 위험을 설명해야 합니다.",
"Thuốc hạ huyết áp, thường phải uống suốt đời",
"내과, 심장내과","한국에서 혈압약은 가장 흔히 처방되는 약물 중 하나입니다. 증상이 없어도 복용해야 하며 임의 중단이 위험함을 강조합니다.",
[{"mistake":"혈압 정상화되면 중단해도 된다고 설명","correction":"약으로 조절되는 것이므로 계속 복용 필요","explanation":"약 중단 시 혈압이 다시 오릅니다"},
{"mistake":"부작용 발생 시 임의 중단","correction":"부작용 있으면 의사와 상담하여 약 변경","explanation":"갑자기 중단하면 위험합니다"},
{"mistake":"복용 시간 미안내","correction":"같은 시간에 복용, 일부는 아침/저녁 구분 필요","explanation":"약효 유지에 중요합니다"}],
[{"ko":"혈압약은 매일 아침 드세요.","vi":"Uống thuốc huyết áp mỗi sáng.","situation":"formal"},
{"ko":"좋아져도 약을 끊으면 안 됩니다.","vi":"Dù đỡ cũng không được ngưng thuốc.","situation":"formal"},
{"ko":"어지러우면 약 바꿀 수 있어요, 말씀하세요.","vi":"Nếu chóng mặt có thể đổi thuốc, hãy nói.","situation":"informal"}],
["고혈압","이뇨제","ACE억제제"]),

t("thuoc-ha-mo-mau","콜레스테롤약","thuốc hạ mỡ máu",
"혈중 콜레스테롤을 낮추는 약물입니다. 스타틴이 가장 흔히 사용됩니다. 심혈관질환 예방에 중요합니다. 통역 시 복용 시간(저녁), 근육통 부작용, 간기능 검사 필요성을 설명해야 합니다.",
"Thuốc hạ cholesterol máu, thường dùng statin",
"내과, 심장내과","한국에서 스타틴은 널리 처방됩니다. 복용 시 근육통이 생기면 의사에게 보고하도록 교육합니다.",
[{"mistake":"모든 스타틴을 저녁에 복용하라고 안내","correction":"약물에 따라 복용 시간이 다름(일부는 언제든)","explanation":"약사/의사 지시를 따릅니다"},
{"mistake":"근육통 부작용 미설명","correction":"특히 종아리 근육통 시 보고하도록 안내","explanation":"드물게 심각한 부작용 가능"},
{"mistake":"식이요법 병행 미강조","correction":"약만으로 부족, 식이조절도 필요","explanation":"생활습관 개선이 함께 필요합니다"}],
[{"ko":"콜레스테롤을 낮추는 약을 처방합니다.","vi":"Kê thuốc hạ cholesterol.","situation":"formal"},
{"ko":"이 약은 저녁에 드세요.","vi":"Thuốc này uống vào buổi tối.","situation":"formal"},
{"ko":"근육 아프면 바로 말해요.","vi":"Nếu đau cơ thì nói ngay.","situation":"informal"}],
["고지혈증","스타틴","동맥경화"]),

t("kem-boi-da","스테로이드연고","kem bôi da steroid",
"피부 염증을 줄이는 연고입니다. 아토피, 습진, 건선 등에 사용됩니다. 강도에 따라 사용 부위와 기간이 다릅니다. 통역 시 사용 부위, 사용 기간, 부작용(피부 위축)을 설명해야 합니다.",
"Kem bôi chứa steroid để giảm viêm da",
"피부과","한국에서 스테로이드연고는 피부 질환에 흔히 처방됩니다. 베트남 환자들이 스테로이드에 대한 막연한 공포가 있을 수 있어 적절한 사용의 안전성을 설명합니다.",
[{"mistake":"스테로이드를 무조건 위험하다고 설명","correction":"적절히 사용하면 안전하고 효과적","explanation":"편견을 줄이고 치료 순응도를 높입니다"},
{"mistake":"얼굴 사용 주의사항 미설명","correction":"얼굴은 약한 연고로 단기간만 사용","explanation":"얼굴 피부가 얇아 부작용 위험이 높습니다"},
{"mistake":"점진적 중단 미안내","correction":"갑자기 중단하지 말고 서서히 줄이기","explanation":"반동 현상을 예방합니다"}],
[{"ko":"아토피에 스테로이드연고를 처방합니다.","vi":"Kê kem steroid cho viêm da cơ địa.","situation":"formal"},
{"ko":"얼굴에는 일주일 이상 바르지 마세요.","vi":"Không bôi trên mặt quá một tuần.","situation":"formal"},
{"ko":"이거 적당히 쓰면 안전해요.","vi":"Thuốc này dùng vừa phải thì an toàn.","situation":"informal"}],
["아토피","습진","피부위축"]),

t("thuoc-tri-tram-cam","항우울제","thuốc trị trầm cảm",
"우울증 치료에 사용되는 약물입니다. SSRI, SNRI 등 다양한 종류가 있습니다. 효과가 나타나기까지 2-4주가 걸립니다. 통역 시 복용 기간, 효과 발현 시간, 임의 중단 위험을 설명해야 합니다.",
"Thuốc điều trị trầm cảm, cần uống ít nhất vài tuần để có hiệu quả",
"정신건강의학과","한국에서 항우울제 처방이 증가하고 있습니다. 베트남에서 정신과 치료에 대한 편견이 있을 수 있어 약물 치료의 필요성과 안전성을 설명합니다.",
[{"mistake":"즉시 효과가 있다고 설명","correction":"2-4주 후 효과 나타남, 초기에 포기하지 않도록","explanation":"조기 중단을 방지합니다"},
{"mistake":"임의 중단 위험성 미설명","correction":"갑자기 끊으면 금단 증상, 서서히 줄여야 함","explanation":"안전한 중단이 필요합니다"},
{"mistake":"부작용만 강조","correction":"초기 부작용은 대부분 일시적임을 설명","explanation":"치료 순응도를 높입니다"}],
[{"ko":"우울증 치료를 위해 약을 처방합니다.","vi":"Kê thuốc để điều trị trầm cảm.","situation":"formal"},
{"ko":"효과는 2주 후부터 느껴지실 거예요.","vi":"Hiệu quả sẽ thấy sau 2 tuần.","situation":"formal"},
{"ko":"좋아져도 함부로 끊으면 안 돼요.","vi":"Dù đỡ cũng không được tự ý ngưng thuốc.","situation":"informal"}],
["우울증","SSRI","정신건강"]),

t("bao-hiem-y-te","건강보험","bảo hiểm y tế",
"질병 치료 비용을 지원하는 사회보험입니다. 한국에서는 국민건강보험이 있어 외국인 근로자도 가입됩니다. 본인부담금만 내면 됩니다. 통역 시 보험 적용 범위, 본인부담금, 비급여 항목을 설명해야 합니다.",
"Bảo hiểm xã hội chi trả chi phí điều trị bệnh",
"의료행정","한국의 건강보험은 전국민 대상이며 외국인 근로자도 의무가입입니다. 베트남과 시스템이 다르므로 자세한 설명이 필요합니다.",
[{"mistake":"건강보험과 실손보험 혼동","correction":"건강보험은 의무, 실손보험은 선택임을 구분","explanation":"두 보험의 역할이 다릅니다"},
{"mistake":"비급여 설명 부족","correction":"일부 항목은 보험 적용 안 됨을 안내","explanation":"예상치 못한 비용을 방지합니다"},
{"mistake":"본인부담금 계산 방법 미설명","correction":"등급에 따라 30-60% 본인부담 안내","explanation":"비용 예측에 도움이 됩니다"}],
[{"ko":"건강보험이 적용되어 비용이 저렴합니다.","vi":"Có bảo hiểm y tế nên chi phí rẻ.","situation":"formal"},
{"ko":"이 검사는 비급여라 본인부담입니다.","vi":"Xét nghiệm này không được bảo hiểm nên tự trả.","situation":"formal"},
{"ko":"외국인도 보험 되니까 걱정 마세요.","vi":"Người nước ngoài cũng có bảo hiểm, đừng lo.","situation":"informal"}],
["본인부담금","비급여","의료비"]),

t("giay-gioi-thieu","진료의뢰서","giấy giới thiệu",
"다른 병원이나 전문의에게 환자를 의뢰할 때 작성하는 문서입니다. 한국의 의료전달체계에서 상급병원 진료 시 필요합니다. 통역 시 의뢰서의 필요성, 발급 방법, 유효기간을 설명해야 합니다.",
"Giấy giới thiệu bệnh nhân đến bệnh viện hoặc bác sĩ chuyên khoa khác",
"의료행정","한국에서 3차 병원(대학병원) 진료 시 의뢰서가 필요합니다. 의뢰서 없이 방문하면 가산금이 붙습니다.",
[{"mistake":"의뢰서 없이 대학병원 가면 진료 불가라고 설명","correction":"진료는 가능하나 가산금 부과됨을 설명","explanation":"정확한 정보를 제공합니다"},
{"mistake":"의뢰서 유효기간 미안내","correction":"발급일로부터 7일 이내 사용 안내","explanation":"기간 경과 시 재발급 필요합니다"},
{"mistake":"응급 상황에도 의뢰서 필요하다고 설명","correction":"응급은 의뢰서 없이 바로 방문 가능","explanation":"응급 환자의 접근성을 보장합니다"}],
[{"ko":"대학병원 가시려면 진료의뢰서가 필요합니다.","vi":"Muốn đến bệnh viện đại học cần giấy giới thiệu.","situation":"formal"},
{"ko":"의뢰서는 7일 안에 사용하셔야 합니다.","vi":"Giấy giới thiệu phải dùng trong vòng 7 ngày.","situation":"formal"},
{"ko":"응급이면 의뢰서 없이 바로 가세요.","vi":"Nếu cấp cứu thì đi luôn, không cần giấy giới thiệu.","situation":"informal"}],
["전원","상급병원","의료전달체계"]),

t("benh-an","진료기록","bệnh án",
"환자의 진료 내용을 기록한 문서입니다. 진단명, 검사 결과, 치료 내용 등이 포함됩니다. 환자 본인은 열람 및 사본 발급이 가능합니다. 통역 시 기록 열람권, 사본 발급 방법, 개인정보 보호를 설명해야 합니다.",
"Hồ sơ ghi chép nội dung khám chữa bệnh của bệnh nhân",
"의료행정","한국에서 환자는 본인의 진료기록을 열람하고 사본을 받을 권리가 있습니다. 타 병원 전원 시 기록 지참이 도움이 됩니다.",
[{"mistake":"진료기록 열람이 불가능하다고 설명","correction":"환자 본인은 열람 및 사본 발급 권리 있음","explanation":"환자 권리를 알려줍니다"},
{"mistake":"기록 발급 비용 미안내","correction":"사본 발급 시 수수료 발생 안내","explanation":"비용 예측에 도움이 됩니다"},
{"mistake":"보험회사 제출용 서류 안내 부족","correction":"보험 청구 시 필요한 서류 종류 안내","explanation":"보험 청구에 필요합니다"}],
[{"ko":"진료기록 사본이 필요하시면 원무과에 요청하세요.","vi":"Nếu cần bản sao bệnh án hãy yêu cầu ở phòng hành chính.","situation":"formal"},
{"ko":"다른 병원에 가실 때 기록을 가져가세요.","vi":"Khi đến bệnh viện khác hãy mang theo hồ sơ.","situation":"formal"},
{"ko":"내 기록은 언제든 볼 수 있어요.","vi":"Hồ sơ của mình lúc nào cũng xem được.","situation":"informal"}],
["의무기록","진단서","사본"]),

t("giay-chung-nhan-benh","진단서","giấy chứng nhận bệnh",
"의사가 환자의 질병을 확인하여 발급하는 공식 문서입니다. 보험청구, 직장 제출, 법적 증빙에 사용됩니다. 통역 시 발급 목적, 소요 시간, 비용을 설명해야 합니다.",
"Giấy xác nhận bệnh do bác sĩ cấp, dùng cho bảo hiểm hoặc nộp cơ quan",
"의료행정","한국에서 진단서는 유료로 발급됩니다. 용도에 따라 필요한 서류가 다르므로 정확한 안내가 필요합니다.",
[{"mistake":"진단서와 소견서 구분 안 함","correction":"진단서는 질병 확인, 소견서는 의견 포함","explanation":"용도에 맞는 서류를 발급받습니다"},
{"mistake":"영문 진단서 가능 여부 미안내","correction":"영문 발급 가능하나 시간/비용 추가 안내","explanation":"본국 제출 시 필요할 수 있습니다"},
{"mistake":"발급 소요 시간 미안내","correction":"당일 또는 1-3일 소요 안내","explanation":"일정 계획에 도움이 됩니다"}],
[{"ko":"보험청구용 진단서를 발급해 드릴게요.","vi":"Tôi sẽ cấp giấy chứng nhận bệnh để bảo hiểm.","situation":"formal"},
{"ko":"영문으로 필요하시면 며칠 더 걸립니다.","vi":"Nếu cần bằng tiếng Anh thì mất thêm vài ngày.","situation":"formal"},
{"ko":"진단서 떼려면 진료비 내고 원무과 가세요.","vi":"Muốn lấy giấy chứng nhận thì đóng tiền rồi đến phòng hành chính.","situation":"informal"}],
["소견서","의무기록","보험청구"]),

t("dong-y-dieu-tri","치료동의서","đồng ý điều trị",
"시술이나 수술 전에 환자가 설명을 듣고 동의하는 문서입니다. 치료 방법, 위험성, 대안을 설명받고 서명합니다. 통역 시 내용을 정확히 전달하고 환자의 이해를 확인해야 합니다.",
"Văn bản bệnh nhân đồng ý sau khi được giải thích về điều trị",
"의료행정","한국에서 수술 전 동의서는 법적 필수입니다. 환자가 내용을 이해하고 서명하도록 통역이 중요합니다.",
[{"mistake":"형식적으로 서명만 받음","correction":"내용을 충분히 설명하고 이해 확인 후 서명","explanation":"충분한 설명을 받을 권리가 있습니다"},
{"mistake":"합병증 가능성 축소","correction":"드물지만 발생 가능한 합병증도 설명","explanation":"정보에 기반한 동의가 필요합니다"},
{"mistake":"거부 가능성 미안내","correction":"동의하지 않을 권리도 있음을 안내","explanation":"환자 자율성을 존중합니다"}],
[{"ko":"수술 전에 동의서에 서명하셔야 합니다.","vi":"Trước mổ phải ký giấy đồng ý.","situation":"formal"},
{"ko":"설명 중 이해 안 되는 부분 있으면 말씀하세요.","vi":"Nếu có gì không hiểu trong lời giải thích thì hãy nói.","situation":"formal"},
{"ko":"이 종이는 수술 허락한다는 거예요.","vi":"Giấy này là đồng ý cho mổ.","situation":"informal"}],
["수술동의서","마취동의서","설명의무"]),

t("cham-soc-dieu-duong","간호","chăm sóc điều dưỡng",
"환자의 건강 회복을 돕는 의료 활동입니다. 활력징후 측정, 투약, 상처 관리, 환자 교육 등을 수행합니다. 통역 시 간호사의 역할과 환자 협조 사항을 설명해야 합니다.",
"Hoạt động y tế hỗ trợ bệnh nhân hồi phục sức khỏe",
"간호","한국 병원에서 간호사는 24시간 환자를 돌봅니다. 베트남의 보호자 중심 간병 문화와 다를 수 있어 설명이 필요합니다.",
[{"mistake":"간호사를 의사 보조로만 설명","correction":"독립적인 전문직으로 중요한 역할 수행","explanation":"간호사 역할을 정확히 전달합니다"},
{"mistake":"콜벨 사용법 미안내","correction":"도움 필요 시 콜벨 누르라고 안내","explanation":"적시에 도움을 받을 수 있습니다"},
{"mistake":"보호자 면회 규정 미설명","correction":"면회 시간, 감염관리 규정 안내","explanation":"병원 규정을 따르도록 합니다"}],
[{"ko":"간호사가 4시간마다 활력징후를 측정합니다.","vi":"Điều dưỡng sẽ đo sinh hiệu mỗi 4 tiếng.","situation":"formal"},
{"ko":"필요하시면 이 버튼을 누르세요.","vi":"Nếu cần gì hãy nhấn nút này.","situation":"formal"},
{"ko":"간호사 선생님이 주사 놓으러 올 거예요.","vi":"Cô điều dưỡng sẽ đến để tiêm.","situation":"informal"}],
["활력징후","투약","환자교육"]),

t("phuc-hoi-chuc-nang","재활치료","phục hồi chức năng",
"질병이나 손상 후 기능 회복을 위한 치료입니다. 물리치료, 작업치료, 언어치료 등이 포함됩니다. 뇌졸중, 골절, 수술 후에 중요합니다. 통역 시 재활의 중요성과 환자의 적극적 참여를 강조해야 합니다.",
"Điều trị phục hồi chức năng sau bệnh hoặc chấn thương",
"재활의학과","한국에서 재활치료는 급성기 치료 후 중요한 과정입니다. 환자와 가족의 적극적인 참여가 결과를 좌우합니다.",
[{"mistake":"재활을 수동적 치료로 설명","correction":"환자의 적극적 참여가 필수임을 강조","explanation":"노력 없이는 회복이 어렵습니다"},
{"mistake":"재활 기간 설명 부족","correction":"수개월 이상 걸릴 수 있음을 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"가정 운동 프로그램 미안내","correction":"병원 외에서도 운동 계속해야 함을 강조","explanation":"일상에서의 노력이 중요합니다"}],
[{"ko":"뇌졸중 후 재활치료가 중요합니다.","vi":"Sau đột quỵ cần phục hồi chức năng.","situation":"formal"},
{"ko":"집에서도 운동을 계속하셔야 합니다.","vi":"Ở nhà cũng phải tiếp tục tập.","situation":"formal"},
{"ko":"재활 열심히 하면 많이 좋아질 수 있어요.","vi":"Tập phục hồi chăm chỉ thì sẽ khá hơn nhiều.","situation":"informal"}],
["물리치료","작업치료","언어치료"]),

t("cham-soc-giam-nhe","완화의료","chăm sóc giảm nhẹ",
"완치가 어려운 환자의 통증과 증상을 완화하고 삶의 질을 높이는 의료입니다. 암 말기 환자에게 주로 제공됩니다. 통역 시 완화의료의 목적, 가족 지지, 호스피스와의 관계를 설명해야 합니다.",
"Y tế giảm đau và triệu chứng cho bệnh nhân không thể chữa khỏi",
"완화의학과, 종양내과","한국에서 완화의료는 암 환자의 권리로 인정됩니다. 치료 포기가 아닌 삶의 질 향상이 목표임을 설명합니다.",
[{"mistake":"완화의료를 포기로 설명","correction":"적극적인 증상 관리와 삶의 질 향상 목표","explanation":"부정적 인식을 바로잡습니다"},
{"mistake":"호스피스와 완화의료 혼동","correction":"완화의료는 치료와 병행 가능, 호스피스는 말기","explanation":"두 개념을 구분합니다"},
{"mistake":"가족 지지 중요성 미강조","correction":"환자와 가족 모두를 위한 의료임을 설명","explanation":"가족도 돌봄의 대상입니다"}],
[{"ko":"완화의료로 통증 관리를 받으실 수 있습니다.","vi":"Có thể được chăm sóc giảm nhẹ để kiểm soát đau.","situation":"formal"},
{"ko":"편안하게 지내시는 것이 목표입니다.","vi":"Mục tiêu là để bệnh nhân được thoải mái.","situation":"formal"},
{"ko":"완화의료는 포기가 아니에요.","vi":"Chăm sóc giảm nhẹ không phải là từ bỏ.","situation":"informal"}],
["호스피스","통증관리","삶의질"]),

t("hospice","호스피스","hospice",
"말기 환자에게 임종까지 편안한 돌봄을 제공하는 의료 서비스입니다. 통증 관리, 정서적 지지, 영적 돌봄을 포함합니다. 통역 시 호스피스의 의미, 가족의 역할, 임종 준비를 민감하게 설명해야 합니다.",
"Dịch vụ chăm sóc bệnh nhân giai đoạn cuối đến khi qua đời",
"호스피스완화의료","한국에서 호스피스는 건강보험이 적용됩니다. 문화적으로 민감한 주제이므로 환자와 가족의 준비 정도를 고려하여 설명합니다.",
[{"mistake":"호스피스를 죽음을 기다리는 곳으로만 설명","correction":"남은 시간을 의미있게 보내도록 돕는 곳","explanation":"긍정적인 측면을 강조합니다"},
{"mistake":"가족 참여 미안내","correction":"가족이 함께 머물며 돌볼 수 있음을 안내","explanation":"가족의 역할이 중요합니다"},
{"mistake":"비용 부담 미설명","correction":"건강보험 적용으로 부담이 적음을 안내","explanation":"경제적 걱정을 덜어줍니다"}],
[{"ko":"호스피스에서 편안하게 지내실 수 있습니다.","vi":"Có thể nghỉ ngơi thoải mái ở hospice.","situation":"formal"},
{"ko":"가족분들도 함께 계실 수 있어요.","vi":"Người nhà cũng có thể ở cùng.","situation":"formal"},
{"ko":"호스피스는 마지막 시간을 좋게 보내는 곳이에요.","vi":"Hospice là nơi để trải qua thời gian cuối một cách tốt đẹp.","situation":"informal"}],
["완화의료","임종","가족지지"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
