#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 추가 질병/증상 및 검사 용어들
new = [
t("viem-da-co-dia","아토피피부염","viêm da cơ địa","피부에 만성적으로 가려움과 발진이 반복되는 질환입니다. 유전적 요인과 환경적 요인이 복합적으로 작용합니다. 보습, 스테로이드, 면역조절제로 관리합니다. 통역 시 만성 질환임을 설명하고 악화 요인 회피, 보습의 중요성을 교육해야 합니다.",
"Bệnh da mãn tính gây ngứa và phát ban, do yếu tố di truyền và môi trường",
"피부과, 알레르기내과","한국에서 아토피피부염 환자가 증가하고 있습니다. 베트남 환자에게 보습제 사용, 목욕 방법, 악화 요인 회피를 교육합니다.",
[{"mistake":"완치 가능하다고 설명","correction":"만성 질환으로 관리가 목표임을 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"스테로이드 공포 조장","correction":"적절히 사용하면 안전함을 설명","explanation":"치료 순응도를 높입니다"},
{"mistake":"보습 중요성 미강조","correction":"하루 2회 이상 보습제 사용 권고","explanation":"피부장벽 회복에 필수입니다"}],
[{"ko":"아토피피부염은 꾸준한 관리가 필요합니다.","vi":"Viêm da cơ địa cần quản lý lâu dài.","situation":"formal"},
{"ko":"보습제를 자주 바르세요.","vi":"Bôi kem dưỡng ẩm thường xuyên.","situation":"formal"},
{"ko":"가려워도 긁지 마세요.","vi":"Dù ngứa cũng đừng gãi.","situation":"informal"}],
["보습제","스테로이드연고","알레르기"]),

t("dai-thao-duong","당뇨병","đái tháo đường","혈당이 지속적으로 높은 대사 질환입니다. 제1형(인슐린 의존)과 제2형(인슐린 저항)으로 구분됩니다. 합병증 예방을 위해 혈당 조절이 중요합니다. 통역 시 혈당 목표, 저혈당 대처, 정기 검진 항목을 교육해야 합니다.",
"Bệnh rối loạn chuyển hóa với đường huyết cao liên tục",
"내분비내과","한국에서 당뇨병은 성인의 약 10%가 앓습니다. 베트남 환자에게 식이, 운동, 약물 복용의 중요성을 강조합니다.",
[{"mistake":"당뇨를 완치 가능하다고 설명","correction":"평생 관리가 필요한 만성질환임을 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"저혈당 대처법 미교육","correction":"사탕/주스 상비, 증상 시 즉시 섭취 안내","explanation":"저혈당은 응급상황입니다"},
{"mistake":"합병증 검사 미안내","correction":"눈, 신장, 발 정기 검사 필요성 안내","explanation":"합병증 조기 발견이 중요합니다"}],
[{"ko":"혈당이 높아 당뇨병 진단입니다.","vi":"Đường huyết cao nên chẩn đoán tiểu đường.","situation":"formal"},
{"ko":"하루에 혈당을 2번 재세요.","vi":"Mỗi ngày đo đường huyết 2 lần.","situation":"formal"},
{"ko":"단 거 많이 드시면 안 돼요.","vi":"Không được ăn nhiều đồ ngọt.","situation":"informal"}],
["혈당","인슐린","당화혈색소"]),

t("viem-gan-man","만성간염","viêm gan mạn","간에 염증이 6개월 이상 지속되는 상태입니다. B형, C형 간염 바이러스가 주요 원인입니다. 간경변, 간암으로 진행할 수 있어 정기 관리가 필요합니다. 통역 시 정기 검진 일정, 음주 금지, 항바이러스 치료 필요성을 설명해야 합니다.",
"Viêm gan kéo dài trên 6 tháng, có thể tiến triển thành xơ gan và ung thư gan",
"소화기내과, 감염내과","한국에서 B형간염 보유자가 많아 정기 관리가 중요합니다. 베트남도 B형간염 유병률이 높아 환자 교육이 필요합니다.",
[{"mistake":"간염 보유자를 환자와 동일시","correction":"보유자는 무증상일 수 있으나 전염 가능성 있음 설명","explanation":"정확한 상태를 이해시킵니다"},
{"mistake":"항바이러스 치료 시작 기준 미설명","correction":"바이러스 수치, 간 상태에 따라 치료 결정","explanation":"모든 보유자가 치료 대상은 아닙니다"},
{"mistake":"생활 주의사항 미안내","correction":"음주 금지, 정기 검진, 가족 검사 권고","explanation":"간 보호와 전파 예방이 필요합니다"}],
[{"ko":"만성간염으로 정기 관리가 필요합니다.","vi":"Viêm gan mạn cần quản lý định kỳ.","situation":"formal"},
{"ko":"술은 절대 드시면 안 됩니다.","vi":"Tuyệt đối không được uống rượu.","situation":"formal"},
{"ko":"6개월마다 검사받으세요.","vi":"Mỗi 6 tháng khám một lần.","situation":"informal"}],
["B형간염","간경변","간암"]),

t("loet-da-day","위궤양","loét dạ dày","위 점막에 궤양(상처)이 생긴 질환입니다. 헬리코박터균 감염과 진통제 사용이 주요 원인입니다. 위산 억제제와 항생제로 치료합니다. 통역 시 약 복용 기간, 식이 주의사항, 헬리코박터 제균 치료를 설명해야 합니다.",
"Vết loét ở niêm mạc dạ dày, do vi khuẩn HP hoặc thuốc giảm đau",
"소화기내과","한국에서 위궤양은 흔한 소화기 질환입니다. 헬리코박터 제균 성공률이 높아 완치가 가능합니다.",
[{"mistake":"헬리코박터 제균 치료 미설명","correction":"항생제 병용으로 균 제거 가능함을 안내","explanation":"원인 치료가 중요합니다"},
{"mistake":"식이 제한 과장","correction":"매운 음식보다 과식, 음주가 더 해로움 설명","explanation":"올바른 식이 교육을 합니다"},
{"mistake":"진통제 주의사항 미안내","correction":"NSAIDs 장기 복용 시 위험, 대안 안내","explanation":"재발 예방에 중요합니다"}],
[{"ko":"위궤양으로 약물 치료가 필요합니다.","vi":"Loét dạ dày cần điều trị bằng thuốc.","situation":"formal"},
{"ko":"헬리코박터균을 제거하는 항생제입니다.","vi":"Đây là kháng sinh diệt vi khuẩn HP.","situation":"formal"},
{"ko":"밥 먹기 전에 속쓰림 약 드세요.","vi":"Uống thuốc dạ dày trước khi ăn.","situation":"informal"}],
["헬리코박터","위산억제제","위내시경"]),

t("soi-than","신장결석","sỏi thận","신장에 돌(결석)이 생기는 질환입니다. 심한 옆구리 통증(산통)이 특징입니다. 크기에 따라 자연 배출, 체외충격파, 수술로 치료합니다. 통역 시 통증 관리, 수분 섭취, 재발 예방을 교육해야 합니다.",
"Sỏi hình thành trong thận gây đau dữ dội ở hông",
"비뇨기과","한국에서 신장결석은 여름에 많이 발생합니다. 수분 섭취 부족이 주요 원인이므로 예방법을 교육합니다.",
[{"mistake":"모든 결석이 수술 필요하다고 설명","correction":"작은 결석은 자연 배출 가능함을 안내","explanation":"불필요한 불안을 줄입니다"},
{"mistake":"체외충격파(ESWL) 설명 부족","correction":"비침습적으로 결석을 깨는 방법 설명","explanation":"치료 옵션을 이해시킵니다"},
{"mistake":"재발 예방 미교육","correction":"하루 2L 이상 수분 섭취 권고","explanation":"재발률이 높아 예방이 중요합니다"}],
[{"ko":"신장결석으로 통증이 심하십니다.","vi":"Sỏi thận gây đau dữ dội.","situation":"formal"},
{"ko":"물을 많이 드시면 자연 배출될 수 있어요.","vi":"Uống nhiều nước thì có thể tự ra.","situation":"formal"},
{"ko":"물 많이 마시는 게 제일 중요해요.","vi":"Uống nhiều nước là quan trọng nhất.","situation":"informal"}],
["요로결석","체외충격파","수분섭취"]),

t("thoat-vi-dia-dem","디스크","thoát vị đĩa đệm","척추 뼈 사이 디스크(추간판)가 튀어나와 신경을 누르는 질환입니다. 허리, 목에 주로 발생하며 팔다리 저림, 통증이 나타납니다. 물리치료, 약물, 시술, 수술로 치료합니다. 통역 시 보존적 치료의 중요성과 수술 기준을 설명해야 합니다.",
"Đĩa đệm cột sống thoát ra ngoài chèn ép thần kinh gây đau và tê",
"신경외과, 정형외과","한국에서 디스크는 흔한 척추 질환입니다. 대부분 수술 없이 호전되므로 보존적 치료를 먼저 시도합니다.",
[{"mistake":"디스크를 모두 수술이 필요한 병으로 설명","correction":"80-90%는 비수술적 치료로 호전됨을 안내","explanation":"불필요한 수술 공포를 줄입니다"},
{"mistake":"허리 디스크와 목 디스크 구분 안 함","correction":"증상 부위(팔/다리)에 따라 위치가 다름 설명","explanation":"정확한 진단 위치를 이해시킵니다"},
{"mistake":"응급 수술 기준 미설명","correction":"마비, 대소변 장애 시 응급 수술 필요","explanation":"위험 신호를 알려줍니다"}],
[{"ko":"허리 디스크로 다리가 저리십니다.","vi":"Thoát vị đĩa đệm lưng gây tê chân.","situation":"formal"},
{"ko":"물리치료를 먼저 해보겠습니다.","vi":"Sẽ thử vật lý trị liệu trước.","situation":"formal"},
{"ko":"디스크 대부분은 수술 안 해도 돼요.","vi":"Hầu hết thoát vị đĩa đệm không cần mổ.","situation":"informal"}],
["추간판탈출증","물리치료","신경차단술"]),

t("viem-khop-dang-thap","류마티스관절염","viêm khớp dạng thấp","면역체계가 자신의 관절을 공격하는 자가면역 질환입니다. 여러 관절에 대칭적으로 부종과 통증이 나타납니다. 조기 치료로 관절 변형을 예방합니다. 통역 시 약물 복용의 중요성, 정기 검사, 생활 관리를 교육해야 합니다.",
"Bệnh tự miễn khiến hệ miễn dịch tấn công khớp gây sưng đau nhiều khớp",
"류마티스내과","한국에서 류마티스관절염은 여성에게 많습니다. 조기 진단과 치료가 예후를 크게 좌우합니다.",
[{"mistake":"퇴행성관절염과 혼동","correction":"류마티스는 자가면역, 퇴행성은 마모 질환","explanation":"치료 방법이 다릅니다"},
{"mistake":"완치 가능하다고 설명","correction":"관해(증상 조절) 상태 유지가 목표","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"면역억제제 부작용만 강조","correction":"약물 이점이 위험보다 크다는 것을 설명","explanation":"치료 순응도를 높입니다"}],
[{"ko":"류마티스관절염으로 면역억제제가 필요합니다.","vi":"Viêm khớp dạng thấp cần thuốc ức chế miễn dịch.","situation":"formal"},
{"ko":"정기적으로 혈액검사를 받으셔야 합니다.","vi":"Cần xét nghiệm máu định kỳ.","situation":"formal"},
{"ko":"약 잘 드시면 관절 안 망가져요.","vi":"Uống thuốc đều thì khớp không bị hỏng.","situation":"informal"}],
["자가면역질환","면역억제제","관절변형"]),

t("gout","통풍","gout","요산이 관절에 쌓여 심한 통증을 유발하는 질환입니다. 주로 엄지발가락에 갑자기 발생합니다. 급성기에는 소염제, 장기적으로 요산저하제로 관리합니다. 통역 시 식이 제한(퓨린), 금주, 약물 복용을 교육해야 합니다.",
"Bệnh gây đau dữ dội ở khớp do acid uric tích tụ",
"류마티스내과","한국에서 통풍은 중년 남성에게 많습니다. 맥주와 내장류 섭취를 피하도록 식이 교육이 중요합니다.",
[{"mistake":"통풍 발작 중 요산저하제 시작","correction":"발작이 가라앉은 후 시작해야 함을 설명","explanation":"발작 중 시작하면 악화될 수 있습니다"},
{"mistake":"식이만으로 조절 가능하다고 설명","correction":"대부분 약물 치료가 필요함을 안내","explanation":"식이만으로는 한계가 있습니다"},
{"mistake":"증상 없으면 약 중단해도 된다고 설명","correction":"요산 수치 유지를 위해 지속 복용 필요","explanation":"발작 예방이 목표입니다"}],
[{"ko":"통풍 발작으로 관절이 붓고 아프십니다.","vi":"Cơn gout làm khớp sưng đau.","situation":"formal"},
{"ko":"맥주와 내장류는 피하세요.","vi":"Tránh bia và nội tạng.","situation":"formal"},
{"ko":"술 드시면 통풍 또 와요.","vi":"Uống rượu thì lại bị gout.","situation":"informal"}],
["요산","퓨린","소염제"]),

t("co-giat-sot","열성경련","co giật sốt","고열 시 발생하는 어린이의 경련입니다. 6개월-5세 사이에 흔합니다. 대부분 양성이며 후유증 없이 호전됩니다. 통역 시 응급 대처법, 간질과의 차이, 재발 가능성을 설명해야 합니다.",
"Co giật ở trẻ em khi sốt cao, thường xảy ra ở trẻ 6 tháng đến 5 tuổi",
"소아과, 응급의학과","한국에서 열성경련은 부모에게 매우 두려운 상황입니다. 대부분 양호한 예후를 가지므로 안심시키는 것이 중요합니다.",
[{"mistake":"열성경련을 간질로 설명","correction":"열성경련은 간질과 다르며 대부분 5세 이후 없어짐","explanation":"불필요한 걱정을 줄입니다"},
{"mistake":"경련 중 입에 뭔가 넣으라고 안내","correction":"입에 아무것도 넣지 말고 옆으로 눕히라고 안내","explanation":"올바른 응급 대처법입니다"},
{"mistake":"해열제로 예방 가능하다고 설명","correction":"해열제가 열성경련을 예방하지 못함을 안내","explanation":"과학적 근거를 전달합니다"}],
[{"ko":"열성경련으로 보입니다, 크게 걱정 안 하셔도 됩니다.","vi":"Đây là co giật sốt, không cần lo lắng nhiều.","situation":"formal"},
{"ko":"경련할 때 옆으로 눕히세요.","vi":"Khi co giật cho bé nằm nghiêng.","situation":"formal"},
{"ko":"크면 안 그래요, 걱정 마세요.","vi":"Lớn lên sẽ hết, đừng lo.","situation":"informal"}],
["고열","경련","소아과"]),

t("viem-tai-giua","중이염","viêm tai giữa","귀 안쪽(중이)에 염증이 생기는 질환입니다. 어린이에게 흔하며 감기 후 발생합니다. 통증, 발열, 청력 저하가 나타납니다. 통역 시 항생제 필요성, 귀 관리, 합병증 예방을 설명해야 합니다.",
"Viêm tai giữa, phổ biến ở trẻ em sau khi bị cảm",
"이비인후과, 소아과","한국에서 중이염은 소아 외래 방문의 흔한 원인입니다. 항생제 사용 기준과 귀 관리 방법을 교육합니다.",
[{"mistake":"모든 중이염에 항생제 필요하다고 설명","correction":"경증은 경과 관찰 가능, 의사 판단에 따름","explanation":"항생제 남용을 줄입니다"},
{"mistake":"귀에 물 들어가서 생긴다고 설명","correction":"대부분 상기도 감염 후 이관 기능 장애로 발생","explanation":"정확한 원인을 설명합니다"},
{"mistake":"완전히 나을 때까지 치료 중요성 미강조","correction":"중간에 끊으면 재발, 만성화 위험 안내","explanation":"치료 완료의 중요성을 강조합니다"}],
[{"ko":"중이염으로 항생제가 필요합니다.","vi":"Viêm tai giữa cần kháng sinh.","situation":"formal"},
{"ko":"약은 끝까지 다 드셔야 합니다.","vi":"Thuốc phải uống hết.","situation":"formal"},
{"ko":"아이가 귀 아프다고 하면 빨리 오세요.","vi":"Nếu bé kêu đau tai thì đến ngay.","situation":"informal"}],
["이비인후과","항생제","청력"]),

t("viem-ket-mac","결막염","viêm kết mạc","눈 결막에 염증이 생기는 질환입니다. 바이러스, 세균, 알레르기가 원인입니다. 충혈, 분비물, 가려움이 나타납니다. 통역 시 전염 예방, 눈 위생, 약물 사용법을 교육해야 합니다.",
"Viêm kết mạc (mắt đỏ) do virus, vi khuẩn hoặc dị ứng",
"안과","한국에서 유행성결막염은 전염성이 높아 격리가 필요합니다. 손 씻기와 개인 물건 분리 사용을 강조합니다.",
[{"mistake":"모든 결막염에 항생제 안약 처방","correction":"바이러스성은 항생제 효과 없음, 대증치료 설명","explanation":"원인에 따라 치료가 다릅니다"},
{"mistake":"전염 기간 미안내","correction":"유행성결막염은 2주간 전염 가능, 출근/등교 제한","explanation":"전파 예방이 중요합니다"},
{"mistake":"안약 사용법 미교육","correction":"손 씻고 점안, 용기 끝 닿지 않게 안내","explanation":"2차 감염을 예방합니다"}],
[{"ko":"결막염으로 안약을 처방합니다.","vi":"Viêm kết mạc nên kê thuốc nhỏ mắt.","situation":"formal"},
{"ko":"수건 따로 쓰시고 손 자주 씻으세요.","vi":"Dùng khăn riêng và rửa tay thường xuyên.","situation":"formal"},
{"ko":"눈병이라 다른 사람한테 옮길 수 있어요.","vi":"Đau mắt đỏ có thể lây cho người khác.","situation":"informal"}],
["안과","안약","전염병"]),

t("cam-cum","독감","cảm cúm","인플루엔자 바이러스에 의한 급성 호흡기 질환입니다. 고열, 근육통, 기침이 특징입니다. 일반 감기보다 증상이 심합니다. 통역 시 예방접종, 항바이러스제, 합병증 위험군을 설명해야 합니다.",
"Bệnh cấp tính do virus cúm gây sốt cao, đau cơ, ho",
"내과, 감염내과","한국에서 독감 예방접종은 매년 가을에 권장됩니다. 고위험군(노인, 만성질환자)은 무료 접종이 가능합니다.",
[{"mistake":"독감과 감기 구분 안 함","correction":"독감은 더 심하고 갑자기 시작됨을 설명","explanation":"적절한 치료 시기를 놓치지 않습니다"},
{"mistake":"항바이러스제 시기 미안내","correction":"증상 48시간 내 복용 시 효과적","explanation":"조기 치료가 중요합니다"},
{"mistake":"합병증 위험군 미설명","correction":"노인, 임산부, 만성질환자 합병증 주의","explanation":"고위험군 관리가 필요합니다"}],
[{"ko":"독감 양성으로 항바이러스제를 처방합니다.","vi":"Dương tính cúm nên kê thuốc kháng virus.","situation":"formal"},
{"ko":"증상 시작 2일 내에 약을 드셔야 효과가 좋습니다.","vi":"Uống thuốc trong 2 ngày đầu triệu chứng mới hiệu quả.","situation":"formal"},
{"ko":"독감은 감기보다 심해요, 푹 쉬세요.","vi":"Cúm nặng hơn cảm, nghỉ ngơi đi.","situation":"informal"}],
["인플루엔자","예방접종","타미플루"]),

t("xet-nghiem-phan","대변검사","xét nghiệm phân","대변을 검사하여 소화기 질환을 진단하는 방법입니다. 잠혈, 기생충, 세균 감염을 확인합니다. 대장암 선별검사로도 사용됩니다. 통역 시 검체 채취 방법, 검사 목적을 설명해야 합니다.",
"Xét nghiệm phân để chẩn đoán bệnh tiêu hóa, ký sinh trùng, máu ẩn",
"소화기내과, 건강검진","한국에서 분변잠혈검사는 50세 이상 대장암 선별검사입니다. 양성 시 대장내시경을 권장합니다.",
[{"mistake":"검체 채취 방법 미설명","correction":"검체 용기 사용법, 냉장 보관 안내","explanation":"검체 품질이 결과에 영향을 미칩니다"},
{"mistake":"잠혈 양성의 의미 미설명","correction":"양성이 곧 암을 의미하지 않음, 추가 검사 필요","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"생리 중 검사 주의 미안내","correction":"여성은 생리 후 검사 권고","explanation":"위양성을 줄입니다"}],
[{"ko":"대장암 선별을 위해 대변검사를 합니다.","vi":"Xét nghiệm phân để tầm soát ung thư đại tràng.","situation":"formal"},
{"ko":"이 용기에 변을 조금 담아오세요.","vi":"Lấy một ít phân vào hộp này.","situation":"formal"},
{"ko":"피 섞여 나왔다고 다 암은 아니에요.","vi":"Có máu ẩn không có nghĩa là ung thư.","situation":"informal"}],
["분변잠혈검사","대장내시경","대장암"]),

t("soi-duc-thuy-tinh-the","백내장","đục thủy tinh thể","눈의 수정체가 혼탁해지는 질환입니다. 노화가 주요 원인이며 시력 저하가 나타납니다. 수술로 인공수정체를 삽입하여 치료합니다. 통역 시 수술 과정, 회복 기간, 인공수정체 종류를 설명해야 합니다.",
"Bệnh đục thủy tinh thể do lão hóa gây giảm thị lực, điều trị bằng phẫu thuật",
"안과","한국에서 백내장 수술은 가장 흔한 안과 수술입니다. 보험 적용 인공수정체와 비급여 다초점 렌즈의 차이를 설명합니다.",
[{"mistake":"백내장과 녹내장 혼동","correction":"백내장은 수정체 혼탁, 녹내장은 안압 상승으로 구분","explanation":"두 질환은 다릅니다"},
{"mistake":"수술 후 즉시 정상 시력 기대","correction":"완전 회복에 1-2개월 소요될 수 있음 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"인공수정체 종류 미설명","correction":"단초점/다초점, 보험/비급여 옵션 안내","explanation":"환자가 선택할 수 있어야 합니다"}],
[{"ko":"백내장 수술로 시력이 회복됩니다.","vi":"Mổ đục thủy tinh thể sẽ phục hồi thị lực.","situation":"formal"},
{"ko":"수술 후 한 달 정도 눈을 조심하셔야 합니다.","vi":"Sau mổ phải cẩn thận mắt khoảng 1 tháng.","situation":"formal"},
{"ko":"백내장 수술은 간단해요, 걱정 마세요.","vi":"Mổ đục thủy tinh thể đơn giản, đừng lo.","situation":"informal"}],
["인공수정체","안과수술","시력"]),

t("glaucoma","녹내장","glaucoma","안압 상승으로 시신경이 손상되는 질환입니다. 서서히 시야가 좁아지며 실명으로 이어질 수 있습니다. 안약, 레이저, 수술로 안압을 조절합니다. 통역 시 정기 검진, 안약 사용의 중요성, 비가역적 손상을 설명해야 합니다.",
"Bệnh tăng nhãn áp làm tổn thương thần kinh thị giác, có thể dẫn đến mù",
"안과","한국에서 녹내장은 40세 이상 정기 검진이 권장됩니다. 초기에 증상이 없어 발견이 늦어지는 경우가 많습니다.",
[{"mistake":"녹내장을 완치 가능하다고 설명","correction":"진행을 늦추는 것이 목표, 손상된 시야는 회복 안 됨","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"안약 사용 중요성 미강조","correction":"매일 정해진 시간에 점안, 임의 중단 금지","explanation":"안압 조절에 필수입니다"},
{"mistake":"정기 검진 필요성 미안내","correction":"3-6개월마다 안압, 시야 검사 필요","explanation":"진행 모니터링이 중요합니다"}],
[{"ko":"녹내장으로 안압 관리가 필요합니다.","vi":"Glaucoma cần kiểm soát nhãn áp.","situation":"formal"},
{"ko":"안약을 매일 꼭 넣으셔야 합니다.","vi":"Phải nhỏ thuốc mỗi ngày.","situation":"formal"},
{"ko":"녹내장은 실명할 수 있으니 약 꼭 넣으세요.","vi":"Glaucoma có thể mù nên phải nhỏ thuốc.","situation":"informal"}],
["안압","시야검사","안과"]),

t("suy-giam-thinh-luc","난청","suy giảm thính lực","청력이 저하되는 상태입니다. 노화, 소음, 질병 등이 원인입니다. 보청기나 인공와우 이식으로 재활합니다. 통역 시 청력검사 결과 해석, 보청기 적응, 의사소통 방법을 설명해야 합니다.",
"Tình trạng giảm khả năng nghe do lão hóa, tiếng ồn hoặc bệnh",
"이비인후과","한국에서 고령화로 난청 환자가 증가하고 있습니다. 보청기에 대한 편견을 줄이고 조기 재활의 중요성을 설명합니다.",
[{"mistake":"난청을 완전히 교정 가능하다고 설명","correction":"보청기는 소리를 키우는 것, 정상 청력 회복은 아님","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"보청기 적응 기간 미안내","correction":"적응에 수주-수개월 소요될 수 있음 안내","explanation":"조기 포기를 방지합니다"},
{"mistake":"대화 시 주의사항 미설명","correction":"정면에서 천천히 말하기, 입모양 보이게 하기 안내","explanation":"효과적인 의사소통을 돕습니다"}],
[{"ko":"난청으로 보청기가 필요합니다.","vi":"Suy giảm thính lực cần đeo máy trợ thính.","situation":"formal"},
{"ko":"보청기 적응에 시간이 좀 걸립니다.","vi":"Cần thời gian để làm quen với máy trợ thính.","situation":"formal"},
{"ko":"보청기 끼면 많이 들려요.","vi":"Đeo máy trợ thính sẽ nghe rõ hơn nhiều.","situation":"informal"}],
["청력검사","보청기","인공와우"]),

t("benh-alzheimer","알츠하이머병","bệnh Alzheimer","뇌세포가 점진적으로 손상되어 기억력과 인지기능이 저하되는 질환입니다. 치매의 가장 흔한 원인입니다. 약물로 진행을 늦출 수 있습니다. 통역 시 질환의 진행성, 가족 부담, 돌봄 자원을 설명해야 합니다.",
"Bệnh thoái hóa não gây suy giảm trí nhớ và nhận thức, nguyên nhân phổ biến nhất của sa sút trí tuệ",
"신경과","한국에서 알츠하이머 환자는 고령화로 급증하고 있습니다. 환자와 가족 모두를 위한 지원이 필요합니다.",
[{"mistake":"알츠하이머를 정상 노화로 설명","correction":"정상 노화와 다른 질병임을 구분하여 설명","explanation":"조기 진단이 중요합니다"},
{"mistake":"완치 가능하다고 설명","correction":"진행을 늦추는 것이 현재 치료 목표","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"가족 돌봄 부담 미설명","correction":"장기요양보험, 돌봄 서비스 정보 제공","explanation":"가족 지지가 중요합니다"}],
[{"ko":"알츠하이머병 초기로 약물 치료를 시작합니다.","vi":"Alzheimer giai đoạn đầu, bắt đầu điều trị bằng thuốc.","situation":"formal"},
{"ko":"약으로 진행을 늦출 수 있습니다.","vi":"Thuốc có thể làm chậm tiến triển bệnh.","situation":"formal"},
{"ko":"보호자 분도 많이 힘드실 텐데 도움받을 수 있어요.","vi":"Người chăm sóc cũng vất vả, có thể nhận hỗ trợ.","situation":"informal"}],
["치매","인지기능","장기요양"]),

t("tram-cam-2","우울증","trầm cảm","지속적인 우울한 기분과 흥미 상실이 특징인 정신질환입니다. 수면장애, 식욕 변화, 피로감이 동반됩니다. 약물과 상담으로 치료합니다. 통역 시 정신과 치료에 대한 편견 해소, 자살 위험 평가, 가족 지지를 설명해야 합니다.",
"Bệnh tâm thần với khí sắc trầm và mất hứng thú kéo dài",
"정신건강의학과","한국에서 우울증에 대한 인식이 개선되고 있습니다. 베트남 환자에게 정신과 치료의 필요성과 효과를 설명합니다.",
[{"mistake":"우울증을 의지 부족으로 설명","correction":"뇌의 화학적 불균형에 의한 질병임을 설명","explanation":"편견을 줄이고 치료를 권합니다"},
{"mistake":"자살 위험 평가 생략","correction":"자해 생각 여부를 직접 물어보기","explanation":"위험 환자를 발견합니다"},
{"mistake":"약물 치료 효과 즉시 나타난다고 설명","correction":"2-4주 후 효과 나타남, 조기 중단 방지","explanation":"치료 지속을 격려합니다"}],
[{"ko":"우울증 진단으로 약물과 상담 치료를 권합니다.","vi":"Chẩn đoán trầm cảm, khuyên dùng thuốc và tư vấn.","situation":"formal"},
{"ko":"스스로 해치고 싶은 생각이 드시나요?","vi":"Bạn có ý nghĩ tự làm hại bản thân không?","situation":"formal"},
{"ko":"우울증은 약 먹으면 많이 좋아져요.","vi":"Trầm cảm uống thuốc sẽ đỡ nhiều.","situation":"informal"}],
["항우울제","심리상담","자살예방"]),

t("roi-loan-lo-au","불안장애","rối loạn lo âu","과도하고 지속적인 불안과 걱정이 특징인 정신질환입니다. 공황장애, 범불안장애, 사회불안장애 등이 있습니다. 약물과 인지행동치료로 치료합니다. 통역 시 증상의 다양성, 치료 효과, 생활 관리를 설명해야 합니다.",
"Bệnh tâm thần với lo âu và lo lắng quá mức kéo dài",
"정신건강의학과","한국에서 불안장애는 흔한 정신질환입니다. 치료 효과가 좋으므로 적극적인 치료를 권합니다.",
[{"mistake":"불안장애를 성격 문제로 치부","correction":"치료 가능한 질병임을 설명","explanation":"치료의 필요성을 이해시킵니다"},
{"mistake":"공황발작을 심장마비로 오해","correction":"공황발작은 생명에 지장 없음을 안내","explanation":"불안을 줄여줍니다"},
{"mistake":"약물 의존성만 강조","correction":"적절히 사용하면 안전하고 효과적","explanation":"치료 순응도를 높입니다"}],
[{"ko":"불안장애로 약물 치료가 도움이 됩니다.","vi":"Rối loạn lo âu có thể điều trị bằng thuốc.","situation":"formal"},
{"ko":"갑자기 심장이 빨리 뛰고 숨이 안 쉬어지면 공황발작입니다.","vi":"Nếu đột nhiên tim đập nhanh và khó thở thì là cơn hoảng loạn.","situation":"formal"},
{"ko":"불안장애는 치료 잘 돼요, 걱정 마세요.","vi":"Rối loạn lo âu điều trị tốt, đừng lo.","situation":"informal"}],
["공황장애","인지행동치료","항불안제"]),

t("mat-ngu-man","불면증","mất ngủ mạn","지속적으로 잠들기 어렵거나 잠을 유지하기 어려운 상태입니다. 피로, 집중력 저하, 기분 변화가 동반됩니다. 수면위생, 인지행동치료, 약물로 치료합니다. 통역 시 수면위생, 약물 의존성, 근본 원인을 설명해야 합니다.",
"Tình trạng khó ngủ hoặc khó duy trì giấc ngủ kéo dài",
"정신건강의학과, 신경과","한국에서 불면증은 흔한 수면장애입니다. 수면제 의존보다 수면위생 개선이 우선입니다.",
[{"mistake":"수면제를 장기 해결책으로 제시","correction":"수면위생, 인지행동치료가 근본 치료","explanation":"약물 의존을 방지합니다"},
{"mistake":"수면위생 교육 부족","correction":"규칙적 수면시간, 카페인 제한 등 구체적 안내","explanation":"생활습관 개선이 중요합니다"},
{"mistake":"근본 원인 탐색 부족","correction":"우울증, 수면무호흡 등 원인 확인 필요","explanation":"원인 치료가 효과적입니다"}],
[{"ko":"불면증에 수면위생 개선이 중요합니다.","vi":"Với mất ngủ, cải thiện vệ sinh giấc ngủ quan trọng.","situation":"formal"},
{"ko":"매일 같은 시간에 자고 일어나세요.","vi":"Mỗi ngày ngủ dậy cùng giờ.","situation":"formal"},
{"ko":"수면제는 계속 먹는 거 아니에요.","vi":"Thuốc ngủ không nên dùng lâu dài.","situation":"informal"}],
["수면위생","인지행동치료","수면제"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
