#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,"pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

# 치료/시술 용어
new = [
t("noi-soi-cat-polyp","용종절제술","cắt polyp qua nội soi",
"내시경을 통해 대장이나 위의 용종을 제거하는 시술입니다. 대장내시경 중 발견되면 즉시 제거하여 암 예방이 가능합니다. 시술 후 출혈 위험이 있어 활동 제한과 식이 조절이 필요합니다. 통역 시 용종 크기에 따른 조직검사 결과 확인, 추적 내시경 일정을 안내해야 합니다.",
"Thủ thuật cắt polyp qua nội soi để ngăn ngừa ung thư",
"소화기내과","한국에서 용종절제술은 대장암 예방의 핵심입니다. 시술 후 2주간 격한 운동, 음주를 피해야 함을 환자에게 강조합니다.",
[{"mistake":"용종을 모두 암으로 설명","correction":"대부분 양성이지만 일부가 암으로 진행 가능","explanation":"불필요한 공포를 주지 않습니다"},
{"mistake":"시술 후 주의사항 생략","correction":"2주간 운동/음주 제한, 검은 변 시 내원 안내","explanation":"출혈 합병증을 예방합니다"},
{"mistake":"추적검사 일정 미안내","correction":"용종 크기/개수에 따라 1-3년 후 재검사 안내","explanation":"재발 감시가 필요합니다"}],
[{"ko":"용종이 발견되어 제거했습니다.","vi":"Phát hiện polyp và đã cắt bỏ.","situation":"formal"},
{"ko":"2주간 술 드시면 안 됩니다.","vi":"Trong 2 tuần không được uống rượu.","situation":"formal"},
{"ko":"용종 떼면 암 예방돼요.","vi":"Cắt polyp thì phòng được ung thư.","situation":"informal"}],
["대장내시경","조직검사","대장암"]),

t("dat-stent","스텐트시술","đặt stent",
"좁아지거나 막힌 혈관에 금속 그물망(스텐트)을 삽입하여 혈류를 회복시키는 시술입니다. 관상동맥, 경동맥, 말초혈관 등에 시행합니다. 시술 후 항혈소판제 복용이 필수입니다. 통역 시 약물 복용 기간, 출혈 주의사항, 정기 검진 일정을 안내해야 합니다.",
"Thủ thuật đặt khung kim loại (stent) vào mạch máu bị hẹp hoặc tắc",
"심장내과, 영상의학과","한국에서 스텐트시술은 심근경색, 협심증 치료의 표준입니다. 약물방출스텐트 사용 시 1년 이상 항혈소판제 복용이 필요함을 강조합니다.",
[{"mistake":"스텐트 삽입을 완치로 설명","correction":"생활습관 개선과 약물 복용 계속 필요","explanation":"재협착 예방이 중요합니다"},
{"mistake":"항혈소판제 복용 중요성 미강조","correction":"임의 중단 시 스텐트 혈전 위험 설명","explanation":"생명을 위협하는 합병증입니다"},
{"mistake":"시술 후 활동 제한 미설명","correction":"1주간 무거운 것 들기, 격한 운동 제한","explanation":"삽입 부위 출혈을 예방합니다"}],
[{"ko":"심장 혈관에 스텐트를 넣겠습니다.","vi":"Sẽ đặt stent vào mạch máu tim.","situation":"formal"},
{"ko":"피 묽게 하는 약을 1년 이상 드셔야 합니다.","vi":"Phải uống thuốc làm loãng máu ít nhất 1 năm.","situation":"formal"},
{"ko":"스텐트 넣어도 담배는 끊어야 해요.","vi":"Dù đặt stent cũng phải bỏ thuốc lá.","situation":"informal"}],
["관상동맥조영술","협심증","항혈소판제"]),

t("phau-thuat-tim-ho","심장수술","phẫu thuật tim hở",
"가슴을 열고 심장을 직접 수술하는 개심술입니다. 관상동맥우회술, 판막수술, 선천성심장병 교정 등이 있습니다. 인공심폐기를 사용하고 회복에 수개월이 걸립니다. 통역 시 수술 과정, 중환자실 입실, 재활 과정을 상세히 설명해야 합니다.",
"Phẫu thuật mở ngực để điều trị trực tiếp trên tim",
"흉부외과","한국에서 심장수술은 대형 병원에서 시행됩니다. 수술 후 심장재활이 회복에 중요하며, 가족의 지지가 필수적입니다.",
[{"mistake":"개심술을 간단한 수술로 설명","correction":"대수술임을 인지시키고 회복 기간 안내","explanation":"환자와 가족의 준비가 필요합니다"},
{"mistake":"수술 후 흉터, 통증 미설명","correction":"정중 흉골절개 흉터, 수개월 통증 가능성 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"심장재활 중요성 미강조","correction":"운동재활이 회복과 예후에 중요함을 설명","explanation":"재활 참여를 독려합니다"}],
[{"ko":"관상동맥우회술이 필요합니다.","vi":"Cần phẫu thuật bắc cầu mạch vành.","situation":"formal"},
{"ko":"수술 후 중환자실에서 2-3일 계십니다.","vi":"Sau mổ sẽ ở ICU 2-3 ngày.","situation":"formal"},
{"ko":"심장수술 후 운동재활 열심히 하셔야 해요.","vi":"Sau mổ tim phải tập phục hồi chức năng chăm chỉ.","situation":"informal"}],
["관상동맥우회술","판막수술","인공심폐기"]),

t("hoa-tri","항암치료","hóa trị",
"암세포를 죽이거나 성장을 억제하는 약물 치료입니다. 정맥주사나 경구 복용으로 투여합니다. 오심, 탈모, 면역저하 등 부작용이 있습니다. 통역 시 치료 일정(사이클), 부작용 관리, 감염 예방 수칙을 자세히 설명해야 합니다.",
"Điều trị bằng thuốc để tiêu diệt hoặc ức chế tế bào ung thư",
"종양내과","한국에서 항암치료는 암 치료의 핵심입니다. 부작용이 힘들지만 완치 또는 생존율 향상에 중요함을 환자에게 격려합니다.",
[{"mistake":"모든 항암제가 탈모를 유발한다고 설명","correction":"약물에 따라 부작용이 다름을 안내","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"면역저하 시 주의사항 미설명","correction":"감염 예방, 날음식 피하기, 사람 많은 곳 피하기 안내","explanation":"감염이 치명적일 수 있습니다"},
{"mistake":"치료 사이클 설명 부족","correction":"몇 주마다, 몇 회 치료하는지 구체적으로 안내","explanation":"환자가 일정을 계획할 수 있습니다"}],
[{"ko":"3주마다 6회 항암치료를 받습니다.","vi":"Hóa trị 6 lần, cách nhau 3 tuần.","situation":"formal"},
{"ko":"백혈구가 떨어지면 감염에 주의하세요.","vi":"Nếu bạch cầu giảm thì cẩn thận nhiễm trùng.","situation":"formal"},
{"ko":"항암 중에는 회 같은 날것 드시면 안 돼요.","vi":"Trong khi hóa trị không được ăn đồ sống.","situation":"informal"}],
["부작용","백혈구","구토"]),

t("xa-tri","방사선치료","xạ trị",
"고에너지 방사선으로 암세포를 파괴하는 치료입니다. 매일 짧은 시간(10-15분) 동안 수 주간 치료합니다. 피부 반응, 피로 등 부작용이 있습니다. 통역 시 치료 일정, 피부 관리, 치료 중 느낄 수 없다는 점을 설명해야 합니다.",
"Điều trị bằng tia xạ năng lượng cao để tiêu diệt tế bào ung thư",
"방사선종양학과","한국에서 방사선치료는 암 치료에 널리 사용됩니다. 치료 자체는 아프지 않으며 부작용은 치료 부위에 따라 다름을 설명합니다.",
[{"mistake":"방사선치료가 아프다고 설명","correction":"치료 자체는 느껴지지 않음, 부작용은 나중에 발생","explanation":"환자의 불안을 줄입니다"},
{"mistake":"피부 관리 미설명","correction":"치료 부위 보습, 자극 피하기 안내","explanation":"피부 반응을 최소화합니다"},
{"mistake":"치료 기간 설명 부족","correction":"보통 5-7주간 매일(주 5회) 치료함을 안내","explanation":"환자가 일정을 계획합니다"}],
[{"ko":"6주간 매일 방사선치료를 받습니다.","vi":"Xạ trị hàng ngày trong 6 tuần.","situation":"formal"},
{"ko":"치료 부위 피부에 로션을 발라주세요.","vi":"Thoa kem dưỡng ở vùng xạ trị.","situation":"formal"},
{"ko":"방사선 쏠 때는 안 아파요, 걱정 마세요.","vi":"Khi chiếu xạ không đau đâu, đừng lo.","situation":"informal"}],
["피부반응","피로","항암치료"]),

t("dieu-tri-nham-trung-dich","표적치료","điều trị nhắm trúng đích",
"암세포의 특정 분자를 표적으로 공격하는 치료입니다. 유전자 검사로 표적 유무를 확인 후 투여합니다. 기존 항암제보다 부작용이 적은 경우가 많습니다. 통역 시 유전자 검사의 필요성, 표적치료제의 장단점을 설명해야 합니다.",
"Điều trị tấn công vào phân tử cụ thể của tế bào ung thư",
"종양내과","한국에서 표적치료는 폐암, 유방암 등에 널리 사용됩니다. 모든 환자에게 효과적인 것은 아니며 유전자 검사가 선행되어야 함을 설명합니다.",
[{"mistake":"표적치료가 모든 암에 효과적이라고 설명","correction":"특정 유전자 변이가 있어야 효과적","explanation":"유전자 검사의 중요성을 강조합니다"},
{"mistake":"부작용이 전혀 없다고 설명","correction":"피부 발진, 설사 등 특유의 부작용 있음","explanation":"다른 종류의 부작용이 있습니다"},
{"mistake":"경구제 복용법 미설명","correction":"식전/식후, 복용 시간 등 구체적 안내","explanation":"약효에 영향을 미칩니다"}],
[{"ko":"유전자 검사 결과 표적치료가 가능합니다.","vi":"Kết quả xét nghiệm gene cho thấy có thể dùng thuốc nhắm trúng đích.","situation":"formal"},
{"ko":"이 약은 매일 같은 시간에 드세요.","vi":"Thuốc này uống cùng giờ mỗi ngày.","situation":"formal"},
{"ko":"표적치료제는 항암보다 부작용이 좀 덜해요.","vi":"Thuốc nhắm trúng đích ít tác dụng phụ hơn hóa trị.","situation":"informal"}],
["유전자검사","EGFR","폐암"]),

t("mien-dich-tri-lieu","면역치료","miễn dịch trị liệu",
"면역세포가 암세포를 공격하도록 돕는 치료입니다. 면역관문억제제(PD-1, PD-L1 억제제)가 대표적입니다. 다양한 암에서 효과를 보이고 있습니다. 통역 시 기존 항암치료와의 차이, 면역 관련 부작용 가능성을 설명해야 합니다.",
"Điều trị giúp hệ miễn dịch tấn công tế bào ung thư",
"종양내과","한국에서 면역치료는 암 치료의 새로운 표준이 되고 있습니다. 부작용 양상이 항암치료와 다르므로 주의 깊은 모니터링이 필요합니다.",
[{"mistake":"면역치료가 부작용이 없다고 설명","correction":"면역 관련 부작용(갑상선, 폐, 간 등) 가능성 안내","explanation":"다른 종류의 부작용이 있습니다"},
{"mistake":"모든 환자에게 효과적이라고 설명","correction":"반응률이 20-40% 정도임을 설명","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"치료 기간 설명 부족","correction":"2-3주마다 투여, 2년 이상 지속될 수 있음","explanation":"장기 치료 계획을 안내합니다"}],
[{"ko":"면역치료로 암을 공격하겠습니다.","vi":"Sẽ dùng miễn dịch trị liệu để tấn công ung thư.","situation":"formal"},
{"ko":"피부 발진이나 설사가 생기면 말씀하세요.","vi":"Nếu nổi mẩn hoặc tiêu chảy thì báo bác sĩ.","situation":"formal"},
{"ko":"면역치료는 우리 몸이 암을 이기게 도와주는 거예요.","vi":"Miễn dịch trị liệu giúp cơ thể chiến thắng ung thư.","situation":"informal"}],
["PD-1억제제","면역관문억제제","부작용"]),

t("gay-me-toan-than","전신마취","gây mê toàn thân",
"약물로 의식을 잃게 하고 통증을 차단하여 수술하는 방법입니다. 마취과 의사가 수술 내내 환자 상태를 관리합니다. 통역 시 마취 전 금식, 마취 후 회복 과정, 오심/구토 가능성을 설명해야 합니다.",
"Phương pháp gây mê làm mất ý thức và chặn đau để phẫu thuật",
"마취통증의학과","한국에서 전신마취는 대부분의 대수술에 사용됩니다. 마취 전 금식 위반 시 수술이 취소될 수 있음을 강조합니다.",
[{"mistake":"전신마취를 위험하다고만 설명","correction":"현대 마취는 안전하며 마취과 의사가 모니터링","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"금식 시간 부정확하게 안내","correction":"수술 8시간 전 음식, 2시간 전 맑은 물도 금지","explanation":"흡인성 폐렴 예방에 중요합니다"},
{"mistake":"마취 후 증상 미설명","correction":"목 아픔, 오심, 졸림 등 일시적 증상 안내","explanation":"정상 반응임을 알려줍니다"}],
[{"ko":"내일 아침 8시 수술이라 오늘 밤부터 금식입니다.","vi":"Mổ lúc 8 giờ sáng mai nên từ tối nay phải nhịn ăn.","situation":"formal"},
{"ko":"마취에서 깨면 목이 좀 아플 수 있어요.","vi":"Khi tỉnh dậy sau mê có thể hơi đau họng.","situation":"formal"},
{"ko":"마취 중에는 아무것도 안 느껴요, 걱정 마세요.","vi":"Trong khi mê không cảm thấy gì cả, đừng lo.","situation":"informal"}],
["금식","기관삽관","회복실"]),

t("gay-te-tuy-song","척추마취","gây tê tủy sống",
"허리에 주사하여 하반신의 감각과 운동을 차단하는 마취 방법입니다. 하복부, 하지 수술에 사용됩니다. 의식이 있는 상태로 수술합니다. 통역 시 마취 자세, 주사 시 느낌, 마취 후 두통 가능성을 설명해야 합니다.",
"Phương pháp gây tê bằng cách tiêm vào cột sống để chặn cảm giác và vận động nửa dưới cơ thể",
"마취통증의학과","한국에서 척추마취는 제왕절개, 하지 수술에 흔히 사용됩니다. 마취 후 두통이 발생할 수 있어 24시간 누워있기를 권합니다.",
[{"mistake":"척추마취를 전신마취와 혼동","correction":"의식은 있고 하반신만 마취됨을 설명","explanation":"수술 중 의식이 있어 불안할 수 있습니다"},
{"mistake":"마취 후 두통 미설명","correction":"두통 발생 시 누워있고 수분 섭취하라고 안내","explanation":"척추마취 후 두통은 흔합니다"},
{"mistake":"다리 움직임 회복 시간 미안내","correction":"수 시간 후 점차 감각과 운동 회복됨을 설명","explanation":"환자가 불안해하지 않도록 합니다"}],
[{"ko":"허리에 주사해서 하반신을 마취합니다.","vi":"Tiêm vào lưng để gây tê nửa dưới cơ thể.","situation":"formal"},
{"ko":"수술 중 의식은 있지만 아프지 않습니다.","vi":"Trong khi mổ vẫn tỉnh nhưng không đau.","situation":"formal"},
{"ko":"마취 후에 두통 오면 누워 계세요.","vi":"Nếu đau đầu sau khi tê thì nằm nghỉ.","situation":"informal"}],
["제왕절개","경막외마취","두통"]),

t("sinh-mo","제왕절개","sinh mổ",
"복부와 자궁을 절개하여 아기를 출산하는 수술입니다. 응급 상황이나 자연분만이 어려운 경우 시행합니다. 회복이 자연분만보다 오래 걸립니다. 통역 시 수술 과정, 마취 방법, 수술 후 통증 관리, 모유수유 가능성을 설명해야 합니다.",
"Phẫu thuật mổ bụng và tử cung để sinh em bé",
"산부인과","한국에서 제왕절개율은 약 45%로 높습니다. 베트남 산모에게 수술 후 조기 보행, 흉터 관리, 다음 임신 시 주의사항을 교육합니다.",
[{"mistake":"제왕절개를 쉬운 출산으로 설명","correction":"대수술이며 회복에 6주 이상 필요","explanation":"산모가 무리하지 않도록 합니다"},
{"mistake":"모유수유 불가능하다고 설명","correction":"수술 후에도 모유수유 가능함을 안내","explanation":"산모의 선택을 존중합니다"},
{"mistake":"다음 임신 주의사항 미설명","correction":"자궁파열 위험으로 다음 임신 시 상담 필요","explanation":"추후 임신 계획에 중요합니다"}],
[{"ko":"응급 제왕절개가 필요합니다.","vi":"Cần mổ sinh cấp cứu.","situation":"formal"},
{"ko":"수술 다음 날부터 걸어 다니셔야 회복이 빨라요.","vi":"Từ ngày sau mổ phải đi lại thì hồi phục nhanh hơn.","situation":"formal"},
{"ko":"제왕절개해도 젖 잘 나와요.","vi":"Mổ đẻ vẫn có sữa bình thường.","situation":"informal"}],
["자연분만","척추마취","산후조리"]),

t("cat-tui-mat","담낭절제술","cắt túi mật",
"담석이나 담낭염으로 담낭을 제거하는 수술입니다. 대부분 복강경으로 시행하여 회복이 빠릅니다. 담낭 없이도 소화에 큰 문제가 없습니다. 통역 시 수술 방법(복강경/개복), 수술 후 식이, 담낭 없이 사는 것에 대해 설명해야 합니다.",
"Phẫu thuật cắt bỏ túi mật do sỏi hoặc viêm túi mật",
"외과","한국에서 담낭절제술은 가장 흔한 복강경 수술 중 하나입니다. 수술 후 기름진 음식에 설사할 수 있으나 점차 적응됨을 설명합니다.",
[{"mistake":"담낭제거 후 소화불량 영구적이라고 설명","correction":"처음에는 기름진 음식 소화 어려우나 점차 적응","explanation":"불필요한 걱정을 줄입니다"},
{"mistake":"복강경과 개복수술 차이 미설명","correction":"복강경은 작은 구멍, 회복 빠름 안내","explanation":"환자가 수술 방법을 이해합니다"},
{"mistake":"담석 원인 설명 부족","correction":"비만, 고지방 식이, 여성 호르몬 등 위험요인 안내","explanation":"재발 방지 교육에 필요합니다"}],
[{"ko":"복강경으로 담낭을 제거하겠습니다.","vi":"Sẽ cắt túi mật bằng nội soi.","situation":"formal"},
{"ko":"담낭 없어도 일상생활에 문제없습니다.","vi":"Không có túi mật vẫn sống bình thường.","situation":"formal"},
{"ko":"처음에 기름진 거 먹으면 설사할 수 있어요.","vi":"Ban đầu ăn đồ dầu mỡ có thể bị tiêu chảy.","situation":"informal"}],
["담석","복강경수술","담낭염"]),

t("cat-ruot-thua","맹장수술","cắt ruột thừa",
"충수(맹장 끝 돌기)를 제거하는 수술입니다. 급성충수염 시 응급으로 시행합니다. 복강경 또는 개복으로 수술합니다. 통역 시 응급 수술의 필요성, 수술 후 회복 과정, 합병증 가능성을 설명해야 합니다.",
"Phẫu thuật cắt ruột thừa (viêm ruột thừa cấp)",
"외과","한국에서 맹장수술은 흔한 응급수술입니다. '맹장'이 일반적으로 쓰이지만 의학적으로 '충수절제술'이 정확합니다.",
[{"mistake":"맹장과 충수 혼동","correction":"제거하는 것은 충수(ruột thừa)임을 명확히","explanation":"의학적으로 정확한 설명이 필요합니다"},
{"mistake":"수술 지연의 위험성 미설명","correction":"충수 파열 시 복막염 위험 안내","explanation":"응급 수술의 필요성을 이해시킵니다"},
{"mistake":"수술 후 회복 과정 미안내","correction":"2-3일 입원, 1-2주 후 일상 복귀 안내","explanation":"환자가 계획을 세울 수 있습니다"}],
[{"ko":"충수염으로 응급수술이 필요합니다.","vi":"Viêm ruột thừa cần mổ cấp cứu.","situation":"formal"},
{"ko":"복강경으로 하면 흉터가 작습니다.","vi":"Mổ nội soi thì sẹo nhỏ.","situation":"formal"},
{"ko":"터지기 전에 빨리 수술해야 해요.","vi":"Phải mổ nhanh trước khi vỡ.","situation":"informal"}],
["충수염","복막염","복강경수술"]),

t("noi-soi-khop-goi","관절경수술","nội soi khớp gối",
"작은 카메라와 기구를 관절 내에 넣어 시행하는 최소침습 수술입니다. 반월판 손상, 인대 손상 등을 치료합니다. 개방수술보다 회복이 빠릅니다. 통역 시 수술 후 재활의 중요성, 체중 부하 시기, 스포츠 복귀 시점을 안내해야 합니다.",
"Phẫu thuật xâm lấn tối thiểu bằng cách đưa camera và dụng cụ vào khớp",
"정형외과","한국에서 관절경수술은 무릎, 어깨 등에 널리 시행됩니다. 수술 자체보다 재활이 결과를 좌우함을 강조합니다.",
[{"mistake":"관절경수술을 간단한 수술로 설명","correction":"수술은 작지만 재활에 수개월 필요","explanation":"재활의 중요성을 강조합니다"},
{"mistake":"즉시 정상활동 가능하다고 설명","correction":"체중 부하, 운동 복귀에 단계적 접근 필요","explanation":"무리하면 재손상됩니다"},
{"mistake":"인대 재건술과 봉합술 구분 안 함","correction":"전방십자인대 재건은 힘줄 이식 필요함을 설명","explanation":"수술 방법에 따라 회복 기간이 다릅니다"}],
[{"ko":"반월판 파열로 관절경수술이 필요합니다.","vi":"Rách sụn chêm cần mổ nội soi khớp.","situation":"formal"},
{"ko":"수술 후 재활이 아주 중요합니다.","vi":"Sau mổ phục hồi chức năng rất quan trọng.","situation":"formal"},
{"ko":"6개월은 뛰지 마세요.","vi":"6 tháng không được chạy nhảy.","situation":"informal"}],
["반월판","전방십자인대","재활치료"]),

t("thay-khop-goi","인공관절치환술","thay khớp gối",
"손상된 관절을 금속과 플라스틱으로 된 인공관절로 교체하는 수술입니다. 무릎, 고관절에 주로 시행됩니다. 말기 관절염에 시행하며 통증이 크게 감소합니다. 통역 시 수술 적응증, 인공관절 수명, 재활 과정을 설명해야 합니다.",
"Phẫu thuật thay thế khớp bị hỏng bằng khớp nhân tạo bằng kim loại và nhựa",
"정형외과","한국에서 인공관절수술은 고령 인구 증가로 늘고 있습니다. 수술 후 적극적인 재활로 보행 기능을 회복할 수 있습니다.",
[{"mistake":"인공관절이 평생 간다고 설명","correction":"15-20년 수명, 재치환 가능성 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"수술 후 바로 걸을 수 있다고 설명","correction":"수술 다음 날부터 보행 시작하나 회복에 수개월","explanation":"재활 과정을 안내합니다"},
{"mistake":"양쪽 동시 수술 가능성 미설명","correction":"환자 상태에 따라 양측 또는 단측 수술 결정","explanation":"수술 계획을 함께 논의합니다"}],
[{"ko":"무릎 인공관절 수술이 필요합니다.","vi":"Cần phẫu thuật thay khớp gối nhân tạo.","situation":"formal"},
{"ko":"수술 다음 날부터 걷는 연습을 합니다.","vi":"Từ ngày sau mổ bắt đầu tập đi.","situation":"formal"},
{"ko":"인공관절 넣으면 무릎 안 아파요.","vi":"Thay khớp nhân tạo thì đầu gối không đau nữa.","situation":"informal"}],
["퇴행성관절염","재활치료","인공관절"]),

t("cat-u-nao","뇌종양수술","cắt u não",
"두개골을 열고 뇌종양을 제거하는 수술입니다. 종양 위치와 크기에 따라 전절제 또는 부분절제를 시행합니다. 통역 시 수술 위험성, 신경학적 후유증 가능성, 보조 치료(방사선, 항암)를 설명해야 합니다.",
"Phẫu thuật mở hộp sọ để cắt bỏ khối u não",
"신경외과","한국에서 뇌종양수술은 신경항법장치, 수술 중 MRI 등 첨단 기술을 활용합니다. 수술 후 신경학적 변화 가능성에 대해 솔직하게 설명해야 합니다.",
[{"mistake":"뇌종양을 모두 악성으로 설명","correction":"양성 뇌종양(수막종 등)도 수술로 완치 가능","explanation":"불필요한 공포를 줄입니다"},
{"mistake":"수술 후 후유증 가능성 미설명","correction":"마비, 언어장애 등 가능성 솔직하게 안내","explanation":"동의서 내용을 정확히 전달합니다"},
{"mistake":"수술 후 추가 치료 미설명","correction":"악성 종양 시 방사선/항암 치료 필요 가능성 안내","explanation":"치료 계획 전체를 설명합니다"}],
[{"ko":"뇌종양 제거 수술을 권합니다.","vi":"Khuyên nên phẫu thuật cắt u não.","situation":"formal"},
{"ko":"수술 후 일시적으로 팔다리가 약해질 수 있습니다.","vi":"Sau mổ có thể tay chân yếu tạm thời.","situation":"formal"},
{"ko":"양성이면 수술만으로 다 낫는 경우 많아요.","vi":"Nếu là u lành thì mổ xong thường khỏi hẳn.","situation":"informal"}],
["수막종","교모세포종","방사선치료"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
