#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms final - 마지막 13개 (500개 도달)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("truyen-mau","수혈","truyền máu",
      "혈액을 정맥으로 주입하는 치료입니다. 통역 시 수혈 동의서, 부작용 관찰의 중요성을 설명합니다.",
      "Điều trị đưa máu vào tĩnh mạch",
      "혈액내과/외과",
      "수혈은 생명을 살릴 수 있지만 동의가 필요합니다. 종교적 이유로 거부하는 경우도 고려합니다.",
      [{"mistake":"수혈 동의 없이 진행","correction":"반드시 동의서 필요","explanation":"환자 권리 존중"},
       {"mistake":"부작용 설명 안 함","correction":"발열, 발진 등 부작용 안내","explanation":"조기 발견이 중요합니다"},
       {"mistake":"종교적 신념 무시","correction":"대안 치료 옵션 설명","explanation":"환자 가치관 존중"}],
      [{"ko":"수혈이 필요합니다. 동의서에 서명해 주세요.","vi":"Cần truyền máu. Vui lòng ký giấy đồng ý.","situation":"formal"},
       {"ko":"수혈 중 이상하면 바로 말씀해 주세요.","vi":"Nếu có gì bất thường khi truyền máu hãy nói ngay.","situation":"onsite"},
       {"ko":"수혈받았어요.","vi":"Đã truyền máu.","situation":"informal"}],
      ["혈액형","수혈동의서","부작용"]),

    t("oxy","산소치료","oxy",
      "산소를 공급하여 호흡을 돕는 치료입니다. 통역 시 산소 공급 방법과 주의사항을 설명합니다.",
      "Điều trị cung cấp oxy hỗ trợ hô hấp",
      "호흡기내과/응급",
      "산소 포화도가 낮을 때 필요합니다. 산소 마스크 사용법을 안내합니다.",
      [{"mistake":"산소는 안전하기만 하다고 설명","correction":"COPD 환자는 주의 필요","explanation":"고농도 산소가 해로울 수 있습니다"},
       {"mistake":"마스크 벗으면 안 된다고만 강조","correction":"편안함도 고려","explanation":"협조를 얻습니다"},
       {"mistake":"산소 불필요하다고 설명","correction":"의사 지시에 따라 사용","explanation":"저산소증은 위험합니다"}],
      [{"ko":"산소 마스크를 쓰고 계세요.","vi":"Đeo mặt nạ oxy.","situation":"formal"},
       {"ko":"숨쉬기 편해졌나요?","vi":"Thở đỡ hơn chưa?","situation":"onsite"},
       {"ko":"산소 쓰고 있어요.","vi":"Đang thở oxy.","situation":"informal"}],
      ["산소포화도","비강캐뉼라","인공호흡기"]),

    t("icu","중환자실","ICU",
      "생명이 위급한 환자를 집중 치료하는 병실입니다. 통역 시 중환자실의 특성과 면회 제한을 설명합니다.",
      "Phòng điều trị tập trung bệnh nhân nguy kịch",
      "중환자의학과",
      "중환자실은 면회가 제한됩니다. 보호자의 불안을 이해하고 정보를 제공합니다.",
      [{"mistake":"상태가 심각하다고만 강조","correction":"치료 내용과 계획 설명","explanation":"정보를 제공합니다"},
       {"mistake":"면회 제한 이유 설명 안 함","correction":"감염 예방과 환자 안정 위해","explanation":"이해를 구합니다"},
       {"mistake":"보호자 감정 무시","correction":"공감하고 지지","explanation":"심리적 지지가 필요합니다"}],
      [{"ko":"중환자실에서 집중 치료가 필요합니다.","vi":"Cần điều trị tích cực ở ICU.","situation":"formal"},
       {"ko":"면회는 정해진 시간에만 가능해요.","vi":"Thăm bệnh chỉ được vào giờ quy định.","situation":"onsite"},
       {"ko":"중환자실에 있어요.","vi":"Đang ở ICU.","situation":"informal"}],
      ["인공호흡기","집중치료","면회"]),

    t("hoi-chuan","회진","hội chẩn",
      "의료진이 병실을 돌며 환자 상태를 확인하는 것입니다. 통역 시 회진 시간과 질문 기회를 안내합니다.",
      "Việc nhân viên y tế đi thăm khám bệnh nhân trong phòng bệnh",
      "입원병동",
      "회진 시 궁금한 점을 질문할 수 있도록 준비를 돕습니다.",
      [{"mistake":"회진 시간 안내 안 함","correction":"대략적인 시간 알려줌","explanation":"환자가 준비할 수 있습니다"},
       {"mistake":"질문 기회 안내 안 함","correction":"궁금한 점 미리 정리하도록 권유","explanation":"효율적인 소통을 돕습니다"},
       {"mistake":"통역 동석 안내 안 함","correction":"필요시 통역 요청 가능","explanation":"이해를 돕습니다"}],
      [{"ko":"아침에 교수님이 회진 오세요.","vi":"Buổi sáng giáo sư sẽ đi thăm bệnh.","situation":"formal"},
       {"ko":"궁금한 점 있으면 회진 때 물어보세요.","vi":"Nếu có thắc mắc hãy hỏi khi thăm bệnh.","situation":"onsite"},
       {"ko":"회진 왔다 갔어요.","vi":"Đã đi thăm bệnh rồi.","situation":"informal"}],
      ["주치의","질문","치료계획"]),

    t("tiem-phong","예방주사","tiêm phòng",
      "질병 예방을 위해 맞는 주사(백신)입니다. 통역 시 접종 종류와 부작용을 설명합니다.",
      "Tiêm vắc xin để phòng bệnh",
      "예방의학과/소아과",
      "예방접종의 중요성과 일정을 안내합니다. 부작용에 대한 올바른 정보를 제공합니다.",
      [{"mistake":"백신이 위험하다고 설명","correction":"이점이 위험보다 큼","explanation":"근거 기반 정보 제공"},
       {"mistake":"부작용을 숨김","correction":"경미한 부작용은 정상 반응","explanation":"투명하게 설명합니다"},
       {"mistake":"강제라고 설명","correction":"권장사항이며 선택 가능","explanation":"자율성을 존중합니다"}],
      [{"ko":"독감 예방주사를 맞으시겠어요?","vi":"Bạn có muốn tiêm phòng cúm không?","situation":"formal"},
       {"ko":"접종 후 30분 관찰이 필요해요.","vi":"Sau tiêm cần theo dõi 30 phút.","situation":"onsite"},
       {"ko":"예방주사 맞았어요.","vi":"Đã tiêm phòng.","situation":"informal"}],
      ["백신","접종일정","부작용"]),

    t("kha-nang-sinh-san","가임기","khả năng sinh sản",
      "임신이 가능한 연령대입니다. 통역 시 가임기 여성 특유의 의료 고려사항을 전달합니다.",
      "Độ tuổi có thể mang thai",
      "산부인과",
      "가임기 여성에게는 임신 가능성을 고려한 약물 처방과 검사가 필요합니다.",
      [{"mistake":"임신 가능성 확인 안 함","correction":"마지막 생리일 확인","explanation":"약물 안전성을 위해 필수"},
       {"mistake":"민감한 질문을 피함","correction":"의료상 필요한 질문임을 설명","explanation":"환자 안전이 우선"},
       {"mistake":"개인정보 보호 미흡","correction":"비밀 보장 확인시킴","explanation":"신뢰를 유지합니다"}],
      [{"ko":"마지막 생리일이 언제셨나요?","vi":"Kỳ kinh cuối cùng là khi nào?","situation":"formal"},
       {"ko":"임신 가능성이 있나요?","vi":"Có khả năng mang thai không?","situation":"onsite"},
       {"ko":"생리 규칙적이에요.","vi":"Kinh nguyệt đều đặn.","situation":"informal"}],
      ["임신","피임","생리"]),

    t("dieu-tri-noi-tru","입원치료","điều trị nội trú",
      "병원에 머물며 받는 치료입니다. 통역 시 입원 필요성, 기간, 비용을 설명합니다.",
      "Điều trị khi ở lại bệnh viện",
      "해당 진료과",
      "입원이 필요한 이유를 명확히 하고, 입원 절차를 안내합니다.",
      [{"mistake":"입원 필요성 설명 안 함","correction":"왜 입원이 필요한지 설명","explanation":"환자 이해와 협조를 얻습니다"},
       {"mistake":"예상 기간 안내 안 함","correction":"대략적 기간 알려줌","explanation":"계획을 세울 수 있습니다"},
       {"mistake":"비용 안내 안 함","correction":"보험 적용과 비용 안내","explanation":"경제적 준비를 돕습니다"}],
      [{"ko":"검사와 치료를 위해 입원하셔야 합니다.","vi":"Cần nhập viện để xét nghiệm và điều trị.","situation":"formal"},
       {"ko":"약 3-5일 정도 입원 예상됩니다.","vi":"Dự kiến nhập viện khoảng 3-5 ngày.","situation":"onsite"},
       {"ko":"입원해야 해요.","vi":"Phải nhập viện.","situation":"informal"}],
      ["병실","입원비","보험"]),

    t("dieu-tri-ngoai-tru","외래치료","điều trị ngoại trú",
      "입원 없이 통원하며 받는 치료입니다. 통역 시 외래 방문 일정과 약 복용을 안내합니다.",
      "Điều trị không cần nhập viện, đến khám định kỳ",
      "해당 진료과",
      "외래 치료의 장점(일상생활 유지)과 필요한 협조사항을 설명합니다.",
      [{"mistake":"외래만으로 충분하다고 안심시킴","correction":"증상 악화 시 재방문 필요","explanation":"위험 신호를 교육합니다"},
       {"mistake":"다음 예약 안내 안 함","correction":"다음 방문일 확인","explanation":"치료 연속성이 중요합니다"},
       {"mistake":"약 복용 지시 불명확","correction":"복용법 상세히 설명","explanation":"치료 효과를 위해 필수"}],
      [{"ko":"입원 없이 외래에서 치료할 수 있습니다.","vi":"Có thể điều trị ngoại trú không cần nhập viện.","situation":"formal"},
       {"ko":"약 다 드시고 2주 후에 다시 오세요.","vi":"Uống hết thuốc rồi 2 tuần sau đến lại.","situation":"onsite"},
       {"ko":"통원 치료해요.","vi":"Điều trị ngoại trú.","situation":"informal"}],
      ["외래예약","처방약","경과관찰"]),

    t("phong-ngua","예방","phòng ngừa",
      "질병이 발생하기 전에 미리 막는 것입니다. 통역 시 예방의 중요성과 구체적 방법을 안내합니다.",
      "Ngăn chặn bệnh trước khi xảy ra",
      "예방의학과",
      "예방이 치료보다 효과적이고 경제적임을 설명합니다.",
      [{"mistake":"예방의 중요성 무시","correction":"예방이 치료보다 낫다","explanation":"근본적 접근"},
       {"mistake":"일반적 조언만 함","correction":"구체적 예방법 제시","explanation":"실천 가능하게 합니다"},
       {"mistake":"겁주기식 설명","correction":"긍정적 동기 부여","explanation":"행동 변화를 유도합니다"}],
      [{"ko":"예방이 치료보다 중요합니다.","vi":"Phòng bệnh hơn chữa bệnh.","situation":"formal"},
       {"ko":"손을 자주 씻으면 감염을 예방할 수 있어요.","vi":"Rửa tay thường xuyên có thể phòng nhiễm trùng.","situation":"onsite"},
       {"ko":"예방이 중요해요.","vi":"Phòng ngừa quan trọng.","situation":"informal"}],
      ["예방접종","건강검진","생활습관"]),

    t("chan-doan-phan-biet","감별진단","chẩn đoán phân biệt",
      "증상이 비슷한 여러 질환 중 원인 질환을 찾아내는 과정입니다. 통역 시 여러 검사가 필요한 이유를 설명합니다.",
      "Quá trình tìm ra bệnh gây ra triệu chứng trong số các bệnh có triệu chứng tương tự",
      "해당 진료과",
      "진단에 시간이 걸릴 수 있음을 이해시키고, 인내심을 요청합니다.",
      [{"mistake":"바로 진단 가능하다고 설명","correction":"검사가 필요할 수 있음","explanation":"정확한 진단이 중요합니다"},
       {"mistake":"환자 불안 가중시킴","correction":"여러 가능성을 열어두고 설명","explanation":"과도한 걱정을 줄입니다"},
       {"mistake":"검사 필요성 설명 안 함","correction":"왜 검사가 필요한지 설명","explanation":"협조를 얻습니다"}],
      [{"ko":"증상이 여러 질환에서 나타날 수 있어 검사가 필요합니다.","vi":"Triệu chứng có thể xuất hiện ở nhiều bệnh nên cần xét nghiệm.","situation":"formal"},
       {"ko":"결과가 나오면 더 정확히 알 수 있어요.","vi":"Khi có kết quả sẽ biết chính xác hơn.","situation":"onsite"},
       {"ko":"여러 검사해봐야 해요.","vi":"Phải làm nhiều xét nghiệm.","situation":"informal"}],
      ["검사","진단","증상"]),

    t("tien-luong","예후","tiên lượng",
      "질병의 경과와 결과를 예측하는 것입니다. 통역 시 예후에 대해 현실적이면서도 희망을 주는 방식으로 전달합니다.",
      "Dự đoán tiến triển và kết quả của bệnh",
      "해당 진료과",
      "예후 설명은 민감한 주제입니다. 환자와 보호자의 감정을 고려합니다.",
      [{"mistake":"비관적으로만 설명","correction":"희망을 유지하면서 현실적으로","explanation":"환자 심리를 고려합니다"},
       {"mistake":"확정적으로 단언","correction":"개인차가 있음을 설명","explanation":"불확실성을 인정합니다"},
       {"mistake":"보호자에게만 설명","correction":"환자 알 권리 존중","explanation":"환자 자율성 존중"}],
      [{"ko":"치료하면 좋아질 가능성이 높습니다.","vi":"Nếu điều trị, khả năng hồi phục cao.","situation":"formal"},
       {"ko":"개인마다 다르지만 희망을 가지세요.","vi":"Mỗi người khác nhau, hãy hy vọng.","situation":"onsite"},
       {"ko":"예후가 좋대요.","vi":"Tiên lượng tốt.","situation":"informal"}],
      ["치료반응","생존율","삶의질"]),

    t("bien-chung","합병증","biến chứng",
      "질병이나 치료로 인해 추가로 발생하는 건강 문제입니다. 통역 시 합병증 가능성과 예방법을 설명합니다.",
      "Vấn đề sức khỏe phát sinh thêm do bệnh hoặc điều trị",
      "해당 진료과",
      "합병증에 대한 정보를 투명하게 제공하되, 과도한 공포를 주지 않습니다.",
      [{"mistake":"합병증 가능성 숨김","correction":"투명하게 설명","explanation":"informed consent 위해 필수"},
       {"mistake":"공포를 조장함","correction":"발생률과 예방법 함께 설명","explanation":"균형 잡힌 정보 제공"},
       {"mistake":"모든 것이 환자 탓이라고 설명","correction":"치료 과정의 일부일 수 있음","explanation":"비난하지 않습니다"}],
      [{"ko":"합병증 예방을 위해 주의사항을 지켜주세요.","vi":"Hãy tuân thủ lưu ý để phòng biến chứng.","situation":"formal"},
       {"ko":"이상 증상이 있으면 바로 연락하세요.","vi":"Nếu có triệu chứng bất thường hãy liên lạc ngay.","situation":"onsite"},
       {"ko":"합병증이 생겼어요.","vi":"Có biến chứng.","situation":"informal"}],
      ["예방","조기발견","치료"]),

    t("di-chung","후유증","di chứng",
      "질병이나 부상 후에 남는 지속적인 증상입니다. 통역 시 후유증 가능성과 재활 치료를 안내합니다.",
      "Triệu chứng kéo dài sau bệnh hoặc chấn thương",
      "재활의학과",
      "후유증이 있더라도 재활로 개선 가능함을 설명합니다.",
      [{"mistake":"후유증이 영구적이라고만 강조","correction":"재활로 개선 가능성 설명","explanation":"희망을 줍니다"},
       {"mistake":"후유증 가능성 언급 안 함","correction":"현실적 기대 설정","explanation":"준비할 수 있게 합니다"},
       {"mistake":"일상생활 불가능하다고 단정","correction":"적응과 보조기구로 생활 가능","explanation":"긍정적 관점 유지"}],
      [{"ko":"재활치료로 후유증을 줄일 수 있습니다.","vi":"Phục hồi chức năng có thể giảm di chứng.","situation":"formal"},
       {"ko":"꾸준히 치료하면 좋아질 거예요.","vi":"Điều trị đều đặn sẽ tốt lên.","situation":"onsite"},
       {"ko":"후유증이 남았어요.","vi":"Còn di chứng.","situation":"informal"}],
      ["재활치료","적응","보조기구"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
