#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch E - 호흡기/심혈관 (20개)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("viem-phoi","폐렴","viêm phổi",
      "폐에 염증이 생겨 발열, 기침, 호흡곤란이 발생하는 감염성 질환입니다. 통역 시 원인균(세균, 바이러스)에 따라 치료가 다르고, 중증도에 따라 입원이 필요할 수 있음을 설명합니다.",
      "Bệnh nhiễm trùng gây viêm phổi với sốt, ho và khó thở",
      "호흡기내과",
      "베트남 근로자들은 좁은 숙소에서 생활하는 경우가 많아 호흡기 감염 전파 위험이 높습니다. 위생 교육이 중요합니다.",
      [{"mistake":"감기와 동일시","correction":"폐렴은 폐 실질의 감염으로 더 심각","explanation":"치료 강도가 다릅니다"},
       {"mistake":"항생제면 다 낫는다고 설명","correction":"바이러스성은 항생제 무효","explanation":"원인에 따른 치료가 필요합니다"},
       {"mistake":"젊으면 괜찮다고 안심시킴","correction":"젊은 사람도 중증 폐렴 가능","explanation":"증상의 심각성을 간과하지 않습니다"}],
      [{"ko":"폐렴으로 입원 치료가 필요합니다.","vi":"Viêm phổi cần nhập viện điều trị.","situation":"formal"},
       {"ko":"기침할 때 입을 가리고 마스크 착용하세요.","vi":"Khi ho hãy che miệng và đeo khẩu trang.","situation":"onsite"},
       {"ko":"폐렴 걸려서 입원했어요.","vi":"Bị viêm phổi nên phải nhập viện.","situation":"informal"}],
      ["항생제","흉부엑스레이","산소치료"]),

    t("hen-suyen","천식","hen suyễn",
      "기도가 좁아지고 염증이 생겨 숨이 차고 쌕쌕거리는 만성 호흡기 질환입니다. 통역 시 유발 요인(알레르기, 운동, 찬공기)을 확인하고, 흡입기 사용법을 정확히 전달합니다.",
      "Bệnh hô hấp mãn tính với đường thở bị hẹp và viêm gây khó thở và thở khò khè",
      "호흡기내과/알레르기내과",
      "한국의 미세먼지가 천식을 악화시킬 수 있습니다. 베트남 환자들에게 한국의 대기오염 상황을 설명하고 대처법을 알려줍니다.",
      [{"mistake":"완치 가능하다고 설명","correction":"관리가 목표, 완치는 어려움","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"증상 있을 때만 약 쓴다고 설명","correction":"예방 흡입기는 매일 사용","explanation":"예방이 치료보다 중요합니다"},
       {"mistake":"흡입기 사용법 확인 안 함","correction":"실제로 사용하는 걸 보고 교정","explanation":"잘못된 사용은 효과가 없습니다"}],
      [{"ko":"천식 조절을 위해 매일 흡입기를 사용해야 합니다.","vi":"Để kiểm soát hen suyễn phải dùng ống hít mỗi ngày.","situation":"formal"},
       {"ko":"숨이 차면 바로 응급 흡입기를 사용하세요.","vi":"Khi khó thở hãy dùng ống hít cấp cứu ngay.","situation":"onsite"},
       {"ko":"천식 있어서 찬바람 피해요.","vi":"Bị hen suyễn nên tránh gió lạnh.","situation":"informal"}],
      ["흡입기","기관지확장제","알레르기"]),

    t("benh-phoi-tac-nghen-man-tinh","만성폐쇄성폐질환","bệnh phổi tắc nghẽn mãn tính",
      "기도가 좁아지고 폐가 손상되어 호흡이 어려워지는 진행성 폐질환입니다. 흡연이 주요 원인이며, 통역 시 금연의 중요성과 폐기능 검사 결과를 명확히 전달합니다.",
      "Bệnh phổi tiến triển với đường thở hẹp và tổn thương phổi gây khó thở",
      "호흡기내과",
      "베트남 남성의 흡연율이 높아 COPD 환자가 많습니다. 금연 상담과 함께 호흡재활의 중요성을 강조합니다.",
      [{"mistake":"COPD라는 약어만 사용","correction":"만성폐쇄성폐질환이라고 풀어 설명","explanation":"환자 이해도를 높입니다"},
       {"mistake":"금연만 강조","correction":"금연 + 약물 + 재활이 복합 치료","explanation":"종합적 관리가 필요합니다"},
       {"mistake":"치료 효과 없다고 낙담시킴","correction":"증상 조절과 진행 억제 가능","explanation":"희망을 유지하게 합니다"}],
      [{"ko":"만성폐쇄성폐질환으로 산소치료가 필요할 수 있습니다.","vi":"Bệnh phổi tắc nghẽn mãn tính có thể cần điều trị oxy.","situation":"formal"},
       {"ko":"숨이 차면 입술 오므리고 천천히 내쉬세요.","vi":"Khi khó thở hãy chúm môi và thở ra từ từ.","situation":"onsite"},
       {"ko":"COPD라서 조금만 걸어도 숨이 차요.","vi":"Bị COPD nên đi bộ chút là thở dốc.","situation":"informal"}],
      ["폐기능검사","기관지확장제","산소치료"]),

    t("lao-phoi","폐결핵","lao phổi",
      "결핵균에 의한 폐 감염으로, 기침, 객혈, 체중 감소, 야간 발한이 특징입니다. 통역 시 전염성과 격리 필요성, 6개월 이상 장기 치료의 중요성을 강조합니다.",
      "Nhiễm trùng phổi do vi khuẩn lao, đặc trưng bởi ho, ho ra máu, giảm cân và đổ mồ hôi đêm",
      "호흡기내과/감염내과",
      "베트남은 결핵 유병률이 높은 국가입니다. 한국에서의 결핵 관리 체계와 치료비 지원에 대해 안내하면 환자의 치료 순응도가 높아집니다.",
      [{"mistake":"에이즈와 연관짓기","correction":"결핵은 누구나 감염 가능","explanation":"낙인을 피합니다"},
       {"mistake":"증상 호전되면 약 중단 가능하다고 설명","correction":"반드시 처방 기간 완료 필수","explanation":"내성균 발생 방지가 중요합니다"},
       {"mistake":"영구 격리라고 설명","correction":"2주 치료 후 전염력 감소","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"결핵 치료는 6개월 이상 꾸준히 약을 드셔야 합니다.","vi":"Điều trị lao phải uống thuốc đều đặn ít nhất 6 tháng.","situation":"formal"},
       {"ko":"마스크를 착용하고 기침 예절을 지켜주세요.","vi":"Đeo khẩu trang và tuân thủ vệ sinh khi ho.","situation":"onsite"},
       {"ko":"결핵이라 격리 입원해야 해요.","vi":"Bị lao nên phải cách ly nhập viện.","situation":"informal"}],
      ["항결핵제","격리","객담검사"]),

    t("tran-khi-mang-phoi","기흉","tràn khí màng phổi",
      "폐와 흉벽 사이에 공기가 차서 폐가 압박되는 상태입니다. 통역 시 갑작스런 흉통과 호흡곤란이 응급 상황임을 강조하고, 흉관 삽입 시술에 대해 설명합니다.",
      "Tình trạng không khí tích tụ giữa phổi và thành ngực gây ép phổi",
      "흉부외과/응급",
      "키가 크고 마른 젊은 남성에서 자연 기흉이 잘 발생합니다. 재발 가능성과 예방법을 안내합니다.",
      [{"mistake":"단순 흉통으로 치부","correction":"기흉은 응급 상황일 수 있음","explanation":"즉각 대응이 필요합니다"},
       {"mistake":"치료 안 해도 된다고 설명","correction":"경증도 경과 관찰 필요","explanation":"악화 가능성이 있습니다"},
       {"mistake":"흉관 삽입을 수술이라고 설명","correction":"간단한 시술임을 설명","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"기흉으로 흉관을 삽입해 공기를 빼야 합니다.","vi":"Tràn khí màng phổi cần đặt ống dẫn lưu để thoát khí.","situation":"formal"},
       {"ko":"갑자기 숨이 차고 가슴이 아프면 바로 오세요.","vi":"Đột ngột khó thở và đau ngực hãy đến ngay.","situation":"onsite"},
       {"ko":"폐에 구멍 나서 공기 빠지게 해야 해요.","vi":"Phổi bị thủng nên phải thoát khí ra.","situation":"informal"}],
      ["흉관삽입","흉부엑스레이","폐쇄술"]),

    t("suy-tim","심부전","suy tim",
      "심장이 혈액을 효과적으로 펌프하지 못해 숨이 차고 부종이 생기는 상태입니다. 통역 시 심장이 약해진 상태라고 설명하고, 염분 제한과 체중 모니터링의 중요성을 강조합니다.",
      "Tình trạng tim không bơm máu hiệu quả gây khó thở và phù",
      "심장내과",
      "심부전 환자는 염분 섭취 제한이 중요한데, 베트남 음식은 느억맘 등 짠 양념이 많아 식이 교육이 필요합니다.",
      [{"mistake":"심장마비와 혼동","correction":"심부전은 만성 상태, 심근경색은 급성 사건","explanation":"질환 개념이 다릅니다"},
       {"mistake":"심장이 멈춘다고 표현","correction":"심장이 약해져 펌프 기능이 떨어진 것","explanation":"정확한 설명이 필요합니다"},
       {"mistake":"약 먹으면 완치라고 설명","correction":"평생 관리가 필요한 만성 질환","explanation":"현실적 기대를 설정합니다"}],
      [{"ko":"심부전으로 이뇨제를 드셔야 부종이 줄어듭니다.","vi":"Suy tim cần uống thuốc lợi tiểu để giảm phù.","situation":"formal"},
       {"ko":"매일 체중을 재고 급격히 늘면 연락하세요.","vi":"Cân nặng mỗi ngày, nếu tăng đột ngột hãy liên lạc.","situation":"onsite"},
       {"ko":"심부전이라 조금만 움직여도 숨이 차요.","vi":"Bị suy tim nên chỉ vận động nhẹ cũng khó thở.","situation":"informal"}],
      ["이뇌제","심박출계수","염분제한"]),

    t("loạn-nhip-tim","부정맥","loạn nhịp tim",
      "심장 박동이 불규칙하거나 너무 빠르거나 느린 상태입니다. 통역 시 종류(빈맥/서맥/심방세동)에 따라 증상과 치료가 다름을 설명합니다.",
      "Tình trạng nhịp tim không đều, quá nhanh hoặc quá chậm",
      "심장내과",
      "심방세동은 뇌졸중 위험을 높여 항응고제가 필요할 수 있습니다. 약물 복용의 중요성과 출혈 주의사항을 안내합니다.",
      [{"mistake":"모든 부정맥이 위험하다고 겁줌","correction":"양성 부정맥도 많음","explanation":"불필요한 불안을 줄입니다"},
       {"mistake":"가슴 두근거림만 증상이라고 설명","correction":"실신, 어지러움, 호흡곤란도 증상","explanation":"다양한 증상을 인지시킵니다"},
       {"mistake":"커피만 끊으라고 조언","correction":"원인과 치료는 다양함","explanation":"개인화된 치료가 필요합니다"}],
      [{"ko":"부정맥 진단을 위해 24시간 심전도 검사가 필요합니다.","vi":"Cần đo điện tâm đồ 24 giờ để chẩn đoán loạn nhịp tim.","situation":"formal"},
       {"ko":"맥박이 불규칙하게 느껴지면 기록해 두세요.","vi":"Nếu cảm thấy mạch không đều hãy ghi lại.","situation":"onsite"},
       {"ko":"부정맥 때문에 가슴이 쿵쾅거려요.","vi":"Loạn nhịp tim nên tim đập thình thịch.","situation":"informal"}],
      ["심전도","심방세동","항응고제"]),

    t("tang-huyet-ap","고혈압","tăng huyết áp",
      "혈압이 지속적으로 높은 상태(140/90mmHg 이상)로, 증상 없이 장기를 손상시켜 '조용한 살인자'라고 불립니다. 통역 시 증상이 없어도 약을 꾸준히 복용해야 함을 강조합니다.",
      "Tình trạng huyết áp cao liên tục (trên 140/90mmHg), được gọi là 'kẻ giết người thầm lặng'",
      "심장내과/내과",
      "베트남 음식의 염분 함량이 높아 고혈압 관리에 식이 조절이 특히 중요합니다. 느억맘, 국물 요리 섭취 줄이기를 권합니다.",
      [{"mistake":"증상 없으면 안 먹어도 된다고 설명","correction":"증상 없어도 장기 손상 진행","explanation":"합병증 예방이 목적입니다"},
       {"mistake":"혈압 정상 되면 약 중단 가능하다고 설명","correction":"대부분 평생 복용 필요","explanation":"중단하면 다시 상승합니다"},
       {"mistake":"약만 강조","correction":"생활습관 개선도 필수","explanation":"식이, 운동, 체중 관리가 중요합니다"}],
      [{"ko":"고혈압 약은 매일 같은 시간에 드세요.","vi":"Thuốc huyết áp cao uống mỗi ngày cùng giờ.","situation":"formal"},
       {"ko":"짠 음식을 줄이면 혈압 조절에 도움됩니다.","vi":"Giảm đồ ăn mặn sẽ giúp kiểm soát huyết áp.","situation":"onsite"},
       {"ko":"혈압 높아서 약 먹고 있어요.","vi":"Huyết áp cao nên đang uống thuốc.","situation":"informal"}],
      ["혈압계","저염식","ACE억제제"]),

    t("xo-vua-dong-mach","동맥경화","xơ vữa động mạch",
      "동맥벽에 지방과 콜레스테롤이 쌓여 혈관이 좁아지고 굳어지는 상태입니다. 통역 시 '혈관에 기름이 끼었다'고 표현하면 이해가 쉽고, 생활습관과의 연관성을 설명합니다.",
      "Tình trạng mỡ và cholesterol tích tụ trên thành động mạch làm hẹp và cứng mạch máu",
      "심장내과/신경과",
      "동맥경화는 심근경색, 뇌졸중의 원인이 됩니다. 예방의 중요성을 강조하고, 베트남 음식의 기름기 많은 요리를 줄이도록 권합니다.",
      [{"mistake":"노화 현상으로만 치부","correction":"생활습관으로 예방·관리 가능","explanation":"적극적 개입이 필요합니다"},
       {"mistake":"콜레스테롤만 강조","correction":"혈압, 혈당, 흡연도 위험인자","explanation":"종합적 관리가 필요합니다"},
       {"mistake":"약 먹으면 해결이라고 설명","correction":"생활습관 개선이 기본","explanation":"약물은 보조적 역할입니다"}],
      [{"ko":"동맥경화 예방을 위해 콜레스테롤 약을 드셔야 합니다.","vi":"Cần uống thuốc cholesterol để phòng xơ vữa động mạch.","situation":"formal"},
       {"ko":"튀긴 음식과 기름진 음식을 줄이세요.","vi":"Hãy giảm đồ chiên và đồ nhiều dầu mỡ.","situation":"onsite"},
       {"ko":"동맥경화라서 혈관이 막힐 위험 있대요.","vi":"Xơ vữa động mạch nên có nguy cơ tắc mạch.","situation":"informal"}],
      ["콜레스테롤","스타틴","경동맥초음파"]),

    t("noi-mach-vanh","관상동맥질환","bệnh động mạch vành",
      "심장에 혈액을 공급하는 관상동맥이 좁아져 협심증이나 심근경색을 유발합니다. 통역 시 가슴 통증의 양상(운동 시 악화, 안정 시 호전)을 정확히 전달합니다.",
      "Bệnh khi động mạch vành cung cấp máu cho tim bị hẹp gây đau thắt ngực hoặc nhồi máu cơ tim",
      "심장내과",
      "관상동맥질환은 생활습관병이므로 식이, 운동, 금연 교육이 필수입니다. 스텐트 시술 후에도 생활습관 관리가 중요함을 강조합니다.",
      [{"mistake":"가슴 통증을 위장병으로 오해","correction":"심장성 통증 가능성 고려 필요","explanation":"중요한 감별진단입니다"},
       {"mistake":"스텐트 넣으면 완치라고 설명","correction":"재협착 가능, 생활관리 필수","explanation":"지속적 관리가 필요합니다"},
       {"mistake":"운동하면 안 된다고 설명","correction":"적절한 유산소 운동 권장","explanation":"심장재활이 중요합니다"}],
      [{"ko":"관상동맥 검사를 위해 심장 CT가 필요합니다.","vi":"Cần chụp CT tim để kiểm tra động mạch vành.","situation":"formal"},
       {"ko":"가슴 통증이 있으면 니트로글리세린을 혀 밑에 넣으세요.","vi":"Nếu đau ngực hãy đặt nitroglycerin dưới lưỡi.","situation":"onsite"},
       {"ko":"심장혈관이 막혀서 스텐트 넣었어요.","vi":"Mạch vành bị tắc nên đặt stent.","situation":"informal"}],
      ["스텐트","관상동맥조영술","니트로글리세린"]),

    t("nhoi-mau-co-tim","심근경색","nhồi máu cơ tim",
      "관상동맥이 완전히 막혀 심장 근육이 손상되는 응급 상황입니다. 통역 시 '가슴을 쥐어짜는 듯한 통증'을 강조하고, 골든타임의 중요성을 전달합니다.",
      "Tình trạng cấp cứu khi động mạch vành bị tắc hoàn toàn gây tổn thương cơ tim",
      "심장내과/응급",
      "심근경색은 분초를 다투는 응급상황입니다. 베트남 환자들이 증상을 참고 넘기지 않도록 즉시 119 호출의 중요성을 교육합니다.",
      [{"mistake":"쉬면 낫는다고 설명","correction":"즉시 응급실 가야 함","explanation":"지연은 생명을 위협합니다"},
       {"mistake":"소화불량과 혼동","correction":"상복부 통증도 심근경색 증상일 수 있음","explanation":"비전형 증상도 알려줍니다"},
       {"mistake":"젊으면 안 걸린다고 안심시킴","correction":"젊은 사람도 발생 가능","explanation":"위험인자가 있으면 주의 필요합니다"}],
      [{"ko":"심근경색 의심으로 심장 혈관 시술이 급히 필요합니다.","vi":"Nghi ngờ nhồi máu cơ tim, cần can thiệp mạch vành gấp.","situation":"formal"},
       {"ko":"가슴이 쥐어짜듯이 아프면 바로 119에 연락하세요.","vi":"Nếu đau ngực như bóp nghẹt, hãy gọi 119 ngay.","situation":"onsite"},
       {"ko":"심근경색으로 쓰러졌다가 살았어요.","vi":"Bị nhồi máu cơ tim ngã rồi được cứu.","situation":"informal"}],
      ["응급혈관성형술","심장효소","심폐소생술"]),

    t("benh-van-tim","심장판막질환","bệnh van tim",
      "심장 판막이 제대로 열리거나 닫히지 않아 혈류에 문제가 생기는 상태입니다. 통역 시 판막의 역할을 '일방통행 문'에 비유하면 이해가 쉽습니다.",
      "Tình trạng van tim không mở hoặc đóng đúng cách gây rối loạn dòng máu",
      "심장내과",
      "류마티스열 후유증으로 판막질환이 생기는 경우가 있어, 어린 시절 류마티스열 병력을 확인합니다.",
      [{"mistake":"심장에 구멍 났다고 표현","correction":"판막 문제는 구멍과 다름","explanation":"정확한 설명이 필요합니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"경증은 약물 관리로 가능","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"평생 조심해야 한다고만 설명","correction":"치료 후 정상 생활 가능","explanation":"희망을 줍니다"}],
      [{"ko":"심장 판막 상태를 확인하기 위해 심장초음파가 필요합니다.","vi":"Cần siêu âm tim để kiểm tra tình trạng van tim.","situation":"formal"},
       {"ko":"숨이 차거나 다리가 부으면 진료받으세요.","vi":"Nếu khó thở hoặc chân phù hãy đến khám.","situation":"onsite"},
       {"ko":"심장판막이 안 좋아서 수술해야 해요.","vi":"Van tim không tốt nên phải phẫu thuật.","situation":"informal"}],
      ["심장초음파","판막성형술","판막치환술"]),

    t("viem-mang-ngoai-tim","심낭염","viêm màng ngoài tim",
      "심장을 싸고 있는 막(심낭)에 염증이 생겨 가슴 통증이 발생합니다. 통역 시 숨을 들이쉬거나 누우면 통증이 악화되는 특징을 전달합니다.",
      "Tình trạng viêm màng bao quanh tim gây đau ngực",
      "심장내과",
      "바이러스 감염 후에 발생하는 경우가 많습니다. 대부분 양성 경과를 보이지만, 심장눌림증 발생 시 응급 상황임을 설명합니다.",
      [{"mistake":"심근경색과 혼동","correction":"심낭염은 자세와 호흡에 따라 통증 변화","explanation":"감별점이 중요합니다"},
       {"mistake":"가볍게 치부","correction":"심장눌림증 발생 시 응급","explanation":"악화 징후를 알려줍니다"},
       {"mistake":"항생제가 필요하다고 설명","correction":"바이러스성은 대증치료","explanation":"원인에 따라 치료가 다릅니다"}],
      [{"ko":"심낭염으로 염증 치료제를 드셔야 합니다.","vi":"Viêm màng ngoài tim cần uống thuốc chống viêm.","situation":"formal"},
       {"ko":"앞으로 숙이면 통증이 줄어들 수 있어요.","vi":"Cúi người về phía trước có thể giảm đau.","situation":"onsite"},
       {"ko":"심낭염이라 숨 쉴 때 가슴이 아파요.","vi":"Viêm màng ngoài tim nên đau ngực khi thở.","situation":"informal"}],
      ["심전도","심장초음파","콜히친"]),

    t("huyet-khoi-tinh-mach-sau","심부정맥혈전증","huyết khối tĩnh mạch sâu",
      "다리의 깊은 정맥에 혈전이 생겨 부종과 통증이 발생합니다. 통역 시 폐색전증으로 진행할 위험성을 설명하고, 장시간 부동 상태를 피하도록 교육합니다.",
      "Tình trạng huyết khối hình thành trong tĩnh mạch sâu ở chân gây sưng và đau",
      "심장내과/혈관외과",
      "장시간 비행이나 입원으로 발생할 수 있습니다. 베트남 왕복 시 예방법을 안내합니다.",
      [{"mistake":"단순 다리 부종으로 치부","correction":"한쪽 다리만 붓고 아프면 의심","explanation":"심부정맥혈전증 가능성 고려"},
       {"mistake":"마사지하라고 권유","correction":"혈전이 떨어질 수 있어 금기","explanation":"폐색전증 위험이 있습니다"},
       {"mistake":"걸으면 안 된다고 설명","correction":"항응고제 시작 후 조기 보행 권장","explanation":"침상안정보다 활동이 좋습니다"}],
      [{"ko":"심부정맥혈전증으로 항응고제 치료가 필요합니다.","vi":"Huyết khối tĩnh mạch sâu cần điều trị thuốc chống đông.","situation":"formal"},
       {"ko":"다리를 주무르지 마시고 높이 올려두세요.","vi":"Đừng xoa bóp chân, hãy kê cao lên.","situation":"onsite"},
       {"ko":"다리에 혈전 생겨서 피 굳는 약 먹어요.","vi":"Chân bị huyết khối nên uống thuốc chống đông.","situation":"informal"}],
      ["항응고제","폐색전증","압박스타킹"]),

    t("gian-tinh-mach","하지정맥류","giãn tĩnh mạch",
      "다리 정맥이 늘어나고 꼬불꼬불해져 혈액이 정체되는 상태입니다. 통역 시 오래 서있는 직업과의 연관성을 설명하고, 압박스타킹 사용법을 안내합니다.",
      "Tình trạng tĩnh mạch chân bị giãn và xoắn khiến máu ứ đọng",
      "혈관외과",
      "장시간 서서 일하는 베트남 근로자들에게 흔합니다. 산업재해로 인정받을 수 있는 경우도 있어 관련 정보를 제공합니다.",
      [{"mistake":"미용 문제로만 치부","correction":"혈전, 피부 궤양 등 합병증 가능","explanation":"치료가 필요할 수 있습니다"},
       {"mistake":"수술만 있다고 설명","correction":"보존적 치료(압박스타킹 등)로 시작","explanation":"단계적 접근이 필요합니다"},
       {"mistake":"운동하면 안 된다고 설명","correction":"걷기 운동 권장","explanation":"근육 펌프 작용이 도움됩니다"}],
      [{"ko":"하지정맥류 예방을 위해 압박스타킹 착용을 권합니다.","vi":"Khuyên đeo vớ áp lực để phòng giãn tĩnh mạch chân.","situation":"formal"},
       {"ko":"오래 서있을 때는 가끔 발꿈치를 들었다 놓으세요.","vi":"Khi đứng lâu hãy thỉnh thoảng nhón gót chân.","situation":"onsite"},
       {"ko":"정맥류 때문에 다리가 무거워요.","vi":"Giãn tĩnh mạch nên chân nặng nề.","situation":"informal"}],
      ["압박스타킹","정맥폐쇄술","경화요법"]),

    t("phình-dong-mach-chu","대동맥류","phình động mạch chủ",
      "대동맥의 일부가 비정상적으로 확장되어 파열 위험이 있는 상태입니다. 통역 시 증상 없이 진행되다 파열 시 생명을 위협할 수 있음을 설명합니다.",
      "Tình trạng một phần động mạch chủ giãn bất thường có nguy cơ vỡ",
      "심장혈관외과",
      "고혈압과 동맥경화가 주요 위험인자입니다. 정기 검진의 중요성을 강조합니다.",
      [{"mistake":"증상이 있다고 설명","correction":"대부분 우연히 발견됨","explanation":"정기 검진이 중요합니다"},
       {"mistake":"작으면 괜찮다고 안심시킴","correction":"크기에 따라 정기 추적 필요","explanation":"성장 속도도 중요합니다"},
       {"mistake":"수술만 있다고 설명","correction":"작은 경우 혈압 조절로 관찰","explanation":"크기에 따라 치료가 다릅니다"}],
      [{"ko":"대동맥류 크기를 확인하기 위해 CT 검사가 필요합니다.","vi":"Cần chụp CT để kiểm tra kích thước phình động mạch chủ.","situation":"formal"},
       {"ko":"혈압을 잘 조절하는 게 중요합니다.","vi":"Kiểm soát huyết áp tốt là quan trọng.","situation":"onsite"},
       {"ko":"대동맥이 부풀어서 지켜보고 있어요.","vi":"Động mạch chủ bị phình nên đang theo dõi.","situation":"informal"}],
      ["CT혈관조영","스텐트그라프트","혈압조절"]),

    t("benh-dong-mach-ngoai-vi","말초동맥질환","bệnh động mạch ngoại vi",
      "다리 동맥이 좁아져 걸을 때 다리가 아프고 쉬면 완화되는(간헐적 파행) 상태입니다. 통역 시 동맥경화가 다리에 나타난 것임을 설명합니다.",
      "Tình trạng động mạch chân bị hẹp gây đau chân khi đi bộ và giảm khi nghỉ",
      "혈관외과",
      "당뇨와 흡연이 주요 위험인자입니다. 금연과 혈당 관리의 중요성을 강조합니다.",
      [{"mistake":"관절염으로 오해","correction":"걸을 때 종아리 통증이 특징","explanation":"감별진단이 중요합니다"},
       {"mistake":"쉬기만 하라고 설명","correction":"적절한 보행 운동 권장","explanation":"측부순환 발달에 도움됩니다"},
       {"mistake":"발 색깔 변화 무시","correction":"창백, 청색증은 중증 징후","explanation":"즉시 진료가 필요합니다"}],
      [{"ko":"말초동맥질환으로 혈관 검사가 필요합니다.","vi":"Bệnh động mạch ngoại vi cần kiểm tra mạch máu.","situation":"formal"},
       {"ko":"담배를 끊으면 다리 혈류가 좋아집니다.","vi":"Bỏ thuốc lá sẽ cải thiện tuần hoàn chân.","situation":"onsite"},
       {"ko":"다리 혈관이 막혀서 걸으면 아파요.","vi":"Mạch máu chân bị tắc nên đi bộ là đau.","situation":"informal"}],
      ["발목상완지수","혈관성형술","금연"]),

    t("viem-tinh-mach-huyet-khoi","혈전성정맥염","viêm tĩnh mạch huyết khối",
      "표재정맥에 혈전이 생기고 염증이 동반되어 붉고 딱딱한 줄이 만져지는 상태입니다. 통역 시 심부정맥혈전증과 구별하되, 확장 가능성을 설명합니다.",
      "Tình trạng huyết khối và viêm ở tĩnh mạch nông gây sưng đỏ và cứng",
      "혈관외과",
      "정맥주사 후에 발생하기도 합니다. 병원에서 주사 맞은 부위가 아프다면 의료진에게 알리도록 교육합니다.",
      [{"mistake":"심부정맥혈전증과 동일시","correction":"표재정맥은 상대적으로 덜 위험","explanation":"그러나 확장 가능성 있음"},
       {"mistake":"문지르라고 권유","correction":"염증 악화 가능","explanation":"안정과 냉찜질 권장"},
       {"mistake":"저절로 낫는다고만 설명","correction":"항염증제와 압박이 도움","explanation":"적절한 치료가 필요합니다"}],
      [{"ko":"혈전성정맥염으로 소염제와 압박이 필요합니다.","vi":"Viêm tĩnh mạch huyết khối cần thuốc chống viêm và băng ép.","situation":"formal"},
       {"ko":"붉게 부은 부위를 냉찜질하세요.","vi":"Chườm lạnh chỗ sưng đỏ.","situation":"onsite"},
       {"ko":"주사 맞은 데가 빨갛고 딱딱해졌어요.","vi":"Chỗ tiêm đỏ và cứng lên.","situation":"informal"}],
      ["소염제","압박붕대","초음파"]),

    t("suy-tim-sung-huyet","울혈성심부전","suy tim sung huyết",
      "심장 기능 저하로 폐와 전신에 혈액이 정체되어 호흡곤란과 부종이 발생합니다. 통역 시 물이 차서 숨이 찬다고 표현하면 이해가 쉽습니다.",
      "Tình trạng chức năng tim giảm gây ứ máu ở phổi và toàn thân, khó thở và phù",
      "심장내과",
      "염분 제한과 수분 제한이 중요합니다. 베트남 음식의 특성상 국물 요리를 줄이도록 구체적으로 안내합니다.",
      [{"mistake":"심장이 멈추는 거라고 설명","correction":"심장이 약해져 혈액 정체되는 것","explanation":"정확한 개념 전달이 필요합니다"},
       {"mistake":"물 많이 마시라고 권유","correction":"수분 제한이 필요할 수 있음","explanation":"증상을 악화시킬 수 있습니다"},
       {"mistake":"누워있으라고만 설명","correction":"상체를 높이고 눕기 권장","explanation":"호흡이 편해집니다"}],
      [{"ko":"울혈성심부전으로 이뇨제와 염분 제한이 필요합니다.","vi":"Suy tim sung huyết cần thuốc lợi tiểu và hạn chế muối.","situation":"formal"},
       {"ko":"누울 때 베개를 높이 베면 숨쉬기가 편해요.","vi":"Nằm kê cao gối sẽ dễ thở hơn.","situation":"onsite"},
       {"ko":"심부전이라 폐에 물 찼어요.","vi":"Suy tim nên phổi bị tràn dịch.","situation":"informal"}],
      ["이뇨제","염분제한","심장재활"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
