#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch D - 신경과/근골격계 (20개)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("dau-dau-migraine","편두통","đau đầu migraine",
      "한쪽 머리에 주로 발생하는 박동성 두통으로, 구역, 구토, 빛과 소리에 예민해지는 증상을 동반합니다. 통역 시 환자가 '머리 한쪽이 쿵쿵거린다'고 표현하면 편두통 가능성을 고려하고, 전조 증상(시야 이상 등)도 확인해야 합니다.",
      "Đau đầu dạng nhịp đập thường xảy ra một bên đầu, kèm buồn nôn, nôn, nhạy cảm với ánh sáng và âm thanh",
      "신경과",
      "베트남에서는 편두통을 'nhức đầu' 정도로 가볍게 표현하는 경향이 있어, 증상의 심각성을 구체적으로 물어봐야 정확한 진단에 도움이 됩니다.",
      [{"mistake":"일반 두통과 동일하게 취급","correction":"편두통은 특정 증상(편측성, 박동성, 동반증상)이 있는 별개 질환","explanation":"치료 방법이 일반 두통과 다릅니다"},
       {"mistake":"진통제로 쉽게 조절된다고 설명","correction":"편두통 전용 약물이 필요할 수 있음","explanation":"일반 진통제가 효과 없는 경우가 많습니다"},
       {"mistake":"스트레스 탓으로만 돌림","correction":"유발 요인은 다양(호르몬, 음식, 수면 등)","explanation":"정확한 유발 요인 파악이 중요합니다"}],
      [{"ko":"편두통으로 예방 약물 복용이 필요합니다.","vi":"Bạn cần uống thuốc phòng ngừa đau đầu migraine.","situation":"formal"},
       {"ko":"편두통 발작 시 어두운 곳에서 쉬세요.","vi":"Khi lên cơn migraine, hãy nghỉ ngơi ở nơi tối.","situation":"onsite"},
       {"ko":"편두통 있어서 밝은 불빛 피해요.","vi":"Bị migraine nên em tránh ánh sáng mạnh.","situation":"informal"}],
      ["두통","전조증상","트립탄"]),

    t("dong-kinh","간질/뇌전증","động kinh",
      "뇌의 비정상적인 전기 활동으로 인해 반복적인 발작이 발생하는 만성 신경질환입니다. 통역 시 '간질'은 사회적 낙인이 있어 '뇌전증'으로 순화하여 사용하며, 발작 유형(전신/부분)을 정확히 전달해야 합니다.",
      "Bệnh thần kinh mãn tính với các cơn co giật lặp đi lặp lại do hoạt động điện bất thường của não",
      "신경과",
      "베트남에서도 간질에 대한 사회적 편견이 있어, 환자가 증상을 숨기려 할 수 있습니다. 비밀 보장을 확인시켜 정확한 병력 청취가 가능하게 합니다.",
      [{"mistake":"간질이라는 용어 사용","correction":"뇌전증으로 순화하여 사용","explanation":"사회적 낙인을 줄이기 위한 배려입니다"},
       {"mistake":"모든 발작을 동일하게 설명","correction":"전신 발작과 부분 발작 구분 필요","explanation":"치료와 예후가 다릅니다"},
       {"mistake":"평생 약을 먹어야 한다고만 설명","correction":"일부 환자는 약물 중단 가능","explanation":"희망적인 정보도 함께 전달합니다"}],
      [{"ko":"뇌전증 약을 꾸준히 복용해야 발작을 예방할 수 있습니다.","vi":"Phải uống thuốc động kinh đều đặn để phòng ngừa cơn co giật.","situation":"formal"},
       {"ko":"발작이 일어나면 안전한 곳으로 옮기세요.","vi":"Khi lên cơn co giật, hãy di chuyển đến nơi an toàn.","situation":"onsite"},
       {"ko":"뇌전증 약 안 먹으면 발작 올 수 있어.","vi":"Không uống thuốc động kinh có thể lên cơn.","situation":"informal"}],
      ["발작","항경련제","뇌파검사"]),

    t("tai-bien-mach-mau-nao","뇌졸중","tai biến mạch máu não",
      "뇌혈관이 막히거나(뇌경색) 터져서(뇌출혈) 뇌 손상이 발생하는 응급 상황입니다. 통역 시 'FAST' 증상(얼굴 처짐, 팔 마비, 언어 장애, 시간 중요)을 신속히 전달하고, 골든타임(4.5시간)의 중요성을 강조해야 합니다.",
      "Tình trạng cấp cứu khi mạch máu não bị tắc (nhồi máu não) hoặc vỡ (xuất huyết não) gây tổn thương não",
      "신경과/응급",
      "베트남에서는 'đột quỵ'라는 용어도 많이 사용됩니다. 한국과 달리 베트남에서는 뇌졸중 초기 증상 인지도가 낮아, 증상 설명에 더 많은 시간을 할애해야 합니다.",
      [{"mistake":"뇌경색과 뇌출혈을 구분하지 않음","correction":"치료법이 다르므로 정확히 구분 필요","explanation":"혈전용해제는 뇌경색에만 사용됩니다"},
       {"mistake":"골든타임 언급 안 함","correction":"4.5시간 내 치료 중요성 강조","explanation":"시간이 예후를 결정합니다"},
       {"mistake":"완전 회복된다고 낙관","correction":"후유증 가능성 함께 설명","explanation":"현실적 기대를 갖게 합니다"}],
      [{"ko":"뇌졸중 의심 증상이 있으니 즉시 CT 촬영이 필요합니다.","vi":"Có triệu chứng nghi ngờ tai biến mạch máu não nên cần chụp CT ngay.","situation":"formal"},
       {"ko":"얼굴이 한쪽으로 처지고 팔에 힘이 없으면 바로 119에 연락하세요.","vi":"Nếu mặt xệ một bên và tay yếu, hãy gọi 119 ngay.","situation":"onsite"},
       {"ko":"뇌졸중 오면 빨리 병원 가야 해요.","vi":"Bị tai biến phải đến bệnh viện ngay.","situation":"informal"}],
      ["뇌경색","뇌출혈","혈전용해제"]),

    t("liet-day-than-kinh-mat","안면마비","liệt dây thần kinh mặt",
      "얼굴 한쪽 근육이 마비되어 표정을 짓거나 눈을 감기 어려운 상태입니다. 벨마비(특발성)와 뇌졸중 감별이 중요하며, 통역 시 이마 주름이 잡히는지 여부가 감별에 도움됨을 전달합니다.",
      "Tình trạng liệt cơ mặt một bên khiến khó biểu cảm hoặc nhắm mắt",
      "신경과",
      "베트남에서는 안면마비를 'trúng gió'(중풍, 바람 맞음)라고 표현하기도 합니다. 미신적 해석보다 의학적 설명이 필요합니다.",
      [{"mistake":"뇌졸중과 구분하지 않음","correction":"이마 주름, 다른 마비 증상 확인 필요","explanation":"뇌졸중이면 즉시 응급 처치가 필요합니다"},
       {"mistake":"영구적이라고 겁줌","correction":"벨마비는 대부분 수주 내 회복","explanation":"불필요한 불안을 줄입니다"},
       {"mistake":"한방 치료만 권유","correction":"초기 스테로이드 치료가 효과적","explanation":"근거 있는 치료를 먼저 시도합니다"}],
      [{"ko":"안면마비 증상이 있어 MRI 검사가 필요합니다.","vi":"Có triệu chứng liệt mặt nên cần chụp MRI.","situation":"formal"},
       {"ko":"눈이 안 감기면 인공눈물을 자주 넣으세요.","vi":"Nếu không nhắm được mắt, hãy nhỏ nước mắt nhân tạo thường xuyên.","situation":"onsite"},
       {"ko":"안면마비는 보통 몇 주면 나아요.","vi":"Liệt mặt thường hồi phục sau vài tuần.","situation":"informal"}],
      ["벨마비","스테로이드","물리치료"]),

    t("thoai-hoa-dot-song-co","경추디스크","thoái hóa đốt sống cổ",
      "목 디스크(추간판)가 탈출하여 신경을 압박해 목, 어깨, 팔 통증 및 저림을 유발하는 질환입니다. 통역 시 환자가 '목이 뻣뻣하다', '팔이 저리다'고 표현하면 경추디스크 가능성을 고려합니다.",
      "Bệnh lý khi đĩa đệm cổ thoát vị chèn ép dây thần kinh gây đau cổ, vai, tay và tê",
      "정형외과/신경외과",
      "베트남 근로자들은 장시간 고개 숙인 작업으로 경추디스크가 흔합니다. 직업력 청취가 진단에 중요합니다.",
      [{"mistake":"허리디스크와 혼동","correction":"경추는 목, 요추는 허리로 명확히 구분","explanation":"위치에 따라 증상이 다릅니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"대부분 보존적 치료로 호전","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"증상 위치 확인 안 함","correction":"어느 손가락이 저린지가 진단에 중요","explanation":"신경 위치를 파악할 수 있습니다"}],
      [{"ko":"경추디스크로 인한 신경 압박이 있어 물리치료가 필요합니다.","vi":"Có chèn ép thần kinh do thoát vị đĩa đệm cổ, cần vật lý trị liệu.","situation":"formal"},
       {"ko":"목을 뒤로 젖히면 통증이 심해지니 피하세요.","vi":"Tránh ngửa cổ ra sau vì sẽ đau hơn.","situation":"onsite"},
       {"ko":"목디스크라 팔이 저려요.","vi":"Bị thoát vị đĩa đệm cổ nên tay tê.","situation":"informal"}],
      ["추간판탈출증","신경근병증","경추견인"]),

    t("thoat-vi-dia-dem-that-lung","요추디스크","thoát vị đĩa đệm thắt lưng",
      "허리 디스크가 탈출하여 신경을 압박해 허리, 엉덩이, 다리 통증 및 저림을 유발합니다. 통역 시 하지방사통(다리로 뻗치는 통증) 여부를 정확히 전달하는 것이 중요합니다.",
      "Bệnh lý khi đĩa đệm thắt lưng thoát vị chèn ép dây thần kinh gây đau lưng, mông, chân và tê",
      "정형외과/신경외과",
      "베트남 근로자들에게 매우 흔한 질환입니다. 무거운 물건 들기, 장시간 서있는 작업이 원인인 경우가 많아 산재 관련 통역에서도 자주 등장합니다.",
      [{"mistake":"단순 요통과 혼동","correction":"하지방사통 여부가 디스크와 근육통 구별 포인트","explanation":"치료 방향이 달라집니다"},
       {"mistake":"절대 안정만 권고","correction":"적절한 활동이 회복에 도움","explanation":"과도한 안정은 오히려 해로울 수 있습니다"},
       {"mistake":"수술만이 답이라고 설명","correction":"80-90%는 보존적 치료로 호전","explanation":"수술은 최후의 선택입니다"}],
      [{"ko":"요추디스크로 수술 없이 보존적 치료를 먼저 시도해 보겠습니다.","vi":"Thoát vị đĩa đệm thắt lưng, sẽ thử điều trị bảo tồn trước không cần phẫu thuật.","situation":"formal"},
       {"ko":"무거운 물건 들 때 무릎을 굽히고 드세요.","vi":"Khi nâng vật nặng, hãy gập đầu gối rồi nâng.","situation":"onsite"},
       {"ko":"허리디스크라서 오래 못 앉아요.","vi":"Bị thoát vị đĩa đệm lưng nên không ngồi lâu được.","situation":"informal"}],
      ["좌골신경통","경막외주사","척추융합술"]),

    t("viem-khop-dang-thap","류마티스관절염","viêm khớp dạng thấp",
      "자가면역질환으로 관절에 만성 염증이 발생하여 통증, 부종, 변형을 유발합니다. 통역 시 아침 강직(30분 이상 지속)이 특징적 증상임을 강조하고, 골관절염과의 차이점을 설명합니다.",
      "Bệnh tự miễn gây viêm mãn tính ở khớp, gây đau, sưng và biến dạng khớp",
      "류마티스내과",
      "베트남에서는 관절염을 'phong thấp'(풍습)이라 부르며 전통적 관념이 있습니다. 자가면역질환이라는 개념 설명이 필요합니다.",
      [{"mistake":"퇴행성관절염과 혼동","correction":"류마티스는 자가면역, 퇴행성은 마모가 원인","explanation":"치료법이 근본적으로 다릅니다"},
       {"mistake":"노인 질환으로만 설명","correction":"젊은 여성에게도 흔함","explanation":"환자 연령대가 다양합니다"},
       {"mistake":"관절만 문제라고 설명","correction":"전신 질환으로 폐, 심장에도 영향 가능","explanation":"전신 관리가 필요합니다"}],
      [{"ko":"류마티스관절염으로 면역억제제 치료가 필요합니다.","vi":"Viêm khớp dạng thấp cần điều trị bằng thuốc ức chế miễn dịch.","situation":"formal"},
       {"ko":"아침에 손가락이 뻣뻣하면 따뜻한 물에 담그세요.","vi":"Sáng dậy nếu ngón tay cứng, hãy ngâm trong nước ấm.","situation":"onsite"},
       {"ko":"류마티스라서 손가락 마디가 아파요.","vi":"Bị viêm khớp dạng thấp nên đau các đốt ngón tay.","situation":"informal"}],
      ["자가면역질환","항류마티스제","관절변형"]),

    t("loang-xuong","골다공증","loãng xương",
      "뼈의 밀도가 감소하여 쉽게 골절되는 상태입니다. 통역 시 '뼈가 약하다'보다 '스펀지처럼 구멍이 생긴다'고 설명하면 환자 이해가 쉽습니다. 폐경 후 여성과 고령자에게 흔합니다.",
      "Tình trạng mật độ xương giảm khiến xương dễ gãy",
      "정형외과/내분비내과",
      "베트남 여성들은 칼슘 섭취와 햇빛 노출이 부족한 경우가 많아 골다공증 위험이 높습니다. 예방 교육이 중요합니다.",
      [{"mistake":"뼈가 약해진다고만 설명","correction":"스펀지처럼 구멍이 생긴다고 시각화","explanation":"환자 이해도를 높입니다"},
       {"mistake":"증상이 있다고 설명","correction":"조용한 질병으로 골절 전까지 증상 없음","explanation":"정기 검사의 중요성을 강조합니다"},
       {"mistake":"칼슘만 강조","correction":"비타민D, 운동도 필수","explanation":"복합적 관리가 필요합니다"}],
      [{"ko":"골다공증 예방을 위해 뼈밀도 검사가 필요합니다.","vi":"Cần đo mật độ xương để phòng ngừa loãng xương.","situation":"formal"},
       {"ko":"넘어지지 않도록 조심하세요. 골절 위험이 있습니다.","vi":"Cẩn thận không ngã vì có nguy cơ gãy xương.","situation":"onsite"},
       {"ko":"골다공증이라 뼈가 약해요.","vi":"Bị loãng xương nên xương yếu.","situation":"informal"}],
      ["뼈밀도검사","비스포스포네이트","골절"]),

    t("gout","통풍","gout/bệnh gút",
      "혈중 요산 수치가 높아져 관절에 요산 결정이 침착되어 극심한 통증을 유발하는 질환입니다. 통역 시 급성 발작 시 '바늘로 찌르는 듯한 통증'이라고 표현하면 증상 이해에 도움됩니다.",
      "Bệnh khi nồng độ axit uric trong máu cao gây lắng đọng tinh thể urat ở khớp, gây đau dữ dội",
      "류마티스내과",
      "베트남에서는 맥주와 해산물 소비가 많아 통풍이 증가하고 있습니다. 식이 조절의 중요성을 강조하면서 문화적 민감성을 유지합니다.",
      [{"mistake":"관절염과 혼동","correction":"급성 발작과 무증상기가 번갈아 나타남","explanation":"질병 경과가 다릅니다"},
       {"mistake":"음식만 주의하면 된다고 설명","correction":"약물 치료가 필수인 경우도 많음","explanation":"요산 조절에 한계가 있습니다"},
       {"mistake":"맥주만 제한하라고 조언","correction":"모든 주류와 과당 음료도 제한","explanation":"정확한 식이 교육이 필요합니다"}],
      [{"ko":"통풍 발작 시 해당 관절을 높이 올리고 냉찜질하세요.","vi":"Khi lên cơn gút, nâng cao khớp đó và chườm lạnh.","situation":"formal"},
       {"ko":"맥주, 내장, 해산물을 줄이세요.","vi":"Hãy giảm bia, nội tạng và hải sản.","situation":"onsite"},
       {"ko":"통풍 때문에 엄지발가락이 엄청 아팠어요.","vi":"Đau ngón chân cái dữ dội vì bệnh gút.","situation":"informal"}],
      ["요산","콜히친","푸린"]),

    t("hoi-chung-ong-co-tay","손목터널증후군","hội chứng ống cổ tay",
      "손목의 좁은 통로(수근관)에서 정중신경이 압박되어 손 저림과 통증이 발생합니다. 통역 시 야간에 증상이 심해지고, 손을 털면 완화되는 특징을 전달하면 진단에 도움됩니다.",
      "Tình trạng dây thần kinh giữa bị chèn ép trong ống cổ tay gây tê và đau tay",
      "정형외과/신경과",
      "베트남 근로자 중 반복 작업(조립, 포장, 봉제)을 하는 경우 흔하게 발생합니다. 산업재해 관련 통역에서 자주 등장합니다.",
      [{"mistake":"경추디스크와 혼동","correction":"손목터널은 1-3번째 손가락에 저림","explanation":"증상 분포가 다릅니다"},
       {"mistake":"손목만 쉬면 된다고 설명","correction":"야간 부목 착용이 효과적","explanation":"수면 중 손목 굽힘을 방지합니다"},
       {"mistake":"수술이 위험하다고 겁줌","correction":"간단한 시술로 호전율 높음","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"손목터널증후군으로 야간 보조기 착용을 권합니다.","vi":"Hội chứng ống cổ tay, khuyên đeo nẹp ban đêm.","situation":"formal"},
       {"ko":"밤에 손이 저리면 손을 흔들어 보세요.","vi":"Đêm nếu tay tê, hãy thử lắc tay.","situation":"onsite"},
       {"ko":"손목터널증후군이라 손가락이 저려요.","vi":"Bị hội chứng ống cổ tay nên ngón tay tê.","situation":"informal"}],
      ["정중신경","근전도검사","수근관유리술"]),

    t("gay-xuong","골절","gãy xương",
      "외부 힘에 의해 뼈가 부러지거나 금이 간 상태입니다. 통역 시 골절 유형(폐쇄성/개방성, 분쇄/단순)을 정확히 전달하고, 치료 기간에 대한 현실적 기대를 설정합니다.",
      "Tình trạng xương bị gãy hoặc nứt do lực từ bên ngoài",
      "정형외과",
      "베트남 근로자들의 산업재해에서 골절이 흔합니다. 산재 처리와 치료 기간, 후유증에 대한 정확한 통역이 중요합니다.",
      [{"mistake":"금간 것은 골절 아니라고 설명","correction":"금간 것도 골절의 일종(불완전골절)","explanation":"적절한 치료가 필요합니다"},
       {"mistake":"깁스만 하면 다 낫는다고 설명","correction":"수술이 필요한 골절도 있음","explanation":"골절 유형에 따라 치료가 다릅니다"},
       {"mistake":"기간을 정확히 단언","correction":"개인차가 있어 대략적 기간만 안내","explanation":"기대와 다를 때 불만이 생깁니다"}],
      [{"ko":"골절로 수술이 필요합니다. 금속판으로 고정합니다.","vi":"Gãy xương cần phẫu thuật. Sẽ cố định bằng nẹp kim loại.","situation":"formal"},
       {"ko":"부러진 부위를 움직이지 마세요.","vi":"Đừng di chuyển chỗ xương gãy.","situation":"onsite"},
       {"ko":"팔이 부러져서 깁스했어요.","vi":"Gãy tay nên phải bó bột.","situation":"informal"}],
      ["깁스","금속판고정술","불유합"]),

    t("bong-gan","인대손상","bong gân",
      "관절을 지지하는 인대가 늘어나거나 찢어진 상태입니다. 통역 시 손상 정도(1-3도)에 따라 치료 방법과 회복 기간이 다름을 설명합니다.",
      "Tình trạng dây chằng hỗ trợ khớp bị giãn hoặc rách",
      "정형외과",
      "운동 중이나 산업 현장에서 흔히 발생합니다. 베트남어로 'bong gân'(인대 손상)과 'trật khớp'(탈구)를 구분해야 합니다.",
      [{"mistake":"염좌와 골절을 구분 못함","correction":"X-ray로 골절 배제 필요","explanation":"동반 손상이 있을 수 있습니다"},
       {"mistake":"가벼운 손상으로 취급","correction":"3도 손상은 수술이 필요할 수 있음","explanation":"정도에 따라 치료가 다릅니다"},
       {"mistake":"찜질만 권유","correction":"RICE 원칙(안정, 냉찜질, 압박, 거상) 설명","explanation":"초기 처치가 중요합니다"}],
      [{"ko":"인대 손상으로 2주간 보조기 착용이 필요합니다.","vi":"Tổn thương dây chằng cần đeo nẹp 2 tuần.","situation":"formal"},
       {"ko":"발목을 삐었으면 먼저 얼음찜질하세요.","vi":"Nếu trẹo mắt cá, hãy chườm đá trước.","situation":"onsite"},
       {"ko":"인대가 늘어나서 좀 쉬어야 해요.","vi":"Dây chằng bị giãn nên phải nghỉ ngơi.","situation":"informal"}],
      ["염좌","RICE요법","관절보조기"]),

    t("viem-gan-co","건염","viêm gân cơ",
      "힘줄(건)에 염증이 생겨 통증과 운동 제한이 발생합니다. 반복 동작이나 과사용이 주원인이며, 통역 시 작업 환경과 동작을 구체적으로 확인합니다.",
      "Tình trạng viêm gân gây đau và hạn chế vận động",
      "정형외과",
      "베트남 근로자들의 직업병에서 건염이 흔합니다. 테니스엘보(외측상과염), 골프엘보(내측상과염) 등 구체적 명칭도 알아두면 좋습니다.",
      [{"mistake":"관절염과 혼동","correction":"건염은 힘줄, 관절염은 관절 문제","explanation":"치료 부위가 다릅니다"},
       {"mistake":"그냥 쉬면 낫는다고만 설명","correction":"원인 동작 교정이 필수","explanation":"재발 방지가 중요합니다"},
       {"mistake":"주사만 권유","correction":"물리치료와 스트레칭도 병행","explanation":"복합 치료가 효과적입니다"}],
      [{"ko":"건염으로 스테로이드 주사를 맞으면 효과가 있습니다.","vi":"Viêm gân tiêm steroid sẽ có hiệu quả.","situation":"formal"},
       {"ko":"반복 동작을 줄이고 스트레칭하세요.","vi":"Giảm động tác lặp lại và tập căng cơ.","situation":"onsite"},
       {"ko":"팔꿈치 건염이라 무거운 거 못 들어요.","vi":"Viêm gân khuỷu tay nên không nâng nặng được.","situation":"informal"}],
      ["테니스엘보","물리치료","체외충격파"]),

    t("thoai-hoa-khop","퇴행성관절염","thoái hóa khớp",
      "관절 연골이 닳아 뼈끼리 마찰하면서 통증과 강직이 발생합니다. 통역 시 '연골이 닳았다'고 표현하면 환자 이해가 쉽고, 류마티스관절염과 구별해야 합니다.",
      "Tình trạng sụn khớp bị mòn khiến xương cọ xát gây đau và cứng khớp",
      "정형외과",
      "고령의 베트남 환자들에게 흔합니다. 인공관절수술에 대한 두려움이 있어 보존적 치료 옵션을 충분히 설명합니다.",
      [{"mistake":"류마티스와 혼동","correction":"퇴행성은 마모, 류마티스는 자가면역","explanation":"원인과 치료가 다릅니다"},
       {"mistake":"운동하면 안 된다고 설명","correction":"적절한 운동이 관절 건강에 필수","explanation":"관절 주변 근육 강화가 중요합니다"},
       {"mistake":"약이 없다고 절망적으로 설명","correction":"증상 조절과 진행 억제가 가능","explanation":"희망을 유지하게 합니다"}],
      [{"ko":"퇴행성관절염으로 연골주사가 도움될 수 있습니다.","vi":"Thoái hóa khớp, tiêm sụn có thể giúp ích.","situation":"formal"},
       {"ko":"계단보다 엘리베이터를 이용하세요.","vi":"Hãy dùng thang máy thay vì cầu thang.","situation":"onsite"},
       {"ko":"무릎 관절염이라 오래 못 걸어요.","vi":"Viêm khớp gối nên không đi bộ lâu được.","situation":"informal"}],
      ["연골","인공관절","관절경"]),

    t("teo-co","근위축","teo cơ",
      "근육이 줄어들어 힘이 약해지는 상태입니다. 신경 손상, 장기간 부동, 영양 결핍 등 다양한 원인이 있으며, 통역 시 원인 파악이 치료의 핵심임을 전달합니다.",
      "Tình trạng cơ bị teo nhỏ và yếu đi",
      "신경과/재활의학과",
      "장기 입원 환자나 깁스 후 환자에게서 흔히 발생합니다. 재활 치료의 중요성을 강조합니다.",
      [{"mistake":"영구적이라고 단정","correction":"원인에 따라 회복 가능","explanation":"희망을 유지하게 합니다"},
       {"mistake":"운동만 하면 회복된다고 설명","correction":"원인 치료가 병행되어야 함","explanation":"근본 원인 해결이 중요합니다"},
       {"mistake":"단순 노화로 치부","correction":"병적 원인 배제 필요","explanation":"치료 가능한 원인이 있을 수 있습니다"}],
      [{"ko":"근위축 예방을 위해 재활운동이 중요합니다.","vi":"Tập phục hồi chức năng quan trọng để ngăn teo cơ.","situation":"formal"},
       {"ko":"깁스 푼 후 꾸준히 운동해야 근육이 돌아옵니다.","vi":"Sau khi tháo bột phải tập đều đặn để cơ phục hồi.","situation":"onsite"},
       {"ko":"오래 안 움직여서 근육이 빠졌어요.","vi":"Không vận động lâu nên cơ bị teo.","situation":"informal"}],
      ["재활치료","신경손상","물리치료"]),

    t("co-giat-co","근경련","co giật cơ",
      "근육이 갑자기 수축하면서 통증을 유발하는 상태입니다. 탈수, 전해질 불균형, 피로가 주원인이며, 통역 시 쥐가 난다는 표현을 사용하면 이해가 쉽습니다.",
      "Tình trạng cơ co thắt đột ngột gây đau",
      "신경과/내과",
      "더운 날씨에 야외 작업하는 베트남 근로자들에게 흔합니다. 수분과 전해질 보충의 중요성을 강조합니다.",
      [{"mistake":"단순 피로로 치부","correction":"전해질 이상, 혈관 문제 등 확인 필요","explanation":"반복되면 검사가 필요합니다"},
       {"mistake":"스트레칭만 권유","correction":"수분과 전해질 보충도 중요","explanation":"근본 원인 해결이 필요합니다"},
       {"mistake":"심각한 질환이라고 겁줌","correction":"대부분 일시적이고 양성","explanation":"불필요한 불안을 줄입니다"}],
      [{"ko":"근경련이 자주 발생하면 전해질 검사가 필요합니다.","vi":"Nếu co giật cơ thường xuyên cần xét nghiệm điện giải.","situation":"formal"},
       {"ko":"쥐가 나면 해당 근육을 천천히 펴세요.","vi":"Khi bị chuột rút, từ từ duỗi cơ đó ra.","situation":"onsite"},
       {"ko":"다리에 쥐가 자주 나요.","vi":"Hay bị chuột rút ở chân.","situation":"informal"}],
      ["전해질","탈수","마그네슘"]),

    t("viem-day-than-kinh-ngoai-vi","말초신경병증","viêm dây thần kinh ngoại vi",
      "손발의 신경이 손상되어 저림, 통증, 감각 이상이 발생합니다. 당뇨병이 가장 흔한 원인이며, 통역 시 '장갑-양말 분포' 패턴을 설명하면 이해가 쉽습니다.",
      "Tình trạng tổn thương thần kinh ở tay chân gây tê, đau và rối loạn cảm giác",
      "신경과/내분비내과",
      "당뇨 합병증으로 오는 경우가 많아, 당뇨 관리의 중요성과 연계하여 설명합니다.",
      [{"mistake":"저림만 설명","correction":"통증, 감각 저하, 근력 약화도 증상","explanation":"다양한 증상을 확인합니다"},
       {"mistake":"당뇨만 원인이라고 설명","correction":"알코올, 약물, 영양결핍도 원인","explanation":"다양한 원인을 고려합니다"},
       {"mistake":"치료가 없다고 단정","correction":"원인 치료와 증상 조절 가능","explanation":"관리가 가능함을 알립니다"}],
      [{"ko":"말초신경병증으로 혈당 조절이 더욱 중요합니다.","vi":"Bệnh thần kinh ngoại vi nên kiểm soát đường huyết càng quan trọng.","situation":"formal"},
       {"ko":"발 감각이 떨어지니 매일 발을 확인하세요.","vi":"Cảm giác chân giảm nên hãy kiểm tra chân mỗi ngày.","situation":"onsite"},
       {"ko":"당뇨 합병증으로 발이 저려요.","vi":"Biến chứng tiểu đường nên chân tê.","situation":"informal"}],
      ["당뇨신경병증","신경전도검사","가바펜틴"]),

    t("benh-parkinson","파킨슨병","bệnh Parkinson",
      "도파민 부족으로 떨림, 강직, 서동증(느린 움직임), 자세 불안정이 나타나는 퇴행성 뇌질환입니다. 통역 시 치료가 증상 조절임을 명확히 하고, 진행성 질환임을 부드럽게 전달합니다.",
      "Bệnh thoái hóa não do thiếu dopamine gây run, cứng cơ, chậm vận động và mất thăng bằng",
      "신경과",
      "고령화로 파킨슨병 환자가 증가하고 있습니다. 보호자 교육도 중요하며, 약물 복용 시간의 중요성을 강조합니다.",
      [{"mistake":"치매와 혼동","correction":"파킨슨은 운동장애, 치매는 인지장애","explanation":"주요 증상이 다릅니다"},
       {"mistake":"약으로 완치된다고 설명","correction":"증상 조절이 목표, 진행은 막을 수 없음","explanation":"현실적 기대를 갖게 합니다"},
       {"mistake":"모든 떨림을 파킨슨으로 단정","correction":"본태성 떨림 등 다른 원인도 있음","explanation":"정확한 진단이 필요합니다"}],
      [{"ko":"파킨슨병 약물은 정확한 시간에 복용해야 합니다.","vi":"Thuốc Parkinson phải uống đúng giờ.","situation":"formal"},
       {"ko":"천천히 움직이고 넘어지지 않도록 조심하세요.","vi":"Di chuyển chậm và cẩn thận không ngã.","situation":"onsite"},
       {"ko":"파킨슨이라 손이 떨려요.","vi":"Bị Parkinson nên tay run.","situation":"informal"}],
      ["도파민","레보도파","심부뇌자극술"]),

    t("benh-alzheimer","알츠하이머병","bệnh Alzheimer",
      "기억력과 인지 기능이 점진적으로 저하되는 퇴행성 뇌질환입니다. 통역 시 초기 증상(최근 기억 저하)과 진행 양상을 설명하고, 보호자의 역할을 강조합니다.",
      "Bệnh thoái hóa não với suy giảm dần trí nhớ và chức năng nhận thức",
      "신경과/정신건강의학과",
      "치매에 대한 사회적 인식이 중요합니다. 베트남에서는 치매를 단순 노화로 여기는 경향이 있어, 질병으로서의 인식 전환이 필요합니다.",
      [{"mistake":"노화와 동일시","correction":"정상 노화와 다른 병적 상태","explanation":"조기 진단과 관리가 중요합니다"},
       {"mistake":"치료가 없다고 단정","correction":"진행 억제 약물과 비약물 치료 있음","explanation":"관리로 삶의 질 향상 가능합니다"},
       {"mistake":"환자 앞에서 직접 설명","correction":"보호자에게 별도 설명 필요","explanation":"환자의 존엄성을 지킵니다"}],
      [{"ko":"알츠하이머병 진행을 늦추는 약물 치료를 시작하겠습니다.","vi":"Sẽ bắt đầu điều trị thuốc làm chậm tiến triển bệnh Alzheimer.","situation":"formal"},
       {"ko":"규칙적인 일과와 인지 활동이 도움됩니다.","vi":"Sinh hoạt điều độ và hoạt động trí óc sẽ giúp ích.","situation":"onsite"},
       {"ko":"할머니가 알츠하이머라 잘 까먹으세요.","vi":"Bà bị Alzheimer nên hay quên.","situation":"informal"}],
      ["치매","인지치료","도네페질"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
