#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch I - 산부인과/소아과/응급 (40개)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("co-thai","임신","có thai",
      "수정란이 자궁에 착상하여 태아가 발달하는 상태입니다. 통역 시 임신 주수 계산법(마지막 생리일 기준)과 산전 검진 일정을 안내합니다.",
      "Tình trạng trứng đã thụ tinh làm tổ trong tử cung và thai nhi phát triển",
      "산부인과",
      "베트남 여성 근로자의 임신 시 산전 관리와 출산 휴가에 대해 안내합니다. 한국의 산전 검진 시스템을 설명합니다.",
      [{"mistake":"임신 주수를 월수로만 설명","correction":"주수로 계산(40주)","explanation":"한국은 주수 기준입니다"},
       {"mistake":"모든 검사를 강제라고 설명","correction":"선택 검사도 있음","explanation":"정보 제공 후 선택하게 합니다"},
       {"mistake":"직장 상황 고려 안 함","correction":"근로기준법상 권리 안내","explanation":"출산휴가 등 권리를 알립니다"}],
      [{"ko":"임신 확인을 위해 혈액검사와 초음파 검사가 필요합니다.","vi":"Cần xét nghiệm máu và siêu âm để xác nhận có thai.","situation":"formal"},
       {"ko":"마지막 생리일이 언제예요?","vi":"Kỳ kinh cuối cùng là khi nào?","situation":"onsite"},
       {"ko":"임신 3개월이에요.","vi":"Có thai 3 tháng rồi.","situation":"informal"}],
      ["산전검사","초음파","임신주수"]),

    t("sinh-mo","제왕절개","sinh mổ",
      "자연 분만이 어려울 때 복부와 자궁을 절개하여 아기를 출산하는 수술입니다. 통역 시 수술 이유, 마취 방법, 회복 과정을 설명합니다.",
      "Phẫu thuật mở bụng và tử cung để lấy em bé khi không thể sinh thường",
      "산부인과",
      "제왕절개 후 회복이 자연분만보다 오래 걸립니다. 직장 복귀 시기에 대해 현실적으로 안내합니다.",
      [{"mistake":"제왕절개가 더 안전하다고 설명","correction":"자연분만이 가능하면 더 권장","explanation":"수술에는 위험이 따릅니다"},
       {"mistake":"다음에도 제왕절개해야 한다고 단정","correction":"VBAC(이전 제왕절개 후 자연분만) 가능할 수 있음","explanation":"개인 상황에 따라 다릅니다"},
       {"mistake":"회복이 빠르다고 설명","correction":"6-8주 회복 기간 필요","explanation":"현실적 기대를 설정합니다"}],
      [{"ko":"제왕절개 수술로 출산하셔야 합니다.","vi":"Phải sinh mổ.","situation":"formal"},
       {"ko":"수술 후 6-8주 회복 기간이 필요해요.","vi":"Sau mổ cần 6-8 tuần hồi phục.","situation":"onsite"},
       {"ko":"제왕절개로 낳았어요.","vi":"Sinh mổ.","situation":"informal"}],
      ["척추마취","자궁절개","흉터관리"]),

    t("sinh-thuong","자연분만","sinh thường",
      "질을 통해 자연스럽게 출산하는 방법입니다. 통역 시 분만 진행 과정(개구기, 만출기, 후산기)과 호흡법을 안내합니다.",
      "Phương pháp sinh con tự nhiên qua đường âm đạo",
      "산부인과",
      "자연분만의 장점과 과정에 대해 설명합니다. 분만실에서의 통역 시 분만 진행 상황을 명확히 전달합니다.",
      [{"mistake":"통증이 없다고 설명","correction":"진통이 있지만 관리 가능","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"무통분만은 위험하다고 겁줌","correction":"무통분만은 안전하고 효과적","explanation":"선택권을 줍니다"},
       {"mistake":"시간이 짧다고 설명","correction":"개인차가 크고 초산은 더 길 수 있음","explanation":"인내심을 갖게 합니다"}],
      [{"ko":"자궁문이 10cm 열리면 분만이 시작됩니다.","vi":"Khi cổ tử cung mở 10cm sẽ bắt đầu sinh.","situation":"formal"},
       {"ko":"힘을 주세요!","vi":"Rặn đi!","situation":"onsite"},
       {"ko":"자연분만으로 낳았어요.","vi":"Sinh thường.","situation":"informal"}],
      ["진통","무통분만","회음절개"]),

    t("say-thai","유산","sảy thai",
      "임신 20주 이전에 태아를 잃는 것입니다. 통역 시 심리적 지지를 제공하고, 신체 회복과 다음 임신 가능성에 대해 부드럽게 설명합니다.",
      "Mất thai trước tuần thứ 20 của thai kỳ",
      "산부인과",
      "유산은 감정적으로 힘든 경험입니다. 문화적으로 민감하게 접근하고 비난하지 않습니다.",
      [{"mistake":"원인을 묻거나 탓함","correction":"대부분 염색체 이상으로 예방 불가","explanation":"죄책감을 줄입니다"},
       {"mistake":"금방 다시 시도하라고 조언","correction":"신체적, 정서적 회복 시간 필요","explanation":"충분한 휴식을 권합니다"},
       {"mistake":"흔한 일이라고 가볍게 말함","correction":"공감하며 슬픔을 인정","explanation":"환자의 감정을 존중합니다"}],
      [{"ko":"유산 후 충분한 휴식이 필요합니다.","vi":"Sau sảy thai cần nghỉ ngơi đầy đủ.","situation":"formal"},
       {"ko":"몸이 회복되면 다시 임신할 수 있어요.","vi":"Khi cơ thể hồi phục có thể mang thai lại.","situation":"onsite"},
       {"ko":"유산했어요.","vi":"Bị sảy thai.","situation":"informal"}],
      ["소파술","휴식","다음임신"]),

    t("viem-am-dao","질염","viêm âm đạo",
      "질에 염증이 생겨 분비물 증가, 가려움, 냄새가 발생합니다. 통역 시 원인(세균성, 진균성, 트리코모나스)에 따라 치료가 다름을 설명합니다.",
      "Tình trạng viêm âm đạo gây ra tiết dịch, ngứa, mùi hôi",
      "산부인과",
      "질염은 흔한 여성 질환입니다. 부끄러워하지 않도록 격려하고 위생 교육을 합니다.",
      [{"mistake":"성병으로만 생각","correction":"비성병성 질염이 더 흔함","explanation":"낙인을 피합니다"},
       {"mistake":"질 세정을 권유","correction":"과도한 세정은 오히려 해로움","explanation":"정상 균총을 보호합니다"},
       {"mistake":"한 번 치료하면 끝이라고 설명","correction":"재발 가능, 예방법 교육","explanation":"위생 관리가 중요합니다"}],
      [{"ko":"질염 원인 확인을 위해 분비물 검사가 필요합니다.","vi":"Cần xét nghiệm dịch tiết để xác định nguyên nhân viêm âm đạo.","situation":"formal"},
       {"ko":"통풍이 잘 되는 속옷을 입으세요.","vi":"Hãy mặc đồ lót thoáng khí.","situation":"onsite"},
       {"ko":"질염 때문에 가려워요.","vi":"Viêm âm đạo nên ngứa.","situation":"informal"}],
      ["질좌약","항진균제","질세정"]),

    t("lac-noi-mac-tu-cung","자궁내막증","lạc nội mạc tử cung",
      "자궁내막 조직이 자궁 밖에서 자라 통증과 불임을 유발합니다. 통역 시 심한 생리통이 정상이 아닐 수 있음을 설명합니다.",
      "Tình trạng mô nội mạc tử cung phát triển bên ngoài tử cung gây đau và vô sinh",
      "산부인과",
      "자궁내막증은 진단이 늦어지는 경우가 많습니다. 심한 생리통을 가볍게 넘기지 않도록 교육합니다.",
      [{"mistake":"생리통은 당연하다고 설명","correction":"심한 생리통은 질환 징후일 수 있음","explanation":"조기 진단이 중요합니다"},
       {"mistake":"임신하면 낫는다고 설명","correction":"일시적 완화일 수 있음","explanation":"근본 치료가 아닙니다"},
       {"mistake":"수술만 있다고 설명","correction":"호르몬 치료도 효과적","explanation":"단계적 접근이 필요합니다"}],
      [{"ko":"자궁내막증 확인을 위해 초음파와 MRI가 필요합니다.","vi":"Cần siêu âm và MRI để xác nhận lạc nội mạc tử cung.","situation":"formal"},
       {"ko":"생리할 때 너무 아프면 검사받으세요.","vi":"Nếu đau nhiều khi có kinh hãy đi khám.","situation":"onsite"},
       {"ko":"자궁내막증이라 생리통이 심해요.","vi":"Lạc nội mạc tử cung nên đau bụng kinh dữ.","situation":"informal"}],
      ["복강경수술","호르몬치료","불임"]),

    t("u-xo-tu-cung","자궁근종","u xơ tử cung",
      "자궁에 양성 종양(근종)이 생긴 상태입니다. 통역 시 근종은 암이 아니며, 증상에 따라 치료 여부를 결정함을 설명합니다.",
      "Tình trạng có khối u lành tính (u xơ) trong tử cung",
      "산부인과",
      "가임기 여성에서 흔합니다. 근종=암이 아님을 명확히 하여 불필요한 공포를 줄입니다.",
      [{"mistake":"근종이 곧 암이라고 겁줌","correction":"대부분 양성, 암 변화는 드물다","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"작고 증상 없으면 관찰 가능","explanation":"개인화된 접근이 필요합니다"},
       {"mistake":"자궁 전체 제거가 필수라고 설명","correction":"근종만 제거하는 수술도 있음","explanation":"가임력 보존이 가능합니다"}],
      [{"ko":"자궁근종이 있지만 증상이 없으면 관찰할 수 있습니다.","vi":"Có u xơ tử cung nhưng không triệu chứng có thể theo dõi.","situation":"formal"},
       {"ko":"생리량이 너무 많으면 치료가 필요해요.","vi":"Nếu kinh nguyệt quá nhiều cần điều trị.","situation":"onsite"},
       {"ko":"자궁근종 때문에 생리량이 많아요.","vi":"U xơ tử cung nên kinh nguyệt nhiều.","situation":"informal"}],
      ["근종절제술","자궁절제술","색전술"]),

    t("ung-thu-co-tu-cung","자궁경부암","ung thư cổ tử cung",
      "자궁경부에 발생하는 악성 종양으로, HPV 감염이 주요 원인입니다. 통역 시 백신 예방과 정기 검진의 중요성을 강조합니다.",
      "Khối u ác tính phát sinh ở cổ tử cung, nguyên nhân chính là nhiễm HPV",
      "산부인과/종양내과",
      "자궁경부암은 예방 가능한 암입니다. 한국의 무료 검진 프로그램을 안내합니다.",
      [{"mistake":"성생활과 연관지어 비난","correction":"HPV는 매우 흔한 바이러스","explanation":"낙인을 피합니다"},
       {"mistake":"백신이 위험하다고 설명","correction":"HPV 백신은 안전하고 효과적","explanation":"예방 기회를 줍니다"},
       {"mistake":"검진이 아프다고 겁줌","correction":"자궁경부세포검사는 간단함","explanation":"검진 참여를 독려합니다"}],
      [{"ko":"자궁경부암 예방을 위해 2년마다 검진을 받으세요.","vi":"Hãy khám sàng lọc ung thư cổ tử cung 2 năm/lần.","situation":"formal"},
       {"ko":"HPV 백신을 맞으면 예방에 도움돼요.","vi":"Tiêm vắc xin HPV giúp phòng ngừa.","situation":"onsite"},
       {"ko":"자궁경부세포검사 받으러 왔어요.","vi":"Đến làm xét nghiệm tế bào cổ tử cung.","situation":"informal"}],
      ["자궁경부세포검사","HPV백신","원추절제술"]),

    t("man-kinh","폐경","mãn kinh",
      "난소 기능이 저하되어 생리가 영구히 멈추는 상태입니다. 통역 시 폐경 증상(안면홍조, 수면장애)과 호르몬 치료 옵션을 설명합니다.",
      "Tình trạng chức năng buồng trứng giảm, kinh nguyệt ngừng vĩnh viễn",
      "산부인과",
      "폐경은 자연스러운 과정입니다. 증상 관리와 삶의 질 유지에 초점을 맞춥니다.",
      [{"mistake":"폐경을 질병처럼 설명","correction":"정상적인 생리적 과정","explanation":"자연스러운 변화입니다"},
       {"mistake":"호르몬 치료가 위험하다고만 강조","correction":"증상 심하면 도움됨","explanation":"장단점을 설명합니다"},
       {"mistake":"모든 증상이 폐경 탓이라고 설명","correction":"다른 원인 배제 필요","explanation":"종합적 평가가 필요합니다"}],
      [{"ko":"폐경 증상 완화를 위해 호르몬 치료를 고려할 수 있습니다.","vi":"Có thể cân nhắc điều trị hormone để giảm triệu chứng mãn kinh.","situation":"formal"},
       {"ko":"얼굴이 화끈거리면 폐경 증상일 수 있어요.","vi":"Nóng bừng mặt có thể là triệu chứng mãn kinh.","situation":"onsite"},
       {"ko":"폐경이라 잠을 잘 못 자요.","vi":"Mãn kinh nên khó ngủ.","situation":"informal"}],
      ["호르몬대체요법","안면홍조","골다공증예방"]),

    t("vo-sinh","불임","vô sinh",
      "1년 이상 피임 없이 정상적인 성관계를 해도 임신이 되지 않는 상태입니다. 통역 시 남녀 모두 검사가 필요하며, 치료 옵션을 설명합니다.",
      "Tình trạng không thể mang thai sau 1 năm quan hệ tình dục bình thường không tránh thai",
      "산부인과/비뇨의학과",
      "불임은 부부 문제이며 여성만의 책임이 아닙니다. 남성 요인도 중요함을 설명합니다.",
      [{"mistake":"여성만 탓함","correction":"남성 요인이 40% 차지","explanation":"부부 모두 검사가 필요합니다"},
       {"mistake":"스트레스 받지 말라고만 조언","correction":"의학적 원인 평가 필요","explanation":"치료 가능한 원인이 있을 수 있습니다"},
       {"mistake":"체외수정만 있다고 설명","correction":"단계적 치료 접근","explanation":"배란유도, 인공수정부터 시도합니다"}],
      [{"ko":"불임 원인 확인을 위해 부부 모두 검사가 필요합니다.","vi":"Cần xét nghiệm cả hai vợ chồng để tìm nguyên nhân vô sinh.","situation":"formal"},
       {"ko":"먼저 기본 검사를 해보고 치료 방향을 정해요.","vi":"Xét nghiệm cơ bản trước rồi quyết định hướng điều trị.","situation":"onsite"},
       {"ko":"불임이라 시험관 시술 받아요.","vi":"Vô sinh nên đang làm thụ tinh ống nghiệm.","situation":"informal"}],
      ["정액검사","난관조영술","체외수정"]),

    t("sot-tre-em","소아발열","sốt trẻ em",
      "체온이 38도 이상 상승한 상태입니다. 통역 시 발열 자체가 질병이 아닌 면역 반응임을 설명하고, 응급 신호를 교육합니다.",
      "Tình trạng nhiệt độ cơ thể tăng trên 38 độ C ở trẻ em",
      "소아과",
      "보호자가 발열에 공포를 느끼지 않도록 하면서 위험 신호는 명확히 알립니다.",
      [{"mistake":"열 자체를 무조건 위험시","correction":"발열은 정상 면역 반응","explanation":"원인 파악이 더 중요합니다"},
       {"mistake":"해열제로 열이 완전히 내려야 한다고 설명","correction":"편안함이 목표, 완전 해열 불필요","explanation":"과도한 기대를 줄입니다"},
       {"mistake":"열 날 때 목욕시키지 말라고 조언","correction":"미지근한 물 목욕은 도움됨","explanation":"체온 조절에 효과적입니다"}],
      [{"ko":"38.5도 이상이면 해열제를 먹이세요.","vi":"Trên 38.5 độ hãy cho uống thuốc hạ sốt.","situation":"formal"},
       {"ko":"열이 3일 이상 지속되면 다시 오세요.","vi":"Nếu sốt kéo dài hơn 3 ngày hãy đến lại.","situation":"onsite"},
       {"ko":"아이가 열나요.","vi":"Con bị sốt.","situation":"informal"}],
      ["해열제","체온계","수분섭취"]),

    t("tieu-chay-tre-em","소아설사","tiêu chảy trẻ em",
      "하루 3회 이상 묽은 변을 보는 상태입니다. 통역 시 탈수 징후와 경구수액보충의 중요성을 강조합니다.",
      "Tình trạng đi phân lỏng 3 lần trở lên mỗi ngày ở trẻ em",
      "소아과",
      "설사로 인한 탈수가 위험합니다. ORS(경구수액) 사용법을 구체적으로 교육합니다.",
      [{"mistake":"굶기라고 조언","correction":"수분과 영양 공급 계속 필요","explanation":"탈수와 영양 부족 예방"},
       {"mistake":"설사약을 먼저 먹이라고 조언","correction":"지사제는 소아에게 권장 안 함","explanation":"원인 배출을 방해할 수 있습니다"},
       {"mistake":"물만 먹이라고 조언","correction":"ORS가 더 효과적","explanation":"전해질 보충이 중요합니다"}],
      [{"ko":"탈수 예방을 위해 ORS를 조금씩 자주 먹이세요.","vi":"Cho uống ORS ít một, thường xuyên để tránh mất nước.","situation":"formal"},
       {"ko":"소변량이 줄거나 보채면 바로 오세요.","vi":"Nếu tiểu ít hoặc quấy khóc hãy đến ngay.","situation":"onsite"},
       {"ko":"아이가 설사해요.","vi":"Con bị tiêu chảy.","situation":"informal"}],
      ["ORS","탈수","로타바이러스"]),

    t("viem-tai-giua-tre-em","소아중이염","viêm tai giữa trẻ em",
      "소아에서 흔한 중이염으로, 귀 통증, 발열, 보챔이 나타납니다. 통역 시 항생제 완료와 추적 검사의 중요성을 강조합니다.",
      "Viêm tai giữa thường gặp ở trẻ em với đau tai, sốt, quấy khóc",
      "소아과/이비인후과",
      "아이가 귀를 잡아당기거나 밤에 보채면 중이염을 의심합니다.",
      [{"mistake":"항생제 안 써도 된다고 설명","correction":"연령과 중증도에 따라 항생제 필요","explanation":"합병증 예방이 중요합니다"},
       {"mistake":"한 번 걸리면 계속 걸린다고 겁줌","correction":"예방 가능, 대부분 성장하며 줄어듦","explanation":"희망을 줍니다"},
       {"mistake":"완치되면 추적 불필요라고 설명","correction":"삼출성중이염 확인 필요","explanation":"청력 보호가 중요합니다"}],
      [{"ko":"중이염으로 항생제를 7일간 먹여야 합니다.","vi":"Viêm tai giữa cần cho uống kháng sinh 7 ngày.","situation":"formal"},
       {"ko":"2주 후 귀가 다 나았는지 확인하러 오세요.","vi":"2 tuần sau đến kiểm tra tai đã khỏi chưa.","situation":"onsite"},
       {"ko":"아이가 귀 아프대요.","vi":"Con nói đau tai.","situation":"informal"}],
      ["항생제","고막","삼출성중이염"]),

    t("viem-phe-quan-tre-em","소아기관지염","viêm phế quản trẻ em",
      "기관지에 염증이 생겨 기침과 가래가 나타납니다. 통역 시 대부분 바이러스성으로 항생제 불필요함을 설명합니다.",
      "Viêm phế quản gây ho và đờm ở trẻ em",
      "소아과",
      "기침이 오래 가도 대부분 자연 호전됩니다. 불필요한 항생제 사용을 줄이도록 교육합니다.",
      [{"mistake":"항생제를 먼저 요구","correction":"대부분 바이러스성으로 항생제 불필요","explanation":"내성 예방이 중요합니다"},
       {"mistake":"기침약을 많이 먹이라고 조언","correction":"6세 미만은 기침약 권장 안 함","explanation":"효과보다 부작용 우려"},
       {"mistake":"기침 오래 가면 큰 병이라고 겁줌","correction":"2-3주까지 기침 지속 가능","explanation":"자연 경과를 설명합니다"}],
      [{"ko":"바이러스성 기관지염으로 항생제는 필요 없습니다.","vi":"Viêm phế quản do virus không cần kháng sinh.","situation":"formal"},
       {"ko":"방을 가습하고 물을 많이 먹이세요.","vi":"Làm ẩm phòng và cho uống nhiều nước.","situation":"onsite"},
       {"ko":"아이 기침이 안 멈춰요.","vi":"Con ho mãi không ngừng.","situation":"informal"}],
      ["가습기","수분섭취","기침"]),

    t("hen-suyen-tre-em","소아천식","hen suyễn trẻ em",
      "기도가 좁아지고 염증이 생겨 기침, 쌕쌕거림, 호흡곤란이 반복되는 만성 질환입니다. 통역 시 흡입기 사용법과 악화 인자 회피를 교육합니다.",
      "Bệnh mãn tính với đường thở hẹp và viêm gây ho, khò khè, khó thở tái phát",
      "소아과/알레르기내과",
      "흡입기 사용법을 부모가 정확히 알아야 합니다. 스페이서 사용을 권장합니다.",
      [{"mistake":"천식은 평생이라고 낙담시킴","correction":"잘 관리하면 정상 생활 가능","explanation":"희망을 줍니다"},
       {"mistake":"운동 금지라고 조언","correction":"운동 전 예방 흡입으로 운동 가능","explanation":"활동 제한을 최소화합니다"},
       {"mistake":"증상 있을 때만 약 쓰라고 설명","correction":"예방 흡입기는 매일 사용","explanation":"예방이 핵심입니다"}],
      [{"ko":"천식 조절을 위해 매일 흡입기를 사용해야 합니다.","vi":"Để kiểm soát hen cần dùng ống hít mỗi ngày.","situation":"formal"},
       {"ko":"쌕쌕거리면 응급 흡입기를 쓰세요.","vi":"Khi thở khò khè hãy dùng ống hít cấp cứu.","situation":"onsite"},
       {"ko":"아이가 천식이 있어서 흡입기 갖고 다녀요.","vi":"Con bị hen suyễn nên mang theo ống hít.","situation":"informal"}],
      ["스페이서","예방흡입기","응급흡입기"]),

    t("cap-cuu","응급실","cấp cứu",
      "생명이 위급하거나 긴급한 의료 상황에 대응하는 병원 부서입니다. 통역 시 응급 상황의 심각성을 빠르게 전달하고 침착하게 진행합니다.",
      "Khoa bệnh viện đối phó với tình huống y tế khẩn cấp hoặc nguy hiểm tính mạng",
      "응급의학과",
      "응급실에서는 신속한 통역이 중요합니다. 핵심 정보(증상, 시작 시간, 알레르기)를 우선 전달합니다.",
      [{"mistake":"너무 많은 정보를 한꺼번에 전달","correction":"핵심 정보부터 간결하게","explanation":"시간이 중요합니다"},
       {"mistake":"의료진 대신 판단하려 함","correction":"통역에 집중, 판단은 의료진이","explanation":"역할을 구분합니다"},
       {"mistake":"환자나 보호자를 안심시키려 축소 전달","correction":"정확하게 전달해야 적절한 처치 가능","explanation":"정확성이 생명입니다"}],
      [{"ko":"응급실로 가셔야 합니다.","vi":"Phải đến phòng cấp cứu.","situation":"formal"},
       {"ko":"지금 바로 119에 전화하세요.","vi":"Gọi 119 ngay bây giờ.","situation":"onsite"},
       {"ko":"응급실 갔다 왔어요.","vi":"Đi cấp cứu về rồi.","situation":"informal"}],
      ["트리아지","119","응급처치"]),

    t("hoi-sinh-tim-phoi","심폐소생술","hồi sinh tim phổi",
      "심장이 멈췄을 때 가슴압박과 인공호흡으로 혈액순환을 유지하는 응급처치입니다. 통역 시 CPR 절차를 정확히 전달합니다.",
      "Phương pháp sơ cứu ép ngực và thổi ngạt để duy trì tuần hoàn máu khi tim ngừng đập",
      "응급의학과",
      "CPR 교육의 중요성을 알리고, 한국에서의 응급처치 방법을 교육합니다.",
      [{"mistake":"전문가만 할 수 있다고 설명","correction":"일반인도 가슴압박 CPR 가능","explanation":"행동이 생명을 살립니다"},
       {"mistake":"인공호흡 필수라고 설명","correction":"가슴압박만으로도 효과","explanation":"행동을 망설이지 않게 합니다"},
       {"mistake":"AED 사용이 어렵다고 겁줌","correction":"AED는 음성 안내를 따르면 됨","explanation":"사용을 독려합니다"}],
      [{"ko":"119에 전화하고 바로 가슴압박을 시작하세요.","vi":"Gọi 119 và bắt đầu ép ngực ngay.","situation":"formal"},
       {"ko":"분당 100-120회 빠르게 눌러요!","vi":"Ép nhanh 100-120 lần/phút!","situation":"onsite"},
       {"ko":"CPR 배웠어요.","vi":"Đã học hồi sinh tim phổi.","situation":"informal"}],
      ["가슴압박","AED","119"]),

    t("soc-phan-ve","아나필락시스","sốc phản vệ",
      "심한 알레르기 반응으로 호흡곤란, 혈압 저하, 의식 저하가 발생하는 생명을 위협하는 응급상황입니다. 통역 시 에피네프린 주사의 중요성을 강조합니다.",
      "Phản ứng dị ứng nghiêm trọng gây khó thở, hạ huyết áp, mất ý thức, đe dọa tính mạng",
      "응급의학과/알레르기내과",
      "아나필락시스는 수분 내 생명을 위협합니다. 에피펜 사용법을 교육합니다.",
      [{"mistake":"항히스타민제로 충분하다고 설명","correction":"에피네프린이 필수","explanation":"항히스타민만으로는 부족합니다"},
       {"mistake":"가벼운 알레르기로 치부","correction":"아나필락시스는 응급 상황","explanation":"즉시 119 호출이 필요합니다"},
       {"mistake":"한 번 주사하면 끝이라고 설명","correction":"증상 재발 가능, 관찰 필요","explanation":"병원 이송이 필수입니다"}],
      [{"ko":"아나필락시스 응급으로 에피네프린 주사가 필요합니다.","vi":"Cấp cứu sốc phản vệ cần tiêm epinephrine.","situation":"formal"},
       {"ko":"숨이 막히고 온몸에 두드러기가 나면 바로 119에 연락하세요.","vi":"Nếu nghẹt thở và nổi mẩn khắp người hãy gọi 119 ngay.","situation":"onsite"},
       {"ko":"땅콩 먹고 아나필락시스 왔어요.","vi":"Ăn đậu phộng bị sốc phản vệ.","situation":"informal"}],
      ["에피네프린","에피펜","알레르기"]),

    t("bong","화상","bỏng",
      "열, 화학물질, 전기 등으로 피부가 손상된 상태입니다. 통역 시 화상 정도(1-3도)와 응급처치(흐르는 찬물)를 설명합니다.",
      "Tình trạng da bị tổn thương do nhiệt, hóa chất, điện",
      "응급의학과/성형외과",
      "산업 현장에서 화상이 발생할 수 있습니다. 올바른 응급처치와 산재 처리를 안내합니다.",
      [{"mistake":"얼음을 직접 대라고 조언","correction":"흐르는 미지근한 물이 좋음","explanation":"얼음은 조직 손상 유발"},
       {"mistake":"물집을 터뜨리라고 조언","correction":"물집은 보호막 역할","explanation":"감염 위험이 있습니다"},
       {"mistake":"연고를 바르라고 조언","correction":"깨끗한 천으로 덮고 병원으로","explanation":"집에서의 처치를 최소화합니다"}],
      [{"ko":"화상 부위를 흐르는 물에 10-20분 식히세요.","vi":"Làm mát chỗ bỏng dưới vòi nước 10-20 phút.","situation":"formal"},
       {"ko":"물집을 터뜨리지 마세요.","vi":"Đừng chọc vỡ bọng nước.","situation":"onsite"},
       {"ko":"뜨거운 물에 화상 입었어요.","vi":"Bị bỏng nước nóng.","situation":"informal"}],
      ["응급처치","피부이식","흉터관리"]),

    t("gay-xuong-tre-em","소아골절","gãy xương trẻ em",
      "어린이의 뼈가 부러진 상태입니다. 통역 시 소아 뼈는 성장판이 있어 성인과 치료가 다를 수 있음을 설명합니다.",
      "Tình trạng gãy xương ở trẻ em",
      "소아정형외과",
      "성장판 손상 여부가 중요합니다. 정기 추적의 필요성을 설명합니다.",
      [{"mistake":"성인과 같은 치료라고 설명","correction":"성장판 고려 필요","explanation":"성장 장애 예방이 중요합니다"},
       {"mistake":"깁스하면 다 낫는다고만 설명","correction":"성장판 손상 시 추적 필요","explanation":"장기 관찰이 필요할 수 있습니다"},
       {"mistake":"활동 제한 없다고 설명","correction":"뼈가 붙을 때까지 활동 제한","explanation":"재손상 예방이 중요합니다"}],
      [{"ko":"성장판 손상 여부 확인을 위해 X-ray가 필요합니다.","vi":"Cần chụp X-quang để kiểm tra có tổn thương sụn tăng trưởng không.","situation":"formal"},
       {"ko":"깁스 기간 동안 뛰거나 심하게 움직이지 마세요.","vi":"Trong thời gian bó bột không chạy nhảy.","situation":"onsite"},
       {"ko":"아이가 팔이 부러졌어요.","vi":"Con bị gãy tay.","situation":"informal"}],
      ["성장판","깁스","소아정형외과"]),

    t("dau-bung-cap","급성복통","đau bụng cấp",
      "갑자기 발생한 심한 복통으로, 응급 수술이 필요할 수 있습니다. 통역 시 통증 위치, 양상, 동반 증상을 정확히 전달합니다.",
      "Đau bụng dữ dội xảy ra đột ngột, có thể cần phẫu thuật cấp cứu",
      "응급의학과/외과",
      "급성복통은 다양한 원인이 있습니다. 핵심 정보를 신속히 전달하여 진단에 도움을 줍니다.",
      [{"mistake":"진통제 먹고 지켜보라고 조언","correction":"원인 확인 전 진통제는 증상을 가릴 수 있음","explanation":"진단 지연 위험"},
       {"mistake":"모든 복통을 가볍게 여김","correction":"일부는 응급 수술 필요","explanation":"심각한 원인을 놓칠 수 있습니다"},
       {"mistake":"통증 위치만 확인","correction":"방사통, 동반 증상도 중요","explanation":"진단에 도움이 됩니다"}],
      [{"ko":"급성복통으로 CT 검사가 필요합니다.","vi":"Đau bụng cấp cần chụp CT.","situation":"formal"},
       {"ko":"언제부터 아프기 시작했어요?","vi":"Bắt đầu đau từ khi nào?","situation":"onsite"},
       {"ko":"배가 갑자기 너무 아파요.","vi":"Bụng đau đột ngột dữ lắm.","situation":"informal"}],
      ["복부CT","응급수술","복막자극증상"]),

    t("mat-mau-cap","급성출혈","mất máu cấp",
      "갑자기 다량의 피를 잃어 쇼크가 발생할 수 있는 응급상황입니다. 통역 시 출혈 부위 압박과 119 호출을 안내합니다.",
      "Tình trạng cấp cứu mất nhiều máu đột ngột có thể gây sốc",
      "응급의학과/외과",
      "산업 재해로 출혈이 발생할 수 있습니다. 지혈법과 응급 대응을 교육합니다.",
      [{"mistake":"지혈대를 느슨하게 묶음","correction":"강하게 압박해야 효과","explanation":"생명이 우선입니다"},
       {"mistake":"출혈이 멈출 때까지 기다림","correction":"압박하면서 119 호출","explanation":"동시 행동이 필요합니다"},
       {"mistake":"상처 부위를 물로 씻으라고 조언","correction":"압박 지혈이 우선","explanation":"감염보다 출혈 조절이 먼저"}],
      [{"ko":"출혈 부위를 깨끗한 천으로 강하게 누르세요.","vi":"Ép mạnh chỗ chảy máu bằng vải sạch.","situation":"formal"},
       {"ko":"119 부르고 계속 눌러요!","vi":"Gọi 119 và tiếp tục ép!","situation":"onsite"},
       {"ko":"피가 많이 나요.","vi":"Chảy máu nhiều lắm.","situation":"informal"}],
      ["지혈","수혈","쇼크"]),

    t("ngo-doc","중독","ngộ độc",
      "유해 물질을 섭취, 흡입, 접촉하여 신체에 해로운 영향이 발생합니다. 통역 시 물질 종류 확인과 응급 조치를 안내합니다.",
      "Tình trạng cơ thể bị ảnh hưởng có hại khi ăn, hít hoặc tiếp xúc với chất độc hại",
      "응급의학과",
      "산업 현장의 화학물질 노출이나 약물 과량 섭취 등 다양한 원인이 있습니다.",
      [{"mistake":"토하게 만들라고 조언","correction":"부식성 물질은 토하면 더 위험","explanation":"물질에 따라 대응이 다릅니다"},
       {"mistake":"물을 많이 마시라고 조언","correction":"일부 물질은 물과 반응","explanation":"전문가 지시를 따릅니다"},
       {"mistake":"용기를 버리라고 조언","correction":"용기를 가져가면 진단에 도움","explanation":"성분 확인이 중요합니다"}],
      [{"ko":"무엇을 먹었는지, 용기를 가져오세요.","vi":"Đã ăn gì, mang theo hộp đựng.","situation":"formal"},
       {"ko":"119에 전화해서 무엇을 먹었는지 말해요.","vi":"Gọi 119 và nói đã ăn gì.","situation":"onsite"},
       {"ko":"세제를 잘못 마셨어요.","vi":"Lỡ uống nhầm chất tẩy rửa.","situation":"informal"}],
      ["해독제","위세척","독극물정보센터"]),

    t("benh-truyen-nhiem","감염병","bệnh truyền nhiễm",
      "세균, 바이러스 등 병원체가 사람 간에 전파되는 질병입니다. 통역 시 전파 경로, 예방법, 격리 필요성을 설명합니다.",
      "Bệnh do vi khuẩn, virus lây truyền giữa người với người",
      "감염내과",
      "감염병은 공중보건 문제입니다. 집단 생활 환경에서의 예방을 강조합니다.",
      [{"mistake":"낙인을 유발하는 표현 사용","correction":"질병을 가진 사람을 비난하지 않음","explanation":"차별 없는 표현이 중요합니다"},
       {"mistake":"격리를 형벌처럼 설명","correction":"격리는 전파 차단을 위한 조치","explanation":"목적을 설명합니다"},
       {"mistake":"예방법을 강요하듯 전달","correction":"협조를 부탁하는 방식으로","explanation":"자발적 참여가 효과적입니다"}],
      [{"ko":"감염병 전파 방지를 위해 격리가 필요합니다.","vi":"Cần cách ly để ngăn lây lan bệnh truyền nhiễm.","situation":"formal"},
       {"ko":"손을 자주 씻고 마스크를 착용하세요.","vi":"Rửa tay thường xuyên và đeo khẩu trang.","situation":"onsite"},
       {"ko":"감염병이라 집에서 쉬어야 해요.","vi":"Bệnh truyền nhiễm nên phải nghỉ ở nhà.","situation":"informal"}],
      ["격리","검역","예방접종"]),

    t("tiem-chung","예방접종","tiêm chủng",
      "백신을 투여하여 특정 감염병에 대한 면역을 형성하는 예방 조치입니다. 통역 시 접종 일정과 부작용에 대해 설명합니다.",
      "Biện pháp phòng ngừa tiêm vắc xin để tạo miễn dịch với bệnh truyền nhiễm",
      "가정의학과/소아과",
      "한국의 예방접종 일정과 무료 접종 프로그램을 안내합니다.",
      [{"mistake":"백신이 100% 효과라고 설명","correction":"높은 예방 효과지만 100%는 아님","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"부작용을 숨김","correction":"경미한 부작용은 정상 면역 반응","explanation":"투명하게 설명합니다"},
       {"mistake":"백신이 위험하다고 과장","correction":"이점이 위험보다 훨씬 큼","explanation":"근거 기반 정보를 제공합니다"}],
      [{"ko":"예방접종 후 접종 부위가 붓거나 열이 날 수 있어요.","vi":"Sau tiêm chỗ tiêm có thể sưng hoặc sốt.","situation":"formal"},
       {"ko":"오늘 독감 백신 맞으러 오셨네요.","vi":"Hôm nay đến tiêm vắc xin cúm.","situation":"onsite"},
       {"ko":"아이 예방접종하러 왔어요.","vi":"Đến tiêm chủng cho con.","situation":"informal"}],
      ["백신","면역","접종일정"]),

    t("nhiem-khuan-huyet","패혈증","nhiễm khuẩn huyết",
      "감염에 대한 면역 반응이 과도하여 장기 손상이 발생하는 생명을 위협하는 상태입니다. 통역 시 조기 인지와 신속한 치료의 중요성을 강조합니다.",
      "Tình trạng đe dọa tính mạng khi phản ứng miễn dịch với nhiễm trùng gây tổn thương cơ quan",
      "감염내과/중환자의학과",
      "패혈증은 빠르게 악화됩니다. 조기 발견과 치료가 생존에 필수적입니다.",
      [{"mistake":"단순 감염으로 치부","correction":"패혈증은 응급 상황","explanation":"시간이 생명입니다"},
       {"mistake":"항생제만 쓰면 된다고 설명","correction":"수액, 장기 지지 등 복합 치료 필요","explanation":"집중치료가 필요합니다"},
       {"mistake":"회복 시간을 짧게 예상","correction":"중환자실 치료가 오래 걸릴 수 있음","explanation":"현실적 기대를 설정합니다"}],
      [{"ko":"패혈증 의심으로 집중치료실 입원이 필요합니다.","vi":"Nghi ngờ nhiễm khuẩn huyết cần nhập ICU.","situation":"formal"},
       {"ko":"열이 나면서 혈압이 떨어지면 바로 오세요.","vi":"Sốt kèm huyết áp tụt hãy đến ngay.","situation":"onsite"},
       {"ko":"패혈증으로 중환자실에 있어요.","vi":"Nhiễm khuẩn huyết nên đang ở ICU.","situation":"informal"}],
      ["중환자실","항생제","승압제"]),

    t("xet-nghiem-mau","혈액검사","xét nghiệm máu",
      "혈액을 채취하여 건강 상태와 질병을 진단하는 검사입니다. 통역 시 공복 필요 여부, 검사 항목을 설명합니다.",
      "Xét nghiệm lấy máu để chẩn đoán tình trạng sức khỏe và bệnh",
      "진단검사의학과",
      "혈액검사는 가장 기본적인 검사입니다. 검사 전 준비사항을 안내합니다.",
      [{"mistake":"모든 검사가 공복 필요하다고 설명","correction":"일부만 공복 필요","explanation":"검사에 따라 다릅니다"},
       {"mistake":"결과가 바로 나온다고 설명","correction":"검사에 따라 수일 소요","explanation":"기다림이 필요할 수 있습니다"},
       {"mistake":"정상 수치를 환자에게 직접 설명","correction":"의사 상담 후 설명","explanation":"해석은 전문가가 합니다"}],
      [{"ko":"혈액검사를 위해 8시간 공복이 필요합니다.","vi":"Cần nhịn ăn 8 tiếng để xét nghiệm máu.","situation":"formal"},
       {"ko":"결과는 3일 후에 나와요.","vi":"Kết quả có sau 3 ngày.","situation":"onsite"},
       {"ko":"피검사 받으러 왔어요.","vi":"Đến xét nghiệm máu.","situation":"informal"}],
      ["채혈","공복","정상수치"]),

    t("sieu-am","초음파검사","siêu âm",
      "초음파를 이용하여 체내 장기를 영상으로 확인하는 검사입니다. 통역 시 검사 부위에 따른 준비(물 마시기, 금식)를 안내합니다.",
      "Xét nghiệm dùng siêu âm để kiểm tra hình ảnh các cơ quan trong cơ thể",
      "영상의학과",
      "초음파는 방사선 노출 없이 안전한 검사입니다. 임산부 검사에도 사용됩니다.",
      [{"mistake":"방사선 노출이 있다고 설명","correction":"초음파는 방사선 없음","explanation":"안전한 검사임을 알립니다"},
       {"mistake":"준비가 필요 없다고 설명","correction":"검사 부위에 따라 준비 필요","explanation":"정확한 안내가 필요합니다"},
       {"mistake":"모든 것을 볼 수 있다고 설명","correction":"일부 부위는 다른 검사 필요","explanation":"한계가 있음을 알립니다"}],
      [{"ko":"복부 초음파를 위해 6시간 금식이 필요합니다.","vi":"Cần nhịn ăn 6 tiếng để siêu âm bụng.","situation":"formal"},
       {"ko":"방광 초음파를 위해 물을 많이 드세요.","vi":"Uống nhiều nước để siêu âm bàng quang.","situation":"onsite"},
       {"ko":"초음파 검사 받으러 왔어요.","vi":"Đến siêu âm.","situation":"informal"}],
      ["젤","금식","영상"]),

    t("chup-ct","CT검사","chụp CT",
      "X선을 이용하여 체내 단면 영상을 얻는 검사입니다. 통역 시 조영제 사용 여부와 알레르기 확인을 안내합니다.",
      "Xét nghiệm dùng tia X để chụp hình ảnh cắt lớp trong cơ thể",
      "영상의학과",
      "CT는 정밀한 진단에 유용합니다. 조영제 사용 시 주의사항을 설명합니다.",
      [{"mistake":"방사선 노출 위험만 강조","correction":"진단 이점이 위험보다 큼","explanation":"필요한 검사임을 설명합니다"},
       {"mistake":"조영제 알레르기 확인 안 함","correction":"과거 알레르기 여부 반드시 확인","explanation":"안전이 우선입니다"},
       {"mistake":"금식 필요 없다고 설명","correction":"조영제 사용 시 금식 필요","explanation":"정확한 준비가 필요합니다"}],
      [{"ko":"CT 검사를 위해 조영제 주사가 필요합니다.","vi":"Cần tiêm thuốc cản quang để chụp CT.","situation":"formal"},
       {"ko":"알레르기가 있으신가요?","vi":"Có bị dị ứng gì không?","situation":"onsite"},
       {"ko":"CT 찍으러 왔어요.","vi":"Đến chụp CT.","situation":"informal"}],
      ["조영제","방사선","단면영상"]),

    t("chup-mri","MRI검사","chụp MRI",
      "자기장을 이용하여 체내 상세 영상을 얻는 검사입니다. 통역 시 금속물 제거와 폐소공포증 확인을 안내합니다.",
      "Xét nghiệm dùng từ trường để chụp hình ảnh chi tiết trong cơ thể",
      "영상의학과",
      "MRI는 방사선 없이 상세한 영상을 얻습니다. 금속 확인이 필수입니다.",
      [{"mistake":"CT와 같은 검사라고 설명","correction":"원리와 적응증이 다름","explanation":"각 검사의 장점이 있습니다"},
       {"mistake":"금속 확인 안 함","correction":"심박조율기, 금속 임플란트 확인 필수","explanation":"안전 문제가 있습니다"},
       {"mistake":"시간이 짧다고 설명","correction":"30분-1시간 소요","explanation":"인내심이 필요합니다"}],
      [{"ko":"MRI 검사 중에는 움직이지 마세요.","vi":"Trong khi chụp MRI không được di chuyển.","situation":"formal"},
       {"ko":"몸에 금속이 있으면 말씀해 주세요.","vi":"Nếu có kim loại trong người hãy nói.","situation":"onsite"},
       {"ko":"MRI 찍으러 왔어요.","vi":"Đến chụp MRI.","situation":"informal"}],
      ["자기장","금속제거","조영제"]),

    t("noi-soi","내시경검사","nội soi",
      "카메라가 달린 관을 체내에 삽입하여 직접 관찰하는 검사입니다. 통역 시 검사 종류(위/대장)에 따른 준비를 안내합니다.",
      "Xét nghiệm đưa ống có camera vào cơ thể để quan sát trực tiếp",
      "소화기내과",
      "내시경은 직접 관찰과 조직검사가 가능합니다. 장 정결의 중요성을 강조합니다.",
      [{"mistake":"수면 내시경이 위험하다고 겁줌","correction":"안전하고 편안함","explanation":"선택권을 줍니다"},
       {"mistake":"장 정결을 가볍게 설명","correction":"철저한 장 정결이 검사 품질 결정","explanation":"정확한 안내가 필요합니다"},
       {"mistake":"검사 후 바로 운전 가능하다고 설명","correction":"수면 내시경 후 운전 금지","explanation":"안전 주의사항을 알립니다"}],
      [{"ko":"위내시경을 위해 8시간 금식이 필요합니다.","vi":"Cần nhịn ăn 8 tiếng để nội soi dạ dày.","situation":"formal"},
       {"ko":"장 정결제를 시간 맞춰 드세요.","vi":"Uống thuốc xổ đúng giờ.","situation":"onsite"},
       {"ko":"위내시경 받으러 왔어요.","vi":"Đến nội soi dạ dày.","situation":"informal"}],
      ["수면내시경","장정결","조직검사"]),

    t("sinh-thiet","조직검사","sinh thiết",
      "조직 일부를 채취하여 현미경으로 관찰하는 검사입니다. 통역 시 암 확진에 필요한 중요한 검사임을 설명합니다.",
      "Xét nghiệm lấy một phần mô để quan sát dưới kính hiển vi",
      "병리과",
      "조직검사는 확진에 필수입니다. 결과가 나오기까지 시간이 걸림을 안내합니다.",
      [{"mistake":"조직검사가 암을 확산시킨다고 설명","correction":"과학적 근거 없는 우려","explanation":"오해를 바로잡습니다"},
       {"mistake":"바로 결과가 나온다고 설명","correction":"보통 1주일 정도 소요","explanation":"기다림이 필요합니다"},
       {"mistake":"조직검사만으로 모든 것을 알 수 있다고 설명","correction":"추가 검사 필요할 수 있음","explanation":"종합적 판단이 필요합니다"}],
      [{"ko":"조직검사 결과는 1주일 후에 나옵니다.","vi":"Kết quả sinh thiết có sau 1 tuần.","situation":"formal"},
       {"ko":"조직검사 부위를 깨끗하게 유지하세요.","vi":"Giữ sạch chỗ sinh thiết.","situation":"onsite"},
       {"ko":"조직검사 결과 나왔어요?","vi":"Kết quả sinh thiết có chưa?","situation":"informal"}],
      ["병리과","현미경","암진단"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
