#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch K - 마지막 35개 (500개 도달)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("buon-non","구역/메스꺼움","buồn nôn",
      "토할 것 같은 불쾌한 느낌입니다. 통역 시 동반 증상(구토, 복통)과 원인 가능성을 확인합니다.",
      "Cảm giác khó chịu như muốn nôn",
      "소화기내과",
      "구역의 원인은 다양합니다. 임신 가능성도 고려합니다.",
      [{"mistake":"무조건 위장 문제라고 설명","correction":"다양한 원인 가능(전정, 약물, 임신 등)","explanation":"종합적 평가 필요"},
       {"mistake":"항구토제를 먼저 권유","correction":"원인 확인이 우선","explanation":"근본 치료가 중요합니다"},
       {"mistake":"가임기 여성에서 임신 가능성 확인 안 함","correction":"마지막 생리일 확인","explanation":"임신초기 증상일 수 있습니다"}],
      [{"ko":"구역감이 언제부터 있었나요?","vi":"Buồn nôn từ khi nào?","situation":"formal"},
       {"ko":"임신 가능성이 있나요?","vi":"Có khả năng mang thai không?","situation":"onsite"},
       {"ko":"속이 메스꺼워요.","vi":"Buồn nôn.","situation":"informal"}],
      ["구토","위장약","임신"]),

    t("non","구토","nôn",
      "위 내용물을 입으로 내보내는 것입니다. 통역 시 구토 양상과 횟수, 탈수 징후를 확인합니다.",
      "Đưa chất trong dạ dày ra ngoài qua miệng",
      "소화기내과/응급",
      "구토가 심하면 탈수가 발생할 수 있어 수분 섭취가 중요합니다.",
      [{"mistake":"먹으면 안 된다고만 설명","correction":"소량씩 자주 수분 섭취","explanation":"탈수 예방이 중요합니다"},
       {"mistake":"구토 색깔 확인 안 함","correction":"혈액 섞인 구토는 응급","explanation":"위험 신호를 파악합니다"},
       {"mistake":"모든 구토에 항구토제 권유","correction":"원인에 따라 치료","explanation":"근본 치료가 필요합니다"}],
      [{"ko":"구토를 몇 번 하셨나요?","vi":"Đã nôn mấy lần?","situation":"formal"},
       {"ko":"피가 섞여 나왔나요?","vi":"Có lẫn máu không?","situation":"onsite"},
       {"ko":"토했어요.","vi":"Đã nôn.","situation":"informal"}],
      ["탈수","항구토제","위장염"]),

    t("tieu-chay","설사","tiêu chảy",
      "묽은 변을 자주 보는 상태입니다. 통역 시 설사 횟수, 양상, 탈수 징후를 확인합니다.",
      "Tình trạng đi phân lỏng nhiều lần",
      "소화기내과",
      "설사의 원인 확인과 탈수 예방이 중요합니다.",
      [{"mistake":"지사제를 먼저 권유","correction":"원인에 따라 지사제가 해로울 수 있음","explanation":"감염성은 배출이 필요할 수 있습니다"},
       {"mistake":"굶기라고 조언","correction":"수분과 영양 공급 필요","explanation":"탈수와 영양 부족 예방"},
       {"mistake":"혈변 확인 안 함","correction":"혈변은 심각한 징후","explanation":"즉시 진료가 필요합니다"}],
      [{"ko":"하루에 몇 번 화장실을 가세요?","vi":"Đi vệ sinh mấy lần một ngày?","situation":"formal"},
       {"ko":"물이나 ORS를 자주 드세요.","vi":"Uống nước hoặc ORS thường xuyên.","situation":"onsite"},
       {"ko":"설사가 심해요.","vi":"Tiêu chảy nhiều.","situation":"informal"}],
      ["ORS","탈수","위장염"]),

    t("tao-bon2","변비","táo bón",
      "배변이 어렵거나 횟수가 적은 상태입니다. 통역 시 배변 습관과 생활습관을 확인합니다.",
      "Tình trạng khó đi đại tiện hoặc ít lần",
      "소화기내과",
      "수분과 섬유질 섭취, 운동의 중요성을 강조합니다.",
      [{"mistake":"하제만 권유","correction":"생활습관 교정이 우선","explanation":"근본 원인 해결이 중요합니다"},
       {"mistake":"매일 배변해야 한다고 설명","correction":"2-3일에 한 번도 정상일 수 있음","explanation":"개인차가 있습니다"},
       {"mistake":"관장을 자주 하라고 권유","correction":"관장 의존성 주의","explanation":"장기적으로 해로울 수 있습니다"}],
      [{"ko":"물을 충분히 드시고 섬유질을 많이 드세요.","vi":"Uống đủ nước và ăn nhiều chất xơ.","situation":"formal"},
       {"ko":"변비약은 의사 상담 후 드세요.","vi":"Uống thuốc táo bón sau khi hỏi bác sĩ.","situation":"onsite"},
       {"ko":"변비가 있어요.","vi":"Bị táo bón.","situation":"informal"}],
      ["섬유질","수분","완하제"]),

    t("kho-tho","호흡곤란","khó thở",
      "숨쉬기가 어려운 상태입니다. 통역 시 호흡곤란의 정도, 시작 시점, 악화 요인을 정확히 전달합니다.",
      "Tình trạng khó thở",
      "호흡기내과/응급",
      "호흡곤란은 응급 상황일 수 있습니다. 심각도를 빠르게 평가합니다.",
      [{"mistake":"가볍게 여김","correction":"심각한 질환의 신호일 수 있음","explanation":"빠른 평가가 필요합니다"},
       {"mistake":"원인 확인 없이 안심시킴","correction":"원인 파악이 중요","explanation":"폐, 심장, 빈혈 등 다양한 원인"},
       {"mistake":"휴식만 권유","correction":"원인에 따라 응급 치료 필요","explanation":"산소 공급이 필요할 수 있습니다"}],
      [{"ko":"숨쉬기가 힘드세요? 언제부터요?","vi":"Khó thở không? Từ khi nào?","situation":"formal"},
       {"ko":"앉아서 숨 쉬는 게 편하세요?","vi":"Ngồi thở có dễ hơn không?","situation":"onsite"},
       {"ko":"숨이 차요.","vi":"Khó thở.","situation":"informal"}],
      ["산소포화도","폐기능","심부전"]),

    t("dau-nguc","흉통","đau ngực",
      "가슴 부위의 통증입니다. 통역 시 통증 양상, 방사통, 동반 증상을 정확히 전달합니다.",
      "Đau ở vùng ngực",
      "순환기내과/응급",
      "흉통은 심장 문제의 신호일 수 있어 응급 평가가 필요합니다.",
      [{"mistake":"소화불량으로만 생각","correction":"심근경색 가능성 고려","explanation":"응급 상황일 수 있습니다"},
       {"mistake":"위치 확인 안 함","correction":"정확한 위치가 진단에 중요","explanation":"심장, 폐, 식도 등 구분"},
       {"mistake":"쉬면 낫는다고만 조언","correction":"지속되면 즉시 응급실","explanation":"시간이 생명입니다"}],
      [{"ko":"가슴 통증이 어디로 퍼지나요?","vi":"Đau ngực lan ra đâu không?","situation":"formal"},
       {"ko":"식은땀이 나거나 구역질이 있나요?","vi":"Có đổ mồ hôi lạnh hoặc buồn nôn không?","situation":"onsite"},
       {"ko":"가슴이 아파요.","vi":"Đau ngực.","situation":"informal"}],
      ["심전도","심근경색","협심증"]),

    t("dau-dau2","두통","đau đầu",
      "머리가 아픈 상태입니다. 통역 시 두통 양상, 위치, 동반 증상을 확인합니다.",
      "Đau đầu",
      "신경과",
      "두통의 원인은 다양합니다. 위험 신호(갑작스러운 극심한 두통)를 확인합니다.",
      [{"mistake":"일반 두통약만 권유","correction":"원인에 따라 치료 다름","explanation":"편두통, 긴장성 등 구분 필요"},
       {"mistake":"위험 신호 확인 안 함","correction":"갑자기 최악의 두통은 응급","explanation":"뇌출혈 가능성"},
       {"mistake":"스트레스 탓으로만 돌림","correction":"다양한 원인 고려","explanation":"종합 평가 필요"}],
      [{"ko":"두통이 어떤 식으로 아프세요?","vi":"Đau đầu như thế nào?","situation":"formal"},
       {"ko":"갑자기 지금까지 경험한 것 중 가장 심한 두통인가요?","vi":"Đây có phải là cơn đau đầu dữ dội nhất chưa từng có không?","situation":"onsite"},
       {"ko":"머리가 아파요.","vi":"Đau đầu.","situation":"informal"}],
      ["편두통","긴장성두통","진통제"]),

    t("phu","부종","phù",
      "신체 일부가 부어오른 상태입니다. 통역 시 부종 위치, 시작 시점, 양측성 여부를 확인합니다.",
      "Tình trạng một phần cơ thể bị sưng lên",
      "내과",
      "부종은 다양한 원인(심장, 신장, 간, 혈관)이 있습니다.",
      [{"mistake":"단순 피로로 치부","correction":"심각한 질환의 신호일 수 있음","explanation":"원인 확인 필요"},
       {"mistake":"한쪽만 부은 것을 무시","correction":"한쪽 부종은 혈전 가능성","explanation":"응급 상황일 수 있습니다"},
       {"mistake":"다리 올려놓기만 권유","correction":"원인 치료가 중요","explanation":"근본 해결이 필요합니다"}],
      [{"ko":"언제부터 부었나요?","vi":"Sưng từ khi nào?","situation":"formal"},
       {"ko":"양쪽 다리 다 부었나요?","vi":"Cả hai chân đều sưng à?","situation":"onsite"},
       {"ko":"다리가 부었어요.","vi":"Chân bị sưng.","situation":"informal"}],
      ["심부전","신부전","정맥부전"]),

    t("phat-ban","발진","phát ban",
      "피부에 붉은 반점이나 두드러기가 생긴 상태입니다. 통역 시 발진 양상, 가려움 여부, 전신 증상을 확인합니다.",
      "Tình trạng da nổi đốm đỏ hoặc mề đay",
      "피부과/알레르기내과",
      "발진은 알레르기, 감염, 약물 반응 등 다양한 원인이 있습니다.",
      [{"mistake":"단순 피부 문제로만 치부","correction":"전신 질환의 피부 증상일 수 있음","explanation":"종합 평가 필요"},
       {"mistake":"약물 복용력 확인 안 함","correction":"약물 알레르기 가능성 확인","explanation":"원인 약물 중단 필요할 수 있습니다"},
       {"mistake":"알레르기 반응 심각성 무시","correction":"아나필락시스로 진행 가능","explanation":"호흡곤란 동반 시 응급"}],
      [{"ko":"언제부터 발진이 생겼나요?","vi":"Phát ban từ khi nào?","situation":"formal"},
       {"ko":"새로 먹기 시작한 약이 있나요?","vi":"Có thuốc mới bắt đầu uống không?","situation":"onsite"},
       {"ko":"피부에 뭐가 났어요.","vi":"Da nổi gì đó.","situation":"informal"}],
      ["두드러기","약물알레르기","감염"]),

    t("ngua","가려움","ngứa",
      "피부를 긁고 싶은 느낌입니다. 통역 시 가려움 위치, 발진 동반 여부, 원인 가능성을 확인합니다.",
      "Cảm giác muốn gãi da",
      "피부과",
      "가려움의 원인은 피부 질환뿐 아니라 전신 질환도 있을 수 있습니다.",
      [{"mistake":"긁으라고 조언","correction":"긁으면 악화, 냉찜질이나 약 사용","explanation":"이차 감염 예방"},
       {"mistake":"피부 문제로만 생각","correction":"간, 신장 질환도 가려움 유발","explanation":"전신 검사 필요할 수 있습니다"},
       {"mistake":"보습제만 권유","correction":"원인에 따라 치료 다름","explanation":"진단이 중요합니다"}],
      [{"ko":"어디가 가려우세요?","vi":"Ngứa ở đâu?","situation":"formal"},
       {"ko":"긁지 말고 냉찜질 해보세요.","vi":"Đừng gãi, thử chườm lạnh.","situation":"onsite"},
       {"ko":"가려워요.","vi":"Bị ngứa.","situation":"informal"}],
      ["항히스타민제","보습제","피부질환"]),

    t("mat-y-thuc","의식저하","mất ý thức",
      "의식이 흐려지거나 없어진 상태입니다. 통역 시 의식 수준, 호흡, 맥박을 빠르게 확인합니다.",
      "Tình trạng ý thức mờ hoặc mất",
      "응급의학과",
      "의식저하는 응급 상황입니다. 즉시 도움을 요청합니다.",
      [{"mistake":"가볍게 여김","correction":"생명을 위협하는 응급","explanation":"즉각 대응 필요"},
       {"mistake":"깨우려고 흔듦","correction":"기도 확보와 119 호출이 우선","explanation":"안전 확보가 먼저"},
       {"mistake":"물을 먹이려 함","correction":"의식 없을 때 물 먹이면 위험","explanation":"흡인 위험"}],
      [{"ko":"의식이 없습니다. 119에 전화하세요!","vi":"Bất tỉnh. Gọi 119!","situation":"formal"},
       {"ko":"숨 쉬고 있나요?","vi":"Còn thở không?","situation":"onsite"},
       {"ko":"기절했어요.","vi":"Bị ngất.","situation":"informal"}],
      ["119","기도확보","CPR"]),

    t("co-giat2","경련/발작","co giật",
      "근육이 불수의적으로 수축하는 상태입니다. 통역 시 발작 양상, 지속 시간, 의식 상태를 확인합니다.",
      "Tình trạng cơ co bóp không tự chủ",
      "신경과/응급",
      "발작은 응급 상황입니다. 안전 확보와 관찰이 중요합니다.",
      [{"mistake":"입에 뭘 물리려 함","correction":"입에 아무것도 넣지 말 것","explanation":"부상 위험"},
       {"mistake":"억지로 잡으려 함","correction":"주변 위험물 치우고 지켜봄","explanation":"안전 확보가 우선"},
       {"mistake":"발작 후 바로 일으키려 함","correction":"옆으로 눕혀 기도 확보","explanation":"회복 체위 유지"}],
      [{"ko":"발작이 5분 이상 지속되면 119에 연락하세요.","vi":"Nếu co giật kéo dài hơn 5 phút hãy gọi 119.","situation":"formal"},
       {"ko":"주변 위험한 물건을 치워주세요.","vi":"Dọn đồ nguy hiểm xung quanh.","situation":"onsite"},
       {"ko":"경련을 했어요.","vi":"Bị co giật.","situation":"informal"}],
      ["뇌전증","119","회복체위"]),

    t("xay-xat","찰과상","xây xát",
      "피부가 긁히거나 벗겨진 가벼운 상처입니다. 통역 시 상처 세척과 드레싱 방법을 안내합니다.",
      "Vết thương nhẹ khi da bị trầy hoặc xước",
      "응급/외과",
      "깨끗한 상처 관리로 감염을 예방합니다.",
      [{"mistake":"그냥 두라고 조언","correction":"깨끗이 씻고 드레싱","explanation":"감염 예방이 중요합니다"},
       {"mistake":"소독약을 과하게 사용","correction":"깨끗한 물로 씻기가 기본","explanation":"과도한 소독은 치유 지연"},
       {"mistake":"딱지 떼라고 조언","correction":"자연스럽게 떨어지게 둠","explanation":"흉터 예방"}],
      [{"ko":"상처를 깨끗한 물로 씻으세요.","vi":"Rửa sạch vết thương bằng nước sạch.","situation":"formal"},
       {"ko":"딱지를 떼지 마세요.","vi":"Đừng bóc vảy.","situation":"onsite"},
       {"ko":"넘어져서 긁혔어요.","vi":"Ngã bị xước.","situation":"informal"}],
      ["소독","드레싱","파상풍"]),

    t("vet-cat","베인상처","vết cắt",
      "칼 등에 피부가 베인 상처입니다. 통역 시 출혈 조절, 상처 깊이, 봉합 필요성을 확인합니다.",
      "Vết thương do bị dao cắt vào da",
      "응급/외과",
      "출혈 조절과 상처 깊이 평가가 중요합니다.",
      [{"mistake":"얕은 상처로 단정","correction":"깊이 평가 필요","explanation":"건이나 신경 손상 가능"},
       {"mistake":"바로 봉합한다고 설명","correction":"상처 세척 후 결정","explanation":"오염 정도 확인 필요"},
       {"mistake":"피 멈추면 된다고 설명","correction":"파상풍 예방접종 확인","explanation":"감염 예방이 중요합니다"}],
      [{"ko":"상처가 깊으면 봉합이 필요할 수 있습니다.","vi":"Vết thương sâu có thể cần khâu.","situation":"formal"},
       {"ko":"깨끗한 천으로 눌러 지혈하세요.","vi":"Ép vải sạch để cầm máu.","situation":"onsite"},
       {"ko":"칼에 베였어요.","vi":"Bị dao cắt.","situation":"informal"}],
      ["지혈","봉합","파상풍"]),

    t("bam-tim","타박상/멍","bầm tím",
      "충격으로 피부 아래 출혈이 생긴 상태입니다. 통역 시 골절 가능성과 자가 관리 방법을 안내합니다.",
      "Tình trạng chảy máu dưới da do va đập",
      "응급/정형외과",
      "멍은 대부분 자연 치유되지만, 심한 통증이나 부종은 골절 의심합니다.",
      [{"mistake":"모든 멍을 가볍게 여김","correction":"심하면 골절이나 내부 손상 가능","explanation":"X선 검사 필요할 수 있습니다"},
       {"mistake":"바로 온찜질 권유","correction":"처음 48시간은 냉찜질","explanation":"부종 감소에 효과적"},
       {"mistake":"마사지 권유","correction":"초기에는 마사지 금지","explanation":"출혈 악화 가능"}],
      [{"ko":"처음 48시간은 냉찜질을 하세요.","vi":"48 giờ đầu hãy chườm lạnh.","situation":"formal"},
       {"ko":"많이 부으면 X선을 찍어봐야 해요.","vi":"Nếu sưng nhiều cần chụp X-quang.","situation":"onsite"},
       {"ko":"멍들었어요.","vi":"Bị bầm tím.","situation":"informal"}],
      ["냉찜질","골절","RICE"]),

    t("chan-thuong","외상","chấn thương",
      "외부 힘에 의한 신체 손상입니다. 통역 시 손상 부위, 기전, 심각도를 빠르게 파악합니다.",
      "Tổn thương cơ thể do lực bên ngoài",
      "응급/외과/정형외과",
      "외상은 산업재해에서 흔합니다. 안전 확보와 응급 처치가 우선입니다.",
      [{"mistake":"움직이라고 권유","correction":"척추 손상 가능 시 움직이지 않기","explanation":"이차 손상 예방"},
       {"mistake":"손상 기전 확인 안 함","correction":"어떻게 다쳤는지가 중요","explanation":"숨은 손상 예측 가능"},
       {"mistake":"출혈만 확인","correction":"내부 손상도 고려","explanation":"보이지 않는 손상 주의"}],
      [{"ko":"어떻게 다치셨어요?","vi":"Bị thương như thế nào?","situation":"formal"},
       {"ko":"목이나 허리가 아프면 움직이지 마세요.","vi":"Nếu đau cổ hoặc lưng đừng di chuyển.","situation":"onsite"},
       {"ko":"다쳤어요.","vi":"Bị thương.","situation":"informal"}],
      ["골절","출혈","응급처치"]),

    t("ngat-xiu","실신/기절","ngất xỉu",
      "일시적으로 의식을 잃는 것입니다. 통역 시 실신 전 증상, 상황, 회복 양상을 확인합니다.",
      "Mất ý thức tạm thời",
      "응급/내과/신경과",
      "실신의 원인을 파악하는 것이 중요합니다. 심장 문제 가능성을 배제합니다.",
      [{"mistake":"단순 빈혈로 치부","correction":"심장 문제 가능성 배제 필요","explanation":"심각한 원인일 수 있습니다"},
       {"mistake":"바로 일으키려 함","correction":"다리를 올리고 눕혀둠","explanation":"뇌 혈류 회복 돕습니다"},
       {"mistake":"물을 먹이려 함","correction":"의식 완전 회복 전까지 금식","explanation":"흡인 위험"}],
      [{"ko":"기절하기 전에 어떤 느낌이었나요?","vi":"Trước khi ngất cảm thấy như thế nào?","situation":"formal"},
       {"ko":"다리를 올리고 누워 계세요.","vi":"Nằm xuống và kê cao chân.","situation":"onsite"},
       {"ko":"쓰러졌어요.","vi":"Bị ngất.","situation":"informal"}],
      ["심전도","혈압","저혈당"]),

    t("benh-vien-tuyen-tinh","상급병원","bệnh viện tuyến tỉnh",
      "전문적인 진료가 가능한 큰 병원입니다. 통역 시 전원의 이유와 절차를 설명합니다.",
      "Bệnh viện lớn có thể điều trị chuyên môn",
      "원무과",
      "상급병원 전원이 필요한 경우 그 이유를 명확히 설명합니다.",
      [{"mistake":"작은 병원이 못 한다고 비하","correction":"전문 장비나 전문의 필요 설명","explanation":"적절한 의료 시스템 이용"},
       {"mistake":"전원 절차 설명 안 함","correction":"진료의뢰서, 예약 절차 안내","explanation":"원활한 전원을 돕습니다"},
       {"mistake":"비용 부담 설명 안 함","correction":"상급병원 비용이 더 높을 수 있음","explanation":"경제적 준비를 돕습니다"}],
      [{"ko":"전문 치료를 위해 큰 병원으로 가셔야 합니다.","vi":"Cần đến bệnh viện lớn để điều trị chuyên môn.","situation":"formal"},
       {"ko":"진료의뢰서를 드릴게요.","vi":"Sẽ cấp giấy giới thiệu.","situation":"onsite"},
       {"ko":"큰 병원 가야 해요.","vi":"Phải đến bệnh viện lớn.","situation":"informal"}],
      ["진료의뢰서","전원","전문의"]),

    t("phong-kham","의원/클리닉","phòng khám",
      "1차 진료를 담당하는 작은 의료기관입니다. 통역 시 의원과 병원의 차이를 설명합니다.",
      "Cơ sở y tế nhỏ đảm nhận khám bệnh ban đầu",
      "해당 의원",
      "경증은 의원에서 먼저 진료받는 것이 효율적입니다.",
      [{"mistake":"의원은 수준이 낮다고 설명","correction":"1차 진료에 적합","explanation":"의료 체계 이해를 돕습니다"},
       {"mistake":"모든 환자를 큰 병원으로 안내","correction":"경증은 의원이 적합","explanation":"의료 자원의 적절한 사용"},
       {"mistake":"전문 진료가 가능하다고 설명","correction":"전문 진료는 상급병원에서","explanation":"정확한 안내가 필요합니다"}],
      [{"ko":"간단한 진료는 가까운 의원에서 받으세요.","vi":"Khám đơn giản hãy đến phòng khám gần nhà.","situation":"formal"},
       {"ko":"전문 검사가 필요하면 큰 병원으로 보내드릴게요.","vi":"Nếu cần xét nghiệm chuyên môn sẽ giới thiệu đến bệnh viện lớn.","situation":"onsite"},
       {"ko":"동네 의원 갔어요.","vi":"Đã đi phòng khám gần nhà.","situation":"informal"}],
      ["1차의료","진료의뢰","접근성"]),

    t("dieu-duong","간호","điều dưỡng",
      "환자를 돌보고 치료를 보조하는 의료 서비스입니다. 통역 시 간호사의 역할과 환자-간호사 소통을 돕습니다.",
      "Dịch vụ y tế chăm sóc bệnh nhân và hỗ trợ điều trị",
      "간호팀",
      "간호사와의 원활한 소통이 치료에 중요합니다.",
      [{"mistake":"간호사를 의사와 혼동","correction":"역할이 다름을 설명","explanation":"적절한 기대를 갖게 합니다"},
       {"mistake":"간호사에게 의료 결정 요청","correction":"의료 결정은 의사가 함","explanation":"역할 구분이 필요합니다"},
       {"mistake":"간호 요청을 무시","correction":"불편사항은 간호사에게 알림","explanation":"적절한 케어를 받습니다"}],
      [{"ko":"불편하시면 간호사 호출 버튼을 누르세요.","vi":"Nếu khó chịu hãy bấm chuông gọi y tá.","situation":"formal"},
       {"ko":"간호사가 주사를 놔드릴 거예요.","vi":"Y tá sẽ tiêm cho bạn.","situation":"onsite"},
       {"ko":"간호사 불러주세요.","vi":"Gọi y tá cho tôi.","situation":"informal"}],
      ["간호사","환자케어","호출벨"]),

    t("duoc-pham","약국","dược phẩm",
      "약을 조제하고 판매하는 곳입니다. 통역 시 처방전 약과 일반약의 차이를 설명합니다.",
      "Nơi pha chế và bán thuốc",
      "약국",
      "처방전이 필요한 약과 그렇지 않은 약을 구분합니다.",
      [{"mistake":"모든 약을 처방 없이 살 수 있다고 설명","correction":"일부는 처방전 필요","explanation":"약사에게 문의하도록 안내"},
       {"mistake":"약사 상담 없이 약 구매 권유","correction":"약사 상담이 중요","explanation":"안전한 약 복용을 위해"},
       {"mistake":"한국 약국 시스템 설명 안 함","correction":"처방전 제출 절차 안내","explanation":"원활한 약 수령을 돕습니다"}],
      [{"ko":"처방전을 약국에 내시면 약을 받으실 수 있어요.","vi":"Nộp đơn thuốc ở nhà thuốc sẽ nhận được thuốc.","situation":"formal"},
       {"ko":"이 약은 처방전 없이 살 수 있어요.","vi":"Thuốc này mua được không cần đơn.","situation":"onsite"},
       {"ko":"약국 어디예요?","vi":"Nhà thuốc ở đâu?","situation":"informal"}],
      ["처방전","약사","일반약"]),

    t("kham-suc-khoe","건강검진","khám sức khỏe",
      "질병 조기 발견을 위해 정기적으로 받는 검사입니다. 통역 시 검진 항목과 준비사항을 안내합니다.",
      "Xét nghiệm định kỳ để phát hiện sớm bệnh",
      "건강검진센터",
      "한국의 국가건강검진 제도와 외국인 근로자 적용 여부를 안내합니다.",
      [{"mistake":"검진이 불필요하다고 설명","correction":"조기 발견으로 치료 용이","explanation":"예방이 치료보다 효과적"},
       {"mistake":"검진 준비사항 안내 안 함","correction":"금식, 복장 등 안내","explanation":"정확한 결과를 위해 필요합니다"},
       {"mistake":"결과 설명 없이 끝냄","correction":"결과 상담이 중요","explanation":"이상 소견 관리가 필요합니다"}],
      [{"ko":"건강검진을 위해 전날 밤 9시부터 금식하세요.","vi":"Nhịn ăn từ 9 giờ tối hôm trước để khám sức khỏe.","situation":"formal"},
       {"ko":"검진 결과는 1주일 후에 나와요.","vi":"Kết quả khám có sau 1 tuần.","situation":"onsite"},
       {"ko":"건강검진 받으러 왔어요.","vi":"Đến khám sức khỏe.","situation":"informal"}],
      ["국가건강검진","조기발견","금식"]),

    t("cuu-thuong","구급차/응급차","cứu thương",
      "응급 환자를 이송하는 차량입니다. 통역 시 119 호출 방법과 응급 상황 전달을 돕습니다.",
      "Xe vận chuyển bệnh nhân cấp cứu",
      "응급의학과",
      "응급 상황에서 119 호출 방법을 교육합니다.",
      [{"mistake":"택시로 가라고 조언","correction":"응급 상황은 119 이용","explanation":"이동 중 응급처치 가능"},
       {"mistake":"119 호출 주저","correction":"생명 위급 시 즉시 호출","explanation":"시간이 생명입니다"},
       {"mistake":"주소 전달 안내 안 함","correction":"정확한 위치 전달 중요","explanation":"빠른 도착을 위해 필수입니다"}],
      [{"ko":"119에 전화해서 구급차를 불러주세요.","vi":"Gọi 119 gọi xe cứu thương.","situation":"formal"},
       {"ko":"주소를 정확히 알려주세요.","vi":"Cho biết địa chỉ chính xác.","situation":"onsite"},
       {"ko":"119 불렀어요.","vi":"Đã gọi 119.","situation":"informal"}],
      ["119","응급이송","응급처치"]),

    t("ca-truc","당직/야간진료","ca trực",
      "야간이나 주말에 근무하는 의료진입니다. 통역 시 야간/휴일 진료 가능 여부를 안내합니다.",
      "Nhân viên y tế làm việc ban đêm hoặc cuối tuần",
      "응급/당직실",
      "응급 상황이 아니면 평일 진료를 권하되, 필요시 야간 진료를 안내합니다.",
      [{"mistake":"야간에는 진료 못 받는다고 설명","correction":"응급실은 24시간 운영","explanation":"응급 상황 시 이용 가능"},
       {"mistake":"모든 진료가 야간에 가능하다고 설명","correction":"전문 진료는 평일에","explanation":"야간은 응급 위주"},
       {"mistake":"당직의 역량을 폄하","correction":"당직의도 전문 의료진","explanation":"신뢰를 유지합니다"}],
      [{"ko":"야간에는 응급실에서 진료받으실 수 있어요.","vi":"Ban đêm có thể khám ở phòng cấp cứu.","situation":"formal"},
       {"ko":"전문 진료는 평일에 다시 오세요.","vi":"Khám chuyên môn hãy đến lại ngày thường.","situation":"onsite"},
       {"ko":"야간 진료 되나요?","vi":"Có khám ban đêm không?","situation":"informal"}],
      ["응급실","주말진료","예약"]),

    t("ho-so-benh-an","의무기록","hồ sơ bệnh án",
      "환자의 진료 내용을 기록한 문서입니다. 통역 시 의무기록 열람 및 발급 절차를 안내합니다.",
      "Văn bản ghi chép nội dung khám chữa bệnh của bệnh nhân",
      "원무과/의무기록실",
      "의무기록은 환자의 권리로 열람 가능함을 알립니다.",
      [{"mistake":"의무기록 열람이 불가하다고 설명","correction":"환자 본인은 열람 권리 있음","explanation":"환자 권리를 알립니다"},
       {"mistake":"발급 절차 안내 안 함","correction":"신청 방법과 비용 안내","explanation":"원활한 발급을 돕습니다"},
       {"mistake":"제3자에게 제공 가능하다고 설명","correction":"본인 동의 없이 제공 불가","explanation":"개인정보 보호가 중요합니다"}],
      [{"ko":"의무기록 사본을 원하시면 원무과에 신청하세요.","vi":"Muốn bản sao hồ sơ bệnh án hãy đăng ký ở phòng hành chính.","situation":"formal"},
       {"ko":"발급에 3일 정도 걸려요.","vi":"Cấp mất khoảng 3 ngày.","situation":"onsite"},
       {"ko":"의무기록 필요해요.","vi":"Cần hồ sơ bệnh án.","situation":"informal"}],
      ["의무기록사본","개인정보","발급비"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
