#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch F - 소화기 (20개)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("viem-da-day","위염","viêm dạ dày",
      "위 점막에 염증이 생겨 속쓰림, 소화불량, 복통이 발생합니다. 통역 시 급성과 만성의 차이, H.pylori 감염 여부 확인의 중요성을 설명합니다.",
      "Tình trạng viêm niêm mạc dạ dày gây ợ nóng, khó tiêu và đau bụng",
      "소화기내과",
      "베트남 음식의 매운 양념이나 산미가 위염을 악화시킬 수 있습니다. 식이 조절에 대해 구체적으로 안내합니다.",
      [{"mistake":"모든 위염에 항생제 필요하다고 설명","correction":"H.pylori 양성일 때만 제균 치료","explanation":"불필요한 항생제 사용을 피합니다"},
       {"mistake":"우유가 좋다고 권유","correction":"우유는 일시적 완화, 오히려 악화 가능","explanation":"위산 분비를 촉진할 수 있습니다"},
       {"mistake":"약만 먹으면 된다고 설명","correction":"식이 조절과 스트레스 관리도 필수","explanation":"생활습관 개선이 중요합니다"}],
      [{"ko":"위염 치료를 위해 위산 억제제를 처방합니다.","vi":"Kê đơn thuốc ức chế axit dạ dày để điều trị viêm dạ dày.","situation":"formal"},
       {"ko":"매운 음식과 술을 피하세요.","vi":"Hãy tránh đồ cay và rượu bia.","situation":"onsite"},
       {"ko":"위염 때문에 속이 쓰려요.","vi":"Viêm dạ dày nên bị ợ nóng.","situation":"informal"}],
      ["위산억제제","H.pylori","위내시경"]),

    t("loet-da-day","위궤양","loét dạ dày",
      "위 점막이 손상되어 궤양이 생긴 상태로, 식후 통증이 특징입니다. 통역 시 출혈, 천공 등 합병증 증상을 알려주고 즉시 내원하도록 안내합니다.",
      "Tình trạng niêm mạc dạ dày bị tổn thương tạo vết loét, đặc trưng bởi đau sau ăn",
      "소화기내과",
      "H.pylori 감염과 진통제(NSAIDs) 복용이 주요 원인입니다. 약국에서 쉽게 구할 수 있는 진통제 주의사항을 안내합니다.",
      [{"mistake":"스트레스만 원인이라고 설명","correction":"H.pylori와 진통제도 주요 원인","explanation":"원인 치료가 중요합니다"},
       {"mistake":"통증 없으면 괜찮다고 안심시킴","correction":"출혈, 천공 시 무증상 가능","explanation":"정기 추적이 필요합니다"},
       {"mistake":"궤양이 암이라고 겁줌","correction":"대부분 양성, 치료로 호전","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"위궤양 확인을 위해 위내시경 검사가 필요합니다.","vi":"Cần nội soi dạ dày để xác nhận loét dạ dày.","situation":"formal"},
       {"ko":"검은색 변이나 피를 토하면 바로 오세요.","vi":"Nếu đi phân đen hoặc nôn ra máu hãy đến ngay.","situation":"onsite"},
       {"ko":"위궤양이라 밥 먹으면 아파요.","vi":"Bị loét dạ dày nên ăn xong là đau.","situation":"informal"}],
      ["H.pylori제균","위산억제제","출혈"]),

    t("trao-nguoc-da-day-thuc-quan","역류성식도염","trào ngược dạ dày thực quản",
      "위산이 식도로 역류하여 가슴쓰림과 신물이 오르는 증상을 유발합니다. 통역 시 생활습관 교정(식후 눕지 않기, 야식 피하기)을 강조합니다.",
      "Tình trạng axit dạ dày trào ngược lên thực quản gây ợ nóng và trào ngược",
      "소화기내과",
      "베트남 환자들이 늦은 저녁 식사를 하는 경우가 많아 이 습관을 교정하도록 안내합니다.",
      [{"mistake":"심장병과 혼동","correction":"가슴 통증이 심장 아닌 식도 문제일 수 있음","explanation":"감별이 필요합니다"},
       {"mistake":"평생 약 먹어야 한다고만 설명","correction":"생활습관으로 약 줄일 수 있음","explanation":"희망을 줍니다"},
       {"mistake":"우유 마시라고 권유","correction":"우유는 일시적 완화, 역류 악화 가능","explanation":"잘못된 민간요법입니다"}],
      [{"ko":"역류성식도염으로 위산 억제제를 드셔야 합니다.","vi":"Trào ngược dạ dày cần uống thuốc ức chế axit.","situation":"formal"},
       {"ko":"자기 전 3시간은 음식을 드시지 마세요.","vi":"Đừng ăn gì trước khi ngủ 3 tiếng.","situation":"onsite"},
       {"ko":"역류성식도염이라 자주 신물이 올라와요.","vi":"Trào ngược dạ dày nên hay bị ợ chua.","situation":"informal"}],
      ["PPI","생활습관","바렛식도"]),

    t("viem-tuy-cap","급성췌장염","viêm tụy cấp",
      "췌장에 급성 염증이 발생하여 심한 복통이 나타나는 응급 상황입니다. 통역 시 금식의 중요성과 알코올/담석이 주요 원인임을 설명합니다.",
      "Tình trạng viêm cấp tính ở tụy gây đau bụng dữ dội, là cấp cứu y khoa",
      "소화기내과/외과",
      "베트남 남성들의 음주 문화로 알코올성 췌장염이 발생할 수 있습니다. 금주의 중요성을 강조합니다.",
      [{"mistake":"가벼운 복통으로 치부","correction":"중증은 생명을 위협할 수 있음","explanation":"입원 치료가 필요합니다"},
       {"mistake":"음식 먹어도 된다고 설명","correction":"급성기에는 반드시 금식","explanation":"췌장 휴식이 필요합니다"},
       {"mistake":"한 번이면 괜찮다고 안심시킴","correction":"재발과 만성화 가능","explanation":"원인 제거가 중요합니다"}],
      [{"ko":"급성췌장염으로 금식과 수액 치료가 필요합니다.","vi":"Viêm tụy cấp cần nhịn ăn và truyền dịch.","situation":"formal"},
       {"ko":"배가 많이 아프면 참지 말고 오세요.","vi":"Đau bụng nhiều đừng chịu, hãy đến ngay.","situation":"onsite"},
       {"ko":"췌장염으로 술 끊어야 해요.","vi":"Viêm tụy nên phải bỏ rượu.","situation":"informal"}],
      ["아밀라아제","CT","담석"]),

    t("xo-gan","간경변","xơ gan",
      "만성 간손상으로 간이 딱딱해지고 기능이 저하되는 상태입니다. 통역 시 합병증(복수, 정맥류, 간성뇌증)을 설명하고 정기 검진의 중요성을 강조합니다.",
      "Tình trạng gan cứng và giảm chức năng do tổn thương gan mãn tính",
      "소화기내과",
      "B형간염과 알코올이 주요 원인입니다. 베트남은 B형간염 유병률이 높아 관련 교육이 중요합니다.",
      [{"mistake":"간경변은 곧 사망이라고 설명","correction":"관리하면 오래 살 수 있음","explanation":"절망감을 주지 않습니다"},
       {"mistake":"합병증 설명 안 함","correction":"복수, 출혈, 뇌증 증상 교육","explanation":"조기 발견이 중요합니다"},
       {"mistake":"술만 안 마시면 된다고 설명","correction":"B형간염, 지방간도 원인","explanation":"원인이 다양합니다"}],
      [{"ko":"간경변으로 정기적인 초음파와 내시경 검사가 필요합니다.","vi":"Xơ gan cần siêu âm và nội soi định kỳ.","situation":"formal"},
       {"ko":"배가 불러오거나 피를 토하면 바로 오세요.","vi":"Bụng phình lên hoặc nôn ra máu hãy đến ngay.","situation":"onsite"},
       {"ko":"간경변이라 술 못 마셔요.","vi":"Bị xơ gan nên không uống rượu được.","situation":"informal"}],
      ["복수","식도정맥류","간성뇌증"]),

    t("viem-gan-virus","바이러스간염","viêm gan virus",
      "바이러스(A, B, C형 등)로 인한 간 염증입니다. 통역 시 전파 경로와 예방법이 유형별로 다름을 설명하고, B형 백신의 중요성을 안내합니다.",
      "Viêm gan do virus (type A, B, C, v.v.)",
      "소화기내과/감염내과",
      "베트남은 B형간염 유병률이 높습니다(약 8-10%). 가족 검진과 백신 접종을 권장합니다.",
      [{"mistake":"모든 간염이 같다고 설명","correction":"유형별로 전파, 치료, 예후가 다름","explanation":"정확한 정보 제공이 중요합니다"},
       {"mistake":"B형은 완치 불가하다고만 설명","correction":"항바이러스제로 조절 가능","explanation":"희망을 줍니다"},
       {"mistake":"전염성을 과장","correction":"일상 접촉으로는 전염 안 됨(B, C형)","explanation":"사회적 낙인을 줄입니다"}],
      [{"ko":"B형간염 보균자로 6개월마다 검사가 필요합니다.","vi":"Người mang virus viêm gan B cần xét nghiệm mỗi 6 tháng.","situation":"formal"},
       {"ko":"가족들도 B형간염 검사와 백신 접종하세요.","vi":"Gia đình cũng nên xét nghiệm và tiêm vắc xin viêm gan B.","situation":"onsite"},
       {"ko":"B형간염 있어서 정기검진 받아요.","vi":"Có viêm gan B nên khám định kỳ.","situation":"informal"}],
      ["HBsAg","항바이러스제","간암선별"]),

    t("soi-mat","담석","sỏi mật",
      "담낭이나 담관에 돌이 생긴 상태로, 우상복부 통증을 유발합니다. 통역 시 기름진 음식 후 통증 악화가 특징적임을 전달합니다.",
      "Tình trạng hình thành sỏi ở túi mật hoặc ống mật gây đau bụng trên bên phải",
      "소화기내과/외과",
      "베트남 환자들에게 기름진 음식 후 복통이 있다면 담석 가능성을 설명합니다.",
      [{"mistake":"작은 돌은 괜찮다고 안심시킴","correction":"작은 돌도 증상 유발 및 합병증 가능","explanation":"크기와 무관하게 관리 필요합니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"무증상이면 경과 관찰도 가능","explanation":"개인화된 접근이 필요합니다"},
       {"mistake":"담낭 제거 후 소화 안 된다고 겁줌","correction":"대부분 정상 생활 가능","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"담석 확인을 위해 복부 초음파 검사가 필요합니다.","vi":"Cần siêu âm bụng để xác nhận sỏi mật.","situation":"formal"},
       {"ko":"기름진 음식을 드시면 통증이 심해질 수 있어요.","vi":"Ăn đồ nhiều dầu mỡ có thể đau hơn.","situation":"onsite"},
       {"ko":"담석 때문에 복강경 수술했어요.","vi":"Mổ nội soi vì sỏi mật.","situation":"informal"}],
      ["복강경담낭절제술","담도염","ERCP"]),

    t("viem-ruot-thua","맹장염/충수염","viêm ruột thừa",
      "충수(맹장 끝 돌기)에 염증이 생겨 우하복부 통증이 발생하는 급성 상태입니다. 통역 시 천공 전 조기 수술의 중요성을 강조합니다.",
      "Tình trạng viêm ruột thừa gây đau bụng dưới bên phải, là cấp cứu ngoại khoa",
      "외과/응급",
      "맹장염은 빠른 수술이 필요한 응급 상황입니다. 복통을 참지 말고 빨리 오도록 안내합니다.",
      [{"mistake":"맹장과 충수를 같다고 설명","correction":"충수가 정확한 명칭, 맹장은 다른 부위","explanation":"의학적 정확성이 필요합니다"},
       {"mistake":"약으로 치료 가능하다고 설명","correction":"대부분 수술이 표준 치료","explanation":"지연 시 천공 위험"},
       {"mistake":"복통 위치만으로 진단","correction":"초기에는 배꼽 주변 통증으로 시작","explanation":"전형적 경과를 설명합니다"}],
      [{"ko":"충수염으로 오늘 수술이 필요합니다.","vi":"Viêm ruột thừa cần phẫu thuật hôm nay.","situation":"formal"},
       {"ko":"복통이 오른쪽 아래로 이동하면 바로 오세요.","vi":"Nếu đau bụng di chuyển xuống bên phải hãy đến ngay.","situation":"onsite"},
       {"ko":"맹장 터지기 전에 수술했어요.","vi":"Mổ ruột thừa trước khi bị vỡ.","situation":"informal"}],
      ["복강경수술","천공","복막염"]),

    t("tac-ruot","장폐색","tắc ruột",
      "장이 막혀 음식물과 가스가 통과하지 못하는 응급 상황입니다. 통역 시 구토, 복부 팽만, 배변 중지가 특징적 증상임을 설명합니다.",
      "Tình trạng cấp cứu khi ruột bị tắc, thức ăn và khí không thể đi qua",
      "외과/응급",
      "과거 복부 수술력이 있으면 유착으로 장폐색이 잘 발생합니다. 수술 병력을 꼭 확인합니다.",
      [{"mistake":"변비와 혼동","correction":"장폐색은 완전 폐쇄로 응급 상황","explanation":"즉각 대응이 필요합니다"},
       {"mistake":"관장하면 된다고 설명","correction":"기계적 폐색은 관장이 위험할 수 있음","explanation":"원인 확인이 먼저입니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"일부는 비수술적 치료 가능","explanation":"원인에 따라 치료가 다릅니다"}],
      [{"ko":"장폐색으로 금식과 비위관 삽입이 필요합니다.","vi":"Tắc ruột cần nhịn ăn và đặt ống thông mũi-dạ dày.","situation":"formal"},
       {"ko":"배가 부풀고 토하면서 가스가 안 나오면 바로 오세요.","vi":"Bụng phình, nôn và không xì hơi hãy đến ngay.","situation":"onsite"},
       {"ko":"장이 막혀서 수술해야 했어요.","vi":"Ruột bị tắc nên phải phẫu thuật.","situation":"informal"}],
      ["복부X선","비위관감압","유착박리술"]),

    t("viem-dai-trang","대장염","viêm đại tràng",
      "대장에 염증이 생겨 설사, 복통, 혈변이 발생합니다. 통역 시 감염성과 염증성(궤양성대장염, 크론병)을 구별하여 설명합니다.",
      "Tình trạng viêm đại tràng gây tiêu chảy, đau bụng và phân có máu",
      "소화기내과",
      "급성 감염성 대장염은 음식과 관련이 많습니다. 식품 위생과 손씻기의 중요성을 강조합니다.",
      [{"mistake":"모든 설사를 대장염이라고 설명","correction":"원인이 다양함(감염, 염증성, 허혈성)","explanation":"정확한 진단이 필요합니다"},
       {"mistake":"항생제가 항상 필요하다고 설명","correction":"바이러스성은 항생제 불필요","explanation":"원인에 따른 치료가 필요합니다"},
       {"mistake":"음식 조심만 강조","correction":"염증성장질환은 자가면역 관련","explanation":"원인이 다를 수 있습니다"}],
      [{"ko":"대장염 원인 확인을 위해 대변 검사와 대장내시경이 필요합니다.","vi":"Cần xét nghiệm phân và nội soi đại tràng để xác định nguyên nhân viêm đại tràng.","situation":"formal"},
       {"ko":"설사할 때는 수분을 충분히 드세요.","vi":"Khi tiêu chảy hãy uống đủ nước.","situation":"onsite"},
       {"ko":"대장염이라 화장실을 자주 가요.","vi":"Viêm đại tràng nên hay đi vệ sinh.","situation":"informal"}],
      ["대장내시경","염증성장질환","프로바이오틱스"]),

    t("hoi-chung-ruot-kich-thich","과민성대장증후군","hội chứng ruột kích thích",
      "기질적 이상 없이 복통, 복부 팽만, 변비 또는 설사가 반복되는 기능성 장질환입니다. 통역 시 스트레스와의 연관성을 설명하고 암이 아님을 안심시킵니다.",
      "Bệnh lý chức năng đường ruột với đau bụng, đầy hơi, táo bón hoặc tiêu chảy lặp đi lặp lại mà không có bất thường thực thể",
      "소화기내과",
      "스트레스가 증상을 악화시킵니다. 이주 노동자의 스트레스 환경을 이해하고 공감합니다.",
      [{"mistake":"꾀병으로 치부","correction":"실제 증상이 있는 질환","explanation":"환자의 고통을 인정합니다"},
       {"mistake":"평생 낫지 않는다고 설명","correction":"관리로 증상 조절 가능","explanation":"희망을 줍니다"},
       {"mistake":"암 가능성만 배제하면 끝이라고 설명","correction":"지속적 관리가 필요","explanation":"만성 질환으로 접근합니다"}],
      [{"ko":"과민성대장증후군으로 식이 조절과 스트레스 관리가 중요합니다.","vi":"Hội chứng ruột kích thích cần điều chỉnh chế độ ăn và quản lý stress.","situation":"formal"},
       {"ko":"스트레스 받으면 배가 아플 수 있어요.","vi":"Stress có thể làm đau bụng.","situation":"onsite"},
       {"ko":"예민한 장이라 자주 배탈 나요.","vi":"Ruột nhạy cảm nên hay đau bụng.","situation":"informal"}],
      ["FODMAP식단","저섬유식","진경제"]),

    t("tao-bon","변비","táo bón",
      "배변 횟수가 적거나 대변이 딱딱해 배출이 어려운 상태입니다. 통역 시 수분, 섬유질, 운동의 중요성을 설명하고 하제 남용을 경고합니다.",
      "Tình trạng đi đại tiện ít hoặc phân cứng khó thoát",
      "소화기내과",
      "이주 노동자들은 식단 변화, 수분 섭취 부족으로 변비가 흔합니다. 생활습관 교정을 강조합니다.",
      [{"mistake":"하제만 처방","correction":"원인 파악과 생활습관 교정이 우선","explanation":"근본 해결이 필요합니다"},
       {"mistake":"심각한 질환으로 겁줌","correction":"대부분 기능성 변비","explanation":"불필요한 불안을 줄입니다"},
       {"mistake":"매일 배변해야 정상이라고 설명","correction":"주 3회 이상이면 정상 범위","explanation":"개인차가 있습니다"}],
      [{"ko":"변비 개선을 위해 수분과 섬유질 섭취를 늘리세요.","vi":"Để cải thiện táo bón hãy tăng uống nước và ăn chất xơ.","situation":"formal"},
       {"ko":"하루 8잔 이상 물을 드세요.","vi":"Uống ít nhất 8 ly nước mỗi ngày.","situation":"onsite"},
       {"ko":"변비가 심해서 힘들어요.","vi":"Táo bón nặng nên khổ lắm.","situation":"informal"}],
      ["섬유질","완하제","대장통과시간검사"]),

    t("tri","치질","trĩ",
      "항문 주변 혈관이 늘어나 덩어리가 생기고 출혈, 통증이 발생합니다. 통역 시 1-4도 분류와 치료법 차이를 설명합니다.",
      "Tình trạng mạch máu quanh hậu môn giãn tạo khối u gây chảy máu và đau",
      "외과/대장항문외과",
      "오래 앉아 일하거나 변비가 있으면 치질이 악화됩니다. 직업적 요인을 확인합니다.",
      [{"mistake":"부끄러워서 말 못하게 분위기 조성","correction":"흔한 질환임을 안심시킴","explanation":"조기 치료가 중요합니다"},
       {"mistake":"무조건 수술이라고 설명","correction":"초기에는 보존적 치료로 호전","explanation":"단계적 접근이 필요합니다"},
       {"mistake":"평생 재발한다고 낙담시킴","correction":"생활습관 개선으로 예방 가능","explanation":"희망을 줍니다"}],
      [{"ko":"치질은 초기에 좌욕과 연고로 치료할 수 있습니다.","vi":"Trĩ giai đoạn đầu có thể điều trị bằng ngâm nước ấm và thuốc mỡ.","situation":"formal"},
       {"ko":"변기에 오래 앉지 마세요.","vi":"Đừng ngồi toilet quá lâu.","situation":"onsite"},
       {"ko":"치질 때문에 화장실 갈 때마다 피 나요.","vi":"Bị trĩ nên mỗi lần đi vệ sinh là chảy máu.","situation":"informal"}],
      ["좌욕","고무밴드결찰술","치핵절제술"]),

    t("viem-tui-thua","게실염","viêm túi thừa",
      "대장벽에 생긴 게실(주머니)에 염증이 발생하여 좌하복부 통증을 유발합니다. 통역 시 섬유질 섭취의 중요성과 합병증(천공, 농양)을 설명합니다.",
      "Tình trạng viêm túi thừa (túi nhỏ) ở thành đại tràng gây đau bụng dưới bên trái",
      "소화기내과/외과",
      "서양식 저섬유질 식단과 관련이 있습니다. 한국 생활에서 식단이 바뀐 베트남 환자에게 설명합니다.",
      [{"mistake":"맹장염과 혼동","correction":"게실염은 주로 좌측, 맹장염은 우측","explanation":"위치가 다릅니다"},
       {"mistake":"씨앗이나 견과류 탓이라고만 설명","correction":"섬유질 부족이 주요 원인","explanation":"최신 연구 결과를 반영합니다"},
       {"mistake":"항상 수술이라고 설명","correction":"대부분 항생제로 호전","explanation":"수술은 합병증 시에만"}],
      [{"ko":"게실염으로 항생제 치료와 금식이 필요합니다.","vi":"Viêm túi thừa cần điều trị kháng sinh và nhịn ăn.","situation":"formal"},
       {"ko":"좌측 아랫배가 아프면 게실염일 수 있어요.","vi":"Đau bụng dưới bên trái có thể là viêm túi thừa.","situation":"onsite"},
       {"ko":"게실염이라 대장에 주머니가 있대요.","vi":"Bị viêm túi thừa nên đại tràng có túi nhỏ.","situation":"informal"}],
      ["CT","항생제","고섬유식"]),

    t("xuat-huyet-tieu-hoa","소화기출혈","xuất huyết tiêu hóa",
      "위장관에서 출혈이 발생하여 토혈이나 혈변이 나타나는 응급 상황입니다. 통역 시 출혈 위치(상부/하부)에 따라 증상이 다름을 설명합니다.",
      "Tình trạng cấp cứu khi chảy máu trong đường tiêu hóa gây nôn ra máu hoặc đi phân có máu",
      "소화기내과/응급",
      "소화기출혈은 응급 상황으로 즉시 내원해야 합니다. 증상의 심각성을 명확히 전달합니다.",
      [{"mistake":"검은 변을 단순 변비로 치부","correction":"상부위장관 출혈 징후일 수 있음","explanation":"흑색변은 위험 신호입니다"},
       {"mistake":"출혈량을 과소평가","correction":"토혈, 혈변은 소량도 중요","explanation":"내부 출혈량은 더 많을 수 있습니다"},
       {"mistake":"집에서 지켜보라고 조언","correction":"즉시 응급실 방문 필요","explanation":"생명을 위협할 수 있습니다"}],
      [{"ko":"소화기출혈로 응급 내시경이 필요합니다.","vi":"Xuất huyết tiêu hóa cần nội soi cấp cứu.","situation":"formal"},
       {"ko":"피를 토하거나 검은 변을 보면 바로 119에 연락하세요.","vi":"Nếu nôn ra máu hoặc đi phân đen hãy gọi 119 ngay.","situation":"onsite"},
       {"ko":"피 토해서 응급실 갔어요.","vi":"Nôn ra máu nên đi cấp cứu.","situation":"informal"}],
      ["응급내시경","수혈","지혈술"]),

    t("polyp-dai-trang","대장용종","polyp đại tràng",
      "대장 점막에서 돌출된 조직으로, 일부는 암으로 진행할 수 있습니다. 통역 시 용종 절제와 정기 추적의 중요성을 강조합니다.",
      "Mô nhô ra từ niêm mạc đại tràng, một số có thể tiến triển thành ung thư",
      "소화기내과",
      "대장내시경 검사 시 용종이 발견되면 제거합니다. 용종=암이 아님을 설명하되, 정기 검사의 중요성을 강조합니다.",
      [{"mistake":"용종이 곧 암이라고 겁줌","correction":"대부분 양성, 제거하면 됨","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"한 번 제거하면 끝이라고 설명","correction":"정기 추적 내시경 필요","explanation":"재발과 새 용종 가능"},
       {"mistake":"증상이 없으면 검사 안 해도 된다고 설명","correction":"용종은 보통 무증상","explanation":"선별검사가 중요합니다"}],
      [{"ko":"대장용종을 내시경으로 제거했습니다. 3년 후 재검사하세요.","vi":"Đã cắt polyp đại tràng bằng nội soi. 3 năm sau hãy tái khám.","situation":"formal"},
       {"ko":"용종은 암이 아니지만 정기 검사가 필요해요.","vi":"Polyp không phải ung thư nhưng cần kiểm tra định kỳ.","situation":"onsite"},
       {"ko":"용종 떼어내서 조직검사 보냈어요.","vi":"Cắt polyp rồi gửi xét nghiệm mô.","situation":"informal"}],
      ["용종절제술","조직검사","대장암선별"]),

    t("ung-thu-dai-trang","대장암","ung thư đại tràng",
      "대장에 발생하는 악성 종양으로, 조기 발견 시 완치율이 높습니다. 통역 시 혈변, 체중 감소, 배변 습관 변화 등 경고 증상을 교육합니다.",
      "Khối u ác tính phát sinh ở đại tràng, tỷ lệ chữa khỏi cao nếu phát hiện sớm",
      "종양내과/외과",
      "대장암 선별검사의 중요성을 강조합니다. 50세 이상 또는 가족력이 있으면 정기 검사를 권합니다.",
      [{"mistake":"암 진단을 직접적으로 전달","correction":"보호자와 먼저 상의 후 단계적 설명","explanation":"환자의 심리적 충격을 고려합니다"},
       {"mistake":"말기라고 단정","correction":"병기와 치료 옵션 설명","explanation":"희망을 유지하게 합니다"},
       {"mistake":"수술만 설명","correction":"항암, 방사선 등 다학제 치료 설명","explanation":"종합적 치료 계획이 필요합니다"}],
      [{"ko":"대장암 수술 후 항암 치료가 필요할 수 있습니다.","vi":"Sau phẫu thuật ung thư đại tràng có thể cần hóa trị.","situation":"formal"},
       {"ko":"정기적인 대장내시경 검사로 조기 발견이 가능합니다.","vi":"Nội soi đại tràng định kỳ có thể phát hiện sớm.","situation":"onsite"},
       {"ko":"대장암 2기라서 수술했어요.","vi":"Ung thư đại tràng giai đoạn 2 nên đã phẫu thuật.","situation":"informal"}],
      ["대장절제술","항암치료","CEA"]),

    t("ung-thu-da-day","위암","ung thư dạ dày",
      "위에 발생하는 악성 종양으로, 한국에서 흔한 암 중 하나입니다. 통역 시 조기 위암과 진행성 위암의 예후 차이를 설명합니다.",
      "Khối u ác tính phát sinh ở dạ dày, là một trong những loại ung thư phổ biến ở Hàn Quốc",
      "종양내과/외과",
      "한국의 위암 검진 시스템(40세 이상 2년마다 위내시경)을 안내하고, 조기 발견의 중요성을 강조합니다.",
      [{"mistake":"위암은 곧 사망이라고 설명","correction":"조기 발견 시 5년 생존율 90% 이상","explanation":"희망을 줍니다"},
       {"mistake":"수술만 설명","correction":"내시경 절제, 항암 등 다양한 치료","explanation":"병기에 따른 옵션을 설명합니다"},
       {"mistake":"H.pylori만 원인이라고 설명","correction":"식이, 유전 등 다양한 원인","explanation":"종합적 관점이 필요합니다"}],
      [{"ko":"조기 위암으로 내시경 절제술이 가능합니다.","vi":"Ung thư dạ dày giai đoạn sớm có thể cắt bằng nội soi.","situation":"formal"},
       {"ko":"정기적인 위내시경 검사가 중요합니다.","vi":"Nội soi dạ dày định kỳ rất quan trọng.","situation":"onsite"},
       {"ko":"위암 초기라 내시경으로 잘라냈어요.","vi":"Ung thư dạ dày giai đoạn đầu nên cắt bằng nội soi.","situation":"informal"}],
      ["위절제술","내시경점막하박리술","항암치료"]),

    t("ung-thu-gan","간암","ung thư gan",
      "간에 발생하는 악성 종양으로, B형간염, C형간염, 간경변이 주요 위험인자입니다. 통역 시 고위험군 정기 검진의 중요성을 강조합니다.",
      "Khối u ác tính phát sinh ở gan, với yếu tố nguy cơ chính là viêm gan B, C và xơ gan",
      "종양내과/간담도외과",
      "베트남은 B형간염 유병률이 높아 간암 위험이 높습니다. 정기 검진(초음파, AFP)을 강조합니다.",
      [{"mistake":"간암은 치료 불가라고 설명","correction":"조기 발견 시 수술, 색전술 등 가능","explanation":"치료 옵션이 있습니다"},
       {"mistake":"간염 보균자 모두 간암 된다고 겁줌","correction":"정기 관리로 조기 발견 가능","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"수술만 설명","correction":"색전술, 고주파 치료 등 다양한 방법","explanation":"개인화된 치료가 필요합니다"}],
      [{"ko":"간암 조기 발견을 위해 6개월마다 초음파와 혈액검사가 필요합니다.","vi":"Cần siêu âm và xét nghiệm máu mỗi 6 tháng để phát hiện sớm ung thư gan.","situation":"formal"},
       {"ko":"B형간염 있으면 정기적으로 간암 검사하세요.","vi":"Có viêm gan B thì hãy xét nghiệm ung thư gan định kỳ.","situation":"onsite"},
       {"ko":"간암이라 색전술 받았어요.","vi":"Bị ung thư gan nên đã làm nút mạch.","situation":"informal"}],
      ["간동맥화학색전술","고주파절제술","AFP"]),

    t("ung-thu-tuy","췌장암","ung thư tụy",
      "췌장에 발생하는 악성 종양으로, 조기 발견이 어렵고 예후가 나쁜 편입니다. 통역 시 황달, 체중 감소, 상복부 통증 등 증상을 설명합니다.",
      "Khối u ác tính phát sinh ở tụy, khó phát hiện sớm và tiên lượng thường xấu",
      "종양내과/외과",
      "췌장암은 예후가 좋지 않지만, 환자와 가족에게 현실적이면서도 희망을 주는 방식으로 설명합니다.",
      [{"mistake":"희망이 없다고 단정","correction":"치료 옵션과 완화 치료 설명","explanation":"환자의 존엄성을 유지합니다"},
       {"mistake":"증상을 무시하도록 조언","correction":"조기 증상 인지가 중요","explanation":"조금이라도 빨리 발견해야 합니다"},
       {"mistake":"수술만이 답이라고 설명","correction":"항암, 방사선, 완화 치료도 옵션","explanation":"개인화된 접근이 필요합니다"}],
      [{"ko":"췌장암 병기 확인을 위해 CT와 MRI가 필요합니다.","vi":"Cần chụp CT và MRI để xác định giai đoạn ung thư tụy.","situation":"formal"},
       {"ko":"황달과 체중 감소가 있으면 검사를 받으세요.","vi":"Nếu có vàng da và giảm cân hãy đi khám.","situation":"onsite"},
       {"ko":"췌장암이라 항암치료 받고 있어요.","vi":"Bị ung thư tụy nên đang hóa trị.","situation":"informal"}],
      ["휘플수술","항암치료","완화치료"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
