#!/usr/bin/env python3
import json, os
path = os.path.join(os.path.dirname(__file__), '../data/terms/medical.json')
with open(path, 'r', encoding='utf-8') as f: data = json.load(f)
existing = {t['slug'] for t in data}

def t(s,k,v,h,hr,p,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":h,"hanjaReading":hr,"pronunciation":p,"meaningKo":mk,"meaningVi":mv,"context":cx,"culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

new = [
t("suy-tim","심부전","suy tim","心不全","심(마음 심) + 부(아닐 부) + 전(온전할 전)","sim-bu-jeon",
"심장이 충분한 혈액을 펌프질하지 못하는 상태입니다. 호흡곤란, 부종, 피로감이 주 증상입니다. 만성질환으로 약물과 생활습관 관리가 필요합니다. 통역 시 수분/염분 제한, 체중 모니터링, 약물 복용의 중요성을 강조해야 합니다.",
"Tim không bơm đủ máu cho cơ thể, gây khó thở, phù, mệt mỏi",
"심장내과","한국에서 심부전 환자는 고령화로 증가하고 있습니다. 자가관리가 중요하며 매일 체중 측정, 염분 제한 등을 베트남 환자에게 교육해야 합니다.",
[{"mistake":"심부전을 심장마비로 번역","correction":"'suy tim'이 정확, 'đau tim'(심장마비)과 구분","explanation":"심부전은 만성적 기능 저하, 심장마비는 급성입니다"},
{"mistake":"생활습관 관리 설명 부족","correction":"염분, 수분 제한, 매일 체중 측정 안내","explanation":"자가관리가 입원을 줄입니다"},
{"mistake":"증상 악화 신호 미설명","correction":"체중 급증, 호흡곤란 악화 시 내원 안내","explanation":"조기 대처가 중요합니다"}],
[{"ko":"심부전으로 약물 치료가 필요합니다.","vi":"Suy tim cần điều trị bằng thuốc.","situation":"formal"},
{"ko":"하루에 물을 1.5L 이하로 드세요.","vi":"Mỗi ngày uống không quá 1.5L nước.","situation":"formal"},
{"ko":"다리가 붓고 숨차면 바로 오세요.","vi":"Nếu chân sưng và khó thở thì đến ngay.","situation":"informal"}],
["이뇨제","부종","심장박동기"]),

t("roi-loan-nhip-tim","부정맥","rối loạn nhịp tim","不整脈","부(아닐 부) + 정(바를 정) + 맥(맥 맥)","bu-jeong-maek",
"심장 박동이 불규칙하거나 너무 빠르거나 느린 상태입니다. 두근거림, 어지럼증, 실신이 나타날 수 있습니다. 심방세동, 심실빈맥 등 다양한 유형이 있습니다. 통역 시 유형에 따른 위험도와 치료법(약물, 시술, 제세동기)을 설명해야 합니다.",
"Nhịp tim không đều, quá nhanh hoặc quá chậm",
"심장내과","한국에서 심방세동은 뇌졸중 위험을 높여 항응고제 복용이 필요할 수 있습니다. 맥박 측정 방법을 환자에게 교육하면 좋습니다.",
[{"mistake":"모든 부정맥을 위험하다고 설명","correction":"무해한 것부터 생명 위협까지 다양함을 설명","explanation":"환자의 불필요한 불안을 줄입니다"},
{"mistake":"심방세동의 뇌졸중 위험 미설명","correction":"혈전 형성으로 뇌졸중 위험, 항응고제 필요성 안내","explanation":"합병증 예방이 중요합니다"},
{"mistake":"전극도자절제술 설명 부족","correction":"시술로 완치 가능한 경우 있음을 안내","explanation":"약물 외 치료 옵션을 설명합니다"}],
[{"ko":"심방세동으로 항응고제가 필요합니다.","vi":"Rung nhĩ cần uống thuốc chống đông.","situation":"formal"},
{"ko":"전극도자절제술로 치료할 수 있습니다.","vi":"Có thể điều trị bằng đốt điện.","situation":"formal"},
{"ko":"가끔 두근거리는 건 크게 걱정 안 해도 돼요.","vi":"Thỉnh thoảng tim đập nhanh thì không cần lo lắng.","situation":"informal"}],
["심전도","홀터검사","심방세동"]),

t("hen-suyen","천식","hen suyễn","喘息","천(헐떡일 천) + 식(숨쉴 식)","cheon-sik",
"기관지가 만성적으로 염증을 일으켜 좁아지는 호흡기 질환입니다. 기침, 천명음, 호흡곤란이 반복됩니다. 흡입기 사용이 주 치료법입니다. 통역 시 흡입기 사용법, 악화 요인(알레르겐, 운동, 찬 공기) 회피, 응급 시 대처법을 교육해야 합니다.",
"Bệnh viêm mãn tính đường hô hấp gây ho, khò khè, khó thở",
"호흡기내과, 알레르기내과","한국에서 천식은 흔한 만성질환입니다. 흡입기 사용법이 중요하며, 베트남 환자에게 올바른 흡입 기술을 직접 시연하며 교육해야 합니다.",
[{"mistake":"흡입기 종류 구분 안 함","correction":"조절제(매일)와 완화제(응급) 구분 설명","explanation":"두 가지를 혼동하면 치료 효과가 떨어집니다"},
{"mistake":"흡입기 사용법 설명 생략","correction":"흡입 후 숨 참기, 입 헹구기 등 구체적 안내","explanation":"올바른 사용이 치료 효과를 좌우합니다"},
{"mistake":"악화 시 대처법 미설명","correction":"완화제 사용 후에도 호전 없으면 응급실 안내","explanation":"심한 발작은 생명을 위협할 수 있습니다"}],
[{"ko":"매일 아침저녁으로 흡입기를 사용하세요.","vi":"Hàng ngày sáng tối dùng ống hít.","situation":"formal"},
{"ko":"숨이 차면 이 파란색 흡입기를 쓰세요.","vi":"Nếu khó thở thì dùng ống hít màu xanh này.","situation":"formal"},
{"ko":"천식약 잘 쓰면 정상 생활 다 할 수 있어요.","vi":"Dùng thuốc hen đúng cách thì sống bình thường được.","situation":"informal"}],
["흡입기","폐기능검사","알레르기"]),

t("copd","만성폐쇄성폐질환","COPD","慢性閉塞性肺疾患",None,"man-seong-pye-swae-seong-pye-jil-hwan",
"기도가 좁아지고 폐가 손상되어 호흡이 어려워지는 만성 폐질환입니다. 주로 장기간 흡연이 원인입니다. 기침, 가래, 호흡곤란이 점점 악화됩니다. 통역 시 금연의 중요성, 흡입기 사용법, 급성악화 증상을 설명해야 합니다.",
"Bệnh phổi mãn tính do đường thở hẹp và phổi tổn thương, chủ yếu do hút thuốc",
"호흡기내과","한국에서 COPD는 흡연력이 긴 중년 이상 남성에게 많습니다. 금연이 가장 중요한 치료이며, 베트남 남성의 흡연율이 높아 금연 교육이 필요합니다.",
[{"mistake":"COPD를 천식과 혼동","correction":"COPD는 비가역적, 천식은 가역적 기도 폐쇄","explanation":"치료 방향이 다릅니다"},
{"mistake":"금연 강조 부족","correction":"금연이 질환 진행을 늦추는 유일한 방법임을 강조","explanation":"약물보다 금연이 중요합니다"},
{"mistake":"산소치료 설명 누락","correction":"진행된 경우 가정 산소치료가 필요할 수 있음","explanation":"중증 환자의 삶의 질을 높입니다"}],
[{"ko":"COPD로 매일 흡입기를 사용하셔야 합니다.","vi":"COPD cần dùng ống hít hàng ngày.","situation":"formal"},
{"ko":"담배를 끊으시는 게 가장 중요합니다.","vi":"Bỏ thuốc lá là quan trọng nhất.","situation":"formal"},
{"ko":"숨 많이 차면 산소 쓰셔야 할 수도 있어요.","vi":"Nếu quá khó thở có thể phải dùng oxy.","situation":"informal"}],
["폐기능검사","흡입기","금연"]),

t("viem-phoi-2","폐렴","viêm phổi","肺炎","폐(허파 폐) + 염(불탈 염)","pye-ryeom",
"폐에 염증이 생기는 감염병으로, 세균, 바이러스, 곰팡이 등이 원인입니다. 기침, 가래, 발열, 호흡곤란이 나타납니다. 항생제 치료가 기본이며 중증 시 입원이 필요합니다. 통역 시 원인균에 따른 치료 차이, 폐렴구균 백신 접종을 안내해야 합니다.",
"Nhiễm trùng phổi do vi khuẩn, virus hoặc nấm gây ho, sốt, khó thở",
"호흡기내과, 감염내과","한국에서 폐렴은 고령자 사망원인 상위입니다. 65세 이상은 폐렴구균 백신 무료 접종이 가능하며, 베트남 어르신에게 백신 접종을 권장합니다.",
[{"mistake":"모든 폐렴에 항생제 처방","correction":"바이러스성 폐렴은 항생제가 효과 없음을 설명","explanation":"원인에 따라 치료가 다릅니다"},
{"mistake":"중증도 평가 설명 부족","correction":"산소포화도, 의식상태에 따라 입원 결정","explanation":"고위험군은 즉시 입원이 필요합니다"},
{"mistake":"폐렴 예방 미설명","correction":"폐렴구균 백신, 인플루엔자 백신 접종 권고","explanation":"예방이 최선입니다"}],
[{"ko":"폐렴으로 입원 치료가 필요합니다.","vi":"Viêm phổi cần nhập viện điều trị.","situation":"formal"},
{"ko":"항생제를 끝까지 드셔야 합니다.","vi":"Phải uống kháng sinh đến hết.","situation":"formal"},
{"ko":"어르신은 폐렴 주사 맞으시는 게 좋아요.","vi":"Người cao tuổi nên tiêm vaccine phế cầu.","situation":"informal"}],
["항생제","흉부X선","폐렴구균백신"]),

t("benh-than-man","만성신부전","bệnh thận mạn","慢性腎不全","만(느릴 만) + 성(성품 성) + 신(콩팥 신) + 부(아닐 부) + 전(온전할 전)","man-seong-sin-bu-jeon",
"신장 기능이 점진적으로 저하되는 질환입니다. 당뇨, 고혈압이 주요 원인입니다. 말기에는 투석이나 이식이 필요합니다. 통역 시 신장 기능 단계(1~5기), 식이 제한(단백질, 칼륨, 인), 투석 종류를 설명해야 합니다.",
"Suy giảm chức năng thận tiến triển, giai đoạn cuối cần lọc máu hoặc ghép thận",
"신장내과","한국에서 만성신부전은 당뇨병성 신병증이 가장 흔한 원인입니다. 투석 시작 시기와 방법 선택에 환자의 이해와 동의가 중요합니다.",
[{"mistake":"신부전 단계 설명 부족","correction":"eGFR 수치와 1~5기 단계의 의미 설명","explanation":"환자가 자신의 상태를 이해해야 합니다"},
{"mistake":"식이 제한 내용 부정확","correction":"단백질, 칼륨, 인, 나트륨 제한 구체적 안내","explanation":"식이가 질환 진행에 영향을 미칩니다"},
{"mistake":"투석 종류 설명 생략","correction":"혈액투석, 복막투석의 차이와 장단점 안내","explanation":"환자가 선택할 수 있어야 합니다"}],
[{"ko":"신장 기능이 30%밖에 안 남았습니다.","vi":"Chức năng thận chỉ còn 30%.","situation":"formal"},
{"ko":"투석 준비를 시작해야 합니다.","vi":"Cần bắt đầu chuẩn bị lọc máu.","situation":"formal"},
{"ko":"짜게 드시면 신장에 안 좋아요.","vi":"Ăn mặn không tốt cho thận.","situation":"informal"}],
["투석","크레아티닌","신장이식"]),

t("loc-mau","혈액투석","lọc máu","血液透析","혈(피 혈) + 액(진액 액) + 투(통할 투) + 석(분석할 석)","hyeo-raek-tu-seok",
"말기 신부전 환자의 혈액에서 노폐물과 수분을 제거하는 치료입니다. 보통 주 3회, 회당 4시간 정도 시행합니다. 동정맥루나 카테터를 통해 혈액을 빼고 기계로 걸러 다시 넣습니다. 통역 시 투석 일정, 식이/수분 제한, 동정맥루 관리를 설명해야 합니다.",
"Phương pháp lọc chất thải và nước thừa từ máu cho bệnh nhân suy thận giai đoạn cuối",
"신장내과","한국에서 혈액투석은 가장 흔한 신대체요법입니다. 베트남 환자에게 투석 과정, 생활 변화, 합병증 관리를 충분히 설명해야 합니다.",
[{"mistake":"투석을 일시적 치료로 설명","correction":"평생 또는 이식까지 지속해야 함을 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"동정맥루 관리 설명 부족","correction":"무거운 것 들지 않기, 혈압 측정 금지 등 안내","explanation":"동정맥루가 투석의 생명선입니다"},
{"mistake":"투석 중 증상 미설명","correction":"저혈압, 근육경련 등 발생 가능성 안내","explanation":"환자가 미리 알면 불안이 줄어듭니다"}],
[{"ko":"주 3회 혈액투석을 받으셔야 합니다.","vi":"Cần lọc máu 3 lần mỗi tuần.","situation":"formal"},
{"ko":"투석하는 팔로 무거운 것 들지 마세요.","vi":"Đừng mang vật nặng bằng tay có lỗ thông.","situation":"formal"},
{"ko":"투석하면서도 일상생활 할 수 있어요.","vi":"Vẫn có thể sinh hoạt bình thường khi lọc máu.","situation":"informal"}],
["동정맥루","신부전","복막투석"]),

t("tieu-duong-type2","제2형당뇨","tiểu đường type 2","第二型糖尿",None,"je-i-hyeong-dang-nyo",
"인슐린 저항성으로 혈당 조절이 안 되는 대사질환입니다. 비만, 운동 부족, 유전이 위험요인입니다. 식이, 운동, 약물로 관리합니다. 통역 시 혈당 목표치, 저혈당 증상과 대처, 합병증 예방을 교육해야 합니다.",
"Bệnh đái tháo đường do kháng insulin, quản lý bằng chế độ ăn, tập thể dục và thuốc",
"내분비내과","한국에서 당뇨병은 성인 10명 중 1명이 앓는 흔한 질환입니다. 베트남 환자에게 혈당 자가측정, 발 관리, 정기 검진의 중요성을 교육합니다.",
[{"mistake":"당뇨병을 완치 가능하다고 설명","correction":"평생 관리가 필요한 만성질환임을 안내","explanation":"현실적인 기대를 갖게 합니다"},
{"mistake":"저혈당 대처법 미설명","correction":"식은땀, 떨림 시 사탕/주스 섭취 안내","explanation":"저혈당은 응급상황이 될 수 있습니다"},
{"mistake":"합병증 설명 부족","correction":"눈, 신장, 신경, 혈관 합병증 검사 필요성 안내","explanation":"정기 검진으로 합병증을 예방합니다"}],
[{"ko":"당화혈색소를 7% 이하로 유지해야 합니다.","vi":"Cần duy trì HbA1c dưới 7%.","situation":"formal"},
{"ko":"저혈당 오면 사탕을 바로 드세요.","vi":"Nếu hạ đường huyết thì ăn kẹo ngay.","situation":"formal"},
{"ko":"발에 상처 나면 바로 보여주세요.","vi":"Nếu chân bị thương thì cho bác sĩ xem ngay.","situation":"informal"}],
["혈당","인슐린","당화혈색소"]),

t("tang-huyet-ap","고혈압","tăng huyết áp","高血壓","고(높을 고) + 혈(피 혈) + 압(누를 압)","go-hyeo-rap",
"혈압이 지속적으로 높은 상태(140/90mmHg 이상)입니다. 뇌졸중, 심근경색, 신부전의 위험요인입니다. 대부분 증상이 없어 '침묵의 살인자'라고 불립니다. 통역 시 가정 혈압 측정법, 약물 복용의 중요성, 생활습관 개선을 교육해야 합니다.",
"Huyết áp cao liên tục (trên 140/90mmHg), yếu tố nguy cơ đột quỵ và nhồi máu cơ tim",
"내과, 심장내과","한국에서 고혈압은 성인 3명 중 1명이 앓습니다. 베트남 음식의 나트륨 함량이 높아 식이 교육이 특히 중요합니다.",
[{"mistake":"증상 없으면 치료 불필요하다고 오해","correction":"증상 없어도 합병증 예방 위해 치료 필요","explanation":"고혈압은 대부분 무증상입니다"},
{"mistake":"약물 임의 중단 가능성","correction":"의사 상담 없이 약 끊으면 안 됨을 강조","explanation":"갑자기 중단하면 위험합니다"},
{"mistake":"가정 혈압 측정법 미설명","correction":"아침 식전, 저녁 취침 전 측정 방법 안내","explanation":"가정 혈압이 더 정확합니다"}],
[{"ko":"혈압이 160/100으로 높습니다.","vi":"Huyết áp cao 160/100.","situation":"formal"},
{"ko":"혈압약은 평생 드셔야 합니다.","vi":"Thuốc huyết áp phải uống suốt đời.","situation":"formal"},
{"ko":"짜게 안 드시면 혈압 많이 내려가요.","vi":"Không ăn mặn thì huyết áp giảm nhiều.","situation":"informal"}],
["혈압측정","나트륨","뇌졸중"]),

t("mo-mau-cao","고지혈증","mỡ máu cao","高脂血症","고(높을 고) + 지(기름 지) + 혈(피 혈) + 증(증거 증)","go-ji-hyeol-jeung",
"혈액 내 콜레스테롤이나 중성지방이 높은 상태입니다. 동맥경화, 심혈관질환의 위험요인입니다. 식이요법, 운동, 약물(스타틴)로 관리합니다. 통역 시 LDL/HDL 콜레스테롤의 의미, 식이 개선, 약물 부작용을 설명해야 합니다.",
"Mức cholesterol hoặc triglyceride trong máu cao, yếu tố nguy cơ bệnh tim mạch",
"내과, 심장내과","한국에서 고지혈증은 건강검진에서 흔히 발견됩니다. 베트남 환자에게 '좋은 콜레스테롤(HDL)'과 '나쁜 콜레스테롤(LDL)' 개념을 쉽게 설명합니다.",
[{"mistake":"총콜레스테롤만 설명","correction":"LDL, HDL, 중성지방 각각의 의미와 목표치 설명","explanation":"각 수치의 의미가 다릅니다"},
{"mistake":"약물 부작용 설명 부족","correction":"스타틴의 근육통 부작용 가능성 안내","explanation":"이상 증상 시 보고하도록 합니다"},
{"mistake":"식이요법 구체적 안내 없음","correction":"포화지방 제한, 오메가3 섭취 권장 등 구체적 안내","explanation":"생활습관이 수치에 영향을 미칩니다"}],
[{"ko":"LDL 콜레스테롤을 100 이하로 낮춰야 합니다.","vi":"Cần giảm LDL cholesterol xuống dưới 100.","situation":"formal"},
{"ko":"콜레스테롤 약을 드실 때 근육통이 있으면 말씀하세요.","vi":"Nếu đau cơ khi uống thuốc cholesterol thì báo bác sĩ.","situation":"formal"},
{"ko":"기름진 거 줄이면 수치 많이 좋아져요.","vi":"Giảm đồ dầu mỡ thì chỉ số sẽ tốt lên nhiều.","situation":"informal"}],
["콜레스테롤","동맥경화","스타틴"]),
]

added = [n for n in new if n['slug'] not in existing]
data.extend(added)
print(f"추가: {len(added)}개, 총: {len(data)}개")
with open(path, 'w', encoding='utf-8') as f: json.dump(data, f, ensure_ascii=False, indent=2)
