#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical 601-650번 용어 추가 (신경과, 순환기내과, 호흡기내과)"""

import json

def t(s,k,v,hj,hjr,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":hj,"hanjaReading":hjr,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    # 신경과 (601-620)
    t("dot-quy-thieu-mau-cuc-bo",
      "허혈성 뇌졸중",
      "đột quỵ thiếu máu cục bộ",
      "虛血性腦卒中",
      "허(빌 허) + 혈(피 혈) + 성(성질 성) + 뇌(뇌 뇌) + 졸(갑자기 졸) + 중(맞을 중)",
      "뇌혈관이 막혀서 뇌 조직에 혈액 공급이 차단되어 발생하는 뇌졸중입니다. 전체 뇌졸중의 약 80%를 차지하며, 골든타임(4.5시간) 내 혈전용해제 투여가 매우 중요합니다. 통역 시 '허혈성'이 '피가 부족한'이라는 의미임을 명확히 전달하고, 출혈성 뇌졸중과 구별해야 합니다. 증상 발현 시간을 정확히 파악하는 것이 치료 결정에 핵심입니다.",
      "Đột quỵ xảy ra khi mạch máu não bị tắc, cắt đứt nguồn cung cấp máu cho mô não. Chiếm khoảng 80% các ca đột quỵ.",
      "신경과, 응급의학과, 재활의학과",
      "베트남에서는 뇌졸중을 'tai biến mạch máu não'(뇌혈관 사고)라고도 부르며, 'đột quỵ'는 더 의학적인 표현입니다. 한국의 뇌졸중 치료 시스템은 매우 발달해 있어 골든타임 내 도착 시 좋은 예후를 기대할 수 있음을 설명해야 합니다.",
      [{"mistake":"허혈성과 출혈성 구분 없이 번역","correction":"허혈성(thiếu máu cục bộ)과 출혈성(xuất huyết) 명확히 구분","explanation":"치료 방법이 완전히 다르므로 정확한 구분이 필수입니다"},
       {"mistake":"골든타임 개념 설명 누락","correction":"증상 발현 후 4.5시간 내 치료의 중요성 강조","explanation":"시간이 치료 성공률과 직결됩니다"},
       {"mistake":"전조증상 설명 생략","correction":"FAST(얼굴, 팔, 언어, 시간) 증상 설명","explanation":"조기 발견이 예후를 결정합니다"}],
      [{"ko":"허혈성 뇌졸중입니다. 뇌혈관이 막혔습니다. 혈전용해제 투여가 필요합니다.","vi":"Đây là đột quỵ thiếu máu cục bộ. Mạch máu não bị tắc. Cần dùng thuốc tiêu huyết khối.","situation":"formal"},
       {"ko":"뇌졸중이에요. 피가 안 통해서 그래요. 빨리 치료해야 해요.","vi":"Bị đột quỵ. Do máu không lưu thông được. Phải điều trị nhanh.","situation":"onsite"},
       {"ko":"뇌에 피가 안 가서 쓰러진 거예요. 시간이 중요해요!","vi":"Ngã do máu không đến não. Thời gian rất quan trọng!","situation":"informal"}],
      ["뇌졸중", "혈전", "마비", "재활"]),

    t("xuat-huyet-nao",
      "뇌출혈",
      "xuất huyết não",
      "腦出血",
      "뇌(뇌 뇌) + 출(날 출) + 혈(피 혈)",
      "뇌혈관이 터져서 뇌 조직 내부로 피가 새어 나오는 상태입니다. 고혈압이 가장 흔한 원인이며, 갑작스러운 심한 두통, 구토, 의식 저하가 특징입니다. 통역 시 출혈 위치와 양에 따라 예후가 크게 달라질 수 있음을 설명하고, 혈압 관리의 중요성을 강조해야 합니다. 수술이 필요한 경우도 있습니다.",
      "Tình trạng mạch máu não vỡ và máu chảy vào mô não. Nguyên nhân thường gặp nhất là tăng huyết áp.",
      "신경외과, 신경과, 응급의학과",
      "베트남에서는 고혈압 관리가 잘 되지 않는 경우가 많아 뇌출혈 위험이 높습니다. 한국에서 근무하는 베트남 근로자들에게 정기적인 혈압 측정과 관리의 중요성을 통역 시 강조해야 합니다.",
      [{"mistake":"뇌출혈과 뇌경색을 혼동","correction":"출혈(xuất huyết)은 피가 터진 것, 경색(nhồi máu)은 막힌 것","explanation":"치료 접근이 완전히 다릅니다"},
       {"mistake":"수술 필요성 설명 시 공포 유발","correction":"출혈 양과 위치에 따라 수술 여부가 결정됨을 차분히 설명","explanation":"모든 뇌출혈이 수술을 요하는 것은 아닙니다"},
       {"mistake":"고혈압과의 관계 설명 누락","correction":"고혈압이 주요 원인임을 강조하고 예방 중요성 설명","explanation":"재발 방지를 위해 혈압 관리가 필수입니다"}],
      [{"ko":"뇌출혈이 발생했습니다. 뇌혈관이 터져서 출혈이 있습니다.","vi":"Đã xảy ra xuất huyết não. Mạch máu não vỡ và đang chảy máu.","situation":"formal"},
       {"ko":"뇌에서 피가 났어요. 혈압이 너무 높아서 그래요.","vi":"Não bị chảy máu. Do huyết áp quá cao.","situation":"onsite"},
       {"ko":"머리에서 피 터진 거예요. 혈압 관리 안 해서요.","vi":"Vỡ mạch máu trong đầu. Do không kiểm soát huyết áp.","situation":"informal"}],
      ["고혈압", "뇌졸중", "두통", "의식저하"]),

    t("dong-kinh",
      "간질/뇌전증",
      "động kinh",
      "癲癇",
      "간(미칠 간) + 질(병 질)",
      "뇌의 비정상적인 전기 활동으로 인해 반복적인 발작이 나타나는 신경계 질환입니다. 현재 '뇌전증'이 공식 명칭이지만, 일반인들은 여전히 '간질'이라는 용어를 많이 사용합니다. 통역 시 발작 유형(전신 발작, 부분 발작)에 따른 증상 차이를 설명하고, 약물로 잘 조절될 수 있음을 강조하여 환자의 불안을 줄여야 합니다.",
      "Bệnh thần kinh với các cơn co giật tái phát do hoạt động điện bất thường trong não.",
      "신경과, 소아신경과",
      "베트남에서는 간질에 대한 사회적 편견이 심해 'động kinh' 대신 완곡한 표현을 쓰는 경우가 있습니다. 한국에서는 '뇌전증'으로 명칭이 변경되어 질환에 대한 인식 개선이 이루어지고 있음을 설명할 수 있습니다.",
      [{"mistake":"간질을 정신질환으로 오해하게 설명","correction":"뇌의 전기 신호 이상임을 명확히 설명","explanation":"정신질환이 아닌 신경계 질환입니다"},
       {"mistake":"발작 대처법 설명 누락","correction":"발작 시 안전 확보, 억지로 입 벌리지 않기 등 설명","explanation":"잘못된 응급처치가 더 위험할 수 있습니다"},
       {"mistake":"완치 불가능하다고 단정","correction":"약물로 70% 이상 조절 가능함을 설명","explanation":"적절한 치료로 정상 생활이 가능합니다"}],
      [{"ko":"뇌전증 진단입니다. 뇌파 검사에서 이상 소견이 있습니다. 약물 치료가 필요합니다.","vi":"Chẩn đoán động kinh. Có bất thường trên điện não đồ. Cần điều trị bằng thuốc.","situation":"formal"},
       {"ko":"간질이에요. 뇌의 전기 신호 문제예요. 약 먹으면 조절돼요.","vi":"Bị động kinh. Là vấn đề tín hiệu điện trong não. Uống thuốc sẽ kiểm soát được.","situation":"onsite"},
       {"ko":"경련 일으키는 병이에요. 약 잘 먹으면 괜찮아요.","vi":"Bệnh gây co giật. Uống thuốc đều đặn sẽ ổn.","situation":"informal"}],
      ["발작", "경련", "뇌파검사", "항경련제"]),

    t("benh-parkinson",
      "파킨슨병",
      "bệnh Parkinson",
      None,
      None,
      "뇌의 도파민 신경세포가 점진적으로 손상되어 발생하는 퇴행성 신경질환입니다. 손 떨림, 근육 경직, 동작 느려짐, 자세 불안정이 주요 증상입니다. 통역 시 파킨슨병이 치매와 다른 질환임을 구별하고, 약물과 재활로 증상을 상당히 조절할 수 있음을 설명해야 합니다. 조기 발견과 꾸준한 치료가 중요합니다.",
      "Bệnh thoái hóa thần kinh do tổn thương tiến triển của tế bào thần kinh sản xuất dopamine trong não.",
      "신경과, 재활의학과",
      "베트남에서는 파킨슨병에 대한 인식이 낮아 단순 노화 증상으로 오해하는 경우가 많습니다. 한국에서는 파킨슨병 전문 클리닉이 발달해 있어 체계적인 치료를 받을 수 있음을 설명할 수 있습니다.",
      [{"mistake":"파킨슨병을 치매로 번역","correction":"파킨슨병(Parkinson)과 치매(sa sút trí tuệ)는 다른 질환","explanation":"파킨슨병은 운동장애가 주 증상이고, 치매는 인지장애가 주 증상입니다"},
       {"mistake":"떨림만 파킨슨 증상으로 설명","correction":"경직, 서동증, 자세불안정 등 4대 증상 모두 설명","explanation":"떨림이 없는 파킨슨병도 있습니다"},
       {"mistake":"완치 가능하다고 오해 유발","correction":"완치는 어렵지만 증상 조절이 가능함을 설명","explanation":"현실적인 치료 목표를 이해시켜야 합니다"}],
      [{"ko":"파킨슨병 진단입니다. 도파민 부족으로 인한 신경퇴행성 질환입니다.","vi":"Chẩn đoán bệnh Parkinson. Đây là bệnh thoái hóa thần kinh do thiếu dopamine.","situation":"formal"},
       {"ko":"파킨슨병이에요. 손 떨리고 움직임 느려지는 병이에요. 약으로 조절해요.","vi":"Bị bệnh Parkinson. Là bệnh gây run tay và chậm vận động. Kiểm soát bằng thuốc.","situation":"onsite"},
       {"ko":"파킨슨이에요. 치매 아니에요. 약 먹으면 많이 좋아져요.","vi":"Bị Parkinson. Không phải sa sút trí tuệ. Uống thuốc sẽ đỡ nhiều.","situation":"informal"}],
      ["떨림", "도파민", "신경퇴행", "재활"]),

    t("benh-alzheimer",
      "알츠하이머병",
      "bệnh Alzheimer",
      None,
      None,
      "뇌세포가 점진적으로 손상되어 기억력, 사고력, 행동에 장애가 나타나는 가장 흔한 치매 유형입니다. 초기에는 최근 기억 저하로 시작하여 점차 일상생활 수행 능력이 떨어집니다. 통역 시 알츠하이머가 단순 노화가 아닌 뇌 질환임을 명확히 하고, 조기 진단과 치료의 중요성을 설명해야 합니다.",
      "Loại sa sút trí tuệ phổ biến nhất, gây suy giảm tiến triển về trí nhớ, tư duy và hành vi do tổn thương tế bào não.",
      "신경과, 정신건강의학과",
      "베트남에서는 치매를 '미친 병'으로 오해하거나, 단순 노화로 여겨 치료를 받지 않는 경우가 많습니다. 한국에서는 치매국가책임제가 시행되어 치매안심센터에서 무료 검진을 받을 수 있음을 안내할 수 있습니다.",
      [{"mistake":"알츠하이머를 단순 건망증으로 번역","correction":"뇌세포 손상으로 인한 진행성 질환임을 설명","explanation":"건망증과 치매는 본질적으로 다릅니다"},
       {"mistake":"치료 불가능하다고 단정","correction":"진행을 늦추는 약물과 비약물 치료가 있음을 설명","explanation":"조기 개입으로 삶의 질을 유지할 수 있습니다"},
       {"mistake":"환자 앞에서 치매라고 직접적으로 말함","correction":"상황에 따라 '기억력 문제' 등 완곡한 표현 사용 고려","explanation":"환자의 자존감을 고려해야 합니다"}],
      [{"ko":"알츠하이머병 초기 단계입니다. 기억력 저하를 늦추는 치료를 시작하겠습니다.","vi":"Đây là giai đoạn đầu bệnh Alzheimer. Sẽ bắt đầu điều trị để làm chậm suy giảm trí nhớ.","situation":"formal"},
       {"ko":"알츠하이머 치매예요. 기억력이 계속 나빠지는 병이에요. 약으로 늦출 수 있어요.","vi":"Bị Alzheimer. Là bệnh làm trí nhớ ngày càng kém. Có thể làm chậm bằng thuốc.","situation":"onsite"},
       {"ko":"치매 시작이에요. 빨리 치료하면 오래 버틸 수 있어요.","vi":"Bắt đầu sa sút trí tuệ. Điều trị sớm thì có thể duy trì lâu hơn.","situation":"informal"}],
      ["치매", "기억력저하", "인지장애", "뇌위축"]),

    t("dau-nua-dau",
      "편두통",
      "đau nửa đầu",
      "偏頭痛",
      "편(치우칠 편) + 두(머리 두) + 통(아플 통)",
      "주로 머리 한쪽에서 발생하는 중등도 이상의 박동성 두통으로, 구역, 구토, 빛/소리 민감성을 동반합니다. 전조 증상(시각 장애 등)이 있는 경우도 있습니다. 통역 시 일반 두통과 편두통의 차이를 명확히 하고, 유발 요인(스트레스, 수면 부족, 특정 음식)을 파악하는 것이 중요함을 설명해야 합니다.",
      "Đau đầu vừa đến nặng thường ở một bên đầu, kèm buồn nôn, nôn và nhạy cảm với ánh sáng/âm thanh.",
      "신경과, 두통클리닉",
      "베트남에서는 편두통을 단순 두통으로 여겨 진통제만 복용하는 경우가 많습니다. 한국에서는 편두통 전문 치료제(트립탄)와 예방약이 발달해 있어 전문 치료를 받으면 삶의 질이 크게 개선됨을 설명할 수 있습니다.",
      [{"mistake":"편두통을 단순 두통으로 번역","correction":"편두통(đau nửa đầu/migraine)은 특정 증후군임을 설명","explanation":"일반 두통과 치료 접근이 다릅니다"},
       {"mistake":"전조증상 설명 누락","correction":"시각 장애, 감각 이상 등 전조증상도 설명","explanation":"전조 편두통은 뇌졸중과 감별이 필요합니다"},
       {"mistake":"진통제만으로 충분하다고 설명","correction":"편두통 전문 치료제와 예방 치료 안내","explanation":"만성화 예방을 위해 전문 치료가 필요합니다"}],
      [{"ko":"편두통입니다. 한쪽 머리에 박동성 통증이 특징입니다. 전문 치료제를 처방합니다.","vi":"Đây là đau nửa đầu. Đặc trưng là đau nhói một bên đầu. Sẽ kê thuốc điều trị chuyên biệt.","situation":"formal"},
       {"ko":"편두통이에요. 일반 두통약으로 안 나아요. 편두통약 써야 해요.","vi":"Bị đau nửa đầu. Thuốc đau đầu thường không hiệu quả. Cần dùng thuốc chuyên trị.","situation":"onsite"},
       {"ko":"머리 한쪽이 쿵쿵 아프죠? 편두통이에요. 전문약 있어요.","vi":"Đau nhói một bên đầu phải không? Là đau nửa đầu. Có thuốc chuyên trị.","situation":"informal"}],
      ["두통", "구역", "전조증상", "트립탄"]),

    t("thoat-vi-dia-dem",
      "추간판탈출증",
      "thoát vị đĩa đệm",
      "椎間板脫出症",
      "추(등뼈 추) + 간(사이 간) + 판(판 판) + 탈(벗을 탈) + 출(날 출) + 증(증상 증)",
      "척추 뼈 사이의 디스크(추간판)가 튀어나와 신경을 압박하는 상태로, 흔히 '디스크'라고 부릅니다. 허리 통증, 다리 저림, 근력 저하가 나타납니다. 통역 시 '디스크'가 질병명이 아니라 해부학적 구조물이며, 정확한 명칭은 '추간판탈출증'임을 설명해야 합니다. 대부분 보존적 치료로 호전됩니다.",
      "Tình trạng đĩa đệm giữa các đốt sống lồi ra và chèn ép dây thần kinh, thường gọi là 'thoát vị đĩa đệm'.",
      "신경외과, 정형외과, 재활의학과",
      "베트남에서는 허리 통증 시 전통 마사지나 침술에 의존하는 경우가 많습니다. 한국에서는 MRI를 통한 정확한 진단 후 물리치료, 약물, 주사, 수술 등 단계적 치료가 가능함을 설명할 수 있습니다.",
      [{"mistake":"디스크를 질병명으로 사용","correction":"'추간판탈출증(thoát vị đĩa đệm)'이 정확한 명칭","explanation":"디스크는 구조물 이름이지 질병명이 아닙니다"},
       {"mistake":"무조건 수술이 필요하다고 설명","correction":"대부분 보존적 치료로 호전됨을 설명","explanation":"수술은 보존적 치료 실패 시 고려합니다"},
       {"mistake":"허리 디스크와 목 디스크 구분 없이 설명","correction":"요추(lưng)와 경추(cổ) 위치를 명확히","explanation":"증상과 치료 접근이 다릅니다"}],
      [{"ko":"요추 추간판탈출증입니다. 디스크가 신경을 누르고 있습니다.","vi":"Đây là thoát vị đĩa đệm thắt lưng. Đĩa đệm đang chèn ép dây thần kinh.","situation":"formal"},
       {"ko":"허리 디스크예요. 물리치료 먼저 하고, 안 나으면 주사나 수술 고려해요.","vi":"Bị thoát vị đĩa đệm lưng. Vật lý trị liệu trước, không đỡ thì tiêm hoặc mổ.","situation":"onsite"},
       {"ko":"디스크 튀어나온 거예요. 대부분 수술 없이 나아요.","vi":"Đĩa đệm lồi ra. Phần lớn khỏi không cần mổ.","situation":"informal"}],
      ["허리통증", "좌골신경통", "물리치료", "척추"]),

    t("hep-ong-song",
      "척추관협착증",
      "hẹp ống sống",
      "脊椎管狹窄症",
      "척(등뼈 척) + 추(등뼈 추) + 관(대롱 관) + 협(좁을 협) + 착(좁을 착) + 증(증상 증)",
      "척추 중앙의 신경이 지나가는 통로(척추관)가 좁아져서 신경을 압박하는 질환입니다. 주로 노화로 인해 발생하며, 오래 걷거나 서 있으면 다리가 저리고 아파서 쉬어야 하는 '간헐적 파행'이 특징입니다. 통역 시 디스크와 협착증의 차이를 설명하고, 수술 외에도 다양한 치료 옵션이 있음을 안내해야 합니다.",
      "Bệnh lý khi ống sống chứa dây thần kinh bị thu hẹp và chèn ép thần kinh, thường do lão hóa.",
      "신경외과, 정형외과, 재활의학과",
      "베트남에서는 노인들이 허리 통증을 당연한 노화 현상으로 받아들여 치료를 미루는 경향이 있습니다. 한국에서는 협착증에 대한 비수술적 치료(약물, 물리치료, 신경차단술)와 최소침습 수술이 발달해 있음을 설명할 수 있습니다.",
      [{"mistake":"협착증과 디스크를 같은 질환으로 설명","correction":"협착증(hẹp ống sống)은 통로가 좁아진 것, 디스크는 튀어나온 것","explanation":"발생 기전과 치료 접근이 다릅니다"},
       {"mistake":"간헐적 파행 설명 누락","correction":"걸으면 아프고 쉬면 나아지는 특징적 증상 설명","explanation":"진단과 치료 효과 판정에 중요한 증상입니다"},
       {"mistake":"수술만이 유일한 치료로 설명","correction":"비수술적 치료 옵션도 함께 안내","explanation":"환자 상태에 따라 적합한 치료가 다릅니다"}],
      [{"ko":"척추관협착증입니다. 신경이 지나가는 통로가 좁아졌습니다.","vi":"Đây là hẹp ống sống. Đường đi của dây thần kinh bị thu hẹp.","situation":"formal"},
       {"ko":"척추 협착증이에요. 오래 걸으면 다리 저리고 쉬면 나아지죠?","vi":"Bị hẹp ống sống. Đi lâu thì tê chân, nghỉ thì đỡ phải không?","situation":"onsite"},
       {"ko":"신경 지나가는 길이 좁아진 거예요. 디스크랑 달라요.","vi":"Đường thần kinh đi bị hẹp. Khác với thoát vị đĩa đệm.","situation":"informal"}],
      ["허리통증", "간헐적파행", "신경압박", "척추"]),

    t("viem-mang-nao",
      "뇌수막염",
      "viêm màng não",
      "腦髓膜炎",
      "뇌(뇌 뇌) + 수(골 수) + 막(막 막) + 염(불꽃 염)",
      "뇌와 척수를 둘러싼 막(수막)에 염증이 생긴 상태로, 세균성과 바이러스성으로 나뉩니다. 심한 두통, 발열, 목 경직이 특징적 증상입니다. 통역 시 세균성 뇌수막염은 응급 상황으로 즉각적인 항생제 치료가 필요함을 강조해야 합니다. 바이러스성은 상대적으로 경과가 양호합니다.",
      "Tình trạng viêm màng bao quanh não và tủy sống, chia thành viêm màng não do vi khuẩn và do virus.",
      "신경과, 감염내과, 응급의학과",
      "베트남에서는 뇌수막염 예방접종률이 지역에 따라 차이가 있습니다. 한국에서 근무하는 베트남 근로자들에게 필수 예방접종 일정과 증상 발생 시 즉시 병원 방문의 중요성을 안내해야 합니다.",
      [{"mistake":"세균성과 바이러스성 구분 없이 설명","correction":"세균성(do vi khuẩn)은 응급, 바이러스성(do virus)은 상대적 경증","explanation":"치료 긴급성과 예후가 크게 다릅니다"},
       {"mistake":"목 경직 증상 설명 누락","correction":"고개를 숙이기 어려운 목 경직(cứng cổ)은 핵심 증상","explanation":"뇌수막염 의심의 중요한 단서입니다"},
       {"mistake":"예방접종 안내 누락","correction":"수막구균, 폐렴구균 등 예방접종 가능함을 안내","explanation":"특히 단체 생활 시 예방이 중요합니다"}],
      [{"ko":"세균성 뇌수막염 의심입니다. 즉시 항생제 투여가 필요합니다.","vi":"Nghi ngờ viêm màng não do vi khuẩn. Cần dùng kháng sinh ngay lập tức.","situation":"formal"},
       {"ko":"뇌수막염이에요. 뇌를 싸고 있는 막에 염증이 생긴 거예요.","vi":"Bị viêm màng não. Là viêm màng bao quanh não.","situation":"onsite"},
       {"ko":"뇌막에 염증 생긴 거예요. 빨리 치료해야 해요.","vi":"Viêm màng não. Phải điều trị nhanh.","situation":"informal"}],
      ["두통", "발열", "목경직", "감염"]),

    t("u-nao",
      "뇌종양",
      "u não",
      "腦腫瘍",
      "뇌(뇌 뇌) + 종(종기 종) + 양(덩이 양)",
      "뇌에서 발생하거나 다른 장기에서 전이된 종양입니다. 양성과 악성으로 구분되며, 위치와 크기에 따라 두통, 구역, 시력 장애, 경련, 마비 등 다양한 증상이 나타납니다. 통역 시 '종양'이라는 단어가 환자에게 큰 충격을 줄 수 있으므로, 양성과 악성의 차이를 설명하고 치료 가능성을 함께 전달해야 합니다.",
      "Khối u phát sinh trong não hoặc di căn từ cơ quan khác, chia thành lành tính và ác tính.",
      "신경외과, 종양내과, 방사선종양학과",
      "베트남에서는 암 진단에 대한 두려움이 커서 정기 검진을 피하는 경향이 있습니다. 한국에서는 뇌종양 치료(수술, 방사선, 항암)가 발달해 있어 조기 발견 시 좋은 예후를 기대할 수 있음을 설명할 수 있습니다.",
      [{"mistake":"종양을 무조건 암으로 번역","correction":"양성(lành tính)과 악성(ác tính) 구분 필요","explanation":"양성 종양은 암이 아니며 치료 예후가 좋습니다"},
       {"mistake":"위치의 중요성 설명 누락","correction":"종양 위치에 따라 수술 가능 여부와 예후가 달라짐 설명","explanation":"같은 크기라도 위치에 따라 심각도가 다릅니다"},
       {"mistake":"치료 불가능하다는 인상 전달","correction":"수술, 방사선, 항암 등 다양한 치료 옵션 안내","explanation":"희망을 유지하면서 현실적 정보를 전달해야 합니다"}],
      [{"ko":"뇌종양이 발견되었습니다. 양성으로 보이며, 수술로 제거 가능합니다.","vi":"Đã phát hiện u não. Có vẻ lành tính và có thể phẫu thuật cắt bỏ.","situation":"formal"},
       {"ko":"뇌에 혹이 있어요. 암인지 아닌지는 더 검사해 봐야 해요.","vi":"Có khối u trong não. Cần xét nghiệm thêm để biết có phải ung thư không.","situation":"onsite"},
       {"ko":"머리에 뭐가 자랐어요. 일단 더 검사해 봐요.","vi":"Có gì đó mọc trong đầu. Cần kiểm tra thêm.","situation":"informal"}],
      ["두통", "종양", "수술", "방사선치료"]),

    # 순환기내과 (621-635)
    t("nhoi-mau-co-tim",
      "심근경색",
      "nhồi máu cơ tim",
      "心筋梗塞",
      "심(마음 심) + 근(힘줄 근) + 경(막힐 경) + 색(막힐 색)",
      "심장 근육에 혈액을 공급하는 관상동맥이 막혀서 심장 근육이 괴사하는 응급 상황입니다. 가슴 통증, 호흡곤란, 식은땀이 특징이며, 골든타임(2시간) 내 혈관 개통이 중요합니다. 통역 시 즉각적인 119 신고와 심폐소생술의 중요성을 강조하고, '체한 것 같다'는 비전형적 증상도 심근경색일 수 있음을 설명해야 합니다.",
      "Tình huống cấp cứu khi động mạch vành cung cấp máu cho cơ tim bị tắc, gây hoại tử cơ tim.",
      "심장내과, 응급의학과, 중환자의학과",
      "베트남에서는 가슴 통증을 위장 문제로 오해하는 경우가 많습니다. 한국의 응급의료 시스템은 심근경색 대응에 특화되어 있어 119 신고 후 빠른 시술이 가능함을 설명할 수 있습니다.",
      [{"mistake":"심근경색을 심장마비와 동일시","correction":"심근경색(nhồi máu)은 혈관 막힘, 심장마비(ngừng tim)는 심장 정지","explanation":"심근경색은 심장마비의 원인 중 하나입니다"},
       {"mistake":"골든타임 강조 누락","correction":"증상 발생 후 2시간 내 치료의 중요성 설명","explanation":"시간이 지날수록 심장 근육 손상이 커집니다"},
       {"mistake":"비전형 증상 설명 누락","correction":"소화불량, 턱/팔 통증도 심근경색 증상일 수 있음 설명","explanation":"특히 여성, 당뇨 환자에서 비전형적 증상이 흔합니다"}],
      [{"ko":"급성 심근경색입니다. 관상동맥이 막혔습니다. 즉시 시술이 필요합니다.","vi":"Đây là nhồi máu cơ tim cấp. Động mạch vành bị tắc. Cần can thiệp ngay lập tức.","situation":"formal"},
       {"ko":"심근경색이에요. 심장 혈관이 막힌 거예요. 빨리 뚫어야 해요.","vi":"Bị nhồi máu cơ tim. Mạch máu tim bị tắc. Cần thông nhanh.","situation":"onsite"},
       {"ko":"심장 혈관 막힌 거예요. 응급이에요!","vi":"Mạch máu tim bị tắc. Cấp cứu!","situation":"informal"}],
      ["흉통", "관상동맥", "스텐트", "심폐소생술"]),

    t("dau-that-nguc",
      "협심증",
      "đau thắt ngực",
      "狹心症",
      "협(좁을 협) + 심(마음 심) + 증(증상 증)",
      "관상동맥이 좁아져 심장 근육에 충분한 혈액이 공급되지 않아 가슴 통증이 발생하는 상태입니다. 운동이나 스트레스 시 악화되고 휴식하면 호전됩니다. 통역 시 협심증이 심근경색의 경고 신호일 수 있음을 설명하고, 니트로글리세린 설하정 사용법을 정확히 전달해야 합니다.",
      "Tình trạng đau ngực do động mạch vành bị hẹp, không cung cấp đủ máu cho cơ tim.",
      "심장내과, 응급의학과",
      "베트남에서는 가슴 답답함을 단순 피로로 여기는 경우가 많습니다. 한국에서는 협심증 진단 시 관상동맥 조영술을 통한 정확한 평가와 스텐트 시술이 가능함을 설명할 수 있습니다.",
      [{"mistake":"협심증과 심근경색 구분 없이 설명","correction":"협심증(đau thắt ngực)은 일시적, 심근경색(nhồi máu)은 영구적 손상","explanation":"치료 긴급성과 예후가 다릅니다"},
       {"mistake":"니트로글리세린 사용법 설명 누락","correction":"혀 밑에 넣어 녹이는 설하정 사용법 설명","explanation":"응급 시 자가 대처 방법입니다"},
       {"mistake":"생활습관 개선 강조 누락","correction":"금연, 운동, 식이조절의 중요성 설명","explanation":"약물 치료와 함께 생활습관 개선이 필수입니다"}],
      [{"ko":"협심증입니다. 관상동맥이 좁아져서 가슴 통증이 생깁니다.","vi":"Đây là đau thắt ngực. Động mạch vành bị hẹp gây đau ngực.","situation":"formal"},
       {"ko":"협심증이에요. 심장 혈관이 좁아진 거예요. 약 먹고 관리해야 해요.","vi":"Bị đau thắt ngực. Mạch máu tim bị hẹp. Cần uống thuốc và theo dõi.","situation":"onsite"},
       {"ko":"심장 혈관 좁아졌어요. 더 막히면 심근경색 돼요.","vi":"Mạch máu tim bị hẹp. Nếu tắc thêm sẽ thành nhồi máu cơ tim.","situation":"informal"}],
      ["흉통", "관상동맥", "니트로글리세린", "스텐트"]),

    t("suy-tim",
      "심부전",
      "suy tim",
      "心不全",
      "심(마음 심) + 부(아닐 부) + 전(온전할 전)",
      "심장의 펌프 기능이 저하되어 전신에 충분한 혈액을 공급하지 못하는 상태입니다. 호흡곤란, 부종, 피로감이 주요 증상이며, 만성적으로 관리해야 합니다. 통역 시 '심부전'이 심장이 완전히 멈춘 것이 아니라 기능이 약해진 상태임을 명확히 하고, 약물 복용과 염분 제한의 중요성을 강조해야 합니다.",
      "Tình trạng chức năng bơm của tim suy giảm, không cung cấp đủ máu cho toàn thân.",
      "심장내과, 응급의학과",
      "베트남에서는 짠 음식을 선호하는 식습관이 심부전 관리에 방해가 될 수 있습니다. 한국에서 심부전 치료 시 염분 제한의 중요성을 설명하고, 베트남 음식 중 염분이 높은 것(nước mắm 등)의 섭취를 줄여야 함을 안내해야 합니다.",
      [{"mistake":"심부전을 심장마비로 번역","correction":"심부전(suy tim)은 기능 저하, 심장마비(ngừng tim)는 정지","explanation":"심부전은 만성 질환으로 관리하며 살 수 있습니다"},
       {"mistake":"염분 제한 설명 누락","correction":"하루 소금 섭취 6g 이하로 제한 필요성 설명","explanation":"염분이 체액 저류를 악화시킵니다"},
       {"mistake":"매일 체중 측정의 중요성 누락","correction":"급격한 체중 증가는 부종 악화 신호임을 설명","explanation":"조기에 악화를 발견하여 대처할 수 있습니다"}],
      [{"ko":"심부전입니다. 심장 기능이 약해져서 호흡곤란과 부종이 생깁니다.","vi":"Đây là suy tim. Tim yếu nên gây khó thở và phù.","situation":"formal"},
       {"ko":"심부전이에요. 심장이 약해진 거예요. 짠 거 적게 드세요.","vi":"Bị suy tim. Tim yếu đi. Ăn ít mặn nhé.","situation":"onsite"},
       {"ko":"심장 힘이 약해졌어요. 물 적게, 소금 적게요.","vi":"Tim yếu đi. Uống ít nước, ăn ít muối.","situation":"informal"}],
      ["호흡곤란", "부종", "이뇨제", "저염식"]),

    t("loan-nhip-tim",
      "부정맥",
      "loạn nhịp tim",
      "不整脈",
      "부(아닐 부) + 정(바를 정) + 맥(맥 맥)",
      "심장 박동이 불규칙하거나, 너무 빠르거나, 너무 느린 상태를 총칭합니다. 두근거림, 어지러움, 실신 등의 증상이 나타날 수 있습니다. 통역 시 부정맥의 종류(심방세동, 심실빈맥 등)에 따라 위험도가 다름을 설명하고, 약물 외에도 시술(고주파 절제술) 옵션이 있음을 안내해야 합니다.",
      "Tình trạng nhịp tim không đều, quá nhanh hoặc quá chậm.",
      "심장내과, 응급의학과",
      "베트남에서는 두근거림을 스트레스나 피로 탓으로 여기는 경우가 많습니다. 한국에서는 홀터 모니터(24시간 심전도)를 통한 정확한 진단과 고주파 절제술을 통한 완치가 가능한 경우가 많음을 설명할 수 있습니다.",
      [{"mistake":"모든 부정맥이 위험하다고 설명","correction":"종류에 따라 양성부터 생명 위협까지 다양함을 설명","explanation":"불필요한 공포를 주지 않도록 해야 합니다"},
       {"mistake":"심방세동과 뇌졸중 관계 설명 누락","correction":"심방세동은 혈전 형성으로 뇌졸중 위험 증가시킴을 설명","explanation":"항응고제 복용의 이유를 이해시켜야 합니다"},
       {"mistake":"시술 치료 옵션 설명 누락","correction":"고주파 절제술로 완치 가능한 부정맥도 있음을 안내","explanation":"평생 약물 복용만이 해결책은 아닙니다"}],
      [{"ko":"심방세동이 발견되었습니다. 혈전 예방을 위해 항응고제가 필요합니다.","vi":"Đã phát hiện rung nhĩ. Cần thuốc chống đông để phòng ngừa huyết khối.","situation":"formal"},
       {"ko":"부정맥이에요. 심장 박동이 불규칙해요. 약으로 조절해 봐요.","vi":"Bị loạn nhịp tim. Nhịp tim không đều. Thử điều chỉnh bằng thuốc.","situation":"onsite"},
       {"ko":"심장이 불규칙하게 뛰어요. 검사 더 해 봐야 해요.","vi":"Tim đập không đều. Cần xét nghiệm thêm.","situation":"informal"}],
      ["두근거림", "심방세동", "항응고제", "전기심장충격"]),

    t("tang-huyet-ap",
      "고혈압",
      "tăng huyết áp",
      "高血壓",
      "고(높을 고) + 혈(피 혈) + 압(누를 압)",
      "혈압이 지속적으로 정상 범위(120/80mmHg)를 초과하는 상태입니다. 대부분 증상이 없어 '침묵의 살인자'라 불리며, 방치 시 뇌졸중, 심근경색, 신부전 등 심각한 합병증을 유발합니다. 통역 시 증상이 없어도 약물 복용을 중단하면 안 됨을 강조하고, 가정 혈압 측정의 중요성을 설명해야 합니다.",
      "Tình trạng huyết áp liên tục cao hơn mức bình thường, thường không có triệu chứng nên được gọi là 'kẻ giết người thầm lặng'.",
      "심장내과, 내과, 가정의학과",
      "베트남에서는 고혈압 인식이 낮아 치료율이 낮습니다. 한국에서는 고혈압약이 건강보험 적용을 받아 저렴하게 치료받을 수 있으며, 정기 검진의 중요성을 설명해야 합니다.",
      [{"mistake":"증상 없으면 치료 불필요하다고 설명","correction":"증상 없어도 합병증 예방을 위해 치료 필수임을 강조","explanation":"고혈압 합병증은 치명적입니다"},
       {"mistake":"약 중단해도 된다고 설명","correction":"혈압이 정상화되어도 약물 유지 필요함을 설명","explanation":"약 중단 시 혈압이 다시 올라갑니다"},
       {"mistake":"생활습관 개선만으로 충분하다고 설명","correction":"생활습관과 약물 치료 병행 필요성 설명","explanation":"대부분의 환자는 약물 치료가 필요합니다"}],
      [{"ko":"고혈압입니다. 혈압이 140/90 이상입니다. 약물 치료를 시작합니다.","vi":"Đây là tăng huyết áp. Huyết áp trên 140/90. Sẽ bắt đầu điều trị bằng thuốc.","situation":"formal"},
       {"ko":"혈압이 높아요. 약 드시고 짜게 안 드시면 돼요.","vi":"Huyết áp cao. Uống thuốc và ăn nhạt là được.","situation":"onsite"},
       {"ko":"혈압 높은 거예요. 약 꼭 드세요, 안 아파도요.","vi":"Huyết áp cao. Phải uống thuốc đều, dù không đau.","situation":"informal"}],
      ["혈압", "뇌졸중", "심장", "저염식"]),

    t("xo-vua-dong-mach",
      "동맥경화",
      "xơ vữa động mạch",
      "動脈硬化",
      "동(움직일 동) + 맥(맥 맥) + 경(굳을 경) + 화(될 화)",
      "동맥 벽에 콜레스테롤 등이 쌓여 혈관이 좁아지고 딱딱해지는 상태입니다. 심근경색, 뇌졸중의 주요 원인이며, 초기에는 증상이 없습니다. 통역 시 고지혈증, 고혈압, 당뇨, 흡연 등 위험요인 관리의 중요성을 강조하고, 정기적인 혈관 건강 검진을 권장해야 합니다.",
      "Tình trạng thành động mạch tích tụ cholesterol, làm mạch máu hẹp và cứng lại.",
      "심장내과, 신경과, 혈관외과",
      "베트남 근로자들은 육체 노동으로 건강하다고 생각할 수 있지만, 흡연율이 높고 기름진 음식을 선호하여 동맥경화 위험이 있습니다. 한국에서 CT/MRI를 통한 혈관 상태 확인이 가능함을 안내할 수 있습니다.",
      [{"mistake":"동맥경화를 노화로만 설명","correction":"생활습관(흡연, 식습관)이 주요 원인임을 설명","explanation":"젊은 나이에도 발생할 수 있습니다"},
       {"mistake":"증상이 없어 괜찮다고 설명","correction":"증상 없이 진행되어 갑자기 심근경색/뇌졸중 발생함을 설명","explanation":"예방적 관리가 중요합니다"},
       {"mistake":"치료 불가능하다고 설명","correction":"생활습관 개선과 약물로 진행을 늦출 수 있음을 설명","explanation":"적극적 관리로 합병증을 예방할 수 있습니다"}],
      [{"ko":"동맥경화가 진행 중입니다. 콜레스테롤 관리와 생활습관 개선이 필요합니다.","vi":"Xơ vữa động mạch đang tiến triển. Cần kiểm soát cholesterol và thay đổi lối sống.","situation":"formal"},
       {"ko":"혈관이 좁아지고 딱딱해졌어요. 담배 끊고 기름진 거 줄이세요.","vi":"Mạch máu bị hẹp và cứng. Bỏ thuốc lá và giảm đồ dầu mỡ.","situation":"onsite"},
       {"ko":"혈관에 기름 껴서 막히는 거예요. 조심해야 해요.","vi":"Mạch máu bị mỡ bám và tắc. Phải cẩn thận.","situation":"informal"}],
      ["콜레스테롤", "심근경색", "뇌졸중", "스타틴"]),

    t("phinh-dong-mach-chu",
      "대동맥류",
      "phình động mạch chủ",
      "大動脈瘤",
      "대(클 대) + 동(움직일 동) + 맥(맥 맥) + 류(혹 류)",
      "대동맥의 벽이 약해져서 풍선처럼 부풀어 오른 상태입니다. 파열 시 대량 출혈로 사망할 수 있는 매우 위험한 질환입니다. 대부분 증상이 없어 우연히 발견되며, 크기에 따라 경과 관찰 또는 수술이 필요합니다. 통역 시 정기 검진으로 발견되면 관리 가능함을 설명하고, 혈압 조절의 중요성을 강조해야 합니다.",
      "Tình trạng thành động mạch chủ yếu đi và phình ra như quả bóng, có thể vỡ gây chảy máu ồ ạt.",
      "심장외과, 혈관외과, 응급의학과",
      "베트남에서는 대동맥류에 대한 인식이 매우 낮습니다. 한국에서는 건강검진 시 복부초음파나 CT로 발견되는 경우가 많으며, 크기에 따라 스텐트그라프트 시술이나 수술로 치료 가능함을 설명할 수 있습니다.",
      [{"mistake":"대동맥류를 암으로 오해하게 설명","correction":"혈관 벽이 약해져 부푼 것이지 종양이 아님을 설명","explanation":"환자의 불필요한 공포를 방지해야 합니다"},
       {"mistake":"증상 없으면 괜찮다고 설명","correction":"증상 없이 커지다 파열하면 치명적임을 설명","explanation":"정기 추적 관찰이 필수입니다"},
       {"mistake":"혈압 관리 중요성 누락","correction":"고혈압이 파열 위험을 높임을 강조","explanation":"철저한 혈압 조절이 필요합니다"}],
      [{"ko":"대동맥류가 발견되었습니다. 현재 크기로는 경과 관찰하며 혈압 조절이 중요합니다.","vi":"Đã phát hiện phình động mạch chủ. Với kích thước hiện tại cần theo dõi và kiểm soát huyết áp.","situation":"formal"},
       {"ko":"대동맥이 부풀어 있어요. 터지면 위험해요. 혈압 관리 잘 하세요.","vi":"Động mạch chủ bị phình. Nếu vỡ thì nguy hiểm. Kiểm soát huyết áp tốt nhé.","situation":"onsite"},
       {"ko":"큰 혈관이 부풀었어요. 정기 검사 받으세요.","vi":"Mạch máu lớn bị phình. Cần khám định kỳ.","situation":"informal"}],
      ["대동맥", "파열", "혈압", "스텐트"]),

    t("viem-co-tim",
      "심근염",
      "viêm cơ tim",
      "心筋炎",
      "심(마음 심) + 근(힘줄 근) + 염(불꽃 염)",
      "심장 근육에 염증이 생긴 상태로, 주로 바이러스 감염 후 발생합니다. 가슴 통증, 호흡곤란, 부정맥, 심부전 증상이 나타날 수 있습니다. 통역 시 감기나 장염 후 가슴 통증이 나타나면 심근염을 의심해야 함을 설명하고, 안정과 심장 기능 모니터링의 중요성을 강조해야 합니다.",
      "Tình trạng viêm cơ tim, thường xảy ra sau nhiễm virus.",
      "심장내과, 응급의학과",
      "베트남 근로자들이 감기 후에도 무리하게 일하다가 심근염이 악화되는 경우가 있습니다. 발열 후 가슴 통증이 있으면 반드시 휴식하고 진료를 받아야 함을 강조해야 합니다.",
      [{"mistake":"심근염을 단순 가슴 통증으로 설명","correction":"심장 근육 자체의 염증으로 심부전까지 진행 가능함을 설명","explanation":"적절한 안정과 치료가 필수입니다"},
       {"mistake":"바이러스 감염과의 연관성 설명 누락","correction":"감기, 장염 후 발생할 수 있음을 설명","explanation":"선행 감염 병력 확인이 중요합니다"},
       {"mistake":"운동 제한의 중요성 누락","correction":"심근염 회복 시 격렬한 운동은 갑작스러운 심장마비 위험이 있음을 설명","explanation":"충분한 회복 기간이 필요합니다"}],
      [{"ko":"심근염입니다. 심장 근육에 염증이 생겼습니다. 절대 안정이 필요합니다.","vi":"Đây là viêm cơ tim. Cơ tim bị viêm. Cần nghỉ ngơi tuyệt đối.","situation":"formal"},
       {"ko":"심근염이에요. 심장에 염증 생긴 거예요. 일 하면 안 돼요.","vi":"Bị viêm cơ tim. Cơ tim bị viêm. Không được làm việc.","situation":"onsite"},
       {"ko":"심장 근육 염증이에요. 쉬어야 해요, 무리하면 큰일 나요.","vi":"Viêm cơ tim. Phải nghỉ ngơi, gắng sức thì nguy.","situation":"informal"}],
      ["가슴통증", "바이러스", "심부전", "안정"]),

    t("viem-noi-tam-mac",
      "심내막염",
      "viêm nội tâm mạc",
      "心內膜炎",
      "심(마음 심) + 내(안 내) + 막(막 막) + 염(불꽃 염)",
      "심장 내벽(심내막)과 판막에 세균 등이 감염되어 염증이 생긴 상태입니다. 발열, 피로, 심잡음이 특징이며, 방치 시 판막 손상과 색전증으로 사망할 수 있습니다. 통역 시 치과 시술 전 예방적 항생제의 중요성을 설명하고, 고열과 함께 새로운 심잡음이 들리면 즉시 검사가 필요함을 강조해야 합니다.",
      "Tình trạng nhiễm trùng thành trong tim (nội tâm mạc) và van tim, thường do vi khuẩn.",
      "심장내과, 감염내과",
      "베트남에서는 치과 치료 전 예방적 항생제 사용이 일반적이지 않을 수 있습니다. 판막 질환이 있는 환자에게 한국에서의 치과 시술 전 반드시 심장내과 상담이 필요함을 설명해야 합니다.",
      [{"mistake":"심내막염을 단순 감염으로 설명","correction":"심장 판막 손상과 전신 색전증의 위험성 설명","explanation":"치료하지 않으면 사망률이 높습니다"},
       {"mistake":"치과 시술과의 관계 설명 누락","correction":"치과 시술 시 혈중 세균이 심장에 감염될 수 있음을 설명","explanation":"예방적 항생제가 필요한 이유입니다"},
       {"mistake":"장기 치료 필요성 설명 누락","correction":"항생제를 4-6주간 정맥 투여해야 함을 설명","explanation":"치료 기간과 방법의 이해가 필요합니다"}],
      [{"ko":"감염성 심내막염입니다. 심장 판막에 세균 감염이 있습니다. 장기 항생제 치료가 필요합니다.","vi":"Đây là viêm nội tâm mạc nhiễm trùng. Van tim bị nhiễm vi khuẩn. Cần điều trị kháng sinh dài ngày.","situation":"formal"},
       {"ko":"심내막염이에요. 심장에 세균이 붙었어요. 몇 주 동안 주사 맞아야 해요.","vi":"Bị viêm nội tâm mạc. Vi khuẩn bám vào tim. Cần tiêm thuốc nhiều tuần.","situation":"onsite"},
       {"ko":"심장에 균 감염됐어요. 오래 치료해야 해요.","vi":"Tim bị nhiễm khuẩn. Phải điều trị lâu.","situation":"informal"}],
      ["발열", "심잡음", "판막", "항생제"]),

    t("viem-mang-ngoai-tim",
      "심낭염",
      "viêm màng ngoài tim",
      "心囊炎",
      "심(마음 심) + 낭(주머니 낭) + 염(불꽃 염)",
      "심장을 둘러싼 막(심낭)에 염증이 생긴 상태입니다. 숨을 깊이 들이쉬거나 눕는 자세에서 악화되는 날카로운 가슴 통증이 특징입니다. 바이러스 감염이 흔한 원인이며, 대부분 예후가 좋습니다. 통역 시 심근경색과 증상이 비슷할 수 있어 감별이 필요함을 설명하고, 심낭 삼출이 동반된 경우 심장 압전의 위험이 있음을 안내해야 합니다.",
      "Tình trạng viêm màng bao quanh tim (màng ngoài tim), đặc trưng bởi đau ngực tăng khi hít sâu hoặc nằm.",
      "심장내과, 응급의학과",
      "베트남에서는 가슴 통증이 자세에 따라 변하면 근육통으로 오해하는 경우가 있습니다. 한국에서는 심전도와 심초음파로 빠르게 진단이 가능함을 설명할 수 있습니다.",
      [{"mistake":"심낭염과 심근경색 감별 설명 누락","correction":"자세에 따라 통증이 변하면 심낭염 가능성 높음을 설명","explanation":"치료 접근이 다르므로 감별이 중요합니다"},
       {"mistake":"심낭 삼출의 위험성 누락","correction":"물이 많이 차면 심장을 압박해 위험함을 설명","explanation":"심장 압전은 응급 상황입니다"},
       {"mistake":"재발 가능성 설명 누락","correction":"심낭염은 재발할 수 있어 예방 치료가 필요할 수 있음을 설명","explanation":"콜키신 등으로 재발을 예방합니다"}],
      [{"ko":"심낭염입니다. 심장을 싸고 있는 막에 염증이 생겼습니다.","vi":"Đây là viêm màng ngoài tim. Màng bao quanh tim bị viêm.","situation":"formal"},
       {"ko":"심낭염이에요. 숨 쉴 때, 누우면 가슴 아프죠? 약 먹으면 나아요.","vi":"Bị viêm màng ngoài tim. Đau ngực khi thở và nằm phải không? Uống thuốc sẽ đỡ.","situation":"onsite"},
       {"ko":"심장 싸개에 염증이에요. 심근경색 아니에요, 걱정 마세요.","vi":"Viêm màng bọc tim. Không phải nhồi máu cơ tim, đừng lo.","situation":"informal"}],
      ["가슴통증", "심낭삼출", "심전도", "소염제"]),

    t("benh-van-tim",
      "판막질환",
      "bệnh van tim",
      "瓣膜疾患",
      "판(조각 판) + 막(막 막) + 질(병 질) + 환(걱정 환)",
      "심장 판막이 제대로 열리지 않거나(협착) 닫히지 않아(역류) 혈액 흐름에 문제가 생기는 질환입니다. 호흡곤란, 피로, 부정맥이 나타날 수 있습니다. 통역 시 판막의 종류(승모판, 대동맥판 등)와 문제 유형(협착, 역류)을 정확히 전달하고, 심한 경우 수술이나 시술이 필요함을 설명해야 합니다.",
      "Bệnh lý khi van tim không mở (hẹp) hoặc đóng (hở) đúng cách, gây rối loạn lưu thông máu.",
      "심장내과, 심장외과",
      "베트남에서는 류마티스열로 인한 판막질환이 아직 발생합니다. 한국에서는 퇴행성 변화나 선천적 원인이 더 흔하며, TAVI(경피적 대동맥판막 치환술) 같은 비수술적 치료도 발달해 있음을 설명할 수 있습니다.",
      [{"mistake":"판막 협착과 역류를 구분하지 않음","correction":"협착(hẹp)은 안 열림, 역류(hở)는 안 닫힘으로 구분","explanation":"치료 방법이 다릅니다"},
       {"mistake":"판막 위치 설명 누락","correction":"승모판(van hai lá), 대동맥판(van động mạch chủ) 등 위치 명시","explanation":"각 판막의 문제가 다른 증상을 유발합니다"},
       {"mistake":"치료 옵션 설명 불충분","correction":"약물, 시술(TAVI), 수술 등 다양한 옵션 안내","explanation":"환자 상태에 따라 적합한 치료가 다릅니다"}],
      [{"ko":"대동맥판막 협착증입니다. 판막이 잘 열리지 않아 혈액 흐름이 막힙니다.","vi":"Đây là hẹp van động mạch chủ. Van không mở tốt nên máu không lưu thông.","situation":"formal"},
       {"ko":"심장 판막이 문제예요. 피가 잘 안 흘러요. 수술 필요할 수도 있어요.","vi":"Van tim có vấn đề. Máu không chảy tốt. Có thể cần phẫu thuật.","situation":"onsite"},
       {"ko":"심장 판막이 잘 안 닫혀요. 피가 새요.","vi":"Van tim đóng không kín. Máu bị hở.","situation":"informal"}],
      ["심잡음", "호흡곤란", "판막수술", "TAVI"]),

    # 호흡기내과 (636-650)
    t("viem-phoi",
      "폐렴",
      "viêm phổi",
      "肺炎",
      "폐(허파 폐) + 염(불꽃 염)",
      "폐 조직에 염증이 생긴 상태로, 세균, 바이러스, 진균 등이 원인이 됩니다. 기침, 가래, 발열, 호흡곤란이 주요 증상입니다. 통역 시 폐렴의 원인균에 따라 치료가 달라짐을 설명하고, 노인이나 면역력 저하 환자에서 심각할 수 있음을 강조해야 합니다. 입원 치료가 필요한 경우도 있습니다.",
      "Tình trạng viêm mô phổi, có thể do vi khuẩn, virus hoặc nấm gây ra.",
      "호흡기내과, 감염내과, 응급의학과",
      "베트남 근로자들이 폐렴 초기 증상을 감기로 오인하여 치료가 늦어지는 경우가 있습니다. 한국에서는 폐렴구균 예방접종이 권장되며, 특히 만성질환자는 접종이 필요함을 안내해야 합니다.",
      [{"mistake":"폐렴을 단순 감기로 설명","correction":"폐 조직 자체의 감염으로 중증화 가능함을 설명","explanation":"적절한 치료 없이 사망할 수 있습니다"},
       {"mistake":"원인균 구분 없이 항생제 설명","correction":"세균성은 항생제, 바이러스성은 대증치료가 기본임을 설명","explanation":"치료 접근이 다릅니다"},
       {"mistake":"예방접종 안내 누락","correction":"폐렴구균 백신으로 예방 가능함을 안내","explanation":"고위험군은 예방접종이 중요합니다"}],
      [{"ko":"세균성 폐렴입니다. 항생제 치료가 필요하며, 중증이면 입원하셔야 합니다.","vi":"Đây là viêm phổi do vi khuẩn. Cần điều trị kháng sinh, nếu nặng phải nhập viện.","situation":"formal"},
       {"ko":"폐렴이에요. 폐에 염증 생긴 거예요. 약 먹고 푹 쉬세요.","vi":"Bị viêm phổi. Phổi bị viêm. Uống thuốc và nghỉ ngơi.","situation":"onsite"},
       {"ko":"감기 아니고 폐렴이에요. 심하면 입원해야 해요.","vi":"Không phải cảm mà là viêm phổi. Nặng thì phải nhập viện.","situation":"informal"}],
      ["기침", "발열", "항생제", "폐렴구균백신"]),

    t("hen-suyen",
      "천식",
      "hen suyễn",
      "喘息",
      "천(숨찰 천) + 식(숨쉴 식)",
      "기도가 만성적으로 염증을 일으켜 좁아지고, 자극에 과민하게 반응하여 기침, 쌕쌕거림, 호흡곤란이 반복되는 질환입니다. 알레르기, 운동, 찬 공기 등이 유발 요인입니다. 통역 시 천식이 완치보다는 조절이 목표임을 설명하고, 흡입기 사용법을 정확히 전달해야 합니다.",
      "Bệnh mạn tính với đường thở bị viêm và thu hẹp, gây ho, khò khè và khó thở tái phát.",
      "호흡기내과, 알레르기내과",
      "베트남에서는 천식에 대한 인식이 낮아 흡입기를 꺼리는 경우가 있습니다. 한국에서는 흡입 스테로이드가 천식 조절의 핵심이며, 부작용이 적어 장기 사용이 안전함을 설명해야 합니다.",
      [{"mistake":"천식을 일시적 증상으로 설명","correction":"만성 질환으로 꾸준한 관리가 필요함을 설명","explanation":"증상 없어도 염증은 지속됩니다"},
       {"mistake":"흡입기 사용법 설명 누락","correction":"흡입기 종류와 정확한 사용법 교육 필요","explanation":"잘못된 사용은 효과를 떨어뜨립니다"},
       {"mistake":"응급 흡입기와 유지 흡입기 구분 안 함","correction":"증상 완화용(속효성)과 예방용(스테로이드) 구분 설명","explanation":"각각의 역할이 다릅니다"}],
      [{"ko":"천식입니다. 기도에 만성 염증이 있어 꾸준한 흡입제 사용이 필요합니다.","vi":"Đây là hen suyễn. Đường thở bị viêm mạn tính nên cần dùng thuốc hít đều đặn.","situation":"formal"},
       {"ko":"천식이에요. 흡입기 매일 써야 해요. 안 아파도요.","vi":"Bị hen suyễn. Phải dùng thuốc hít hàng ngày. Dù không khó thở.","situation":"onsite"},
       {"ko":"숨 찬 게 천식이에요. 흡입기 잘 쓰면 괜찮아요.","vi":"Khó thở là hen suyễn. Dùng thuốc hít đúng cách sẽ ổn.","situation":"informal"}],
      ["기침", "쌕쌕거림", "흡입기", "알레르기"]),

    t("benh-phoi-tac-nghen-man-tinh",
      "만성폐쇄성폐질환",
      "bệnh phổi tắc nghẽn mạn tính",
      "慢性閉塞性肺疾患",
      "만(오랠 만) + 성(성품 성) + 폐(닫을 폐) + 쇄(막을 쇄) + 성(성품 성) + 폐(허파 폐) + 질(병 질) + 환(걱정 환)",
      "담배 연기 등의 유해물질에 장기간 노출되어 기도가 좁아지고 폐가 손상되는 진행성 폐질환입니다. 만성 기침, 가래, 운동 시 호흡곤란이 특징입니다. 통역 시 COPD(씨오피디)라는 약어로도 불림을 알리고, 금연이 가장 중요한 치료임을 강조해야 합니다.",
      "Bệnh phổi tiến triển do tiếp xúc lâu dài với chất độc hại như khói thuốc, làm hẹp đường thở và tổn thương phổi.",
      "호흡기내과",
      "베트남 남성의 흡연율이 높아 COPD 위험이 큽니다. 한국에서 근무하면서 금연 지원 프로그램과 흡입제 치료를 받을 수 있음을 안내하고, 폐 기능이 더 손상되기 전에 금연해야 함을 강조해야 합니다.",
      [{"mistake":"COPD를 천식과 동일시","correction":"COPD(tắc nghẽn)는 비가역적, 천식(hen)은 가역적 기도 폐쇄","explanation":"치료 접근과 예후가 다릅니다"},
       {"mistake":"금연의 중요성 과소평가","correction":"금연만이 COPD 진행을 막을 수 있음을 강조","explanation":"약물은 증상 완화일 뿐 진행을 막지 못합니다"},
       {"mistake":"산소치료 필요성 설명 누락","correction":"중증 COPD는 가정 산소치료가 필요할 수 있음을 설명","explanation":"생존율을 높이는 중요한 치료입니다"}],
      [{"ko":"COPD, 만성폐쇄성폐질환입니다. 흡연으로 폐가 손상되었습니다. 반드시 금연하셔야 합니다.","vi":"Đây là COPD, bệnh phổi tắc nghẽn mạn tính. Phổi bị tổn thương do hút thuốc. Phải bỏ thuốc lá.","situation":"formal"},
       {"ko":"폐가 많이 안 좋아요. 담배 때문이에요. 지금이라도 끊으세요.","vi":"Phổi rất yếu. Do thuốc lá. Bây giờ phải bỏ.","situation":"onsite"},
       {"ko":"담배 피워서 폐가 망가진 거예요. 담배 끊어야 더 안 나빠져요.","vi":"Phổi hỏng do hút thuốc. Phải bỏ thuốc để không xấu thêm.","situation":"informal"}],
      ["금연", "흡입기", "폐기능검사", "산소치료"]),

    t("lao-phoi",
      "폐결핵",
      "lao phổi",
      "肺結核",
      "폐(허파 폐) + 결(맺을 결) + 핵(씨 핵)",
      "결핵균(Mycobacterium tuberculosis)이 폐에 감염되어 발생하는 전염성 질환입니다. 기침, 가래, 미열, 체중 감소, 야간 발한이 특징입니다. 통역 시 결핵이 공기로 전파됨을 설명하고, 6개월 이상 꾸준한 약물 복용의 중요성을 강조해야 합니다. 중단 시 내성 결핵이 발생합니다.",
      "Bệnh truyền nhiễm do vi khuẩn lao (Mycobacterium tuberculosis) xâm nhập phổi.",
      "호흡기내과, 감염내과",
      "베트남은 결핵 고위험 국가로, 한국에 입국한 베트남 근로자들의 결핵 검진이 중요합니다. 한국에서는 결핵 치료가 무료이며, 복약 관리 지원 프로그램이 있음을 안내해야 합니다. 치료 중단은 절대 금지입니다.",
      [{"mistake":"결핵을 과거 질환으로 설명","correction":"현재도 발생하며 내성 결핵은 치료가 어려움을 설명","explanation":"방심하면 전파와 내성 발생 위험이 있습니다"},
       {"mistake":"약물 복용 기간 설명 누락","correction":"최소 6개월 이상, 중단 없이 복용해야 함을 강조","explanation":"중단 시 내성 결핵이 발생합니다"},
       {"mistake":"전파 경로 설명 불충분","correction":"기침할 때 공기로 전파되며, 마스크 착용 중요함을 설명","explanation":"가족과 동료 보호를 위한 격리가 필요합니다"}],
      [{"ko":"폐결핵입니다. 결핵균에 감염되셨습니다. 6개월간 약을 꾸준히 드셔야 합니다.","vi":"Đây là lao phổi. Bị nhiễm vi khuẩn lao. Phải uống thuốc đều đặn trong 6 tháng.","situation":"formal"},
       {"ko":"결핵이에요. 전염되니까 마스크 쓰고 격리해야 해요. 약 꼭 드세요.","vi":"Bị lao. Lây được nên phải đeo khẩu trang và cách ly. Phải uống thuốc đều.","situation":"onsite"},
       {"ko":"결핵 걸렸어요. 약 6개월 먹어야 해요. 중간에 끊으면 안 돼요.","vi":"Bị lao. Phải uống thuốc 6 tháng. Không được bỏ giữa chừng.","situation":"informal"}],
      ["기침", "가래", "격리", "항결핵제"]),

    t("ung-thu-phoi",
      "폐암",
      "ung thư phổi",
      "肺癌",
      "폐(허파 폐) + 암(바위 암)",
      "폐에서 발생하는 악성 종양으로, 흡연이 가장 큰 위험요인입니다. 초기에는 증상이 없다가 기침, 객혈, 호흡곤란, 체중 감소 등이 나타납니다. 통역 시 비흡연자도 폐암에 걸릴 수 있음을 알리고, 조기 발견을 위한 저선량 CT 검진의 중요성을 설명해야 합니다.",
      "Khối u ác tính phát sinh ở phổi, hút thuốc là yếu tố nguy cơ lớn nhất.",
      "호흡기내과, 종양내과, 흉부외과",
      "베트남 남성의 높은 흡연율로 인해 폐암 위험이 큽니다. 한국에서는 폐암 검진 프로그램이 있으며, 표적치료제와 면역항암제 등 발전된 치료를 받을 수 있음을 설명할 수 있습니다.",
      [{"mistake":"폐암을 흡연자만의 질환으로 설명","correction":"비흡연자, 특히 여성에서도 폐암 발생함을 설명","explanation":"간접흡연, 미세먼지, 유전 등도 원인입니다"},
       {"mistake":"말기 진단만을 설명","correction":"조기 발견 시 완치 가능함을 설명","explanation":"희망을 유지하면서 검진의 중요성을 알려야 합니다"},
       {"mistake":"치료 옵션 설명 불충분","correction":"수술, 항암, 방사선, 표적/면역치료 등 다양한 옵션 안내","explanation":"환자 상태에 맞는 치료를 선택합니다"}],
      [{"ko":"폐암 진단입니다. 조직검사 결과 악성으로 확인되었습니다. 치료 계획을 상담하겠습니다.","vi":"Chẩn đoán ung thư phổi. Kết quả sinh thiết xác nhận ác tính. Sẽ tư vấn kế hoạch điều trị.","situation":"formal"},
       {"ko":"폐에 암이 있어요. 빨리 치료 시작해야 해요. 방법은 여러 가지 있어요.","vi":"Có ung thư ở phổi. Phải bắt đầu điều trị sớm. Có nhiều phương pháp.","situation":"onsite"},
       {"ko":"폐암이에요. 담배 때문일 수도 있어요. 치료하면 나을 수 있어요.","vi":"Bị ung thư phổi. Có thể do thuốc lá. Điều trị thì có thể khỏi.","situation":"informal"}],
      ["기침", "객혈", "흉부CT", "항암치료"]),

    t("tran-khi-mang-phoi",
      "기흉",
      "tràn khí màng phổi",
      "氣胸",
      "기(기운 기) + 흉(가슴 흉)",
      "폐와 흉벽 사이 공간(흉막강)에 공기가 차서 폐가 쪼그라드는 상태입니다. 갑작스러운 가슴 통증과 호흡곤란이 특징이며, 키 크고 마른 젊은 남성에서 흔합니다. 통역 시 자연 기흉과 외상성 기흉을 구별하고, 중증 시 흉관 삽입이 필요함을 설명해야 합니다.",
      "Tình trạng khí tích tụ trong khoang màng phổi làm phổi xẹp lại.",
      "호흡기내과, 흉부외과, 응급의학과",
      "베트남 젊은 남성 근로자 중 키 크고 마른 체형에서 자연 기흉이 발생할 수 있습니다. 갑작스러운 가슴 통증과 호흡곤란 시 즉시 응급실을 방문해야 함을 강조해야 합니다.",
      [{"mistake":"기흉을 심장 문제로 오해하게 설명","correction":"폐에 공기가 새어 나와 생긴 문제임을 설명","explanation":"심장과 무관한 폐 문제입니다"},
       {"mistake":"흉관 삽입 설명 시 공포 유발","correction":"흉관은 공기를 빼는 일시적 치료임을 차분히 설명","explanation":"대부분 잘 회복됩니다"},
       {"mistake":"재발 가능성 설명 누락","correction":"자연 기흉은 재발률이 높음을 안내","explanation":"재발 방지를 위한 시술이 필요할 수 있습니다"}],
      [{"ko":"자연 기흉입니다. 폐에서 공기가 새어 폐가 쪼그라들었습니다. 흉관 삽입이 필요합니다.","vi":"Đây là tràn khí màng phổi tự phát. Khí thoát ra từ phổi làm phổi xẹp. Cần đặt ống dẫn lưu ngực.","situation":"formal"},
       {"ko":"기흉이에요. 폐가 바람 빠진 것처럼 쪼그라들었어요. 관 넣어서 공기 빼야 해요.","vi":"Bị tràn khí màng phổi. Phổi xẹp như xì hơi. Cần đặt ống hút khí ra.","situation":"onsite"},
       {"ko":"폐에 구멍 나서 바람 샌 거예요. 관 꽂아서 빼면 돼요.","vi":"Phổi bị thủng nên khí thoát ra. Đặt ống hút ra là được.","situation":"informal"}],
      ["가슴통증", "호흡곤란", "흉관", "흉부X선"]),

    t("tran-dich-mang-phoi",
      "흉수",
      "tràn dịch màng phổi",
      "胸水",
      "흉(가슴 흉) + 수(물 수)",
      "폐와 흉벽 사이 공간(흉막강)에 비정상적으로 물이 차는 상태입니다. 호흡곤란, 기침, 가슴 불편감이 나타납니다. 심부전, 폐렴, 암 등 다양한 원인이 있어 원인 규명이 중요합니다. 통역 시 흉수 자체는 질병이 아니라 다른 질환의 결과임을 설명하고, 원인 치료의 중요성을 강조해야 합니다.",
      "Tình trạng tích tụ dịch bất thường trong khoang màng phổi.",
      "호흡기내과, 종양내과, 심장내과",
      "베트남에서는 흉수가 폐 문제만의 결과라고 생각할 수 있지만, 한국에서는 심장, 간, 신장, 암 등 다양한 원인을 종합적으로 평가함을 설명할 수 있습니다.",
      [{"mistake":"흉수를 단독 질환으로 설명","correction":"다른 질환(심부전, 암 등)의 결과임을 설명","explanation":"원인 치료가 핵심입니다"},
       {"mistake":"흉수 천자 설명 시 공포 유발","correction":"진단과 증상 완화를 위한 비교적 간단한 시술임을 설명","explanation":"국소마취로 시행하며 안전합니다"},
       {"mistake":"양성/악성 감별의 중요성 누락","correction":"흉수 검사로 암 여부를 확인해야 함을 설명","explanation":"치료 방향이 완전히 달라집니다"}],
      [{"ko":"흉수가 발견되었습니다. 폐 주변에 물이 차 있습니다. 원인을 찾기 위한 검사가 필요합니다.","vi":"Đã phát hiện tràn dịch màng phổi. Có nước quanh phổi. Cần xét nghiệm tìm nguyên nhân.","situation":"formal"},
       {"ko":"폐에 물 찼어요. 왜 찼는지 알아봐야 해요. 물 빼는 검사할게요.","vi":"Có nước trong phổi. Cần tìm hiểu nguyên nhân. Sẽ chọc hút để xét nghiệm.","situation":"onsite"},
       {"ko":"폐에 물이 고였어요. 심장 문제일 수도, 다른 문제일 수도 있어요.","vi":"Nước đọng trong phổi. Có thể do tim hoặc nguyên nhân khác.","situation":"informal"}],
      ["호흡곤란", "흉막천자", "심부전", "폐암"]),

    t("thuyen-tac-phoi",
      "폐색전증",
      "thuyên tắc phổi",
      "肺塞栓症",
      "폐(허파 폐) + 색(막을 색) + 전(구를 전) + 증(증상 증)",
      "혈전(주로 다리 정맥에서 발생)이 폐동맥을 막아 발생하는 응급 상황입니다. 갑작스러운 호흡곤란, 가슴 통증, 객혈이 특징이며, 대량 색전 시 사망할 수 있습니다. 통역 시 장시간 비행이나 부동 자세가 위험요인임을 설명하고, 항응고제 치료의 중요성을 강조해야 합니다.",
      "Tình huống cấp cứu khi huyết khối (thường từ tĩnh mạch chân) tắc động mạch phổi.",
      "호흡기내과, 응급의학과, 심장내과",
      "베트남에서 한국으로 오는 장거리 비행 후 폐색전증 위험이 있습니다. 또한 공장에서 오래 서서 일하는 근로자도 위험할 수 있어, 정기적인 다리 운동과 수분 섭취의 중요성을 안내해야 합니다.",
      [{"mistake":"폐색전증을 폐 자체 문제로 설명","correction":"다리 혈전이 폐로 이동한 것임을 설명","explanation":"다리 부종이 선행 증상일 수 있습니다"},
       {"mistake":"위험요인 설명 누락","correction":"장시간 비행, 부동, 수술 후, 피임약 등이 위험요인임을 설명","explanation":"예방이 가능한 질환입니다"},
       {"mistake":"항응고제 복용 기간 설명 누락","correction":"최소 3-6개월, 경우에 따라 평생 복용이 필요함을 설명","explanation":"재발 방지를 위해 중요합니다"}],
      [{"ko":"폐색전증입니다. 혈전이 폐동맥을 막았습니다. 항응고제 치료를 즉시 시작합니다.","vi":"Đây là thuyên tắc phổi. Huyết khối tắc động mạch phổi. Bắt đầu điều trị chống đông ngay.","situation":"formal"},
       {"ko":"폐에 피떡이 막은 거예요. 다리에서 올라온 거예요. 피 묽게 하는 약 써야 해요.","vi":"Cục máu đông tắc trong phổi. Từ chân đi lên. Cần dùng thuốc làm loãng máu.","situation":"onsite"},
       {"ko":"폐혈관 막힌 거예요. 응급이에요. 피떡 녹이는 약 써요.","vi":"Mạch máu phổi bị tắc. Cấp cứu. Cần thuốc tan cục máu đông.","situation":"informal"}],
      ["호흡곤란", "심부정맥혈전증", "항응고제", "D-dimer"]),

    t("ngung-tho-khi-ngu",
      "수면무호흡증",
      "ngừng thở khi ngủ",
      "睡眠無呼吸症",
      "수(잠 수) + 면(잠 면) + 무(없을 무) + 호(부를 호) + 흡(마실 흡) + 증(증상 증)",
      "수면 중 반복적으로 호흡이 멈추는 질환으로, 코골이, 주간 졸림, 피로가 특징입니다. 비만이 주요 원인이며, 치료하지 않으면 고혈압, 심장병, 뇌졸중 위험이 증가합니다. 통역 시 단순 코골이가 아닌 질병임을 설명하고, CPAP(양압기) 치료의 효과를 안내해야 합니다.",
      "Bệnh lý với hiện tượng ngừng thở lặp đi lặp lại khi ngủ, gây ngáy, buồn ngủ ban ngày và mệt mỏi.",
      "이비인후과, 호흡기내과, 수면클리닉",
      "베트남 근로자들이 코골이를 정상으로 여기거나, 피로를 단순 과로로 생각할 수 있습니다. 한국에서는 수면다원검사로 정확한 진단이 가능하고, CPAP 치료로 삶의 질이 크게 개선됨을 설명할 수 있습니다.",
      [{"mistake":"코골이와 수면무호흡을 동일시","correction":"코골이는 증상, 수면무호흡은 호흡 정지를 동반하는 질환","explanation":"수면무호흡은 건강에 심각한 영향을 미칩니다"},
       {"mistake":"CPAP 사용 거부감 해소 실패","correction":"처음엔 불편해도 적응되면 삶의 질이 크게 개선됨을 설명","explanation":"꾸준한 사용이 중요합니다"},
       {"mistake":"합병증 설명 누락","correction":"고혈압, 당뇨, 심장병, 뇌졸중 위험 증가함을 설명","explanation":"치료의 동기 부여에 중요합니다"}],
      [{"ko":"수면무호흡증입니다. 잠잘 때 호흡이 자주 멈춥니다. 양압기 치료를 권합니다.","vi":"Đây là chứng ngừng thở khi ngủ. Thường xuyên ngừng thở lúc ngủ. Khuyến nghị điều trị bằng máy thở áp lực dương.","situation":"formal"},
       {"ko":"수면무호흡이에요. 잘 때 숨 멈추는 거예요. 기계 쓰면 많이 좋아져요.","vi":"Bị ngừng thở khi ngủ. Ngủ mà ngừng thở. Dùng máy sẽ đỡ nhiều.","situation":"onsite"},
       {"ko":"코골이가 심한 건 숨이 막혀서예요. 치료하면 피곤함도 나아요.","vi":"Ngáy nhiều là do tắc thở. Điều trị thì bớt mệt.","situation":"informal"}],
      ["코골이", "비만", "CPAP", "주간졸림"]),

    t("benh-phoi-ke",
      "간질성폐질환",
      "bệnh phổi kẽ",
      "間質性肺疾患",
      "간(사이 간) + 질(바탕 질) + 성(성품 성) + 폐(허파 폐) + 질(병 질) + 환(걱정 환)",
      "폐포 주변의 간질(지지 조직)에 염증과 섬유화가 진행되는 질환군입니다. 마른 기침, 진행성 호흡곤란이 특징이며, 원인이 다양합니다(특발성, 자가면역, 직업성 등). 통역 시 간질성 폐질환이 여러 질환의 집합임을 설명하고, 원인에 따라 치료와 예후가 다름을 안내해야 합니다.",
      "Nhóm bệnh với viêm và xơ hóa tiến triển ở mô kẽ (mô nâng đỡ) xung quanh phế nang.",
      "호흡기내과, 류마티스내과",
      "베트남 근로자들이 먼지가 많은 환경(건설, 제조업)에서 일하는 경우 직업성 간질성 폐질환 위험이 있습니다. 작업 시 마스크 착용의 중요성과 정기 검진 필요성을 강조해야 합니다.",
      [{"mistake":"간질성 폐질환을 단일 질환으로 설명","correction":"여러 원인에 의한 다양한 질환군임을 설명","explanation":"원인에 따라 치료가 다릅니다"},
       {"mistake":"직업력 파악의 중요성 누락","correction":"분진, 석면 등 노출력을 확인해야 함을 설명","explanation":"산재 인정과 치료에 중요합니다"},
       {"mistake":"예후 설명 시 절망감 유발","correction":"일부는 치료 가능하고, 진행을 늦출 수 있음을 설명","explanation":"원인에 따라 예후가 다양합니다"}],
      [{"ko":"간질성 폐질환입니다. 폐의 지지 조직에 문제가 생겼습니다. 원인을 찾는 검사가 필요합니다.","vi":"Đây là bệnh phổi kẽ. Mô nâng đỡ của phổi có vấn đề. Cần xét nghiệm tìm nguyên nhân.","situation":"formal"},
       {"ko":"폐가 딱딱해지는 병이에요. 왜 그런지 알아봐야 해요. 일하는 환경이랑 관련 있을 수도 있어요.","vi":"Bệnh làm phổi cứng lại. Cần tìm hiểu nguyên nhân. Có thể liên quan đến môi trường làm việc.","situation":"onsite"},
       {"ko":"폐에 흉터 생기는 병이에요. 먼지 마시면 안 좋아요.","vi":"Bệnh gây sẹo ở phổi. Hít bụi không tốt.","situation":"informal"}],
      ["마른기침", "호흡곤란", "폐섬유화", "고해상도CT"]),

    t("viem-phe-quan",
      "기관지염",
      "viêm phế quản",
      "氣管支炎",
      "기(기운 기) + 관(대롱 관) + 지(가지 지) + 염(불꽃 염)",
      "기관지에 염증이 생긴 상태로, 급성과 만성으로 나뉩니다. 기침, 가래가 주요 증상이며, 급성은 대부분 바이러스 감염으로 자연 회복됩니다. 만성 기관지염은 흡연이 주원인이며 COPD의 한 유형입니다. 통역 시 급성 기관지염에 항생제가 대부분 불필요함을 설명하고, 기침이 2-3주 지속될 수 있음을 안내해야 합니다.",
      "Tình trạng viêm phế quản, chia thành cấp tính và mạn tính.",
      "호흡기내과, 가정의학과",
      "베트남 근로자들이 기침에 항생제를 요구하는 경우가 있습니다. 급성 기관지염은 대부분 바이러스 감염으로 항생제가 효과 없음을 설명하고, 충분한 휴식과 수분 섭취가 중요함을 안내해야 합니다.",
      [{"mistake":"기관지염에 항생제 필수라고 설명","correction":"급성 기관지염은 대부분 바이러스성으로 항생제 불필요함을 설명","explanation":"불필요한 항생제는 내성을 유발합니다"},
       {"mistake":"만성 기관지염과 급성을 구분 안 함","correction":"급성(vài ngày/tuần)과 만성(3개월 이상 지속) 구분","explanation":"치료 접근이 다릅니다"},
       {"mistake":"기침 지속 기간 설명 누락","correction":"급성 기관지염 후 기침이 2-3주 지속될 수 있음을 설명","explanation":"환자의 불안을 줄여줍니다"}],
      [{"ko":"급성 기관지염입니다. 바이러스 감염으로 보여 항생제 없이 치료합니다.","vi":"Đây là viêm phế quản cấp. Có vẻ do virus nên điều trị không cần kháng sinh.","situation":"formal"},
       {"ko":"기관지염이에요. 감기 비슷한 거예요. 푹 쉬면 나아요.","vi":"Bị viêm phế quản. Giống như cảm. Nghỉ ngơi sẽ khỏi.","situation":"onsite"},
       {"ko":"기침이 기관지 문제예요. 항생제 필요 없어요, 좀 쉬세요.","vi":"Ho do phế quản. Không cần kháng sinh, cứ nghỉ ngơi.","situation":"informal"}],
      ["기침", "가래", "감기", "휴식"]),
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms (601-650). Total: {len(data)}")
