#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch J - 추가 35개 (500개 도달)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("xu-ly-thuoc","약물치료","xử lý thuốc",
      "약을 사용하여 질병을 치료하거나 증상을 완화하는 방법입니다. 통역 시 복용 방법, 용량, 부작용 주의사항을 정확히 전달합니다.",
      "Phương pháp dùng thuốc để điều trị bệnh hoặc giảm triệu chứng",
      "내과/약제과",
      "약물 복용 지시를 정확히 이해하는 것이 중요합니다. 언어 장벽으로 인한 오해를 방지합니다.",
      [{"mistake":"용량을 대충 전달","correction":"정확한 용량과 횟수 전달","explanation":"과량 또는 과소 복용 방지"},
       {"mistake":"부작용 설명 생략","correction":"주요 부작용 알려주기","explanation":"조기 발견이 중요합니다"},
       {"mistake":"약 이름만 전달","correction":"복용법도 함께 전달","explanation":"효과적인 치료를 위해 필수입니다"}],
      [{"ko":"이 약은 하루 3번 식후 30분에 드세요.","vi":"Thuốc này uống 3 lần/ngày, 30 phút sau ăn.","situation":"formal"},
       {"ko":"졸릴 수 있으니 운전을 피하세요.","vi":"Có thể buồn ngủ nên tránh lái xe.","situation":"onsite"},
       {"ko":"약 먹고 있어요.","vi":"Đang uống thuốc.","situation":"informal"}],
      ["복용법","부작용","상호작용"]),

    t("phau-thuat","수술","phẫu thuật",
      "질병 치료를 위해 신체를 절개하여 처치하는 의료 행위입니다. 통역 시 수술 과정, 마취, 회복 기간을 설명합니다.",
      "Hành vi y tế mở cơ thể để điều trị bệnh",
      "외과",
      "수술에 대한 두려움을 완화하고, 동의서 내용을 명확히 설명합니다.",
      [{"mistake":"수술이 간단하다고만 설명","correction":"모든 수술에는 위험이 따름","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"회복 기간을 짧게 예상","correction":"개인차가 있음을 설명","explanation":"충분한 회복 시간 확보"},
       {"mistake":"동의서 내용 설명 없이 서명 요청","correction":"내용을 충분히 설명","explanation":"informed consent가 중요합니다"}],
      [{"ko":"수술 전 금식이 필요합니다.","vi":"Cần nhịn ăn trước phẫu thuật.","situation":"formal"},
       {"ko":"수술 동의서에 서명해 주세요.","vi":"Vui lòng ký giấy đồng ý phẫu thuật.","situation":"onsite"},
       {"ko":"수술 잘 됐어요.","vi":"Phẫu thuật thành công.","situation":"informal"}],
      ["마취","동의서","회복실"]),

    t("gay-me","마취","gây mê",
      "수술 중 통증을 느끼지 못하게 하는 의료 행위입니다. 통역 시 마취 종류(전신/부분)와 주의사항을 설명합니다.",
      "Hành vi y tế làm mất cảm giác đau trong phẫu thuật",
      "마취과",
      "마취에 대한 공포를 줄이고, 안전성을 설명합니다.",
      [{"mistake":"마취가 깨지 않을 수 있다고 겁줌","correction":"현대 마취는 매우 안전","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"금식 지시를 가볍게 전달","correction":"금식 위반은 수술 취소 사유","explanation":"폐흡인 예방이 중요합니다"},
       {"mistake":"부작용 설명 안 함","correction":"구역, 두통 등 일시적 부작용 안내","explanation":"대비할 수 있게 합니다"}],
      [{"ko":"전신마취를 위해 자정부터 금식하세요.","vi":"Nhịn ăn từ nửa đêm để gây mê toàn thân.","situation":"formal"},
       {"ko":"마취 후 목이 아플 수 있어요.","vi":"Sau gây mê có thể đau họng.","situation":"onsite"},
       {"ko":"부분마취로 수술했어요.","vi":"Phẫu thuật với gây tê cục bộ.","situation":"informal"}],
      ["전신마취","척추마취","금식"]),

    t("hoi-phuc","회복","hồi phục",
      "치료나 수술 후 건강한 상태로 돌아가는 과정입니다. 통역 시 회복 기간과 주의사항을 안내합니다.",
      "Quá trình trở lại trạng thái khỏe mạnh sau điều trị hoặc phẫu thuật",
      "전과",
      "회복 기간에 대한 현실적 기대를 설정하고, 재활의 중요성을 강조합니다.",
      [{"mistake":"빨리 낫는다고만 설명","correction":"개인차가 있음을 안내","explanation":"조급함을 줄입니다"},
       {"mistake":"활동 제한을 엄격하게만 강조","correction":"단계적 활동 증가 권장","explanation":"적절한 활동이 회복을 돕습니다"},
       {"mistake":"증상 호전만 확인","correction":"합병증 징후도 교육","explanation":"문제 조기 발견이 중요합니다"}],
      [{"ko":"완전 회복까지 6주 정도 걸립니다.","vi":"Hồi phục hoàn toàn mất khoảng 6 tuần.","situation":"formal"},
       {"ko":"무리하지 말고 천천히 움직이세요.","vi":"Đừng gắng sức, di chuyển từ từ.","situation":"onsite"},
       {"ko":"회복 중이에요.","vi":"Đang hồi phục.","situation":"informal"}],
      ["재활","합병증","퇴원"]),

    t("tai-kham","재진/추적검사","tái khám",
      "치료 효과 확인이나 질병 경과 관찰을 위해 다시 방문하는 것입니다. 통역 시 재진 일정과 이유를 설명합니다.",
      "Tái khám để kiểm tra hiệu quả điều trị hoặc theo dõi tiến triển bệnh",
      "외래",
      "재진의 중요성을 강조하고, 일정을 정확히 안내합니다.",
      [{"mistake":"재진이 형식적이라고 설명","correction":"재진으로 문제 조기 발견 가능","explanation":"치료 효과 확인이 중요합니다"},
       {"mistake":"증상 없으면 안 와도 된다고 설명","correction":"예정된 재진은 중요","explanation":"무증상 악화 가능"},
       {"mistake":"일정을 대충 전달","correction":"정확한 날짜와 시간 전달","explanation":"예약 관리가 중요합니다"}],
      [{"ko":"2주 후에 재진 오세요.","vi":"2 tuần sau đến tái khám.","situation":"formal"},
       {"ko":"약 다 먹으면 다시 오세요.","vi":"Uống hết thuốc rồi đến lại.","situation":"onsite"},
       {"ko":"재진 예약했어요.","vi":"Đã đặt lịch tái khám.","situation":"informal"}],
      ["외래","예약","경과관찰"]),

    t("nhap-vien","입원","nhập viện",
      "치료를 위해 병원에 머무르는 것입니다. 통역 시 입원 절차, 준비물, 면회 시간을 안내합니다.",
      "Ở lại bệnh viện để điều trị",
      "원무과",
      "입원 절차와 병원 규칙을 설명하고, 불안을 줄입니다.",
      [{"mistake":"비용 안내 없이 입원 권유","correction":"예상 비용과 보험 적용 확인","explanation":"경제적 부담을 고려합니다"},
       {"mistake":"병원 규칙 설명 안 함","correction":"면회, 식사 시간 등 안내","explanation":"병원 생활 적응을 돕습니다"},
       {"mistake":"입원 기간을 단정적으로 말함","correction":"예상 기간이며 변동 가능","explanation":"상황에 따라 달라질 수 있습니다"}],
      [{"ko":"입원 수속을 위해 원무과로 가세요.","vi":"Đến phòng hành chính để làm thủ tục nhập viện.","situation":"formal"},
       {"ko":"면회 시간은 오후 2시부터 5시까지예요.","vi":"Giờ thăm bệnh từ 2 giờ đến 5 giờ chiều.","situation":"onsite"},
       {"ko":"입원해야 해요.","vi":"Phải nhập viện.","situation":"informal"}],
      ["병실","면회","입원비"]),

    t("xuat-vien","퇴원","xuất viện",
      "치료를 마치고 병원을 떠나는 것입니다. 통역 시 퇴원 후 주의사항과 약 처방을 설명합니다.",
      "Rời bệnh viện sau khi điều trị xong",
      "원무과",
      "퇴원 후 자가 관리 방법을 교육하고, 응급 상황 대처를 안내합니다.",
      [{"mistake":"퇴원하면 다 나았다고 설명","correction":"회복 중이므로 주의 필요","explanation":"자가 관리가 중요합니다"},
       {"mistake":"퇴원 약 복용법 설명 생략","correction":"약 복용법 상세히 설명","explanation":"치료 지속이 필요합니다"},
       {"mistake":"응급 상황 대처 안내 안 함","correction":"위험 증상 시 연락처 안내","explanation":"문제 시 빠른 대응이 가능합니다"}],
      [{"ko":"퇴원 후 이 약을 드시고 2주 후 외래 오세요.","vi":"Sau xuất viện uống thuốc này và đến tái khám sau 2 tuần.","situation":"formal"},
       {"ko":"열이 나거나 통증이 심해지면 바로 연락하세요.","vi":"Nếu sốt hoặc đau nhiều hơn hãy liên lạc ngay.","situation":"onsite"},
       {"ko":"오늘 퇴원해요.","vi":"Hôm nay xuất viện.","situation":"informal"}],
      ["퇴원약","외래예약","자가관리"]),

    t("cham-soc-tai-nha","가정간호","chăm sóc tại nhà",
      "집에서 전문 간호를 받는 서비스입니다. 통역 시 서비스 내용과 비용을 안내합니다.",
      "Dịch vụ chăm sóc y tế chuyên môn tại nhà",
      "가정간호팀",
      "가정간호 서비스의 장점과 이용 방법을 설명합니다.",
      [{"mistake":"병원 치료보다 못하다고 설명","correction":"적합한 환자에게는 효과적","explanation":"편안한 환경에서 치료 가능"},
       {"mistake":"비용이 비싸다고만 강조","correction":"건강보험 적용 여부 확인","explanation":"부담을 줄일 수 있습니다"},
       {"mistake":"모든 치료가 가능하다고 설명","correction":"병원 치료가 필요한 경우도 있음","explanation":"한계를 명확히 합니다"}],
      [{"ko":"가정간호 서비스를 이용하실 수 있습니다.","vi":"Có thể sử dụng dịch vụ chăm sóc tại nhà.","situation":"formal"},
       {"ko":"간호사가 집으로 방문합니다.","vi":"Y tá sẽ đến nhà.","situation":"onsite"},
       {"ko":"집에서 간호 받아요.","vi":"Được chăm sóc ở nhà.","situation":"informal"}],
      ["방문간호","주사","상처관리"]),

    t("tam-than","정신건강","tâm thần",
      "마음과 감정의 건강 상태입니다. 통역 시 정신건강 질환에 대한 편견 없이 설명합니다.",
      "Tình trạng sức khỏe của tâm trí và cảm xúc",
      "정신건강의학과",
      "정신건강에 대한 낙인을 줄이고, 도움을 받도록 격려합니다.",
      [{"mistake":"정신과 방문을 꺼리게 만듦","correction":"정신건강 관리도 일반 건강 관리와 같음","explanation":"자연스럽게 접근합니다"},
       {"mistake":"미쳤다는 표현 사용","correction":"질병으로 존중하며 표현","explanation":"낙인을 피합니다"},
       {"mistake":"혼자 해결하라고 조언","correction":"전문가 도움의 중요성 강조","explanation":"치료가 필요합니다"}],
      [{"ko":"정신건강 상담을 받아보시는 게 좋겠습니다.","vi":"Nên đi tư vấn sức khỏe tâm thần.","situation":"formal"},
       {"ko":"마음이 힘드시면 말씀해 주세요.","vi":"Nếu khó khăn về tinh thần hãy nói.","situation":"onsite"},
       {"ko":"정신과 다녀요.","vi":"Đang đi khám tâm thần.","situation":"informal"}],
      ["상담","약물치료","심리치료"]),

    t("phuc-hoi-chuc-nang","재활치료","phục hồi chức năng",
      "질병이나 부상 후 기능을 회복하기 위한 치료입니다. 통역 시 재활 목표와 과정을 설명합니다.",
      "Điều trị phục hồi chức năng sau bệnh hoặc chấn thương",
      "재활의학과",
      "재활은 장기적 과정임을 이해시키고, 동기를 부여합니다.",
      [{"mistake":"빨리 회복된다고만 설명","correction":"인내와 꾸준함이 필요","explanation":"현실적 목표를 설정합니다"},
       {"mistake":"환자의 노력만 강조","correction":"팀 접근(의사, 치료사, 가족)이 중요","explanation":"지지 체계가 필요합니다"},
       {"mistake":"100% 회복을 약속","correction":"개인차가 있음을 설명","explanation":"최선을 다하되 한계를 인정합니다"}],
      [{"ko":"재활치료를 위해 매일 운동해야 합니다.","vi":"Cần tập mỗi ngày để phục hồi chức năng.","situation":"formal"},
       {"ko":"조금씩 좋아지고 있어요.","vi":"Đang tiến bộ dần.","situation":"onsite"},
       {"ko":"재활 받고 있어요.","vi":"Đang tập phục hồi.","situation":"informal"}],
      ["물리치료","작업치료","언어치료"]),

    t("cham-soc-giam-nhe","완화의료","chăm sóc giảm nhẹ",
      "완치가 어려운 질환에서 증상을 조절하고 삶의 질을 높이는 의료입니다. 통역 시 완화의료의 목표와 가치를 민감하게 전달합니다.",
      "Y tế điều trị triệu chứng và nâng cao chất lượng sống khi bệnh khó chữa khỏi",
      "완화의료팀",
      "완화의료가 포기가 아님을 이해시키고, 환자와 가족을 지지합니다.",
      [{"mistake":"완화의료를 포기로 설명","correction":"적극적 증상 관리와 지지","explanation":"삶의 질이 목표입니다"},
       {"mistake":"죽음만 강조","correction":"남은 시간을 의미있게 보내도록 돕는 것","explanation":"긍정적 관점을 유지합니다"},
       {"mistake":"가족 감정 무시","correction":"환자와 가족 모두 케어 대상","explanation":"전인적 접근이 필요합니다"}],
      [{"ko":"완화의료팀이 통증 조절을 도와드립니다.","vi":"Đội chăm sóc giảm nhẹ sẽ giúp kiểm soát đau.","situation":"formal"},
       {"ko":"편안하게 지내시도록 최선을 다하겠습니다.","vi":"Sẽ cố gắng hết sức để bạn được thoải mái.","situation":"onsite"},
       {"ko":"완화치료 받고 있어요.","vi":"Đang điều trị giảm nhẹ.","situation":"informal"}],
      ["통증관리","호스피스","가족지지"]),

    t("ho-tro-tam-ly","심리상담","hỗ trợ tâm lý",
      "정신적 어려움에 대해 전문가와 대화하며 도움을 받는 것입니다. 통역 시 상담의 비밀 보장을 강조합니다.",
      "Nhận giúp đỡ từ chuyên gia qua đối thoại về khó khăn tâm lý",
      "정신건강의학과/상담센터",
      "상담은 안전하고 비밀이 보장됨을 알려 참여를 독려합니다.",
      [{"mistake":"상담이 약하다는 증거라고 암시","correction":"도움을 구하는 것은 용기","explanation":"긍정적으로 접근합니다"},
       {"mistake":"상담 내용이 공개된다고 설명","correction":"비밀 보장이 원칙","explanation":"안심시킵니다"},
       {"mistake":"한두 번으로 해결된다고 설명","correction":"과정이 필요함을 안내","explanation":"지속적 참여가 중요합니다"}],
      [{"ko":"심리상담을 통해 도움을 받을 수 있습니다.","vi":"Có thể nhận giúp đỡ qua tư vấn tâm lý.","situation":"formal"},
       {"ko":"말씀하신 내용은 비밀이 보장됩니다.","vi":"Những gì bạn nói sẽ được bảo mật.","situation":"onsite"},
       {"ko":"상담 받고 있어요.","vi":"Đang được tư vấn.","situation":"informal"}],
      ["비밀보장","심리치료","상담사"]),

    t("bao-hiem-y-te","건강보험","bảo hiểm y tế",
      "의료비 부담을 줄이기 위한 사회보험 제도입니다. 통역 시 보험 적용 범위와 본인부담금을 설명합니다.",
      "Chế độ bảo hiểm xã hội giảm gánh nặng chi phí y tế",
      "원무과",
      "외국인 근로자의 건강보험 적용 여부와 절차를 안내합니다.",
      [{"mistake":"모든 것이 무료라고 설명","correction":"본인부담금 있음","explanation":"예상 비용을 알려줍니다"},
       {"mistake":"보험 적용 절차 안내 안 함","correction":"보험증 지참, 등록 절차 안내","explanation":"적용받을 수 있게 돕습니다"},
       {"mistake":"비급여 항목 설명 안 함","correction":"일부 항목은 보험 미적용","explanation":"예상치 못한 비용 방지"}],
      [{"ko":"건강보험증을 가져오셨나요?","vi":"Bạn có mang thẻ bảo hiểm y tế không?","situation":"formal"},
       {"ko":"이 검사는 보험이 적용됩니다.","vi":"Xét nghiệm này được bảo hiểm.","situation":"onsite"},
       {"ko":"보험 돼요?","vi":"Có được bảo hiểm không?","situation":"informal"}],
      ["본인부담금","비급여","보험증"]),

    t("giay-chung-nhan-y-te","진단서","giấy chứng nhận y tế",
      "질병이나 상태에 대한 의사의 공식 문서입니다. 통역 시 발급 목적과 절차를 안내합니다.",
      "Văn bản chính thức của bác sĩ về bệnh hoặc tình trạng sức khỏe",
      "원무과",
      "진단서가 필요한 상황(직장, 보험, 법적)과 발급 절차를 설명합니다.",
      [{"mistake":"모든 내용을 환자가 정할 수 있다고 설명","correction":"의사가 사실대로 기재","explanation":"위조는 불법입니다"},
       {"mistake":"바로 발급된다고 설명","correction":"발급에 시간이 걸릴 수 있음","explanation":"여유를 두고 신청합니다"},
       {"mistake":"무료라고 설명","correction":"발급 비용 있음","explanation":"비용을 안내합니다"}],
      [{"ko":"진단서 발급을 원하시면 원무과에 신청하세요.","vi":"Muốn cấp giấy chẩn đoán hãy đăng ký ở phòng hành chính.","situation":"formal"},
       {"ko":"진단서는 3일 후에 받으실 수 있어요.","vi":"Giấy chẩn đoán nhận được sau 3 ngày.","situation":"onsite"},
       {"ko":"진단서 필요해요.","vi":"Cần giấy chẩn đoán.","situation":"informal"}],
      ["발급비","원무과","의무기록"]),

    t("dong-y","동의서","đồng ý",
      "의료 행위에 대해 환자가 이해하고 동의함을 확인하는 문서입니다. 통역 시 내용을 충분히 설명하고 질문할 기회를 줍니다.",
      "Văn bản xác nhận bệnh nhân hiểu và đồng ý hành vi y tế",
      "해당 진료과",
      "동의서는 환자 권리 보호를 위한 것임을 설명합니다.",
      [{"mistake":"형식적으로 서명만 받음","correction":"내용을 충분히 설명","explanation":"informed consent가 중요합니다"},
       {"mistake":"질문할 시간 안 줌","correction":"질문하도록 독려","explanation":"이해하고 동의해야 합니다"},
       {"mistake":"거부하면 안 된다고 압박","correction":"거부권이 있음을 알림","explanation":"자발적 동의가 원칙입니다"}],
      [{"ko":"수술 동의서 내용을 설명해 드리겠습니다.","vi":"Tôi sẽ giải thích nội dung giấy đồng ý phẫu thuật.","situation":"formal"},
       {"ko":"질문 있으시면 말씀해 주세요.","vi":"Nếu có thắc mắc hãy nói.","situation":"onsite"},
       {"ko":"동의서 써야 해요.","vi":"Phải ký giấy đồng ý.","situation":"informal"}],
      ["설명동의","서명","환자권리"]),

    t("ho-tro-ngon-ngu","통역서비스","hỗ trợ ngôn ngữ",
      "언어 장벽을 해소하기 위해 제공되는 통역 지원입니다. 통역 시 전문 의료통역의 중요성을 강조합니다.",
      "Dịch vụ phiên dịch để vượt qua rào cản ngôn ngữ",
      "국제진료센터",
      "전문 통역의 중요성과 이용 방법을 안내합니다.",
      [{"mistake":"가족 통역으로 충분하다고 설명","correction":"전문 의료통역이 더 정확","explanation":"오역을 방지합니다"},
       {"mistake":"통역 비용을 환자에게 전가","correction":"무료 통역 서비스 있으면 안내","explanation":"접근성을 높입니다"},
       {"mistake":"통역 없이 진료 진행","correction":"이해 확인 후 진행","explanation":"환자 안전이 우선입니다"}],
      [{"ko":"통역 서비스가 필요하시면 말씀해 주세요.","vi":"Nếu cần dịch vụ phiên dịch hãy nói.","situation":"formal"},
       {"ko":"베트남어 통역사가 있습니다.","vi":"Có phiên dịch tiếng Việt.","situation":"onsite"},
       {"ko":"통역사 불러주세요.","vi":"Gọi phiên dịch cho tôi.","situation":"informal"}],
      ["의료통역","국제진료","다문화"]),

    t("truyen-dich","수액/링거","truyền dịch",
      "정맥으로 수분, 전해질, 영양분을 공급하는 치료입니다. 통역 시 수액의 목적과 주의사항을 설명합니다.",
      "Điều trị cung cấp nước, điện giải, dinh dưỡng qua tĩnh mạch",
      "해당 진료과",
      "수액 치료의 이유와 예상 시간을 설명합니다.",
      [{"mistake":"수액이 만병통치라고 설명","correction":"특정 상황에 필요한 치료","explanation":"적응증을 설명합니다"},
       {"mistake":"주입 속도를 환자가 조절하게 함","correction":"의료진이 조절","explanation":"안전 문제가 있습니다"},
       {"mistake":"불편감 무시","correction":"통증이나 부종 시 알리도록 교육","explanation":"합병증 조기 발견"}],
      [{"ko":"탈수가 있어서 수액을 맞으셔야 합니다.","vi":"Bị mất nước nên cần truyền dịch.","situation":"formal"},
       {"ko":"팔이 부으면 말씀해 주세요.","vi":"Nếu tay sưng hãy nói.","situation":"onsite"},
       {"ko":"링거 맞고 있어요.","vi":"Đang truyền dịch.","situation":"informal"}],
      ["정맥주사","전해질","탈수"]),

    t("tiem","주사","tiêm",
      "바늘을 이용해 약물을 체내에 투여하는 방법입니다. 통역 시 주사 종류와 부위를 설명합니다.",
      "Phương pháp đưa thuốc vào cơ thể qua kim",
      "해당 진료과",
      "주사에 대한 두려움을 완화하고, 부작용을 안내합니다.",
      [{"mistake":"아프지 않다고만 설명","correction":"약간의 통증은 있을 수 있음","explanation":"솔직하게 설명합니다"},
       {"mistake":"알레르기 확인 안 함","correction":"약물 알레르기 반드시 확인","explanation":"안전이 우선입니다"},
       {"mistake":"주사 후 관찰 안 함","correction":"알레르기 반응 관찰 필요","explanation":"즉각 대응이 가능합니다"}],
      [{"ko":"이 주사는 엉덩이에 맞습니다.","vi":"Mũi tiêm này tiêm vào mông.","situation":"formal"},
       {"ko":"주사 맞은 자리를 문지르지 마세요.","vi":"Đừng xoa chỗ tiêm.","situation":"onsite"},
       {"ko":"주사 맞았어요.","vi":"Đã tiêm.","situation":"informal"}],
      ["근육주사","피하주사","정맥주사"]),

    t("bang-bo","붕대/드레싱","băng bó",
      "상처를 보호하고 치유를 돕기 위해 감싸는 것입니다. 통역 시 드레싱 교체 시기와 방법을 설명합니다.",
      "Việc quấn băng để bảo vệ vết thương và giúp lành",
      "외과/응급",
      "자가 드레싱 방법과 감염 징후를 교육합니다.",
      [{"mistake":"젖은 채로 두라고 조언","correction":"깨끗하고 건조하게 유지","explanation":"감염 예방이 중요합니다"},
       {"mistake":"드레싱 교체 안내 안 함","correction":"교체 주기와 방법 설명","explanation":"치유를 돕습니다"},
       {"mistake":"감염 징후 교육 안 함","correction":"발적, 부종, 분비물 시 내원","explanation":"조기 발견이 중요합니다"}],
      [{"ko":"붕대는 2일마다 갈아주세요.","vi":"Thay băng 2 ngày một lần.","situation":"formal"},
       {"ko":"상처 부위가 빨갛게 부으면 오세요.","vi":"Nếu vết thương sưng đỏ hãy đến.","situation":"onsite"},
       {"ko":"붕대 갈아야 해요.","vi":"Phải thay băng.","situation":"informal"}],
      ["소독","상처관리","감염징후"]),

    t("chi-khau","봉합/실밥","chỉ khâu",
      "상처를 꿰매어 치유를 돕는 것입니다. 통역 시 실밥 제거 시기와 관리 방법을 설명합니다.",
      "Việc khâu vết thương để giúp lành",
      "외과/응급",
      "봉합 부위 관리와 실밥 제거 일정을 안내합니다.",
      [{"mistake":"실밥을 직접 빼도 된다고 설명","correction":"반드시 병원에서 제거","explanation":"감염과 흉터 예방"},
       {"mistake":"물에 닿아도 된다고 설명","correction":"건조하게 유지","explanation":"감염 예방이 중요합니다"},
       {"mistake":"실밥 제거 일정 안내 안 함","correction":"부위에 따라 7-14일 후 제거","explanation":"적절한 시기가 중요합니다"}],
      [{"ko":"실밥은 7일 후에 빼러 오세요.","vi":"7 ngày sau đến cắt chỉ.","situation":"formal"},
       {"ko":"봉합 부위를 물에 적시지 마세요.","vi":"Đừng để chỗ khâu dính nước.","situation":"onsite"},
       {"ko":"실밥 빼러 왔어요.","vi":"Đến cắt chỉ.","situation":"informal"}],
      ["실밥제거","흉터관리","상처치유"]),

    t("benh-man-tinh","만성질환","bệnh mãn tính",
      "오랜 기간 지속되며 관리가 필요한 질병입니다. 통역 시 장기 관리의 중요성과 방법을 설명합니다.",
      "Bệnh kéo dài lâu và cần quản lý",
      "해당 진료과",
      "만성질환은 완치보다 관리가 목표임을 이해시킵니다.",
      [{"mistake":"완치할 수 있다고 설명","correction":"관리가 목표임을 설명","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"약만 먹으면 된다고 설명","correction":"생활습관 관리도 필수","explanation":"종합적 접근이 필요합니다"},
       {"mistake":"포기하게 만드는 설명","correction":"잘 관리하면 정상 생활 가능","explanation":"희망을 줍니다"}],
      [{"ko":"만성질환이라 평생 관리가 필요합니다.","vi":"Bệnh mãn tính cần quản lý suốt đời.","situation":"formal"},
       {"ko":"약을 꾸준히 드시면 좋은 상태를 유지할 수 있어요.","vi":"Uống thuốc đều đặn có thể duy trì tình trạng tốt.","situation":"onsite"},
       {"ko":"만성질환이 있어요.","vi":"Có bệnh mãn tính.","situation":"informal"}],
      ["당뇨","고혈압","관리"]),

    t("di-ung","알레르기","dị ứng",
      "특정 물질에 면역체계가 과민 반응하는 것입니다. 통역 시 알레르기 병력 확인과 회피법을 안내합니다.",
      "Phản ứng quá mẫn của hệ miễn dịch với chất nhất định",
      "알레르기내과",
      "약물 알레르기를 반드시 확인하고, 비상 대처법을 교육합니다.",
      [{"mistake":"알레르기 병력 확인 안 함","correction":"모든 진료 전 반드시 확인","explanation":"안전이 최우선입니다"},
       {"mistake":"경미한 알레르기 무시","correction":"심해질 수 있음을 설명","explanation":"예방이 중요합니다"},
       {"mistake":"알레르기원 회피법 안내 안 함","correction":"구체적 회피 방법 교육","explanation":"재발 예방에 필수입니다"}],
      [{"ko":"알레르기가 있으시면 말씀해 주세요.","vi":"Nếu có dị ứng hãy nói.","situation":"formal"},
       {"ko":"이 약에 알레르기가 있으셨나요?","vi":"Trước đây có bị dị ứng thuốc này không?","situation":"onsite"},
       {"ko":"알레르기 있어요.","vi":"Có dị ứng.","situation":"informal"}],
      ["약물알레르기","음식알레르기","아나필락시스"]),

    t("dau","통증","đau",
      "신체적 불편함이나 고통의 감각입니다. 통역 시 통증 양상, 위치, 강도를 정확히 전달합니다.",
      "Cảm giác khó chịu hoặc đau đớn về thể chất",
      "해당 진료과",
      "통증 표현에 어려움이 있으면 통증 척도를 활용합니다.",
      [{"mistake":"통증을 가볍게 여김","correction":"환자의 통증 호소를 진지하게 받아들임","explanation":"주관적 경험을 존중합니다"},
       {"mistake":"구체적 표현을 요구하지 않음","correction":"위치, 양상, 강도 확인","explanation":"진단에 도움이 됩니다"},
       {"mistake":"참으라고만 조언","correction":"통증 조절 방법 안내","explanation":"삶의 질이 중요합니다"}],
      [{"ko":"통증이 어떤 식으로 아프세요? 쑤시듯이? 찌르듯이?","vi":"Đau như thế nào? Nhức? Như dao đâm?","situation":"formal"},
       {"ko":"0에서 10까지 중 얼마나 아프세요?","vi":"Từ 0 đến 10, đau mức mấy?","situation":"onsite"},
       {"ko":"여기가 아파요.","vi":"Đau ở đây.","situation":"informal"}],
      ["통증척도","진통제","만성통증"]),

    t("sot","발열","sốt",
      "체온이 정상보다 높아진 상태입니다. 통역 시 체온 측정 방법과 해열 방법을 안내합니다.",
      "Tình trạng nhiệt độ cơ thể cao hơn bình thường",
      "해당 진료과",
      "발열의 원인을 찾는 것이 중요함을 설명합니다.",
      [{"mistake":"열 자체만 치료 목표로 설명","correction":"원인 파악이 더 중요","explanation":"근본 치료가 필요합니다"},
       {"mistake":"해열제를 과도하게 사용하게 조언","correction":"적절한 용량과 간격 유지","explanation":"과량 복용 위험"},
       {"mistake":"열이 조금 나면 응급이라고 겁줌","correction":"위험 신호를 구분하여 설명","explanation":"불필요한 불안을 줄입니다"}],
      [{"ko":"체온이 38.5도 이상이면 해열제를 드세요.","vi":"Nếu nhiệt độ trên 38.5 độ hãy uống hạ sốt.","situation":"formal"},
       {"ko":"물을 많이 드시고 쉬세요.","vi":"Uống nhiều nước và nghỉ ngơi.","situation":"onsite"},
       {"ko":"열이 나요.","vi":"Bị sốt.","situation":"informal"}],
      ["해열제","체온계","감염"]),

    t("met-moi","피로","mệt mỏi",
      "에너지가 부족하고 지친 느낌입니다. 통역 시 원인 가능성(질병, 수면, 스트레스)을 설명합니다.",
      "Cảm giác thiếu năng lượng và kiệt sức",
      "해당 진료과",
      "피로의 원인은 다양하며, 지속되면 검사가 필요함을 설명합니다.",
      [{"mistake":"피로를 가볍게 여김","correction":"지속되는 피로는 질병 신호일 수 있음","explanation":"원인 확인이 필요합니다"},
       {"mistake":"쉬면 낫는다고만 설명","correction":"원인에 따라 치료 필요","explanation":"근본 원인을 찾습니다"},
       {"mistake":"정신적 문제로만 치부","correction":"신체적 원인도 흔함","explanation":"종합적 평가가 필요합니다"}],
      [{"ko":"피로가 지속되면 혈액검사가 필요합니다.","vi":"Nếu mệt mỏi kéo dài cần xét nghiệm máu.","situation":"formal"},
       {"ko":"요즘 많이 피곤하세요?","vi":"Dạo này có mệt nhiều không?","situation":"onsite"},
       {"ko":"너무 피곤해요.","vi":"Mệt quá.","situation":"informal"}],
      ["빈혈","갑상선","수면"]),

    t("chong-mat","어지러움","chóng mặt",
      "균형감각이 흔들리거나 빙빙 도는 느낌입니다. 통역 시 어지러움의 양상(빙빙 도는 vs 아찔한)을 구분합니다.",
      "Cảm giác mất thăng bằng hoặc xoay tròn",
      "이비인후과/신경과",
      "어지러움의 원인은 다양하며, 정확한 표현이 진단에 중요합니다.",
      [{"mistake":"모든 어지러움을 같게 취급","correction":"양상에 따라 원인이 다름","explanation":"정확한 묘사가 필요합니다"},
       {"mistake":"가볍게 여김","correction":"뇌졸중 증상일 수 있음","explanation":"위험 신호를 확인합니다"},
       {"mistake":"어지러우면 눕기만 권유","correction":"원인에 따라 운동이 치료일 수 있음","explanation":"개인화된 치료가 필요합니다"}],
      [{"ko":"어지러움이 빙빙 도는 느낌인가요, 아찔한 느낌인가요?","vi":"Chóng mặt như xoay tròn hay như choáng váng?","situation":"formal"},
       {"ko":"갑자기 어지러우면 앉거나 누우세요.","vi":"Nếu đột ngột chóng mặt hãy ngồi hoặc nằm xuống.","situation":"onsite"},
       {"ko":"어지러워요.","vi":"Bị chóng mặt.","situation":"informal"}],
      ["이석증","메니에르","전정신경염"]),

    t("ho","기침","ho",
      "기도를 통해 이물질이나 분비물을 배출하는 반사 작용입니다. 통역 시 기침 양상과 기간을 확인합니다.",
      "Phản xạ tống dị vật hoặc dịch tiết qua đường thở",
      "호흡기내과",
      "기침의 특성(마른/습한, 급성/만성)이 진단에 중요합니다.",
      [{"mistake":"기침약을 먼저 처방","correction":"원인 확인이 우선","explanation":"증상 치료보다 원인 치료"},
       {"mistake":"3주 이상 기침 무시","correction":"결핵 등 감염 배제 필요","explanation":"지속되면 검사 필요"},
       {"mistake":"항생제가 필요하다고 설명","correction":"바이러스성은 항생제 불필요","explanation":"원인에 따른 치료"}],
      [{"ko":"기침이 언제부터 있었나요?","vi":"Bị ho từ khi nào?","situation":"formal"},
       {"ko":"가래가 나오나요?","vi":"Có đờm không?","situation":"onsite"},
       {"ko":"기침이 안 멈춰요.","vi":"Ho mãi không ngừng.","situation":"informal"}],
      ["가래","기침약","흉부X선"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
