#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Medical terms batch H - 내분비/대사 + 피부 (27개 - 500 도달용)"""
import json

def t(s,k,v,mk,mv,cx,cn,cm,ex,rt):
    return {"slug":s,"korean":k,"vietnamese":v,"hanja":None,"hanjaReading":None,
            "pronunciation":s,"meaningKo":mk,"meaningVi":mv,"context":cx,
            "culturalNote":cn,"commonMistakes":cm,"examples":ex,"relatedTerms":rt}

terms = [
    t("tieu-duong-type-1","제1형당뇨병","tiểu đường type 1",
      "췌장에서 인슐린이 거의 분비되지 않아 평생 인슐린 주사가 필요한 자가면역 질환입니다. 통역 시 제2형과 달리 생활습관과 무관하게 발생함을 설명하고, 저혈당 대처법을 교육합니다.",
      "Bệnh tự miễn khi tụy hầu như không tiết insulin, cần tiêm insulin suốt đời",
      "내분비내과",
      "소아·청소년에서 주로 발생하지만 성인에서도 가능합니다. 인슐린 의존적임을 명확히 합니다.",
      [{"mistake":"제2형과 혼동","correction":"제1형은 자가면역, 제2형은 인슐린 저항성","explanation":"원인과 치료가 다릅니다"},
       {"mistake":"살 빼면 낫는다고 설명","correction":"체중과 무관, 인슐린 필수","explanation":"생활습관으로 조절 불가"},
       {"mistake":"인슐린은 최후 수단이라고 설명","correction":"제1형은 처음부터 인슐린 필요","explanation":"생존에 필수입니다"}],
      [{"ko":"제1형당뇨병으로 매일 인슐린 주사가 필요합니다.","vi":"Tiểu đường type 1 cần tiêm insulin mỗi ngày.","situation":"formal"},
       {"ko":"저혈당 증상이 오면 사탕이나 주스를 드세요.","vi":"Khi có triệu chứng hạ đường huyết hãy ăn kẹo hoặc uống nước trái cây.","situation":"onsite"},
       {"ko":"1형 당뇨라서 인슐린 없이는 못 살아요.","vi":"Tiểu đường type 1 nên không có insulin không sống được.","situation":"informal"}],
      ["인슐린펌프","저혈당","연속혈당측정기"]),

    t("tieu-duong-type-2","제2형당뇨병","tiểu đường type 2",
      "인슐린 저항성과 분비 감소로 혈당이 높아지는 대사 질환입니다. 통역 시 생활습관 개선의 중요성과 합병증 예방을 위한 정기 검진을 강조합니다.",
      "Bệnh chuyển hóa với đường huyết cao do kháng insulin và giảm tiết insulin",
      "내분비내과",
      "베트남 환자들에게 흔한 만성질환입니다. 쌀밥 중심 식단에서의 탄수화물 조절을 구체적으로 안내합니다.",
      [{"mistake":"당뇨약 먹으면 뭐든 먹어도 된다고 설명","correction":"식이 조절과 운동 병행 필수","explanation":"약만으로는 조절 어렵습니다"},
       {"mistake":"증상 없으면 괜찮다고 설명","correction":"무증상으로 합병증 진행","explanation":"정기 검진이 필수입니다"},
       {"mistake":"인슐린은 최후 수단이라고 겁줌","correction":"인슐린이 필요하면 쓰는 게 좋음","explanation":"합병증 예방이 우선입니다"}],
      [{"ko":"제2형당뇨병 관리를 위해 식이 조절과 운동이 필요합니다.","vi":"Cần điều chỉnh chế độ ăn và vận động để quản lý tiểu đường type 2.","situation":"formal"},
       {"ko":"밥 양을 줄이고 채소를 먼저 드세요.","vi":"Giảm cơm và ăn rau trước.","situation":"onsite"},
       {"ko":"당뇨 있어서 단거 조심해요.","vi":"Bị tiểu đường nên kiêng đồ ngọt.","situation":"informal"}],
      ["혈당조절","당화혈색소","당뇨합병증"]),

    t("cuong-giap","갑상선기능항진증","cường giáp",
      "갑상선호르몬이 과다 분비되어 대사가 빨라지고 체중 감소, 빈맥, 발한 등이 나타납니다. 통역 시 그레이브스병이 흔한 원인임을 설명합니다.",
      "Tình trạng hormone tuyến giáp tiết quá nhiều làm tăng chuyển hóa, giảm cân, tim nhanh, ra mồ hôi",
      "내분비내과",
      "젊은 여성에게 흔합니다. 스트레스가 악화 요인이 될 수 있음을 알립니다.",
      [{"mistake":"단순히 살 빠지는 병으로 설명","correction":"심장, 뼈 등 전신에 영향","explanation":"방치하면 위험합니다"},
       {"mistake":"약 먹으면 바로 낫는다고 설명","correction":"장기 치료 또는 수술/방사성요오드 필요","explanation":"치료 옵션을 설명합니다"},
       {"mistake":"갑상선암과 혼동","correction":"기능항진은 양성 질환","explanation":"불필요한 공포를 줄입니다"}],
      [{"ko":"갑상선기능항진증으로 항갑상선제를 드셔야 합니다.","vi":"Cường giáp cần uống thuốc kháng giáp.","situation":"formal"},
       {"ko":"가슴이 두근거리고 살이 빠지면 검사받으세요.","vi":"Nếu tim đập nhanh và sụt cân hãy đi xét nghiệm.","situation":"onsite"},
       {"ko":"갑상선 항진이라 심장이 빨리 뛰어요.","vi":"Cường giáp nên tim đập nhanh.","situation":"informal"}],
      ["그레이브스병","항갑상선제","방사성요오드치료"]),

    t("suy-giap","갑상선기능저하증","suy giáp",
      "갑상선호르몬이 부족하여 대사가 느려지고 피로, 체중 증가, 추위를 잘 느낍니다. 통역 시 평생 호르몬 보충이 필요할 수 있음을 설명합니다.",
      "Tình trạng thiếu hormone tuyến giáp làm chậm chuyển hóa, mệt mỏi, tăng cân, sợ lạnh",
      "내분비내과",
      "하시모토갑상선염이 흔한 원인입니다. 약을 꾸준히 복용하면 정상 생활 가능함을 알립니다.",
      [{"mistake":"평생 약 먹어야 한다고만 강조","correction":"약으로 정상 생활 가능","explanation":"희망을 줍니다"},
       {"mistake":"단순 피로로 치부","correction":"갑상선 검사로 확인 필요","explanation":"원인 질환이 있을 수 있습니다"},
       {"mistake":"다이어트해도 살이 안 빠진다고만 설명","correction":"치료하면 체중 조절 가능","explanation":"치료의 효과를 알립니다"}],
      [{"ko":"갑상선기능저하증으로 갑상선호르몬제를 드셔야 합니다.","vi":"Suy giáp cần uống hormone tuyến giáp.","situation":"formal"},
       {"ko":"아침 공복에 약을 드시고 30분 후 식사하세요.","vi":"Uống thuốc lúc đói buổi sáng, 30 phút sau mới ăn.","situation":"onsite"},
       {"ko":"갑상선 저하라서 쉽게 피곤해요.","vi":"Suy giáp nên dễ mệt mỏi.","situation":"informal"}],
      ["레보티록신","하시모토","TSH"]),

    t("nhan-giap","갑상선결절","nhân giáp",
      "갑상선에 혹(결절)이 생긴 상태로, 대부분 양성이지만 일부는 암일 수 있습니다. 통역 시 초음파와 조직검사의 필요성을 설명합니다.",
      "Tình trạng có khối u (nốt) trong tuyến giáp, phần lớn lành tính nhưng một số có thể là ung thư",
      "내분비내과/외과",
      "건강검진에서 흔히 발견됩니다. 결절=암이 아님을 설명하되, 추적의 중요성을 강조합니다.",
      [{"mistake":"결절이 곧 암이라고 겁줌","correction":"90% 이상은 양성","explanation":"불필요한 공포를 줄입니다"},
       {"mistake":"작으면 검사 안 해도 된다고 설명","correction":"크기와 특성에 따라 조직검사 필요","explanation":"악성 배제가 중요합니다"},
       {"mistake":"모두 수술해야 한다고 설명","correction":"양성이면 관찰도 가능","explanation":"개인화된 접근이 필요합니다"}],
      [{"ko":"갑상선결절 확인을 위해 초음파 유도하 세침흡인검사가 필요합니다.","vi":"Cần chọc hút kim nhỏ dưới hướng dẫn siêu âm để xác nhận nhân giáp.","situation":"formal"},
       {"ko":"결절이 있지만 대부분 양성이니 걱정 마세요.","vi":"Có nốt nhưng phần lớn lành tính, đừng lo.","situation":"onsite"},
       {"ko":"갑상선에 혹이 있어서 조직검사했어요.","vi":"Có khối u trong tuyến giáp nên đã sinh thiết.","situation":"informal"}],
      ["세침흡인검사","갑상선초음파","갑상선암"]),

    t("ung-thu-tuyen-giap","갑상선암","ung thư tuyến giáp",
      "갑상선에 발생하는 악성 종양으로, 대부분 예후가 좋습니다. 통역 시 갑상선암 중 유두암이 가장 흔하고 완치율이 높음을 설명합니다.",
      "Khối u ác tính phát sinh ở tuyến giáp, phần lớn có tiên lượng tốt",
      "외과/종양내과",
      "한국에서 갑상선암 발견율이 높습니다. 과잉진단 논란이 있지만, 진단되면 치료를 권합니다.",
      [{"mistake":"암이면 곧 사망이라고 설명","correction":"갑상선암은 예후가 매우 좋음","explanation":"희망을 줍니다"},
       {"mistake":"수술 안 해도 된다고 설명","correction":"대부분 수술이 표준 치료","explanation":"개인 상황에 따라 판단"},
       {"mistake":"방사성요오드는 방사선이라 위험하다고 겁줌","correction":"갑상선 조직에만 작용","explanation":"안전한 치료입니다"}],
      [{"ko":"갑상선암 수술 후 방사성요오드 치료가 필요할 수 있습니다.","vi":"Sau phẫu thuật ung thư tuyến giáp có thể cần điều trị i-ốt phóng xạ.","situation":"formal"},
       {"ko":"갑상선암은 예후가 좋으니 너무 걱정하지 마세요.","vi":"Ung thư tuyến giáp tiên lượng tốt, đừng lo quá.","situation":"onsite"},
       {"ko":"갑상선암 수술하고 약 먹고 있어요.","vi":"Mổ ung thư tuyến giáp xong đang uống thuốc.","situation":"informal"}],
      ["갑상선절제술","방사성요오드","레보티록신"]),

    t("roi-loan-lipid-mau","이상지질혈증","rối loạn lipid máu",
      "혈중 콜레스테롤이나 중성지방이 비정상인 상태로, 동맥경화와 심혈관질환의 위험을 높입니다. 통역 시 증상 없이 진행되므로 정기 검진의 중요성을 강조합니다.",
      "Tình trạng cholesterol hoặc triglyceride trong máu bất thường, tăng nguy cơ xơ vữa động mạch và bệnh tim mạch",
      "내분비내과/순환기내과",
      "베트남 음식의 기름진 요리와 연관지어 식이 교육을 합니다.",
      [{"mistake":"수치가 조금 높은 건 괜찮다고 설명","correction":"경계치도 관리 필요","explanation":"축적되면 문제가 됩니다"},
       {"mistake":"약 먹으면 뭐든 먹어도 된다고 설명","correction":"식이 조절 병행 필수","explanation":"약과 생활습관 모두 중요"},
       {"mistake":"젊으면 괜찮다고 안심시킴","correction":"젊을 때부터 관리 중요","explanation":"누적 효과가 있습니다"}],
      [{"ko":"이상지질혈증으로 스타틴 약물을 처방합니다.","vi":"Rối loạn lipid máu, sẽ kê thuốc statin.","situation":"formal"},
       {"ko":"기름진 음식과 튀김을 줄이세요.","vi":"Hãy giảm đồ nhiều dầu mỡ và chiên.","situation":"onsite"},
       {"ko":"콜레스테롤 높아서 약 먹어요.","vi":"Cholesterol cao nên đang uống thuốc.","situation":"informal"}],
      ["스타틴","LDL콜레스테롤","식이요법"]),

    t("beo-phi","비만","béo phì",
      "체지방이 과다하게 축적된 상태로, 당뇨, 고혈압, 관절질환 등 다양한 합병증을 유발합니다. 통역 시 BMI 계산과 목표 체중 설정을 도와줍니다.",
      "Tình trạng tích tụ quá nhiều mỡ cơ thể, gây ra nhiều biến chứng như tiểu đường, cao huyết áp, bệnh khớp",
      "내분비내과/가정의학과",
      "비만에 대한 사회적 시선에 민감할 수 있습니다. 건강 관점에서 접근하고 비난하지 않습니다.",
      [{"mistake":"의지력 부족으로 비난","correction":"복합적 원인(유전, 환경, 호르몬)","explanation":"비난은 역효과입니다"},
       {"mistake":"굶으라고 조언","correction":"건강한 식이와 운동이 핵심","explanation":"영양 결핍은 위험합니다"},
       {"mistake":"빠른 체중 감량 권유","correction":"주당 0.5-1kg 감량이 안전","explanation":"급격한 감량은 요요 유발"}],
      [{"ko":"비만 관리를 위해 식이 상담과 운동 처방이 필요합니다.","vi":"Cần tư vấn dinh dưỡng và hướng dẫn vận động để quản lý béo phì.","situation":"formal"},
       {"ko":"천천히 오래 걷는 운동부터 시작하세요.","vi":"Bắt đầu từ đi bộ chậm trong thời gian dài.","situation":"onsite"},
       {"ko":"비만이라 무릎이 아파요.","vi":"Béo phì nên đầu gối đau.","situation":"informal"}],
      ["BMI","식이요법","비만수술"]),

    t("hoi-chung-cushing","쿠싱증후군","hội chứng Cushing",
      "코르티솔 호르몬이 과다하여 비만, 고혈압, 당뇨, 골다공증이 발생합니다. 통역 시 달덩이 얼굴, 복부 비만, 피부 변화 등 특징적 증상을 확인합니다.",
      "Tình trạng hormone cortisol quá nhiều gây béo phì, cao huyết áp, tiểu đường, loãng xương",
      "내분비내과",
      "스테로이드 장기 복용이 원인이 될 수 있습니다. 약물력을 꼭 확인합니다.",
      [{"mistake":"단순 비만으로 치부","correction":"특징적 체형 분포 확인 필요","explanation":"복부 비만 + 사지 가늘어짐"},
       {"mistake":"스테로이드 임의 중단 권유","correction":"급격한 중단은 위험","explanation":"서서히 감량해야 합니다"},
       {"mistake":"원인 확인 없이 치료","correction":"뇌하수체, 부신 종양 확인 필요","explanation":"원인에 따라 치료가 다릅니다"}],
      [{"ko":"쿠싱증후군 원인 확인을 위해 호르몬 검사와 CT가 필요합니다.","vi":"Cần xét nghiệm hormone và chụp CT để xác định nguyên nhân hội chứng Cushing.","situation":"formal"},
       {"ko":"얼굴이 둥글어지고 피부에 줄이 생기면 검사받으세요.","vi":"Nếu mặt tròn lên và da có vết rạn hãy đi xét nghiệm.","situation":"onsite"},
       {"ko":"쿠싱증후군이라 살이 이상하게 쪘어요.","vi":"Hội chứng Cushing nên béo lạ.","situation":"informal"}],
      ["코르티솔","뇌하수체종양","부신절제술"]),

    t("suy-tuyen-thuong-than","부신기능저하증","suy tuyến thượng thận",
      "부신에서 호르몬(코르티솔, 알도스테론)이 부족하여 피로, 저혈압, 저혈당이 발생합니다. 통역 시 스트레스 시 위기 발생 가능성을 교육합니다.",
      "Tình trạng thiếu hormone (cortisol, aldosterone) từ tuyến thượng thận gây mệt mỏi, huyết áp thấp, hạ đường huyết",
      "내분비내과",
      "부신위기는 생명을 위협할 수 있습니다. 응급 상황 대처법과 의료 경고 팔찌 착용을 권합니다.",
      [{"mistake":"단순 피로로 치부","correction":"만성 피로 시 호르몬 검사 고려","explanation":"숨은 원인이 있을 수 있습니다"},
       {"mistake":"스테로이드 부작용만 강조","correction":"필수적인 호르몬 보충","explanation":"생존에 필요합니다"},
       {"mistake":"평상시 용량만 설명","correction":"스트레스 시 증량 필요","explanation":"부신위기 예방이 중요합니다"}],
      [{"ko":"부신기능저하증으로 평생 호르몬 보충이 필요합니다.","vi":"Suy tuyến thượng thận cần bổ sung hormone suốt đời.","situation":"formal"},
       {"ko":"아플 때는 약 용량을 2배로 늘리세요.","vi":"Khi ốm hãy tăng gấp đôi liều thuốc.","situation":"onsite"},
       {"ko":"부신이 안 좋아서 스테로이드 먹어요.","vi":"Tuyến thượng thận yếu nên uống steroid.","situation":"informal"}],
      ["하이드로코르티손","부신위기","ACTH자극검사"]),

    t("viem-da-co-dia","아토피피부염","viêm da cơ địa",
      "만성적으로 재발하는 가려움증을 동반한 피부 염증입니다. 통역 시 보습의 중요성과 악화 요인 회피를 강조합니다.",
      "Viêm da mãn tính tái phát với ngứa",
      "피부과",
      "환경 변화(한국의 건조한 겨울)가 악화 요인이 될 수 있습니다. 보습제 사용법을 구체적으로 안내합니다.",
      [{"mistake":"스테로이드는 무조건 나쁘다고 설명","correction":"적절히 사용하면 안전하고 효과적","explanation":"스테로이드 공포증을 줄입니다"},
       {"mistake":"완치 가능하다고 설명","correction":"관리 목표, 완치는 어려움","explanation":"현실적 기대를 설정합니다"},
       {"mistake":"긁지 말라고만 강조","correction":"가려움 조절 치료 필요","explanation":"의지만으로는 어렵습니다"}],
      [{"ko":"아토피피부염 관리를 위해 보습제를 하루 2회 이상 바르세요.","vi":"Để quản lý viêm da cơ địa, bôi kem dưỡng ẩm ít nhất 2 lần/ngày.","situation":"formal"},
       {"ko":"목욕 후 3분 이내에 보습제를 바르세요.","vi":"Bôi kem dưỡng trong vòng 3 phút sau tắm.","situation":"onsite"},
       {"ko":"아토피라서 겨울에 더 가려워요.","vi":"Bị viêm da cơ địa nên mùa đông ngứa hơn.","situation":"informal"}],
      ["보습제","국소스테로이드","가려움증"]),

    t("vay-nen","건선","vảy nến",
      "피부 세포가 빠르게 증식하여 은백색 비늘이 덮인 붉은 반점이 생기는 만성 질환입니다. 통역 시 전염되지 않음을 강조하고, 관절에도 영향을 줄 수 있음을 설명합니다.",
      "Bệnh mãn tính khi tế bào da tăng sinh nhanh tạo mảng đỏ phủ vảy trắng bạc",
      "피부과",
      "건선에 대한 사회적 편견이 있습니다. 전염되지 않음을 명확히 하고, 환자의 심리적 부담을 덜어줍니다.",
      [{"mistake":"전염된다고 오해 유발","correction":"건선은 자가면역 질환, 전염 안 됨","explanation":"사회적 낙인을 줄입니다"},
       {"mistake":"피부 문제로만 설명","correction":"건선성관절염 가능성 있음","explanation":"관절 증상도 확인합니다"},
       {"mistake":"완치 가능하다고 설명","correction":"관리가 목표, 재발 흔함","explanation":"현실적 기대를 설정합니다"}],
      [{"ko":"건선은 전염되지 않는 자가면역 질환입니다.","vi":"Vảy nến là bệnh tự miễn, không lây.","situation":"formal"},
       {"ko":"스트레스가 악화 요인이 될 수 있어요.","vi":"Stress có thể làm bệnh nặng hơn.","situation":"onsite"},
       {"ko":"건선이라 피부에 비늘 같은 게 생겨요.","vi":"Bị vảy nến nên da có vảy.","situation":"informal"}],
      ["생물학적제제","광선치료","건선성관절염"]),

    t("nam-da","피부사상균증/무좀","nấm da",
      "곰팡이가 피부, 손톱, 머리카락을 감염시켜 가려움, 각질, 변색을 유발합니다. 통역 시 완전 치료까지 약을 지속해야 재발을 막을 수 있음을 강조합니다.",
      "Tình trạng nấm nhiễm da, móng, tóc gây ngứa, bong tróc, đổi màu",
      "피부과",
      "공동 생활 환경에서 전염될 수 있습니다. 개인 위생용품 분리 사용을 권합니다.",
      [{"mistake":"증상 호전되면 약 중단","correction":"처방 기간 완료 필수","explanation":"재발 방지가 중요합니다"},
       {"mistake":"연고만 바르면 된다고 설명","correction":"손톱무좀은 먹는 약 필요","explanation":"부위에 따라 치료가 다릅니다"},
       {"mistake":"깨끗이 씻으면 낫는다고 설명","correction":"항진균제 치료 필요","explanation":"씻는 것만으로는 부족합니다"}],
      [{"ko":"무좀 치료를 위해 항진균제를 4주간 바르세요.","vi":"Để trị nấm hãy bôi thuốc kháng nấm 4 tuần.","situation":"formal"},
       {"ko":"발을 잘 말리고 통풍이 잘 되는 신발을 신으세요.","vi":"Lau khô chân và mang giày thoáng khí.","situation":"onsite"},
       {"ko":"무좀이라 발가락 사이가 가려워요.","vi":"Bị nấm chân nên ngứa kẽ ngón chân.","situation":"informal"}],
      ["항진균제","손톱무좀","발무좀"]),

    t("zona","대상포진","zona/giời leo",
      "수두바이러스가 재활성화되어 신경을 따라 물집과 심한 통증이 발생합니다. 통역 시 72시간 내 항바이러스제 투여의 중요성을 강조합니다.",
      "Bệnh do virus thủy đậu tái hoạt gây mụn nước và đau dữ dội dọc theo dây thần kinh",
      "피부과/신경과",
      "면역력 저하 시 발생할 수 있습니다. 50세 이상은 예방접종을 권합니다.",
      [{"mistake":"단순 피부병으로 치부","correction":"신경통이 수년간 지속될 수 있음","explanation":"조기 치료가 중요합니다"},
       {"mistake":"전염 안 된다고 설명","correction":"수두 안 걸린 사람에게 수두 전파 가능","explanation":"접촉 주의가 필요합니다"},
       {"mistake":"진통제만 처방","correction":"항바이러스제가 핵심","explanation":"조기 투여로 합병증 예방"}],
      [{"ko":"대상포진으로 72시간 내 항바이러스제 투여가 중요합니다.","vi":"Zona cần dùng thuốc kháng virus trong 72 giờ.","situation":"formal"},
       {"ko":"물집 부위를 긁지 마시고 깨끗이 유지하세요.","vi":"Đừng gãi chỗ mụn nước, giữ sạch sẽ.","situation":"onsite"},
       {"ko":"대상포진이라 옆구리가 엄청 아파요.","vi":"Bị zona nên hông đau dữ.","situation":"informal"}],
      ["항바이러스제","대상포진후신경통","대상포진백신"]),

    t("mun-trung-ca","여드름","mụn trứng cá",
      "모낭과 피지선의 염증으로 면포, 구진, 농포가 발생합니다. 통역 시 치료 효과가 나타나려면 수주가 필요함을 설명합니다.",
      "Tình trạng viêm nang lông và tuyến bã nhờn tạo mụn đầu đen, mụn sẩn, mụn mủ",
      "피부과",
      "청소년뿐 아니라 성인에서도 흔합니다. 흉터 예방을 위해 함부로 짜지 않도록 교육합니다.",
      [{"mistake":"먹는 게 원인이라고만 강조","correction":"호르몬, 유전 등 복합 원인","explanation":"식이는 일부 요인입니다"},
       {"mistake":"바로 효과 나타난다고 설명","correction":"4-8주 후 효과 나타남","explanation":"인내심이 필요합니다"},
       {"mistake":"짜면 빨리 낫는다고 설명","correction":"흉터 위험, 함부로 짜지 말 것","explanation":"전문가 압출 권장"}],
      [{"ko":"여드름 치료 효과는 4-8주 후에 나타납니다.","vi":"Hiệu quả điều trị mụn trứng cá thấy sau 4-8 tuần.","situation":"formal"},
       {"ko":"얼굴을 자주 만지지 마세요.","vi":"Đừng hay sờ mặt.","situation":"onsite"},
       {"ko":"여드름 때문에 피부과 다녀요.","vi":"Đang đi da liễu vì mụn trứng cá.","situation":"informal"}],
      ["레티노이드","벤조일퍼옥사이드","이소트레티노인"]),

    t("viem-da-tiep-xuc","접촉피부염","viêm da tiếp xúc",
      "특정 물질과 접촉 후 피부에 발진, 가려움, 물집이 생기는 염증입니다. 통역 시 원인 물질 확인과 회피가 치료의 핵심임을 설명합니다.",
      "Tình trạng viêm da với phát ban, ngứa, mụn nước sau khi tiếp xúc với chất gây dị ứng",
      "피부과",
      "직업적 노출(세정제, 화학물질)이 원인인 경우가 많습니다. 직업력을 확인합니다.",
      [{"mistake":"알레르기 검사 없이 치료만","correction":"원인 물질 확인이 재발 방지에 중요","explanation":"패치 테스트 고려"},
       {"mistake":"스테로이드 무기한 사용","correction":"단기 사용 후 보습으로 유지","explanation":"장기 사용 부작용 주의"},
       {"mistake":"자연 치유만 기다림","correction":"원인 회피 없이는 재발","explanation":"원인 제거가 핵심입니다"}],
      [{"ko":"접촉피부염 원인 확인을 위해 패치 테스트가 필요합니다.","vi":"Cần test dán để xác định nguyên nhân viêm da tiếp xúc.","situation":"formal"},
       {"ko":"원인 물질을 피하는 게 가장 중요해요.","vi":"Tránh chất gây dị ứng là quan trọng nhất.","situation":"onsite"},
       {"ko":"장갑 끼면 손이 부어요.","vi":"Đeo găng tay là tay bị sưng.","situation":"informal"}],
      ["패치테스트","국소스테로이드","보습제"]),

    t("dau-mat-do","결막염","đau mắt đỏ",
      "결막에 염증이 생겨 눈이 충혈되고 분비물이 나오며 가려움이 있습니다. 통역 시 감염성 여부에 따라 격리 필요성을 설명합니다.",
      "Tình trạng viêm kết mạc gây đỏ mắt, tiết dịch và ngứa",
      "안과",
      "전염성 결막염은 공동 생활 환경에서 빠르게 퍼질 수 있습니다. 손 위생과 수건 분리 사용을 강조합니다.",
      [{"mistake":"안약 아무거나 사용하라고 조언","correction":"원인에 따라 치료가 다름","explanation":"세균성/바이러스성/알레르기성 구분 필요"},
       {"mistake":"전염 안 된다고 설명","correction":"바이러스성은 매우 전염력 높음","explanation":"격리와 손 위생 필수"},
       {"mistake":"며칠이면 낫는다고 설명","correction":"바이러스성은 2주 이상 지속 가능","explanation":"현실적 기대 설정"}],
      [{"ko":"결막염으로 눈을 만지지 말고 손을 자주 씻으세요.","vi":"Đau mắt đỏ, đừng dụi mắt và rửa tay thường xuyên.","situation":"formal"},
       {"ko":"수건과 베개를 따로 쓰세요.","vi":"Dùng khăn và gối riêng.","situation":"onsite"},
       {"ko":"눈병 걸려서 출근 못 해요.","vi":"Bị đau mắt đỏ nên không đi làm được.","situation":"informal"}],
      ["항생제안약","항히스타민안약","인공눈물"]),

    t("tang-nhan-ap","녹내장","tăng nhãn áp/glôcôm",
      "안압이 높아져 시신경이 손상되고 시야가 점차 좁아지는 질환입니다. 통역 시 증상 없이 진행되므로 정기 검진의 중요성을 강조합니다.",
      "Bệnh tổn thương thần kinh thị giác do nhãn áp cao, thị trường dần thu hẹp",
      "안과",
      "녹내장은 조기 발견이 중요합니다. 가족력이 있으면 정기 검사를 더욱 권합니다.",
      [{"mistake":"녹내장은 백내장이라고 혼동","correction":"녹내장은 시신경, 백내장은 수정체","explanation":"완전히 다른 질환입니다"},
       {"mistake":"안압 정상이면 녹내장 아니라고 설명","correction":"정상안압녹내장도 있음","explanation":"안압만으로 판단 불가"},
       {"mistake":"수술하면 시력 회복된다고 설명","correction":"손상된 시신경은 회복 불가","explanation":"악화 방지가 목표입니다"}],
      [{"ko":"녹내장 조기 발견을 위해 안압과 시신경 검사가 필요합니다.","vi":"Cần đo nhãn áp và kiểm tra thần kinh thị giác để phát hiện sớm glôcôm.","situation":"formal"},
       {"ko":"안약을 매일 같은 시간에 넣으세요.","vi":"Nhỏ thuốc mỗi ngày cùng giờ.","situation":"onsite"},
       {"ko":"녹내장이라 안약 매일 넣어요.","vi":"Bị glôcôm nên nhỏ thuốc mỗi ngày.","situation":"informal"}],
      ["안압","시야검사","안압하강제"]),

    t("duc-thuy-tinh-the","백내장","đục thủy tinh thể",
      "수정체가 혼탁해져 시력이 저하되는 질환입니다. 통역 시 노화로 인한 자연스러운 현상이며, 수술로 회복 가능함을 설명합니다.",
      "Bệnh khi thủy tinh thể bị đục làm giảm thị lực",
      "안과",
      "백내장 수술은 매우 흔한 수술입니다. 수술 두려움을 줄이고 높은 성공률을 안내합니다.",
      [{"mistake":"실명한다고 겁줌","correction":"수술로 시력 회복 가능","explanation":"치료 가능한 질환입니다"},
       {"mistake":"수술 미루라고 조언","correction":"일상에 불편하면 수술 시기","explanation":"너무 늦추면 수술 어려워짐"},
       {"mistake":"수술 후 바로 보인다고 설명","correction":"회복에 수주 필요","explanation":"현실적 기대 설정"}],
      [{"ko":"백내장 수술로 인공수정체를 삽입합니다.","vi":"Phẫu thuật đục thủy tinh thể sẽ đặt thủy tinh thể nhân tạo.","situation":"formal"},
       {"ko":"안경 써도 뿌옇게 보이면 수술을 고려하세요.","vi":"Nếu đeo kính vẫn mờ hãy cân nhắc phẫu thuật.","situation":"onsite"},
       {"ko":"백내장 수술하니까 잘 보여요.","vi":"Mổ đục thủy tinh thể xong nhìn rõ.","situation":"informal"}],
      ["인공수정체","초음파유화술","다초점렌즈"]),

    t("benh-vong-mac-tieu-duong","당뇨망막병증","bệnh võng mạc tiểu đường",
      "당뇨로 인해 망막 혈관이 손상되어 시력 저하와 실명을 유발할 수 있습니다. 통역 시 혈당 조절과 정기 안과 검진의 중요성을 강조합니다.",
      "Bệnh tổn thương mạch máu võng mạc do tiểu đường, có thể gây giảm thị lực và mù",
      "안과/내분비내과",
      "당뇨 환자는 증상 없어도 1년에 한 번 안저검사를 받아야 합니다.",
      [{"mistake":"시력 좋으면 괜찮다고 설명","correction":"증상 없이 진행됨","explanation":"정기 검사가 필수입니다"},
       {"mistake":"당뇨 조절만 하면 안 생긴다고 설명","correction":"잘 조절해도 발생 가능","explanation":"정기 검진 필수"},
       {"mistake":"레이저는 위험하다고 겁줌","correction":"실명 예방을 위한 치료","explanation":"치료의 이점이 큽니다"}],
      [{"ko":"당뇨망막병증 예방을 위해 매년 안저검사가 필요합니다.","vi":"Cần khám đáy mắt hàng năm để phòng bệnh võng mạc tiểu đường.","situation":"formal"},
       {"ko":"혈당을 잘 조절하면 진행을 늦출 수 있어요.","vi":"Kiểm soát đường huyết tốt có thể làm chậm tiến triển.","situation":"onsite"},
       {"ko":"당뇨 오래돼서 눈에 합병증 왔어요.","vi":"Tiểu đường lâu nên mắt bị biến chứng.","situation":"informal"}],
      ["안저검사","레이저광응고술","유리체절제술"]),

    t("thoai-hoa-hoang-diem","황반변성","thoái hóa hoàng điểm",
      "망막 중심부(황반)가 손상되어 중심 시력이 저하됩니다. 통역 시 직선이 휘어 보이는 증상을 확인하고, 조기 치료의 중요성을 강조합니다.",
      "Bệnh tổn thương vùng trung tâm võng mạc (hoàng điểm) gây giảm thị lực trung tâm",
      "안과",
      "고령에서 흔한 실명 원인입니다. 암슬러 격자 자가검사를 교육합니다.",
      [{"mistake":"나이 들면 어쩔 수 없다고만 설명","correction":"습성은 주사 치료로 관리 가능","explanation":"치료 옵션이 있습니다"},
       {"mistake":"백내장과 혼동","correction":"황반변성은 망막, 백내장은 수정체","explanation":"다른 질환입니다"},
       {"mistake":"건성은 치료 안 해도 된다고 설명","correction":"습성으로 진행 감시 필요","explanation":"정기 검진 필수"}],
      [{"ko":"황반변성 치료를 위해 눈에 주사를 맞아야 합니다.","vi":"Để điều trị thoái hóa hoàng điểm cần tiêm mắt.","situation":"formal"},
       {"ko":"직선이 휘어 보이면 바로 오세요.","vi":"Nếu đường thẳng trông cong hãy đến ngay.","situation":"onsite"},
       {"ko":"황반변성이라 눈에 주사 맞아요.","vi":"Bị thoái hóa hoàng điểm nên tiêm mắt.","situation":"informal"}],
      ["항VEGF주사","안저검사","암슬러격자"]),

    t("viem-tai-giua","중이염","viêm tai giữa",
      "중이에 염증이 생겨 귀 통증, 발열, 청력 저하가 발생합니다. 통역 시 소아에서 흔하며, 항생제 완료의 중요성을 강조합니다.",
      "Tình trạng viêm tai giữa gây đau tai, sốt, giảm thính lực",
      "이비인후과",
      "감기 후에 잘 발생합니다. 아이가 귀를 잡아당기거나 보채면 중이염을 의심합니다.",
      [{"mistake":"항생제 안 써도 낫는다고 설명","correction":"세균성은 항생제 필요","explanation":"합병증 예방이 중요합니다"},
       {"mistake":"증상 호전되면 약 중단","correction":"처방 기간 완료 필수","explanation":"재발과 내성 예방"},
       {"mistake":"만성화 안 된다고 안심시킴","correction":"반복되면 만성 중이염, 청력 손실 가능","explanation":"적극 치료가 필요합니다"}],
      [{"ko":"중이염으로 항생제를 7일간 드셔야 합니다.","vi":"Viêm tai giữa cần uống kháng sinh 7 ngày.","situation":"formal"},
       {"ko":"귀에 물이 들어가지 않게 조심하세요.","vi":"Cẩn thận không để nước vào tai.","situation":"onsite"},
       {"ko":"중이염이라 귀가 아파요.","vi":"Viêm tai giữa nên đau tai.","situation":"informal"}],
      ["항생제","고막절개","환기관삽입술"]),

    t("viem-mui-di-ung","알레르기비염","viêm mũi dị ứng",
      "알레르기 반응으로 재채기, 콧물, 코막힘, 가려움이 발생합니다. 통역 시 계절성과 통년성을 구분하고, 원인 항원 회피를 강조합니다.",
      "Tình trạng phản ứng dị ứng gây hắt hơi, sổ mũi, nghẹt mũi, ngứa",
      "이비인후과/알레르기내과",
      "한국의 꽃가루, 미세먼지가 알레르기비염을 악화시킬 수 있습니다. 마스크 착용을 권합니다.",
      [{"mistake":"감기와 혼동","correction":"가려움이 있고 재발하면 알레르기 의심","explanation":"치료 방향이 다릅니다"},
       {"mistake":"약 먹으면 바로 낫는다고 설명","correction":"원인 회피와 장기 관리 필요","explanation":"만성 질환으로 접근"},
       {"mistake":"코막힘 스프레이 계속 쓰라고 조언","correction":"3-5일 이상 사용 금지","explanation":"약물성 비염 유발"}],
      [{"ko":"알레르기비염 관리를 위해 항원 검사가 필요합니다.","vi":"Cần xét nghiệm dị nguyên để quản lý viêm mũi dị ứng.","situation":"formal"},
       {"ko":"미세먼지 많은 날은 마스크를 착용하세요.","vi":"Ngày bụi mịn cao hãy đeo khẩu trang.","situation":"onsite"},
       {"ko":"알레르기비염이라 맨날 재채기해요.","vi":"Viêm mũi dị ứng nên hắt hơi suốt.","situation":"informal"}],
      ["항히스타민제","비강스테로이드","면역치료"]),

    t("viem-xoang","부비동염/축농증","viêm xoang",
      "부비동에 염증이 생겨 코막힘, 두통, 안면 통증, 누런 콧물이 발생합니다. 통역 시 급성과 만성을 구분하고, 항생제 완료의 중요성을 강조합니다.",
      "Tình trạng viêm xoang gây nghẹt mũi, đau đầu, đau mặt, chảy mũi vàng",
      "이비인후과",
      "감기가 오래 가면 부비동염 가능성을 설명합니다. 코를 세게 풀지 않도록 교육합니다.",
      [{"mistake":"감기 오래 가는 것과 동일시","correction":"10일 이상 증상 지속 시 부비동염 의심","explanation":"항생제 필요할 수 있습니다"},
       {"mistake":"코 세게 풀라고 조언","correction":"부드럽게, 한쪽씩 풀기","explanation":"중이염 유발 가능"},
       {"mistake":"만성은 수술만 된다고 설명","correction":"약물 치료 먼저 시도","explanation":"단계적 접근이 필요합니다"}],
      [{"ko":"부비동염으로 항생제를 10일간 드셔야 합니다.","vi":"Viêm xoang cần uống kháng sinh 10 ngày.","situation":"formal"},
       {"ko":"따뜻한 수증기를 쐬면 코가 뚫릴 수 있어요.","vi":"Xông hơi nóng có thể thông mũi.","situation":"onsite"},
       {"ko":"축농증이라 머리가 무거워요.","vi":"Viêm xoang nên đầu nặng.","situation":"informal"}],
      ["항생제","비강세척","내시경수술"]),

    t("tram-cam","우울증","trầm cảm",
      "지속적인 슬픔, 흥미 상실, 에너지 저하, 수면/식욕 변화 등이 나타나는 정신건강 질환입니다. 통역 시 치료 가능한 질환임을 강조하고, 낙인을 줄입니다.",
      "Bệnh sức khỏe tâm thần với buồn kéo dài, mất hứng thú, giảm năng lượng, thay đổi giấc ngủ/ăn uống",
      "정신건강의학과",
      "정신건강에 대한 편견이 있을 수 있습니다. 다른 질환처럼 치료 가능함을 설명합니다.",
      [{"mistake":"의지력 문제로 치부","correction":"뇌의 화학적 불균형이 원인","explanation":"질병으로 접근해야 합니다"},
       {"mistake":"약 먹으면 중독된다고 겁줌","correction":"항우울제는 중독성 없음","explanation":"잘못된 정보를 바로잡습니다"},
       {"mistake":"힘내라고만 조언","correction":"전문 치료가 필요","explanation":"격려만으로는 부족합니다"}],
      [{"ko":"우울증은 치료 가능한 질환입니다. 약물과 상담이 도움됩니다.","vi":"Trầm cảm có thể điều trị. Thuốc và tư vấn sẽ giúp ích.","situation":"formal"},
       {"ko":"혼자 힘들면 전문가 상담을 받으세요.","vi":"Nếu khó khăn một mình hãy gặp chuyên gia.","situation":"onsite"},
       {"ko":"우울증 약 먹고 많이 나아졌어요.","vi":"Uống thuốc trầm cảm đã đỡ nhiều.","situation":"informal"}],
      ["항우울제","인지행동치료","자살위험평가"]),

    t("roi-loan-lo-au","불안장애","rối loạn lo âu",
      "과도한 걱정과 불안이 지속되어 일상생활에 지장을 주는 정신건강 질환입니다. 통역 시 신체 증상(두근거림, 떨림, 호흡곤란)도 나타날 수 있음을 설명합니다.",
      "Bệnh sức khỏe tâm thần với lo lắng và bất an quá mức kéo dài ảnh hưởng đời sống",
      "정신건강의학과",
      "이주 노동자는 언어, 문화, 가족 분리로 불안이 증가할 수 있습니다. 공감과 지지를 표현합니다.",
      [{"mistake":"소심한 성격으로 치부","correction":"치료가 필요한 질환","explanation":"의료적 접근이 필요합니다"},
       {"mistake":"진정제만 처방","correction":"인지행동치료도 효과적","explanation":"복합 치료가 도움됩니다"},
       {"mistake":"평생 약 먹어야 한다고 겁줌","correction":"치료 후 중단 가능한 경우 많음","explanation":"희망을 줍니다"}],
      [{"ko":"불안장애 치료를 위해 약물과 상담을 병행합니다.","vi":"Điều trị rối loạn lo âu cần kết hợp thuốc và tư vấn.","situation":"formal"},
       {"ko":"긴장될 때 천천히 숨을 쉬어보세요.","vi":"Khi căng thẳng hãy thử thở chậm.","situation":"onsite"},
       {"ko":"불안장애라서 가슴이 답답해요.","vi":"Bị rối loạn lo âu nên ngực tức.","situation":"informal"}],
      ["항불안제","인지행동치료","호흡훈련"])
]

# Load and update
with open('../data/terms/medical.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {term['slug'] for term in data}
new_terms = [t for t in terms if t['slug'] not in existing_slugs]
data.extend(new_terms)

with open('../data/terms/medical.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_terms)} terms. Total: {len(data)}")
